### ISSUE TITLE
Support linking pathlines to their source code in a repository

### ISSUE THREAD

**Issue by nichtich** [styleguidist/react-styleguidist#1000]
**The problem**

I want to directly jump to source code of a component for instance the source file at GitHub.

**Proposed solution**

Extend PathlineRenderer to support linking the path. This requires an additional configuration key.

**Alternative solutions**

Hard-code the link into a locally modified copy of PathlineRenderer.js.

**Additional context**

To give an example at <https://react-styleguidist.js.org/examples/basic/#button> the path is shown as `src/components/Button/Button.js`. This should be a link to <https://github.com/styleguidist/react-styleguidist/blob/master/examples/basic/src/components/Button/Button.js> if configured with for instance with a configuration key `linkPathPrefix` set to `https://github.com/styleguidist/react-styleguidist/blob/master/examples/basic/`.

**Comment by sapegin** [comment]
Your alternative solution is the right way to do that.
