### ISSUE TITLE
Component Names matching React Constructors names (such as Map) can break Styleguidist

### ISSUE THREAD

**Issue by MercerK** [styleguidist/react-styleguidist#1001]
**Current behavior**

I was working with a Map component and named it "Map" in my latest iteration within a TypeScript React application. Had no issues with the name. When trying to display it in Styleguidist, it spat out 1017 duplicate errors.

![image](https://user-images.githubusercontent.com/13123338/40808056-fc506f56-64f3-11e8-925b-50f2e27afd4d.png)

Upon looking at the source code, somehow my "Map" component overwrote React's "Map" constructor. 
 
![image](https://user-images.githubusercontent.com/13123338/40808331-ccd93d56-64f4-11e8-820e-ea85955d8e7e.png)

**To reproduce**

1) Create a new project & use "create-react-app"
2) Install react-styleguidist
3) Create a new Component called "Map". 
4) Test and verify it works in "npm start"
5) Run "npx styleguidist server"
6) Review console and you should see:

![image](https://user-images.githubusercontent.com/13123338/40807896-92a3c468-64f3-11e8-83eb-6756a2567555.png)

**Expected behavior**

I expected that a user defined component to work in Styleguidist, just as it would in CRA. 

**Comments**

Hopefully the information provided helps. Renaming the component to "ReactMaps" works just fine, as seen below. 

![image](https://user-images.githubusercontent.com/13123338/40808549-865a077e-64f5-11e8-9090-574f3cbe2618.png)

**Comment by sapegin** [comment]
This was discussed many times with suggested fixes, please use search and feel free to send a pull request to fix that.
