### ISSUE TITLE
Styled components with Create React App

### ISSUE THREAD

**Issue by hirppa** [styleguidist/react-styleguidist#1002]
I have a create react app setup and i got this message when i followed this document to add support for styled components https://github.com/styleguidist/react-styleguidist/blob/master/docs/Thirdparties.md.

```
./styleguide/ThemeWrapper.js
Module parse failed: Unexpected token (8:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <ThemeProvider theme={theme}>
|         {this.props.children}
|       </ThemeProvider>
```

I moved ThemeWrapper.js to ./src/ThemeWrapper.js and message disappeared.

**Comment by jamestowers** [comment]
If using `create-react-app`, you can also add
```
styleguide: resolveApp('styleguide'),
``` 
to `module.exports` of `config/paths.js` and then in `webpack.config.dev.js` change
```
      test: /\.(js|jsx|mjs)$/,
      include: paths.appSrc,
      ...
```
to 
```
      test: /\.(js|jsx|mjs)$/,
      include: [...paths.appSrc, ...paths.styleguide],
      ...
```
