### ISSUE TITLE
Bug IE11, Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by rafaesc** [styleguidist/react-styleguidist#1003]
**Current behavior**

Error when you isolate a section in IE11

**To reproduce**

1. run `npm run start:sections`
2. click on an isolated section in IE

it shows on console
`Object doesn't support property or method 'find'`
of this file 
https://github.com/styleguidist/react-styleguidist/blob/master/src/utils/findSection.js#L8-L10

**Expected behavior**

It should work

**Comment by aabenoja** [comment]
It's like a game of wack-a-mole, since I last fixed this in #912

**Comment by rafaesc** [comment]
Interesting, thanks @aabenoja 
I have to update the PR and to use lodash
