### ISSUE TITLE
`ignore` option not working properly

### ISSUE THREAD

**Issue by selrond** [styleguidist/react-styleguidist#1008]
**Current behavior**

When I try to use `ignore` options to ignore certain subfolder within included folder, it does not seem to work.

**To reproduce**

1. Clone [selrond/example at bug/ignore-not-working](https://github.com/selrond/example/tree/bug/ignore-not-working)
2. `npm start`

**Expected behavior**

`Pencil` should not show up in styleguide, as its' parent folder is ignored in sections:

```js
sections: [
	{
		name: 'Atoms',
		components: 'src/components/atoms/**/*.js',
		ignore: 'src/components/atoms/svg/'
	},
	{
		name: 'Others',
		components: 'src/components/*.js',
	},
]
```

**Comment by sapegin** [comment]
> You should pass glob patterns, for example, use **/components/Button.js instead of components/Button.js.

https://react-styleguidist.js.org/docs/configuration#ignore

**Comment by selrond** [comment]
@sapegin thanks, changed 

```js
ignore: 'src/components/atoms/svg/'
``` 

to 

```js
ignore: '**/src/components/atoms/svg/**'
```

now it works.

But anyway - there are places in the docs where it's encouraged to use globs, but the default is "not a glob" *(although - is it not, really?)*

[Example](https://react-styleguidist.js.org/docs/configuration#components): 

> components
> Type: String, Function or Array, default: `src/components/**/*.{js,jsx,ts,tsx}`
> 
> - when String: a glob pattern that matches all your component modules.
> - when Function: a function that returns an array of module paths.
> - when Array: an array of module paths.
> All paths are relative to config folder.

See examples in the Components section.

How about that?

**Comment by sapegin** [comment]
The default for `ignore` is an array of globs:

`['**/__tests__/**', '**/*.test.{js,jsx,ts,tsx}', '**/*.spec.{js,jsx,ts,tsx}', '**/*.d.ts']`

Do you see any examples of the `ignore` options that aren't globs in the docs?

**Comment by selrond** [comment]
@sapegin look at my comment - the dafault string for components path - it's said to be a glob, although the default one is not

**Comment by sapegin** [comment]
I only see a glob in your example: `src/components/**/*.{js,jsx,ts,tsx}`.

**Comment by selrond** [comment]
@sapegin how is this different from mine `src/components/atoms/svg/**` (which I've tried as well, and doesn't work)?
