### ISSUE TITLE
[Feature Request] Hability to extend schema configuration

### ISSUE THREAD

**Issue by pnepe6** [styleguidist/react-styleguidist#1010]
**The problem**

react-stylegudiist provide a way for using aliases to update rsg-components; but when it comes to extend the features, it becomes impossible to add configuration due to the way the sanitize fonction and webpack are linked together.

**Proposed solution**

Adding a new cli arguments: https://react-styleguidist.js.org/docs/cli.html

`--schemas` : it will contain the source to use to link the schema to be passed to getConfig

**Comment by kopax** [comment]
Hi, we are looking for such way to extend the schemas too. I will prepare a PR very soon.
