### ISSUE TITLE
Make Styleguidist respect the proxy config in react-create-app

### ISSUE THREAD

**Issue by NoMan2000** [styleguidist/react-styleguidist#1013]
Styleguidist does not currently respect the `proxy` config in `package.json`.  So if someone is running `json-server` on port 8080, and has `proxy: http://localhost:8080`, any requests that Styleguidist makes will not proxy the request over.

Either respect the proxy config setting or have it as an optional configuration component.

**Comment by sapegin** [comment]
Feel free to submit a pull request for that.

But in general your style guide should not depend on the backend.

**Comment by NoMan2000** [comment]
I'll check it out and see how involved it is.  

> But in general your style guide should not depend on the backend.

I might be doing this wrong, but the problem is that certain methods get invoked when a React component gets created, particularly fetching data from a server.  If no data is found, it throws an error.  

Is there a way to override that in Styleguidist?

**Comment by sapegin** [comment]
I think [presentational and container components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) is the right pattern here: you don't need containers in your style guide, only presentational components. It would be more convenient to use unit tests to test containers and mock network requests (with Nock, for example).

**Comment by NoMan2000** [comment]
I'll add for anyone looking to get around this problem that it's not too difficult.  This example is using axios:

```js
const sinon = require('sinon');
const resolved = new Promise((r) => r({ data: [] }));
sinon.stub(axios, 'get').returns(resolved);
```

This will stop it from throwing errors.

**Comment by NoMan2000** [comment]
And an even better solution.  In `styleguide.config.js` do this:

```js
configureServer(app) {
    const mockServer = require('./mockAPI/mockServer');
    // `app` is the instance of the express server running Styleguidist
    app.use(mockServer);

  }
```

That will automatically proxy the requests to the mock server.
