### ISSUE TITLE
Babel 7 Upgrade

### ISSUE THREAD

**Issue by jeffscottward** [styleguidist/react-styleguidist#1014]
**The problem**
When attempting to clone this repo (+my new components) into a `next.js` project, it errors out.

```
Error: 
Plugin/Preset files are not allowed to export objects, only functions. In MYPROJECTPATH/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (MYPROJECTPATH/node_modules/@babel/core/lib/config/config-descriptors.js:179:11)
```

Note the modules `babel-preset-react` and `@babel/core`

Respective Babel configs here (Babel 7 vs Babel 6):

https://github.com/zeit/next.js/blob/master/.babelrc
https://github.com/styleguidist/react-styleguidist/blob/master/.babelrc

------------------------

**Proposed solution**
Upgrade the Babel dependencies to Babel 7 and its ecosystem of modules. 
Is there any reason why this can't be done?

**Comment by sapegin** [comment]
Possible reasons:

* nobody sent a pull request for that;
* may not work with Create React App.

**Comment by sapegin** [comment]
Now I'm wondering what are you actually trying to achieve by doing this?

> When attempting to clone this repo (+my new components) into a next.js project
