### ISSUE TITLE
Styleguide crashes when accessing invalid isolated urls

### ISSUE THREAD

**Issue by treylon** [styleguidist/react-styleguidist#1016]
**Current behavior**

When you access an invalid url (eg element name changed) in the isolated view (eg: http://localhost:6060/#!/ButtonTYPO ) the server crashes with an error and does not display a valid error nor provides any fallback.

**To reproduce**

As a demo just open your own styleguide instance, access a component in the isolated mode and change the url manually OR use this url: [http://localhost:6060/#!/ButtonTYPO](http://localhost:6060/#!/ButtonTYPO) (make sure you don't have a `ButtonTypo` Component)

**Expected behavior**

This should display an error like "Component can not be found".

**Comment by sapegin** [comment]
#993 will probably fix it.

**Comment by sapegin** [comment]
Should be fixed in 7.1.0.
