### ISSUE TITLE
Proptypes doesn't show with @component annotation with emotionjs

### ISSUE THREAD

**Issue by kossel** [styleguidist/react-styleguidist#1017]
We are spliting the UI with the styling of our components, eg:
l
Button.jsx
```
class Button extends React.Component {
  ...
  ...
}

Button.propTypes = {
  name: PropTypes.string,
}

export default Button;
```
StyledButton.jsx
```
import styled from 'react-emotion'

const StyledButton = styled(Button)(
  ...
  ...
)

StyledButton.propTypes = {
    size: PropTypes.string
}

export default StyledButton
```
PropTypes doesn't show in styleguide.

tried with `@component` annotation, without success (got warning `TypeError: Attempted to resolveName for an unsupported path. resolveName accepts a VariableDeclaration, FunctionDeclaration, or FunctionExpression. Got "CallExpression".`)

current our work around is create a wrapper component to trick styleguidist...
```
const ThemedButton = styled(Button)(
  ...
  ...
)

const StyledButton = (props) => <ThemedButton {...props} />

export default StyledButton
```

Is there a better way for this?

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
