### ISSUE TITLE
[Bug]  inject many components at once produce setState error

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1019]
## Description

We are trying to inject all our component by default in the global scope as described in the documentation [here](https://react-styleguidist.js.org/docs/cookbook.html#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples).

## Expected

We expect to be able to use our component in the Wrapper scope.

## Result

We are having errors during setup step.

## Reproduction

It says that it is possible to do the following: 

```js
Or, if you want to make these components available for all examples:

// styleguide.config.js
module.exports = {
  require: [path.resolve(__dirname, 'styleguide/setup.js')]
}

// styleguide/setup.js
import Button from './src/components/common/Button'
global.Button = Button
```

**(1) We have tried to do the following:**

```js
const bs = require('bootstrap-styled');

Object.keys(bs).map((k) => {
  if (/[A-Z]/.test(k[0])) {
    console.log('Adding', k, 'to global scope');
    global[k] = bs[k];
  }
});
```

**Result**

![image](https://user-images.githubusercontent.com/1866564/41503120-623b9a76-71f5-11e8-8c67-3146056534e6.png)

**(2) Now if we can't edit the object, we can assign with `Object.assign`**

```js
const bsGlobal = {};
Object.keys(bs).map((k) => {
  if (/[A-Z]/.test(k[0])) {
    console.log('Adding', k, 'to global scope');
    bsGlobal[k] = bs[k];
  }
});

Object.assign(global, bsGlobal);
```

**Result**

same as 1.

**(3) We have also tried to do the following:**

```js
const bs = require('bootstrap-styled');

const bsGlobal = {};
Object.keys(bs).map((k) => {
  if (/[A-Z]/.test(k[0])) {
    console.log('Adding', k, 'to global scope');
    bsGlobal[k] = bs[k];
  }
});
global = { ...global, ...bsGlobal };
```

It produces two warning, not really wanted.
Also, it does not add in any way our `<Components />` in the  global in the scope.

**Result**

![image](https://user-images.githubusercontent.com/1866564/41503096-ed37d7da-71f4-11e8-903d-d41b965b9bd0.png)

**(4) I have tested with a `for` loop, same result**

**(5) I used my loop to output the assignation in text and I copied/past it**

```js
const bs = require('bootstrap-styled');
global = bs.A;
global = bs.Button;
// ... manyes
global = bs.Container;
global = bs.ContainerFluid;

console.log(global.Button); // undefined
console.log(bs.Button); // defined
```

**(6) Using `import`**

```js
import { Button } from 'bootstrap-styled';

global = Button;

console.log(global.Button); // undefined
console.log(Button); // defined
```

**result: also fail**

Do you know why this is happening and if it can be prevented?

## version

`react-styleguidist`: 7.0.12

**Comment by sapegin** [comment]
You need to debug which _your_ component leads to this issue.

**Comment by kopax** [comment]
It seems to be the library. We have made our rsg-components with it, it must be some kind of circular dependency.

Sorry for disturbance,
