### ISSUE TITLE
Can't @import a global stylesheet

### ISSUE THREAD

**Issue by floede** [styleguidist/react-styleguidist#1021]
Forgive me, I've tried everything I can to solve this supposedly simple thing, and I must be missing something super obvious. 
Unfortunately questions on StackOverflow are clearly not getting a lot of attention.

So basically I'm trying to set up Styleguidist for our existing React app, that has quite a complicated webpack config.
For that reason I'm adding a webpack section to styleguide.config.js to make it work, but something about loading less (and css) has me stumped.

We're using global styles and variables and they're imported into the stylesheet for each component.

The structure looks like this:

```
src
└───components
│   │   Button.js
│   │   Button.css
│   
└───styles
│   └───css
│       │   global.css
```

And then in Button.css it imports the global.css:
``` @import './css/global.css'; ```

But it doesn't work.

The error I get is: 

Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import './css/global.css';

But it was able to load the Button.css just fine.

I've created a sample repo and the styleguide.config.js looks like this:

```
const path = require('path');

module.exports = {
	title: 'React Style Guide Example',
	defaultExample: true,
	webpackConfig: {
		module: {
			loaders: [
				{
					test: /\.jsx?$/,
					exclude: /node_modules/,
					loader: 'babel-loader',
				},
				{
					test: /\.css$/,
					loader: 'style-loader!css-loader?modules&importLoaders=1',
					include: path.join(__dirname, 'src/styles'),
				},
			],
		},
	},
};
```

The example repo is here: https://github.com/floede/example

**Comment by sapegin** [comment]
Your `css-loader` only works for files inside `src/styles`, but not in `src/component`, where you're trying to use it.

**Comment by floede** [comment]
The example project works fine, ie it reads the css files in src/component without specifying a path.
I just assumed that include would add to that.

But could you tell me how to accomplish what I'm trying to do?
I've looked all over the webpack documentation, and I can't find anything.
