### ISSUE TITLE
Navigation in V7.0.18 seems broken

### ISSUE THREAD

**Issue by yoksel** [styleguidist/react-styleguidist#1025]
**Current behavior**

After clicking on first link (named App) in the nav, content jumps to the right and text becomes bigger.

_Before:_

![screen shot 2018-06-24 at 20 01 59](https://user-images.githubusercontent.com/2571308/41821495-3d7ae8f4-77ea-11e8-8ac7-8d91c6208833.png)

_After:_ 

![screen shot 2018-06-24 at 20 02 29](https://user-images.githubusercontent.com/2571308/41821497-410d4b7e-77ea-11e8-9aef-241bd3595031.png)

**To reproduce**

https://github.com/yoksel/react-styleguidist-example/

**Expected behavior**

Content mustn't jump to the right

**Comment by sapegin** [comment]
This is weird:

* The base example works fine with 7.0.18.
* With your example it's broken even in 7.0.5.

So I guess it's not a new bug, but somehow your component breaks Styleguidist ;-/

**Comment by sapegin** [comment]
Ah, that! 🤦‍♂️ 

https://github.com/styleguidist/react-styleguidist/blob/3ebcc80d10500a5043cac030e4f20743587f586f/src/index.js#L23-L29

I think we can remove it now.

**Comment by kirill-kruchkov** [comment]
So basically, if I have a component called `App`, it breaks

**Comment by stepancar** [comment]
@sapegin, let I'll create PR to remove https://github.com/styleguidist/react-styleguidist/blob/3ebcc80d10500a5043cac030e4f20743587f586f/src/index.js#L23-L29
?

**Comment by sapegin** [comment]
Great idea!

**Comment by sapegin** [comment]
Out in 7.1.0.
