### ISSUE TITLE
jss-isolate is overriding custom styles, as well as the default styles

### ISSUE THREAD

**Issue by snorrekim** [styleguidist/react-styleguidist#1028]
**Current behavior**

Some custom styles are not having any effect as the styles from jss-isolate is overrideing them. This also means that some of the styles defined in styleguist by default are also overridden.

A simple example is the ComponentList heading class: "rsg--heading-XX". All its 4 defined styles are being overridden by other values by jss-isolate
![image](https://user-images.githubusercontent.com/5329330/41910896-5e02adb6-794b-11e8-903c-e7ba99c9f7b6.png)

**To reproduce**

Simply take a look at any of the example repos. I used the sections example:

https://github.com/styleguidist/react-styleguidist/tree/master/examples/sections

The screenshot on the example actually shows the expected styling. The headings are supposed to be bold, but that style is overriden by jss-isolate to be normal (though I realize the screenshot is not perfectly up to date with the example).
![image](https://user-images.githubusercontent.com/5329330/41910854-344d127c-794b-11e8-8eb2-5e1f140b1ccd.png)

You can also try to customize the style yourself in syleguide.config.js with

```
module.exports = {
  styles: {
    ComponentsList: {
      heading: {
        fontStyle: 'italic'
      }
    }
  }
}
```

**Expected behavior**

jss-isolate should not override styles defined by styleguidist or by custom styles.

**Comment by sapegin** [comment]
This is expected behavior, see more details here:

https://react-styleguidist.js.org/docs/development.html#styles-1
