### ISSUE TITLE
[Flow] Problem with union and literal props not displaying correctly

### ISSUE THREAD

**Issue by fseglard** [styleguidist/react-styleguidist#1032]
Hi there!

**Current behavior**
The props table does not correctly display the list of possible values when using Flow.

_When using React PropTypes:_

![proptypes](https://user-images.githubusercontent.com/13200484/42044532-8f3cffda-7af9-11e8-8c13-511ad3b05d80.png)

_When using FlowTypes:_

![flow](https://user-images.githubusercontent.com/13200484/42044554-99ecccb2-7af9-11e8-8777-5635e3f04d0a.png)

It also display the raw output of the Flow definition when hovering the `union` keyword. I don't know if this is the expected behavior, but it seems weird to me:

![test](https://user-images.githubusercontent.com/13200484/42045329-980613d4-7afb-11e8-8484-1aaf058901a0.png)

**To reproduce**

[https://github.com/fseglard/react-styleguidist-example](https://github.com/fseglard/react-styleguidist-example)

**Expected behavior**

We should have a line displaying the list of possible values like with React PropTypes.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix! ;-)

**Comment by stepancar** [comment]
@sapegin @fseglard flow doesn't support enums, but react-docgen [support it](https://github.com/reactjs/react-docgen#result-data-structure) and emits it in case of use
propTypes.oneOf(...). I just implemented rendering of union literals in extra of description.

**Comment by stepancar** [comment]
Also we can consider Flow union of literals as enum.
```
export function getType(prop) {
	if (prop.flowType) {
		if (
			prop.flowType.name === 'union' &&
			prop.flowType.elements.every(elem => elem.name === 'literal')
		) {
			return {
				...prop.flowType,
				name: 'enum',
				value: prop.flowType.elements,
			};
		}
		return prop.flowType
	}
	return prop.type;
}
```
@sapegin what do you think about it

**Comment by sapegin** [comment]
This sounds like a good idea!

**Comment by stepancar** [comment]
@sapegin , ok, PR updated

**Comment by sapegin** [comment]
Out in 7.1.0.
