### ISSUE TITLE
JSDoc methods with optional params with defaults doesn't work

### ISSUE THREAD

**Issue by reintroducing** [styleguidist/react-styleguidist#1038]
**Current behavior**

When documenting public methods in a component, having an optional param with a default value does not properly document the parameter and hides the return documented value from the docs for said method.

**To reproduce**

https://github.com/reintroducing/example

Look at the two methods in the `Placeholder.js` component, `submitWorking` and `submit` when the style guide is generated.

**Expected behavior**

`submit` method documents the optional param with default correctly and the `@returns` shows the return value in the documentation.

**Comment by sapegin** [comment]
It could be a doctrine issue, or the way we use it. Feel free to send a pull request with a fix.

**Comment by stepancar** [comment]
@sapegin it's not doctrine issue. We should calling doctrine passing sloppy parametr. Look at [test](https://github.com/eslint/doctrine/blob/master/test/parse.js#L2245).
But also we should fix params renderer to generate description for optional parametrs.
I'm started working on this issue.

**Comment by stepancar** [comment]
@reintroducing could you please check latest rsg?

**Comment by reintroducing** [comment]
@stepancar Seems to work, thanks, though the output looks like this: `withEmpty: Boolean?=false`. I think the `?` in there is a bit odd looking but thats just personal opinion :)

A cleaner output would be something like `withEmpty: Boolean (false)`, but again, thats personal opinion.

**Comment by stepancar** [comment]
@reintroducing Thank you. I didn't fixed render for jsdoc, I just mapped docgen info to styleguidist. I try to improve description view in the future in another PR

**Comment by reintroducing** [comment]
@stepancar No worries, sounds good, really appreciate you putting in a fix for this.
