### ISSUE TITLE
Styleguidist overrides CodeMirror styles used in components

### ISSUE THREAD

**Issue by smacker** [styleguidist/react-styleguidist#1047]
**Current behavior**

I have a component which uses CodeMirror. When I click "view code" button it gets broken due to this global styles with increased specificity: https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Editor/EditorLoaderRenderer.js#L14

**To reproduce**

Example with a simplified component which uses CodeMirror:
https://github.com/smacker/example

**Expected behavior**

I would expect Styleguidist not mess with my styles.

**Comment by sapegin** [comment]
Something like this may work I guess:

```diff
- '@global': {
- 		'.CodeMirror.CodeMirror': {
+ '& > .CodeMirror.CodeMirror': {
```

Feel free to send a pull request ;-)
