### ISSUE TITLE
Can't resolve 'rsg-components/Wrapper/Wrapper'

### ISSUE THREAD

**Issue by zGrav** [styleguidist/react-styleguidist#1051]
**Current behavior**

`Module not found: Can't resolve 'rsg-components/Wrapper/Wrapper' in '/Users/zgrav/Downloads/reactjs-boilerplate-feature-2018-garage-sale/node_modules/react-styleguidist/lib/rsg-components/Wrapper'`

**To reproduce**

https://github.com/bitchcraft/reactjs-boilerplate/tree/feature/2018-garage-sale

Please do `yarn install` and `yarn run styleguide:build`

**Expected behavior**

Should resolve module properly and build. Changing `react-styleguidist/lib/rsg-components/Wrapper/index.js` to import `./Wrapper` works as intended.

Could this be a configuration issue?

**Comment by sapegin** [comment]
Use `react-styleguidist/lib/rsg-components/Wrapper/index` or `react-styleguidist/lib/rsg-components/Wrapper/Wrapper`.

**Comment by zGrav** [comment]
Thanks 👍
