### ISSUE TITLE
Does react-styleguidist has support for @typedef in jsDoc

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#1053]
https://stackoverflow.com/questions/51354785/does-react-styleguidist-has-support-for-typedef-in-jsdoc

I would like to contribute if this is not available yet.

**Comment by sapegin** [comment]
We don't do anything special for `@typedef`. And I don't know what happens now if you use it ;-) How do you see its support?

**Comment by dinukadesilva** [comment]
@sapegin 
According to jdDoc specifications, it's possible to have custome object tyles defined as below.
```
/**
 * The complete Triforce, or one or more components of the Triforce.
 * @typedef {Object} WishGranter~Triforce
 * @property {boolean} hasCourage - Indicates whether the Courage component is present.
 * @property {boolean} hasPower - Indicates whether the Power component is present.
 * @property {boolean} hasWisdom - Indicates whether the Wisdom component is present.
 */

/**
 * A class for granting wishes, powered by the Triforce.
 * @class
 * @param {...WishGranter~Triforce} triforce - One to three {@link WishGranter~Triforce} objects
 * containing all three components of the Triforce.
 */
function WishGranter(triforce) {}
```
http://usejsdoc.org/tags-typedef.html

But, when this is compiled, it shows nothing in react-styleguidist. No any errors. But, the the custom object type is not visualized in any way. I assume this hasn't been implemented in react-styleguidist.

**Comment by sapegin** [comment]
I think we can show a name of a custom type, if doctrine returns this information. Would be awesome if you can have a look!

Have a look at #1046 — you'll need to change the same place (so you may have conflicts and it may be a good example ;-)

**Comment by stepancar** [comment]
@dinukadesilva 
<img width="928" alt="screen shot 2018-08-10 at 09 11 36" src="https://user-images.githubusercontent.com/2854910/43941668-aad7d814-9c7d-11e8-88a4-901699d93bb7.png">
<img width="621" alt="screen shot 2018-08-10 at 09 11 48" src="https://user-images.githubusercontent.com/2854910/43941669-aaf37560-9c7d-11e8-9674-285d500f89b4.png">
