### ISSUE TITLE
Default Component specification on application load

### ISSUE THREAD

**Issue by sibamohanty995** [styleguidist/react-styleguidist#1058]
The styleguide.config.js picks up the first component listed inside sections in a listwise manner. Is there a way to specifically explicitly mention which component to load when the application renders for the first time.

**Proposed solution**

**Alternative solutions**

**Additional context**

**Comment by sapegin** [comment]
Not sure I understand what you want. Could you show an example of your config, what it renders and what you want it to render?

**Comment by sibamohanty995** [comment]
@sapegin Apologies. i will try to explain with an example :-

Below is my styleguide.config.js code for rendering sections. By default, when the application loads, i see the "Getting Started" section loaded with all 4 sections rendered under it. Is there a way possible that we get to load only one sub-section, like "introduction" or "Hello World" on the initial load of the application, rather than having all the sections loaded together.

```
sections: [{
  "name": "Getting Started",
  "sections": [{
      "name": "Introduction",
      "content": "../docs/Introduction.md"
    },
    {
      "name": "Getting started",
      "content": "../docs/GettingStarted.md"
    },
    {
      "name": "Hello World",
      "content": "../docs/HelloWorld.md"
    },
    {
      "name": "FAQs",
      "content": "../docs/FAQ.md"
    }
  ]
}
```

**Comment by sibamohanty995** [comment]
To make it simple, what i want to ask is, if **pagePerSection** works at a nested level or not, if it does then how do i set it for the nested sections. On the root level, i am able to render only 1 section, but if that section contains sub sections, all of them get rendered at once.

**Comment by rafaesc** [comment]
@sibamohanty995 yes, you can read the documentation here

https://react-styleguidist.js.org/docs/configuration.html#pagepersection

**Comment by sibamohanty995** [comment]
@rafaesc I had thought of this initially, tried all possible combinations but for some reason, there seems to be no change. All the subsections tend to get rendered, no matter what the value of sectionDepth is. Can you please help me out with a working example or demo?

**Comment by rafaesc** [comment]
Sure, here there is an example

https://github.com/styleguidist/react-styleguidist/tree/master/examples/sections
