### ISSUE TITLE
`pagePerSection` stopped working in 7.1.0

### ISSUE THREAD

**Issue by milesj** [styleguidist/react-styleguidist#1059]
**Current behavior**

When `pagePerSection` is true in the config, clicking a link takes you to `/#/Components?id=button` instead of `/#/Button`. This causes the entire components section to render (which is heavy).

**To reproduce**

Add `pagePerSection` true to config.

And my sections config:

```
sections: [
    {
      name: 'Components',
      components: './src/components/!(private)/+([a-zA-Z]).{tsx,jsx}',
    },
    {
      name: 'Kits',
      components: './src/kits/**/index.{tsx,ts,jsx,js}',
    },
  ],
```

Happens to both components and kits.

**Expected behavior**

Loads in separate pages instead of a single page.

**Comment by milesj** [comment]
That fixed it, thanks. Didn't see it listed in the changelog.

**Comment by aversini** [comment]
This is a breaking change right? Shouldn’t RSG version be bumped to 8? My team started to use the url pattern `#!/Button` to run automated tests... they are now all breaking in 7.1.0 😢
