### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1064]
- [x] [Upgrade config and dependencies](https://babeljs.io/docs/en/next/v7-migration.html)
- [ ] Check if we can use automatic polyfills adding in [preset-env](https://babeljs.io/docs/en/next/babel-preset-env) to remove some of the [polyfills](https://github.com/styleguidist/react-styleguidist/blob/master/src/polyfills.js) from our dependencies. I doubt, but it must help with accidental breaking of IE11 by using something like `Array.includes`.
- [x] Check if we still need [uglify flag](https://github.com/styleguidist/react-styleguidist/blob/master/.babelrc#L7), it shouldn't be needed with [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin), that uses uglify-es that don't break on ES6+ syntax.

**Comment by jeffscottward** [comment]
Whats the status on this?
Babel 7 is now fully released

**Comment by sapegin** [comment]
@jeffscottward Thanks! I've updated the ticket. Only the second point is left, but it needs some investigation — would be cool if you can have a look into that ;-)

**Comment by sapegin** [comment]
(Everything is in the `next` branch.)
