### ISSUE TITLE
Combining several components into one Readme.md

### ISSUE THREAD

**Issue by 0xsven** [styleguidist/react-styleguidist#1065]
I am throwing all my icons into one folder, one component each. Like so:

```
components/
  button.js
  Button.md
  icons/
    icon1.js
    icon2.js
    icon3.js
    icon4.js
    ...

```

Is it somehow possible to combine all icons into one `Readme.md` or `Icons.md` file?

**Comment by sapegin** [comment]
Yes and no.

Yes: you can either access globally registered components or `require` them in any Markdown file.

No: you won't see props table.

**Comment by 0xsven** [comment]
Thanks for the reply

So I ended up merging all icons into one file. This is not optimal because of how dead code removal works. Also the styleguide system shouldn't dictate how we write our app. 

More flexibility would probably conflict with how seamless styleguidist works out of the box. 

Closing this.
