### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by duckscofield** [styleguidist/react-styleguidist#1066]
**Current behavior**

page could not render **PROPS & METHODS** block for display.

**To reproduce**

 /**
   * handle input value when typing
   * @param  Object event [description]
   */
  handleInput = (event) => {
    const { value } = event.target;
    this.foundation_.handleInput_(value);
  }

**Expected behavior**

use arrow function(ES6) or use class **_static / get / set_** keywords, the page should have render **PROPS & METHODS** button.
If I remove all comments, it's ok, but I write comment for method, it will fail.

Please @see https://github.com/reactjs/react-docgen/issues/285
I have posted the question to relative package, and he said that he has fixed it.

Thanks a lot.

**Comment by sapegin** [comment]
Feel free to open a pull request with react-docgen update as soon as it's available.
