### ISSUE TITLE
Overriding Slots or UsageTabButton

### ISSUE THREAD

**Issue by sibamohanty995** [styleguidist/react-styleguidist#1070]
I have to segregate my props and methods into 2 different tabs. (Currently, they are all shown under 1 tab).

I have been trying to override UsageTabButton in particular, but have been unable to do so. 

Custom rendering and therefore, overriding doesn't seem to be working for either Slot or contents of slots.

Please let me know if there's a way.

**Comment by sibamohanty995** [comment]
@sapegin Any help will be appreciated. Thank you.

**Comment by sibamohanty995** [comment]
@sapegin Thank you, Will be sending a pull request, Just one last thing.

The styleguideComponents documentation says "Override React components used to **render** the style guide".

Does this specifically mean that only the files whose names end with **Renderer** like ComponentsListRenderer, PropsRenderer, TabButtonRenderer etc will be able to be overriden as such, and files like **UsageTabButton** wont be able to be overriden using the styleguideComponents?

If so, then the following change would still not be able to help in overriding the UsageTabButton file right?

**Comment by sapegin** [comment]
It should work with any component that's imported using the webpack alias `rsg-components`, though we don't recommend overriding non-render components.

**Comment by sibamohanty995** [comment]
@aversini Yes, it did work for me. Actually for other components when you override them in your styleguide.config.js, you just write the *component name to be overriden* : *path of the overriding component*
But for CodeTabButton, since it resides inside the slots folder, you've to write it like this in the styleguide.config.js :-
"slots/CodeTabButton" : *path of the overriding component*

**Comment by aversini** [comment]
Aaah, that makes sense, yes it's working for me too with that syntax, thanks a lot for the tip @sibamohanty995 👍

**Comment by caseycallow** [comment]
@sibamohanty995 Did you have any luck overriding not just a tab button but `slots` itself? I was doing this successfully prior to 7.2.3 in order to add my own HTML tab button, alongside the current React one. Now I get a `Cannot find module 'rsg-components/slots/IsolateButton'` error in my browser, even though I'm not importing it into the new `slots` override file. Let me know if you have any ideas! 🙌
