### ISSUE TITLE
Live Styleguide for a project which is mixture of React and static templates

### ISSUE THREAD

**Issue by neginbasiri** [styleguidist/react-styleguidist#1072]
Hi everyone,

My project is mixture of static templates (generated by EJS or Handlebars) and React components. I would like to have a style guide which bring both into one styleguide (have all the wonderfull feature react-styleguide provides including webpack env, showing code snippet, live update, etc )

I am wondering how to get those static templates integrated into this react style guide?  any example? or possible solution?

**Comment by sapegin** [comment]
Please edit your comment — it's very hard to read now, because you've left part of the template.
