### ISSUE TITLE
PropTypes are not displayed on certain cases

### ISSUE THREAD

**Issue by michelson** [styleguidist/react-styleguidist#1079]
**Current behavior**
+ using version:     "react-styleguidist": "^7.1.3",

### when the PropTypes are from an imported class does not work

**To reproduce**

### This works: build a proxy class and define propTypes on new class
```js
import {default as Wrapper} from '../../editor/components/Dante/Dante'
class Dante extends React.Component {
  render() {
    return <Wrapper {...this.props}/>
  }
}
Dante.propTypes = {
  onClickCreate: PropTypes.number,
}
```

### This does not work (renders component but not the props table)
use the same proxy but try to assign the propTypes from the wrapper class

```js
import {default as Wrapper} from '../../editor/components/Dante/Dante'
class Dante extends React.Component {
  render() {
    return <Wrapper {...this.props}/>
  }
}
Dante.propTypes = Wrapper.propTypes
```

### This does not work either  (renders component but not the props table)

```js
import Dante from '../../editor/components/Dante/Dante'
export default Dante
```

why it works that way ?

**Comment by sapegin** [comment]
https://github.com/reactjs/react-docgen/issues/33

**Comment by michelson** [comment]
hi @sapegin , if I may ask , why this is closed? I've read the issue on doc gen and I've tried the solutions but it does not work. 
is not clear to me how this issue is solved. I have to assume that this is a wont fix ?

**Comment by sapegin** [comment]
This issue was discussed many times before – please use search. It's an issue in react-docgen – feel free to fix it there.

**Comment by sapegin** [comment]
Sorry for closing the issue — it really was discussed before but nobody was interested in actually solving the problem ;-/

Feel free to investigate how Docz does it and open a pull request — I've looked quickly and I don't see where they are doing it.

Have you tried https://github.com/siddharthkp/react-docgen-external-proptypes-handler ?

**Comment by michelson** [comment]
Yes,  I've tried that solution , and it renders the props but the name of
the prop is rendered as a "0"

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>
