### ISSUE TITLE
Table of content is not rendered in v7.2.0

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#1082]
**Current behavior**

Nothing is loaded in the table of content. It's empty

**To reproduce**

**Expected behavior**

The table of content must be loaded as before

**Comment by sapegin** [comment]
> Post a link to a reproducible demo repository here.
> 
>   1. Fork the example project repository: https://github.com/styleguidist/example
>      (please don’t use the main, styleguidist/react-styleguidist, repository).
>   2. Modify it to reproduce the issue.
>   3. Push to GitHub and paste the link here.
> 
> Most likely you’ll find an issue yourself, while creating a demo.
> 
> Make sure you’re using the latest version of React Styleguidist.
> 
> 💀 Issues without a demo will be closed! 💀

**Comment by dinukadesilva** [comment]
@sapegin 
Please find a demo below
https://dinukadesilva.github.io/react-styleguidist/examples/sections/styleguide//index.html

And here is the updated code
https://github.com/dinukadesilva/react-styleguidist

**Comment by sapegin** [comment]
Have you tried 7.2.1?
