### ISSUE TITLE
Some of the links are broken in v7.0.10

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#1083]
**Current behavior**

It goes to wrong urls

**To reproduce**

1. Click any child section from the table of content
2. Click the title of the preview 

![react-styleguide-broken-links](https://user-images.githubusercontent.com/10680296/43888214-ad87ab74-9bde-11e8-985c-45a32f63db35.gif)

[Demo Example](https://github.com/dinukadesilva/react-styleguidist/tree/gh-1083/examples/sections)

**Expected behavior**

It must be directed to the correct url

**Comment by sapegin** [comment]
I can't reproduce it in 7.2.1.

**Comment by dinukadesilva** [comment]
Try running this
https://github.com/dinukadesilva/react-styleguidist/tree/gh-1083/examples/sections

**Comment by sapegin** [comment]
Your branch is using 7.0.10.
