### ISSUE TITLE
Couldn't connect StyleguideRenderer and Wrapper through Redux

### ISSUE THREAD

**Issue by vgnshs2** [styleguidist/react-styleguidist#1088]
I have customized the Styleguide Renderer with some buttons which is related to the features that my library provides to its consumers. I kept these buttons in styleguide renderer because, I need to have only one Button for each feature, but still pressing on it should affect all the examples in that page. I have my owncustomized Wrapper too. But my requirement is, the button click action from styleguide renderer should modify the state in redux store and in turn give the new state to wrapper. But the problem here is, when i see react tree, `Wrapper` is not part of any child level hierarchy to `StyleguideRenderer`. So I couldn't find an exact place, where i should add the Redux's `Provider` component, so that the same store will be available to both customizes `StyleguideRender` and the `Wrapper`.

![image](https://user-images.githubusercontent.com/8816929/44160037-c7c7b680-a0d6-11e8-89fc-5eca1186d64b.png)

In above Image, we can see that `styleguide` and `Example` component are siblings and not parent-child. So please help me on how/where I can add the provider, so that store is available for both. Thanks.

**Comment by sapegin** [comment]
> Post a link to a reproducible demo repository here.
> 
>   1. Fork the example project repository: https://github.com/styleguidist/example
>      (please don’t use the main, styleguidist/react-styleguidist, repository).
>   2. Modify it to reproduce the issue.
>   3. Push to GitHub and paste the link here.
> 
> Most likely you’ll find an issue yourself, while creating a demo.
> 
> Make sure you’re using the latest version of React Styleguidist.
> 
> 💀 Issues without a demo will be closed! 💀

**Comment by martinburford** [comment]
I have exactly the same issue as of April 2019. Please advise how to make a state change within StyleguideRenderer and for that to be available (and passed) to the Wrapper renderer and all demo components.
