### ISSUE TITLE
The browser URL is always blink

### ISSUE THREAD

**Issue by DongShelton** [styleguidist/react-styleguidist#1089]
**Current behavior**

The browser URL is always blink, it is seems like that the route be pushed all the time.

**To reproduce**

Just install the v7.2.3 and run it.

**Comment by sapegin** [comment]
> Post a link to a reproducible demo repository here.
> 
>   1. Fork the example project repository: https://github.com/styleguidist/example
>      (please don’t use the main, styleguidist/react-styleguidist, repository).
>   2. Modify it to reproduce the issue.
>   3. Push to GitHub and paste the link here.
> 
> Most likely you’ll find an issue yourself, while creating a demo.
> 
> Make sure you’re using the latest version of React Styleguidist.
> 
> 💀 Issues without a demo will be closed! 💀
