### ISSUE TITLE
Is there a way to add a table into <details> tag?

### ISSUE THREAD

**Issue by celiolatorraca** [styleguidist/react-styleguidist#1092]
This sample code below does not work when we use it on our examples markdown.

```
<details>
<summary>Click here</summary>

| Heading 1 | Heading 2 |
| --------- | --------- |
| Foo       | Bar       |

</details>
```

Here at github it works...

<details>
<summary>Click here</summary>

| Heading 1 | Heading 2 |
| ---------- | ---------- |
| Foo            | Bar            |

</details>

Am I doing anything wrong?
Maybe there is some configuration to use with `remark` to make it work, isn't it?

**Comment by sapegin** [comment]
Looks like an issue with markdown-to-jsx, please report there. We're not using Remark for rendering.

**Comment by celiolatorraca** [comment]
@sapegin Incredibly, they have already fixed the problem...
Version [6.7.1](https://github.com/probablyup/markdown-to-jsx/releases/tag/6.7.1) was already released!

Do we need a new version of `react-styleguidist` to get this update?

Thanks!

**Comment by sapegin** [comment]
Should be enough to remove the lock file and reinstall dependencies in your project.
