### ISSUE TITLE
[possible feature request / question] Can't use a babel.rc file

### ISSUE THREAD

**Issue by Pixelatex** [styleguidist/react-styleguidist#1098]
The issue I have is that I can't use a babel.rc file because it conflicts with nwb that I use to publish my library.

Without a babel.rc it obviously fails on the react code. 'unexpected token'... etc

I can't seem to find any options in the config to inject a babel config. Did I overlook this or is there some other solution to my issue>

**Comment by sapegin** [comment]
It's _your project_ webpack config, Styleguidist has very little restrictions here, described in the docs. Babel isn't one of them.
