### ISSUE TITLE
Dynamic property prints function name instead of array

### ISSUE THREAD

**Issue by saschb2b** [styleguidist/react-styleguidist#1101]
**Current behavior**
I have an icon component which takes various names as a property and I don't want to list all of them by hand. So I generated them. Sadly styleguidist doesn't print the generated array in the property description.

**To reproduce**
```
function generateIconNames() {
  const names = [];
  fontelloConfig.glyphs.forEach(g => {
    names.push(g.css);
  });
  return names;
}

Icon.propTypes = {
  className: PropTypes.string,
  color: PropTypes.oneOf(['default', 'inherit', 'primary', 'secondary']),
  name: PropTypes.oneOf(generateIconNames()),
  size: PropTypes.oneOf(['small', 'medium', 'large']),
};
```

![image](https://user-images.githubusercontent.com/2778161/44531850-09b5b580-a6f2-11e8-9759-6683f558c353.png)

**Expected behavior**

I want to see the full generated array list in the property description

**Comment by sapegin** [comment]
It's likely very hard to implement because react-docgen is using static analysis. But feel free to send a pull request.
