### ISSUE TITLE
Customised example rendered twice title.

### ISSUE THREAD

**Issue by MrKou47** [styleguidist/react-styleguidist#1102]
**Current behavior**
![img](https://preview.ibb.co/dSe7Np/Wechat_IMG62.jpg)

```sh
git clone 
npm install
npm run compile
npm run start:customised
```
**To reproduce**

**Expected behavior**
Just rendered as expect.

**Comment by sapegin** [comment]
I guess we need to remove the extra title from one of the custom components in this example.
