### ISSUE TITLE
Not all Flow Props do not render for styled-components. Only defaultProps show

### ISSUE THREAD

**Issue by ryanfabela** [styleguidist/react-styleguidist#1104]
_I am not sure if this is the correct library or if this should go under react-docgen or styled-components. Thank you for your patience_

**Current behavior**

When using flow typing with styled-components, exporting the result of ` styled.div`` `, styleguidist only shows the defaultProps but does not render any from `type Props`

Example:
![image](https://user-images.githubusercontent.com/2537590/44599598-7c7b6b00-a79c-11e8-8bd0-0afec44a3da0.png)

**To reproduce**

```jsx
type Props = {
    /** determines color of hr. Can pass hex as well */
    revColor: string,
    /** allows to customize styles, overwriting defaults */
    customStyles?: string | TaggedTemplateLiteral<any>,
    /** Size to use for margin */
    revSize: number | string
};

const defaultProps = {
    revColor: 'secondary',
    revSize: 'medium'
};

const borderColor = ({ revColor }) => revColor;

const HR: ReactComponentFunctional<Props> = styled.div`
    border-top: 1px solid ${props => transparentize(0.7, borderColor(props))};
    margin: ${props => props.revSize - 4 + 'px'} 0;
    width: 100%;
    height: 0;
    ${props => props.customStyles};
`;

HR.defaultProps = defaultProps;

/**
 * @component
 */
export default compose(
    withRevolution,
    withRevSize,
    withRevColor
)(HR);
```

Instead I must modify the last line to:
```jsx
export default compose(
    withRevolution,
    withRevSize,
    withRevColor
)((props: Props) => <HR {...props} />);
```

Which causes React to render an additional component, `<Unknown />`, in React dev tools

**Expected behavior**
![image](https://user-images.githubusercontent.com/2537590/44599860-3ffc3f00-a79d-11e8-891a-c327e1333741.png)

Instead it should detect the Props types and render as is done with conventional functional components.

Or maybe I just made a mistake in my usage but, after much research and reading, I could not find a solution that works correctly. Any guidance on this issue would be great. Thank you

**Comment by sapegin** [comment]
Could you check which version of react-docgen-annotation-resolver you have (`npm ls react-docgen-annotation-resolver`)? They've added HoCs support that recently.

**Comment by ryanfabela** [comment]
1.1.0 according to the output below
```
└─┬ react-styleguidist@7.2.1
  └── react-docgen-annotation-resolver@1.1.0
```
