### ISSUE TITLE
Importing RSG components to a different standalone Create React App

### ISSUE THREAD

**Issue by gyaneshgouraw** [styleguidist/react-styleguidist#1112]
I  am using react-styleguidst as a stand alone components library. I am finding it difficult to utilize those components in different apps.

- How do we import these components ?

- Can somebody share any example, who has followed this pattern?

**Comment by sapegin** [comment]
What have you tried? What exactly isn't working?

**Comment by gyaneshgouraw** [comment]
Using RSG example `basic`  I have created  components library.
I have a separate application, where i want to export these working components.

I included `basic` example as a dependency in new project.
Now in new project if i want to access these components i get error.
`Required loaders not found`

**Comment by sapegin** [comment]
I have no idea what you're trying to achieve but you definitely shouldn't use our example as a dependency. What preventing you from using Styleguidist in a normal way?
