### ISSUE TITLE
Add tags to the components list

### ISSUE THREAD

**Issue by gazpachu** [styleguidist/react-styleguidist#1114]
It would be cool if we could add tags to the components list, so we could specify their status or what is missing, like `WIP`, `example`, `props`, `docs`.

Something like this:

![screen shot 2018-08-30 at 10 25 10](https://user-images.githubusercontent.com/1721288/44839837-0f565280-ac40-11e8-9a44-ea5ed0b3f1f2.png)

I've tried to hack it targetting the generated class names for the `ul` and `li` items in the list, but it gets translated from this:

```
.rsg--item-69:nth-child(2) {
    background: red;
  }
```

to this:

```
  ._3_veETGqo6h-GGUgi_7XhI:nth-child(2) {
    background: red;
  }
```

Anyway, that's not even a solid way of doing it. So any tip would be welcome :)

**Comment by sapegin** [comment]
You can replace any Styleguidist UI component:

https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide

**Comment by gazpachu** [comment]
Thanks, that should be enough!

**Comment by FezVrasta** [comment]
@gazpachu how do you decide when to show a given badge?

**Comment by FezVrasta** [comment]
Oh I see, thanks
