### ISSUE TITLE
How can I change the base patch of the production build JS file?

### ISSUE THREAD

**Issue by gazpachu** [styleguidist/react-styleguidist#1118]
My styleguide in production sits inside a subfolder within my domain name, i.e. `http://domain.tld/folder`. This means that the generated `index.html` has the incorrect path that points at the generated JS file: `<script src="build/bundle.68155630.js">`. I would need to add `folder` to the path, so that it becomes: `<script src="folder/build/bundle.68155630.js">`.

Thanks

**Comment by sapegin** [comment]
The path is relative to the HTML file. What exactly is the issue here?

Styleguidist works fine in a subfolder: https://react-styleguidist.js.org/examples/basic/

**Comment by sapegin** [comment]
You need to fix your server setup, and this is not the best place for such questions.
