### ISSUE TITLE
Styleguidist server doesn't work with awesome-script-loader

### ISSUE THREAD

**Issue by fnky** [styleguidist/react-styleguidist#1129]
**Current behavior**

Using `awesome-script-loader` with webpack 4 doesn't work when running styleguidist server. This is due to `awesome-script-loader` requiring webpack 4 and `webpack-dev-server@2.11.2` uses webpack 3.

**To reproduce**

Run `styleguidist server` with a webpack config that uses the `awesome-script-loader` loader.

Example project with TypeScript and `awesome-typescript-loader`:

https://github.com/fnky/example

**Expected behavior**

To successfully compile and start the server.

**Comment by fnky** [comment]
This can be circumvented if you install webpack 4 in your repository.

For people using frameworks like NextJS, which doesn't explicitly require webpack to be a dependency, simply add it to fix the issue.

**Comment by sapegin** [comment]
Installing your own webpack is the best solution here, yeah.
