### ISSUE TITLE
Side navigation broken in 7.3.6

### ISSUE THREAD

**Issue by Darrken** [styleguidist/react-styleguidist#1132]
**Current behavior**
Out of 6 parent sections in my sidebar only 3 are displaying, and none of their component links are showing up.

**To reproduce**

This section is taken from my styleguide.config.js, which has been working through 7.3.5:

```
  sections: [
    {
      name: 'Themes',
      content: path.join(baseComponentDir, 'theme/Themes.md')
    },
    {
      name: 'Base',
      components: path.join(baseComponentDir, 'base/**/*.js')
    },
    {
      name: 'Containers',
      content: path.join(baseComponentDir, 'containers/Containers.md'),
      components: path.join(baseComponentDir, 'containers/**/*.js')
    },
    {
      name: 'Controls',
      components: path.join(baseComponentDir, 'controls/**/*.js')
    },
    {
      name: 'Navigation',
      components: path.join(baseComponentDir, 'navigation/**/*.js')
    },
    {
      name: 'Patterns',
      content: path.join(baseComponentDir, 'patterns/Patterns.md'),
      components: path.join(baseComponentDir, 'patterns/**/*.js')
    }
  ],
```

**Current behavior 7.3.6**
![7 3 6](https://user-images.githubusercontent.com/797074/45314402-dabf8200-b4ee-11e8-9d1d-8f0918e31b53.PNG)

**Expected behavior (7.3.5)**
![7 3 5](https://user-images.githubusercontent.com/797074/45314380-cd09fc80-b4ee-11e8-95bc-029b0c2b6c4b.PNG)

I should note that the components themselves are also not rendering in the main content area. Just the headings.

**Comment by sapegin** [comment]
To clarify: you only see sections with `content`, but none of the component pattern works? Do you see contents of your Markdown files (`Themes.md`, etc.)?

Are you on Windows? It's must be cased by #1128. 

/cc @elevatebart

**Comment by elevatebart** [comment]
I agree, it might have to do with the simplification I made in getComponentFiles.js.
It is probable that specifying the cwd instead of giving the full path to look for items messed with the returned results.

Before:
```js
return glob.sync(path.resolve(rootDir, listItem), { ignore });
```

After
```js
return glob.sync(listItem, {cwd: rootDir, ignore});
```

I will have a look

**Comment by elevatebart** [comment]
Thanks, I will have look after lunch.

**Comment by elevatebart** [comment]
@Darrken After testing with your repo, all seems to point to a [windows/node glob issue](https://github.com/isaacs/node-glob/issues/161). 
What makes it fail on your repo is exactly what made the default `{Components,components}` glob work for the standard. I will investigate further and if needed revert the change.
