### ISSUE TITLE
[Docs] config for CRA with typescript (react-scripts-ts) includes webpack version that is incompatible

### ISSUE THREAD

**Issue by jamsch** [styleguidist/react-styleguidist#1134]
Started a new create-react-app project with react-scripts-ts and noticed that the [installation guide](https://react-styleguidist.js.org/docs/webpack.html#create-react-app-with-typescript) says to use the following config:

```javascript
module.exports = {
  propsParser: require('react-docgen-typescript').parse,
  webpackConfig: require('react-scripts-ts/config/webpack.config.dev')
}
```

The problem with the above config is that react-scripts-ts@next still uses webpack 3.8.1 while styleguidist currently uses webpack 4.15.1. This probably should be removed from the docs or point to a relevant webpack config package for typescript.

**Comment by sapegin** [comment]
Feel free to send a pull request to fix that!

**Comment by bebraw** [comment]
@jamsch Note that CRA is close to version 2 which will come with webpack. That should fix some things although a config PR is likely welcome.
