### ISSUE TITLE
Sidebar not loading with multilevel sections

### ISSUE THREAD

**Issue by Acesmndr** [styleguidist/react-styleguidist#1137]
**Current behavior**
Having multilevel sections results in no items in the sidebar.

**To reproduce**
```js
const COMPONENTS = [
  'Avatar',
  'Text',
].map(component => ({
  name: component,
  components: `src/components/${component}/[A-Z]*.js`,
}));

module.exports = snapguidist({
  title: 'UI Foundation',
  sections: [
    {
      name: 'UI Components',
      content: 'src/docs/components.md',
      sections: COMPONENTS,
     }
  ],
 ...
});
```
results in a empty sidebar.
![screen shot 2018-09-13 at 3 50 07 pm](https://user-images.githubusercontent.com/4254571/45482061-c8527c00-b76c-11e8-9caa-dbedd4d58162.png)
But removing the uppermost section solves the issue but it would mean that I would no longer get to add documentation.
```js
module.exports = snapguidist({
  title: 'UI Foundation',
  sections: COMPONENTS,
  ...
});
```

**Expected behavior**
![screen shot 2018-09-13 at 3 54 32 pm](https://user-images.githubusercontent.com/4254571/45482295-5cbcde80-b76d-11e8-8493-d43a7c10d86a.png)

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**

**Comment by stonebk** [comment]
@Acesmndr, a workaround I found is to add an empty object to the sections array:

```diff
const COMPONENTS = [
  'Avatar',
  'Text',
].map(component => ({
  name: component,
  components: `src/components/${component}/[A-Z]*.js`,
}));

module.exports = snapguidist({
  title: 'UI Foundation',
  sections: [
    {
      name: 'UI Components',
      content: 'src/docs/components.md',
      sections: COMPONENTS,
-   }
+   }, {}
  ],
 ...
});
```
