### ISSUE TITLE
Sections with href don't render correctly in sidebar

### ISSUE THREAD

**Issue by reintroducing** [styleguidist/react-styleguidist#1141]
**Current behavior**

When using href in a section the sidebar does not render correctly.

**To reproduce**

Given the following section:
```
{
    name: 'Product (Internal)',
    content: 'config/style-guide/sections/product/introduction.md',
    sections: [
        {
            name: 'Design',
            href: 'https://sites.google.com/spothero.com/product-design/design-systems',
            external: true
        },
        {
            name: 'Web Pattern Library',
            href: 'https://spothero.invisionapp.com/share/CQL70LPMV3D#/screens',
            external: true
        }
    ]
},
```

You get the following output: 

![](https://uc1697bbd438fe7e7b64dcd4f508.previews.dropboxusercontent.com/p/thumb/AAOXSQzEwxzL34xuVqoE3izQF8i1CPiHgNo8mkOPgPp4Qn_zc_CdEqc4asPQzVImFdD54DEyGPQDMsiym6yPLuvyQ6PfLwwV-jfniWheDRzi8WCwL_55EpgPADhXcgFow8cD1KK2e7bpeLMEX8T-gmiiQ2zk5iQ7s1rQZHv39OE6Qm0a3DZCQgSqm7gYDk2Gbw7wbI3yBqxGMCe0fD8f0sDN2TW-VZWI00PHyVf5m7Vkdw/p.png?size=2048x1536&size_mode=3)

**Expected behavior**

Simply changing to this section code:
```
{
    name: 'Product (Internal)',
    content: 'config/style-guide/sections/product/introduction.md',
    sections: [
        {
            name: 'Design',
            content: 'config/style-guide/sections/styling/colors.md'
        },
        {
            name: 'Web Pattern Library',
            content: 'config/style-guide/sections/styling/responsive.md'
        }
    ]
},
```

You get the following, correct display: 

![](https://ucdebc25653ea69fedc8d0ad5852.previews.dropboxusercontent.com/p/thumb/AANh-42QCSuqPzuTp1u_npLOPEEnB5q4fWBnnFXPtUoD878E26sCrsqViCra_3oi_whX9Yee0ut0HpsGNrosNjnXNWrXsEgmETb5vgBxWAyYgmmu2SpQUOwSttFwPFs76KU_H0dMgbfQGq7TOxSgLpsUxFnvdLwQ4jXajaDP_0wKmXNJP2z55ZOYdchpTj9x6zc0wdUc4v019L6UZ7NTnuU4I_ETxcjgq8wJNozFf7cULg/p.png?size=2048x1536&size_mode=3)

When I inspect the incorrect code Product heading in the sidebar, i see that it has an `isChild` class applied to it for some reason.

**Comment by arshadkazmi42** [comment]
I am taking this up

**Comment by arshadkazmi42** [comment]
@sapegin I have made the changes you suggested, but many test cases are failing. Below is the error message and code changes snapshots

<img width="1680" alt="screen shot 2018-10-05 at 10 58 14 pm" src="https://user-images.githubusercontent.com/4654382/46550334-5ba54a00-c8f2-11e8-90b3-8a5a6d649950.png">
<img width="719" alt="screen shot 2018-10-05 at 10 58 27 pm" src="https://user-images.githubusercontent.com/4654382/46550335-5c3de080-c8f2-11e8-89d9-d04016ee4029.png">
<img width="800" alt="screen shot 2018-10-05 at 10 58 46 pm" src="https://user-images.githubusercontent.com/4654382/46550337-5c3de080-c8f2-11e8-99c0-f20619ca16ca.png">

**Comment by sapegin** [comment]
@arshadkazmi42 It's impossible to see what changes you did on these screenshots and why other five tests are failing. The first failure: if this changes is desired, you need to updated the snapshot — https://github.com/styleguidist/react-styleguidist/blob/master/.github/Contributing.md#development-workflow

**Comment by arshadkazmi42** [comment]
@sapegin updating the snapshot fixed it. all tests are passing now. creating a PR

**Comment by arshadkazmi42** [comment]
Oh. I think I created a branch from `master`, it was supposed to be from `next` thats why its giving these many conflicts.

Is there a way to update that? Or should I go for a new PR?

**Comment by arshadkazmi42** [comment]
@reintroducing I got busy, haven't got a chance to look into this again.
It can be made open for other contributors to grab.

**Comment by eragon512** [comment]
I'd like to take up this issue if its available
