### ISSUE TITLE
Isolating RSG Dependencies from Root package.json

### ISSUE THREAD

**Issue by ryanfitzer** [styleguidist/react-styleguidist#1144]
I'd like to keep the dependencies that I use for RSG separate from my root `package.json`. Doing so results in a ` FAIL  Failed to compile` error.

My basic directory looks like the following:

```
├── .babelrc
├── components
├── node_modules
├── package.json
├── static
└── styleguide
    ├── node_modules
    ├── package.json
    └── styleguide.config.js
```

When RSG and `styleguide.config.js` are in the root, everything works fine. But when installed in a subfolder, I'm not able to compile jsx:

```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /Applications/MAMP/htdocs/Starbucks/2018/Repos/strbks-archive-fe/components/nav/index.js: Unexpected token (6:4)

  4 |
  5 | const Nav = () => (
> 6 |     <nav>
    |     ^
  7 |         <ul>
  8 |             { links.map( ( link ) => {
  9 |
```

I've looked through all the config options but I didn't find one that might be relevant to this requirement. Is this possible?

**Comment by sapegin** [comment]
How do you run Styleguidst? I think you need to `cd` to that folder first:

```
cd styleguide && npx styleguidist server
```

**Comment by ryanfitzer** [comment]
I forgot to mention that am running the command from that directory.

**Comment by sapegin** [comment]
Styleguidist doesn't have any relation to babel, it's your project's Babel that you have in your project's webpack config, so you should debug that.

I don't know what problem you're trying to solve with a separate `package.json` though — personally I'd start here, you likely don't need it ;-)

**Comment by ryanfitzer** [comment]
@sapegin Thanks for your quick responses!

> Styleguidist doesn't have any relation to babel

For some reason, I assumed that Styleguidist was responsible for loading the root Babel config, even though this is not stated anywhere in the documentation. Once I realized that, I updated `styleguide/styleguide.config.js` to set the `babel-loader` `root` option correctly and everything worked:

```js
module.exports = {
    components: '../components/*/index.js',
    webpackConfig: {
        module: {
            rules: [
                {
                    test: /\.jsx?$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader',
                    options: {
                        root: '../'
                    }
                }
            ]
        }
    }
};
```
