### ISSUE TITLE
No way to annotate `styled-components` prop types with flow alone

### ISSUE THREAD

**Issue by omninonsense** [styleguidist/react-styleguidist#1147]
### The problem

When using `styled-components` and flow, there is no way to document prop types (that I am aware off). 

What I have tried:

~~~js
// @flow
import styled from 'styled-components'

type Props = {
  color?: string
}

/**
 * This describes the component
 *
 * @param {string} [color] - This describes the prop (doesn't work!)
 */
const Hello = styled.div`
  font-family: sans-serif;
  padding: 10px;
  color: ${(props : Props) => props.color };
`

Hello.defaultProps = {
  color: 'transparent'
}

/** @component */
export default Hello
~~~

`Hello.defaultProps` works to an extent - It creates the "props and methods" table with names and defaults, but no types or descriptions.

---

This example works fine, but it requires creating an "useless" component solely for the purpose of documentation:

~~~js
// @flow
import * as React from 'react'
import styled from 'styled-components'


type Props = {
  /** This describes the prop */
  color?: string
}

const HelloDiv = styled.div`
  font-family: sans-serif;
  padding: 10px;
  color: ${(props : Props) => props.color };
`

/**
* This describes the component
*/
const Hello = (props : Props) => <HelloDiv {...props} />

Hello.defaultProps = {
  color: 'transparent'
}

export default Hello

~~~

### Proposed solution

I think the first example I provided would be the best (and most intuitive) way of making this work, in combination with the `@component` docklet tag also being present.

### Alternative solutions

-  it would be nice if we could put the doclet tag where the component is being defined rather than exported, and then have something like this:
defalt

~~~js
// @flow
import styled from 'styled-components'

/**
 * Component description
 * 
 * @component
 * @args {string} [color] - Prop description
 */
const Hello = styled.div`
  font-family: sans-serif;
  padding: 10px;
  color: ${(props : Props) => props.color };
`

export default Hello
~~~

---

- Possibly have a special/"magic"  exported flow type called `PropTypes`? Not sure how hard this would be to implement, and it's also my least favourite solution.

**Comment by sapegin** [comment]
I don't really see how we can detect which type are you using to describe component props. So maybe something like this could work:

```js
/**
 * @component
 * @type Props
 */
```

But I don't know how to implement that, so will appreciate any help.

**Comment by omninonsense** [comment]
> I don't really see how we can detect which type are you using to describe component props

I am aware there's no way to detect the flow type being used. That is why one of the suggestions was to simply expose the props described in JSDoc comments via `@arg`/`@param`, which would have special meaning in conjugation with `/** @component */`.

> So maybe something like this could work:
> ```js
> /**
>  * @component
>  * @type Props
>  */
> ```

I like this idea a lot! A more succinct way might be  `/** @component Props */`. I wonder how difficult that would be to implement.

**Comment by omninonsense** [comment]
Another idea is to have another JSDoc tag called `/** @props */`, used like this:

~~~js
/** @props */
type Props = {
  color?: string
}
~~~

**Comment by omninonsense** [comment]
BTW, I realise this is _quite_ an uncommon edge case. Also, there is an easy workaround of wrapping the styled component into a functional component.

So, I won't be too surprise if the issue gets put on the back burner or even closed. :)

**Comment by omninonsense** [comment]
Ah, this issue is closely related to #1104.

**Comment by FezVrasta** [comment]
This is still an issue for me. I think the actual place where this should get fixed is the docgen, it should allow to do:

```
const Foo: React.StatelessFunctionalComponent<Props> = styled.div``;
```

and expose the `Props` passed to the Foo type.

**Comment by Gisleburt** [comment]
As a temporary work around, I've manually adding a table to the example markdown file.

README.md:
```markdown
|Prop name|Type  |Default|Description|
|---------|------|-------|-----------|
|id       |string|       |           |

Example:

...
```

This is undesirable as it does not match the style of the styleguidists tables, and would need to be kept up to date manually, but at least the information is given.
