### ISSUE TITLE
Can't install using npm

### ISSUE THREAD

**Issue by jochec** [styleguidist/react-styleguidist#1153]
I am not able to install react-styleguidist using `npm install --save-dev react-styleguidist` with following error:
`npm ERR! code E404
npm ERR! 404 Not Found: styleguidist@latest
`
Installing other packages works without problem. I have tried to remove node_modules and install them all again, but with no luck.

Full npm log:
[2018-09-30T10_44_51_768Z-debug.log](https://github.com/styleguidist/react-styleguidist/files/2431461/2018-09-30T10_44_51_768Z-debug.log)

I am on Ubuntu 18.04.

What is the problem?

Thanks.

**Comment by sapegin** [comment]
Please report issues with npm to npm.
