### ISSUE TITLE
Component naming clash

### ISSUE THREAD

**Issue by yoerivdm** [styleguidist/react-styleguidist#1156]
I have a component named Date.jsx ... just found out the name is causing an error while starting Styleguidist:

> index.js:117 Uncaught TypeError: Date.now is not a function
>     at index.js:117
>     at Array.onProcessRule (index.js:153)
>     at PluginsRegistry.onProcessRule (PluginsRegistry.js:80)
>     at Array.forEach (<anonymous>)
>     at RuleList.process (RuleList.js:184)
>     at new StyleSheet (StyleSheet.js:93)
>     at Jss.createStyleSheet (Jss.js:164)
>     at createStyleSheet.js:8
>     at memoized (memoize.js:65)
>     at new _class (Styled.js:81)

I placed a breakpoint which leads me to:
![image](https://user-images.githubusercontent.com/2699806/46337029-cfaecc00-c62c-11e8-9f92-2f825bba439f.png)

When hovering Dat in the closure, it says Date.jsx which is a ref to a component instead of to the built-in Dat object.

I didn't find naming guidelines in the docs, maybe adding such would be usefull ... as is resolving the issue.

**Comment by sapegin** [comment]
This will be fixed in the next major release.
