### ISSUE TITLE
Problem displaying components in section where one component shares section name

### ISSUE THREAD

**Issue by akramer24** [styleguidist/react-styleguidist#1157]
I have a section named `Form`, which has several components. One component is named `Form.js`. No matter which component I click on in the sidebar, I always see `Form.js` and not the component I'd expect. The URL changes accordingly but the page does not (pictured at the bottom). For other sections, I have no problem rendering the appropriate component documentation.

This is my config for the `Form` section:
`{
      name: 'Form',
      components: 'src/lib/Form/**/[A-Z]*.js',
      exampleMode: 'expand',
      usageMode: 'expand'
    }`

<img width="860" alt="screen shot 2018-10-02 at 4 52 08 pm" src="https://user-images.githubusercontent.com/29418145/46376259-8d54b180-c663-11e8-8ac4-27475aa32ebe.png">

**Comment by akramer24** [comment]
Can anyone please help? @sapegin?

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**

**Comment by akramer24** [comment]
@sapegin here's the reproduced problem https://github.com/akramer24/example
