### ISSUE TITLE
CRA 2.0 generates a warning

### ISSUE THREAD

**Issue by DavidHenri008** [styleguidist/react-styleguidist#1162]
**Current behavior**

When I call the `yarn styleguide` the styleguidist process is launched but I get the following warning message:
> Warning: No webpack config found. You may need to specify "webpackConfig" option in your style guide config:
> https://react-styleguidist.js.org/docs/webpack.html

According to the documentation, since I am using create-react-app the config should be "already included".
As a note, my application is based on create-react-app but I ejected it. However, I did not made major changes to the webpack config.

**To reproduce**

1- Create a new application using create-react-app 2.0.
2- Eject new application.
2- Add styleguidist to the application.
3- Add the npm script to the package.json.
4- Run the `yarn styleguide` command.

**Expected behavior**

I am not expecting to see any warning.

Thanks.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.

**Comment by DavidHenri008** [comment]
Well I'd like to but I am fairly new to webpack and react and I have no idea of the root cause. Moreover, at the moment styleguidist throws an error with my setup (cra 2.0) and I want to try a bit more before filing a new issue.

**Comment by DavidHenri008** [comment]
I finally figured this out...
First, it has nothing to do with CRA 2.0, the issue was reproducible with CRA 1.0.
The issue is related with the ejected CRA. Once ejected the webpack config cannot be found.
The solution is simple: add a styleguidist config file `styleguide.config.js` with the following content:
```js
// Indicate to Styleguidist where to find the webpack config file.
module.exports = {
  webpackConfig(env) {
    if (env === 'development') {
      return require('./config/webpack.config.dev.js');
    }
    return require('./config/webpack.config.prod.js');
  }
}
```
