### ISSUE TITLE
"you can't wrap the whole styleguide"

### ISSUE THREAD

**Issue by benwiley4000** [styleguidist/react-styleguidist#1168]
**The problem**

The docs say ["you can't wrap the whole styleguide because every example is compiled separately in a browser"](https://github.com/styleguidist/react-styleguidist/commit/ad96db8f6587bdbdee97fa724d3d3d6c937e3b7b#diff-1e290ac8433d555bce009b162cb869d0R267). How dramatic of a change would it be to change this so you *can* wrap the whole styleguide? I would *really* like to be able to do that.

**Additional context**

I'm rendering docs for a media player toolkit where it would be nice to be able to render example control components which all manipulate the same global media.

**Comment by benwiley4000** [comment]
Hm, actually it seems like this works, haha.

**Comment by benwiley4000** [comment]
Hmm, so my original problem turned out to be that I just wasn't overriding components correctly, but contrary to what I said earlier, the flagged issue isn't fixed. The note in the docs is correct.

I was able to hack around this using some global variables. But it would be great if there could be first class support for this sort of thing.

**Comment by sapegin** [comment]
If you know a way to do that without changing _each example is a separate React app_, feel free to send a pull request ;-)

**Comment by benwiley4000** [comment]
Aha - I guess the isolation is intentional. Nevermind then! :)
