### ISSUE TITLE
Examples not found

### ISSUE THREAD

**Issue by DavidHenri008** [styleguidist/react-styleguidist#1169]
**Current behavior**
In some conditions, the examples are not found by Styleguidist.

The examples are found when:
- the component filename is ComponentName.js and the example filename is ComponentName.md
- the component filename is index.js and the example filename is Readme.md

The examples are **not** found when:
- the component filename is index.js and the example filename is ComponentName.md

**To reproduce**
1. Create new project using create-react-app.
2. Add Styleguidist package.
3. Add new basic React component following the following folder structure:
    src -> components -> ComponentName
4. Make sure the component filename is index.js.
5. Add a ComponentName.md example file in the ComponentName folder.
6. Run Styleguidist.

See example [HERE](https://github.com/DavidHenri008/Styleguidist-example).

**Expected behavior**
I am expecting, as stated by the documentation, that the examples to be found if the file is inside the component folder and it is named Readme.md or ComponentName.md.

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**

**Comment by DavidHenri008** [comment]
I will add a demo today.
Thanks.

**Comment by DavidHenri008** [comment]
@sapegin I added a link to a fork in the **To reproduce** section of my initial entry.
