### ISSUE TITLE
Support for anchor tags within page per section

### ISSUE THREAD

**Issue by Spenc84** [styleguidist/react-styleguidist#1187]
Hi I've gone through all of your documentation multiple times and searched the web quite extensively and have not been able to find an answer to the following question:

With page per section enabled, while on a component's page, how do you link to anchor tags on that page?

Some of our components have quite a bit of documentation and it would be really helpful to be able to display links at the top of the component's page that jump to anchors on that page. Initially we could simply append '#<anchorName>' to the url and that initially worked. Unfortunately a few versions later that stopped working, and we had to switch to appending '?id=<anchorName>' which also only worked for a version or two, and now I can't seem to figure out how to link to a page anchor, or if that's even possible at this point.

Page anchors are a fairly important part of a good user experience, so I'm assuming that there is some way to do this, and the lack of documentation leads me to believe that perhaps I'm just the only one that hasn't been able to figure this out?

On an additional note, I've noticed that when switching from one page section to another that the scroll bar doesn't jump back to the top of the new page as it ought to? If both components have extensive documentation and you were near the bottom of the first component's page, you will be near the bottom of the second component's page after navigation. Is this also related to the anchor problem?

**Comment by sapegin** [comment]
I think your feedback will be useful in this issue — #1145. Page per section feature is far from perfect now.
