### ISSUE TITLE
Inline JavaScript comments don’t work in template.body.raw

### ISSUE THREAD

**Issue by jaller94** [styleguidist/react-styleguidist#1189]
Trimming template’s white spaces messes with JavaScript inline comments.

https://github.com/styleguidist/react-styleguidist/blob/e59671d4d4f1d57e89e5d731942d616458f492b4/scripts/make-webpack-config.js#L29

The line above removes all white spaces, including new lines. This comments every line after `//` inside a `<script />`.

Demo: https://github.com/jaller94/demo-react-styleguidist-js-inline-comment

**Expected behavior**
Inline comments in `script` node should not break the script.

My suggestions of how to fix this:
* Remove (inline) comments before trimming white spaces.
* Don’t trim new lines.
* Don’t trim any white spaces.
* Transform them to `/* comment */` before trimming white spaces.

**Comment by sapegin** [comment]
> Don’t trim any white spaces.

The templates are usually to small to care about whitespace I think. Feel free to send a pull request!

**Comment by dougmackenzie** [comment]
I've managed to reproduce this with the basic example, but changes to the make-webpack-config.js file don't seem to have any effect (so removing the `trimWhitespace: true` doesn't fix it)- what am I missing? 🤔

**Comment by tonyjmartinez** [comment]
@sapegin This looks like it's actually a problem with [mini-html-webpack-plugin](https://github.com/styleguidist/mini-html-webpack-plugin). Am I on the right track?

**Comment by tonyjmartinez** [comment]
Here's what I have so far. I moved the options to remove whitespace to the **html-minify** config.

```
const template = isFunction(config.template) ? config.template : MiniHtmlWebpackTemplate;
const templateContext = isFunction(config.template) ? {} : config.template;
const htmlPluginOptions = {
	context: Object.assign({}, templateContext, {
		title: config.title,
		container: config.mountPointId,
		// trimWhitespace: true,
	}),
	template: context =>
		minify(template(context), {
			collapseWhitespace: true,
			preserveLineBreaks: true,
		}),
	// template,
};
```

Here's what the result from your example looks like.

```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>React Styleguidist Style Guide</title>
</head>
<body>
<div id="rsg-root"></div>
<script>
function works() {
    		/* Opening and closing comments are fine */
    		console.log('Opening and closing comments work!');
    	}
    	works();
</script>
<script>
function breaks() {
    		// This comment will break the script, because everything after will be in the same line.
    		console.log('Inline comments work too. Good job!');
    	}
    	breaks();
</script>
<script src="build/main.bundle.js"></script>
</body>
</html>
```

I based this off an example from [mini-html-webpack-plugin](https://github.com/styleguidist/mini-html-webpack-plugin)

```
const minify = require('html-minifier').minify;
const MiniHtmlWebpackPlugin = require('mini-html-webpack-plugin');

const config = {
  plugins: [
    new MiniHtmlWebpackPlugin({
      context: {
        title: 'Minification demo'
      },
      template: context =>
        minify(MiniHtmlWebpackPlugin.defaultTemplate(context))
    })
  ]
};
```
