### ISSUE TITLE
Passing custom data throughout the app/config

### ISSUE THREAD

**Issue by milesj** [styleguidist/react-styleguidist#1191]
**The problem**

I'm using `git log` to display new/updated/experimental features, but I'm unable to set/access this data anywhere in SG components.

I tried passing it in each section in `sections`, but the data is lost here: https://github.com/styleguidist/react-styleguidist/blob/master/loaders/utils/getSections.js#L62

I tried passing it as a property in `styleguide.config.js`, but the config schema won't allow unknown properties.

I tried setting a global through webpack, which also didn't work.

**Proposed solution**

Allow custom data either within the root config or within each section.

**Alternative solutions**

At the moment, I'm setting values in `editorConfig`, which I can then consume in the `StyleGuide` component. Super janky but it works for now.

**Additional context**

N/A

**Comment by sapegin** [comment]
What kind of data you’re passing? There was a proposal to support frontmatters for Markdown files. Will that work for you?

**Comment by milesj** [comment]
Not really, I need it global really. I'm basically running `git log` to extra all the recent commits, and I need to access this data with SG components, like `ComponentsListRenderer`. Right now it's very hacky to do this.

**Comment by milesj** [comment]
I'll look into submitting a PR.
