### ISSUE TITLE
Is there a way to inject an external variable to a component in md file

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#1204]
What I'm looking for is a kind of below
```jsx
<MyComponent
   name={"ABCD"}
   env={window.externalVars.env}
/>
```

**Comment by sapegin** [comment]
You can `require` them from another module:

```js
const {env} = require('./externalVars');
<MyComponent
   name={"ABCD"}
   env={env}
/>
```

**Comment by dinukadesilva** [comment]
@sapegin That's cool

But, then it displays these to the live example code as well. Is there a way to avoid that too.

Actually my requirement is, I have a set of component consuming a service that has different environment (staging, development, production etc.). So, that some of the parameter values are veried based on the environment. But, I want these to be displayed as plain component parameters as below.

**Staging**
```
<MyComponent
   name={"ABCD"}
   env={"stg"}
   userId="stg-1234"
/>

```

**Production**
```
<MyComponent
   name={"ABCD"}
   env={"prod"}
   userId="prod-000002"
/>
```

As illustrated above, the things like userIds and all being different to the environments. I have them stored in a config. But, without a require I need to display these code in the demo as above.

**Comment by dinukadesilva** [comment]
May be if there's a way to define some variables through styleguide config and refer them here.

**Comment by dinukadesilva** [comment]
@sapegin Thanks and yes this is also an alternative. I raised another issue with more context on what I'm referring. Closing this.
https://github.com/styleguidist/react-styleguidist/issues/1229
