### ISSUE TITLE
Remove dependency on "walkes"

### ISSUE THREAD

**Issue by ryanmitts** [styleguidist/react-styleguidist#1210]
Starting in version 8 of the package it looks like "walkes" was added as a project dependency, although I cannot find out where it is used. I am not sure if this is needed?

That library is LGPL-3 licensed and can make this project unusable in certain licensing situations starting in version 8.

**Comment by sapegin** [comment]
Thanks for pointing this!

It's used in the next (9.x) version actually:

https://github.com/styleguidist/react-styleguidist/blob/next/src/client/utils/transpileImports.js
https://github.com/styleguidist/react-styleguidist/blob/next/src/loaders/utils/getImports.js

Do you know of a better alternative?

**Comment by ryanmitts** [comment]
Would a package like this work?

https://github.com/estools/estraverse

**Comment by sapegin** [comment]
Nah, it's much much bigger. So we either need to find something similar to walkes or write our own simple function.

**Comment by drublic** [comment]
Any news or plans on this issue?

**Comment by eragon512** [comment]
could this be an alternative replacement? https://github.com/Rich-Harris/estree-walker
