### ISSUE TITLE
Problem: Development build

### ISSUE THREAD

**Issue by KristoferMyhre** [styleguidist/react-styleguidist#1213]
**Current behavior**

I want to make a development build for my project. According to the documentation 
https://github.com/styleguidist/react-styleguidist/blob/master/docs/Cookbook.md#how-to-use-production-or-development-build-of-react all you have to do is to add:
 `"build": "cross-env NODE_ENV=development react-styleguidist build"`
However it still runs a production build.

**To reproduce**

Add `"build": "cross-env NODE_ENV=development react-styleguidist build"` to your styleguide project and run `npm run build`.

**Expected behavior**

To build a development build when running the NODE_ENV=development flag.

-------------------------------

I took a look into https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js and it looks like `isProd` is determined by `env`, which is always `'production'`.

Shouldn't `isProd` be determined by `process.env.NODE_ENV`, which can either be `'development'` or `'production'`? Or am I missing something fundamental?

Snippet from `make-webpack-config.js`:

```
module.exports = function(config, env) {
	process.env.NODE_ENV = process.env.NODE_ENV || env;
        const isProd = env === 'production';

        ....

        if(isProd){
            ....
        }
```

**Comment by sapegin** [comment]
The doc explains how to include a development build of React in your style guide production build. 

What problem you're trying to solve?

**Comment by KristoferMyhre** [comment]
Yes, i am aware that the docs explain how to make a development build. But for me it is not working properly. When I do as it is written in the docs, it still makes a production build, no a development build.

Am I misunderstanding something here?

**Comment by KristoferMyhre** [comment]
I know it is production build because in you webpack config you have the following code:
```
module.exports = function(config, env) {
 process.env.NODE_ENV = process.env.NODE_ENV || env;

 const isProd = env === 'production';
```

`env` is always `'production'`, not matter what I do. Which always makes this a production build.

**What problem you're trying to solve?**
`styleguidist server` doesn't work for me, because of issue #1194 . Therefore I use http-server to serve my build. I dont want to serve a production build, but a development build.

**Comment by sapegin** [comment]
**This is development build of React, not Styleguidist, please read the docs carefully.**

https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem
