### ISSUE TITLE
Secondary navigation for the main content view.

### ISSUE THREAD

**Issue by michaeltrilford** [styleguidist/react-styleguidist#1214]
Provide an easy way for the user to navigated between content under a main navigation section.

If this is possible today, please accept my apology.

Please review the attached image:
<img width="1571" alt="screen shot 2018-11-22 at 8 52 32 pm" src="https://user-images.githubusercontent.com/2483515/48895297-d7eeef00-ee98-11e8-8c22-be3fffe13b41.png">

**Comment by sapegin** [comment]
I guess it's possible if you implement it for your style guide using custom components. I don't think this should be supported out of the box, because these aren't headings but just text paragraphs and they can be quite long.

**Comment by michaeltrilford** [comment]
Perfect, thanks for the tip 😂

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
