### ISSUE TITLE
Displaying Non-React Components

### ISSUE THREAD

**Issue by parshwamehta13** [styleguidist/react-styleguidist#1218]
Can we render vanilla js components in styleguidist

**Comment by sapegin** [comment]
I guess it depends on your use case. 

* You can't have a nice props table unless [you render it yourself](https://github.com/sapegin/stack-styled/blob/master/src/Stack.md) for each component.
* You may have to generate table of contents yourself.
* You'll need to find a way to render examples, right now they are React components.

I'm not sure it all make sense though ;-)
