### ISSUE TITLE
Upgrade kleur dependency to 3.0.0.

### ISSUE THREAD

**Issue by hastebrot** [styleguidist/react-styleguidist#1220]
Dependency `kleur@^2.0.2` is causing a Yarn warning:

~~~
warning react-styleguidist > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer theold syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
~~~

An upgrade to kleur@3 contains breaking changes. Per release notes one can also replace `kleur@2.x` with `ansi-colors` without any code/syntax changes.

I'm using latest `react-styleguidist@9.0.0-beta2`.

**Comment by sapegin** [comment]
Feel free to send a pull request with an update to Kleur 3 ;-)

**Comment by xsnakeex** [comment]
Hello!
Where should I replace the codes?

**Comment by xsnakeex** [comment]
Hello! Where should I replace the codes? I could not understand and correct the mistake when I create a new project.

This error appears:

npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cookie\AppData\Roaming\npm-cache\_logs\2018-12-31T01_32_01_879Z-debug.log
[23:32:01] Process exited with non-zero code: 1
[23:32:01] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by hastebrot** [comment]
@xsnakeex Your error message is not releated to the `kleur` deprecation warning.

`npm` could not find the `git` binary in the `PATH`.

```
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by dsuarezlogans** [comment]
is this issue still open? can I help on this?

**Comment by xsnakeex** [comment]
> is this issue still open? can I help on this?

Hello @dsuarezlogans . This problem don't have anymore.
I think this issue can be closed.
