### ISSUE TITLE
Double title rendered

### ISSUE THREAD

**Issue by FezVrasta** [styleguidist/react-styleguidist#1224]
**The problem**

I use styleguidist in a monorepo, each package contains some react components that are all served by styleguidist.

Each package has a `README.md` file that gets rendered in styleguidist using the `content` of its section.

Each section has as `name` the package name.

When I open styleguidist, each section has two titles, this because in my READMEs I include the title to make sure it is rendered properly once published on npm.

**Proposed solution**
There should be a way to tell styleguidist not to render the title of each section, but still make it visible in the sidebar.

Right now if I don't provide a name, the sidebar will be empty.

**Alternative solutions**

Alternatively, the `content` value could be a function, doing so I can manually read the markdown and strip out the first row.

**Comment by sapegin** [comment]
Feel free to send a pull request with an alternative solution.

**Comment by heatherbooker** [comment]
Tags: duplicate multiple header

**Comment by dougmackenzie** [comment]
I could do a PR for this feature. Presumably we'll just do a new styleguide.config var that allows you to remove the title from all pages?

**Comment by FezVrasta** [comment]
I think  @sapegin wants the suggested alternative solution to be implemented

**Comment by eragon512** [comment]
hey @sapegin did this issue get resolved in #1368 or does it still need work?

**Comment by sapegin** [comment]
I didn't have this issue so I can't test it, but let's close it for now ;-)
