### ISSUE TITLE
Custom prop type label

### ISSUE THREAD

**Issue by schadenn** [styleguidist/react-styleguidist#1225]
**The problem**

Using Typescript we often have a situation in which we use enums as React props. Example:

````
enum Looks {
  PRIMARY = "something";
  SECONDARY = "something else";
}

interface IButtonProps {
  look: Looks
}

export const Button = (props: IButtonProps)  => 
  <button className={props.look} />
````

Styleguidist with react-docgen-typescript will then display the prop like:
````
props: {
  looks: {
    name: "look",
    type: { name: "Looks" }
  }
}
````

Now we are looking for a way to clarify that the user should use the Prop like:
````
<Button look={Button.Looks.PRIMARY} />
````
And also list all the looks there are.

**Proposed solution**

Add a way to create custom props.look.type.name via JSDoc. I'm not sure if JSDocs @property would be the right thing to use or if it'd be better to introduce something custom.

I could create a PR for that. Just wanted to know what you think about that first.

**Additional context**

It might be a Typescript specific problem and there were some similar issues opened within react-docgen-typescript, but I think Flow or others might have similar issues.
It might help with those also:
https://github.com/styleguidist/react-docgen-typescript/issues/48
https://github.com/styleguidist/react-docgen-typescript/issues/93

**Comment by Phizzard** [comment]
For anyone having this issue, react-docgen-typescript that styleguidist uses with typescript has a configuration for this.

https://github.com/styleguidist/react-docgen-typescript

> shouldExtractLiteralValuesFromEnum: boolean
> 
> If set to true, string enums and unions will be converted to docgen enum format. Useful if you use > Storybook and want to generate knobs automatically using addon-smart-knobs.

What my config looks like
```js
...
propsParser: require('react-docgen-typescript').withDefaultConfig({
    shouldExtractLiteralValuesFromEnum: true,
  }).parse,
...
```

Hope this helps anyone else looking!
