### ISSUE TITLE
How to use JSdoc and @Example to conditionnaly render the example code mirror

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1226]
@sapegin , following [#1188](https://github.com/documentationjs/documentation/issues/1188),

We've added documentationjs to generate our jsdoc. We got really surprised when we saw our example rendered in code mirror. Lot's of error so we disabled that behavior by default

I want to know if `@example` annotation in jsdoc can be tweak in order to optionally render the example.

```js
/**
 * @public
 * @name toKeyframeString
 * @description This will convert an object into a valid keyframe string for styled
 * @param obj {Object} - Object of keyFrames
 * @example
 * const kf = {
 *   from: {
 *     width: '0%',
 *   },
 *   '20%, 40%': {
 *     width: '75%',
 *   },
 *   '60%': {
 *     width: '25%',
 *   },
 *   to: {
 *     width: '100%',
 *   },
 * };
 * toKeyframeString(kf);
 * // return the key frame stringified
 * @returns {string} - The keyframe stringified
 */
```

This utility, for example, should be playable with code mirror, but because we globally turn `javascript` static rendering off, it won't. 

Is there a way to restore the behavior from the JSdoc on the side of react-styleguidist ?

That would be cool if

1. react-styleguidist work out of the box for utilities.
1. If we can omit the <div /> wrapper required for the rerendering.
1. Have the import line 1st line of highlight when static utilities are used.

Do you have an idea of implementation? 

## Related issues

- https://github.com/documentationjs/documentation/issues/1188

### version

- react-styleguidist v8.0.6

**Comment by sapegin** [comment]
Probably we should render `@example` as a static code by default, but then how to enable the editor?

I don't understand the second and third points though ;-/

**Comment by kopax** [comment]
@sapegin, you got the most important point. We should be able to render `@example` static and non static. I don't know how.

- Point 2: The live code must return a valid component, so if our function is just returning a string, we must return `<div>{str}</div>` in order to get the result displayed. Fixing point 2 will consist of automatically wrap the return with a div.

- Point 3: This point means showing the import line to access the function, as we do with `getComponentPathLine`.

**Comment by kopax** [comment]
Hi @stale bot, we have found the fix to use `javascript` as static` by default, because this is what `@example` generate.

If we want code editor, we just do it inside `@description`, but this can be inconveniant to read in the jsdoc code and require to modify the default.

Should we keep this open?
