### ISSUE TITLE
Knobs support

### ISSUE THREAD

**Issue by BTMPL** [styleguidist/react-styleguidist#1227]
I'd like to revisit the topic of adding knobs controls to Styleguidist - is this something there's community intrest in still?

I've started prototyping something that can be seen here:

https://www.youtube.com/watch?v=-6gldWa7DZ8

edit: taking it a bit further now:

![image](https://user-images.githubusercontent.com/247153/49689140-3f55a180-fb1d-11e8-8733-8f9fbf3cb8ba.png)

It does not require any changes to the styleguidist as in now, everything is provided as a component (that eventually would could be injected into the workspace by styleguidist; the current hack you see in the code is to overcome the 1 component limit and not inject into internals) and thanks to the render-prop pattern can be used to interact with the markdown changes etc.

**Comment by BTMPL** [comment]
I've also tried experimenting with auto generating knobs, but would need to be able to access the prop types data generated by docgen - don't think those are available anywhere in playground scope?

**Comment by BTMPL** [comment]
Also, this would mean that styleguidist would require 16.7+, right? Which would be a hard requirement (e.g. our project, when I use styleguidist, is at 15.3)

**Comment by BTMPL** [comment]
I went on ahead and created https://github.com/BTMPL/styleguidist-knobs if you want to have a look at it.

I might be abusing a few things (webpack api and global namespace) but couldn't find a way to make the integration easier ;)

**Comment by sapegin** [comment]
I think adding something like `useAllKnobs` to Retoggle will be a simpler solution than recreating 85% the same things yourself ;-)

If you keep the knob thingy separate from Styleguidist, which I thing is the right approach, then the required versions of both will be separate.

That's a great start anyway, thank you for doing that!

**Comment by ammmze** [comment]
I realize this is an old thread, but I've just submitted some changes to retoggle in Raathigesh/retoggle#29 (now retoggle 1.0.0) that should help if anyone is still looking at using retoggle in react-styleguidist. Previously retoggle kept all the knobs in a global place, so if you had many components or code blocks they would all share the same knobs/toggles. So with that fixed we can swap out the `ReactExample` component in styleguidist with something like this:

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import DefaultReactExample from 'react-styleguidist/lib/client/rsg-components/ReactExample/ReactExample';
import { Inspector, InspectorProvider } from 'retoggle';

export default function ReactExample(props) {
    return (
        <InspectorProvider>
            <div style={{position: 'relative'}}>
                <DefaultReactExample {...props} />
                <div style={{position: 'absolute', right: '0', bottom: '0'}}>
                    <Inspector usePortal={false} />
                </div>
            </div>
        </InspectorProvider>
    );
}

ReactExample.propTypes = {
    code: PropTypes.string.isRequired,
    evalInContext: PropTypes.func.isRequired,
    onError: PropTypes.func.isRequired,
    compilerConfig: PropTypes.object
};
```
