### ISSUE TITLE
Enabling the readme.md to be templates compiled from the data provided in styleguide.config.js

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#1229]
**The problem**

For a component as below which are written for consuming APIs, also having different environments in API, it required to display the string url rather variable. 
```jsx
<myComponent
   edit={true}
   apiUrl="https://abcd.stg.com"
/>
```

**Proposed solution**

readme.md
```jsx
<myComponent
   edit={true}
   apiUrl={<%=url %>}
/>
```

styleguide.config.js
```js
module.exports = {
  data: { 
    url: `https://abcd.${env}.com`
  }
}
```
(env is passed based on the environment specified)

So, when this template is compiled it would be as
```jsx
<myComponent
   edit={true}
   apiUrl="https://abcd.stg.com"
/>
```

**Alternative solutions**

For now, this is achieved in following way. Though it works, the problem is it's kind of too much code to who looking at this. I would prefer having just the string rather variables imported from a config.

```jsx
var config = required("my-config")

<myComponent
   edit={true}
   apiUrl={config.url}
/>
```
"my-config" is a dynamic module defined from the template based on the specified environment

**Additional context**

As a solution, I would suggest to compile the readme file as mustache or handlebar templates with the data provided from styleguide config. With that we can make the demos more simpler to consumers.

**Comment by sapegin** [comment]
This should be possible with the updateExample function:

https://react-styleguidist.js.org/docs/configuration#updateexample

**Comment by dinukadesilva** [comment]
@sapegin 
Yes it does.

How about if some parameters are passed at the run time. May be in a query string.
