### ISSUE TITLE
Third-party warning: doesn't export a component

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [styleguidist/react-styleguidist#1234]
I'm using styleguidist with a third-party UI-component library `nessie-ui`.
https://github.com/mahmoud-zakria-sociomantic/nessie-style-guide .

`PropTypes` doesn't generated unless I re-write the components from scratch in a new file and re-define propTypes.

I don't see full solution for the provided third-party page.

![image](https://user-images.githubusercontent.com/37908294/50085525-9bde4e00-01fa-11e9-96fb-c3bbd5ae5c4d.png)

**Comment by zhgbin0501** [comment]
I hava the same question, and  I don't know  how to solve this problem.
![2018-12-19 11 06 25](https://user-images.githubusercontent.com/24954017/50196663-f4d6ef00-037e-11e9-9962-4bce3a03d109.png)

**Comment by mahmoud-zakria-sociomantic** [comment]
@zhgbin0501 Looks like there is only one solution for it at least for now which is creating your own components from scratch instead of importing them from external path.

Check this example https://github.com/everydayhero/constructicon/tree/master/source/components

**Comment by GraySmith00** [comment]
I was getting this problem when styleguidist was trying to import my test files. In my styleguide.config.js, I had my components as /button/*.js . I fixed it by explicitly naming the component files.

**Comment by dinukadesilva** [comment]
Having the same issue. Anybody who found a solution for this?

**Comment by shadowae** [comment]
#1329 Having same problem

**Comment by juxhinNM** [comment]
Any update?
