### ISSUE TITLE
Disable the aggregate view of all the components on one page

### ISSUE THREAD

**Issue by ibrambe** [styleguidist/react-styleguidist#1236]
**The problem**

Rendering of the landing page takes a long time because all the components are rendered with their examples. `pagePerSection` is enabled, so the component detail pages are loading fast, but there seems no way to disable or overwrite the landing page of the styleguide.

**Proposed solution**

A way to disable the aggregate view of all the components.

**Additional context**

I'm using a custom ThemeWrapper with toggleable themes. That's why everything is loading a little slower than usual.

**Comment by sapegin** [comment]
There's no "landing page" in Styleguidist, add a section without components and render it by default. Like this:

https://component-driven.github.io/component-driven-development/styleguide/

**Comment by ibrambe** [comment]
Okay, maybe landing page is the wrong word. The thing is, I don't want all my components rendered on the root of the components list. In your example, that's this page: https://component-driven.github.io/component-driven-development/styleguide/#/Components

**Comment by cake-jnorman** [comment]
I gave the v9 beta4 a trial run today and found that the rendering is VERY slow on what I also call the 'landing page.' (the page that lists all examples, at the root of the built styleguidist site) As a FYI, v8.0.6 runs much faster @ibrambe.  I'm going to have to put off the v9 upgrade until this is resolved.
