### ISSUE TITLE
Support `@ignore` to prevent cataloging "private" component files

### ISSUE THREAD

**Issue by dankreft** [styleguidist/react-styleguidist#1242]
We use a modular project structure which is an adaptation of that which is described in [this article](https://medium.com/@alexmngn/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38). For any given component directory, there are some files that are "public" and others that are considered private implementation details. By convention, only those components exported by the `index.js` file are considered "public":

```js
// file: Foo/index.js
import Foo from './Foo'
import Bar from './Bar'

export default Foo

export {
  Bar
}
```

```js
// file:  Foo/Foo.jsx

import Bar from './Bar'
import BazIsPrivate from './BazIsPrivate'

export default function Foo() {
  return (
    <div>
      <Bar />
      <BazIsPrivate />
    </div>
  )
}
```

**Proposed solution**

I would like to propose that either `@private` and/or `@ignore` will work on components the same way it currently does for properties:

```js
/**
 * @ignore
 */
export default BazIsPrivate(props) {
}
```

```js
/**
 * @private
 */
export default BazIsPrivate(props) {
}
```

**Alternative solutions**

I've considered adopting a file naming convention to leverage the existing "blacklisting" functionality, e.g.:

```
Foo/
  _BazIsPrivate.jsx
```

But this feels suboptimal for a few reasons:

1. It's aesthetically..."icky" (highly subjective, I know);
2. If we decide to make a private file "public" (i.e., export it from the `index.js`), then we have to rename the file, even though no code changes in the file itself; and
3. It involves adopting a non-standard file-naming convention solely for the purpose of supporting a feature (or lack thereof) in a third-party tool.

**Comment by sapegin** [comment]
`skipComponentsWithoutExample` option could be another alternative:

https://react-styleguidist.js.org/docs/configuration#skipcomponentswithoutexample
