### ISSUE TITLE
hot reloading broken on windows

### ISSUE THREAD

**Issue by dbrelovsky** [styleguidist/react-styleguidist#1246]
**Current behavior**

Hot reloading is not working on a windows machine for all versions after 7.3.7.

I tracked it down to this change: https://github.com/styleguidist/react-styleguidist/pull/1133
On my machine all paths produced by ```getComponentFiles``` contain forward slashes as separator (in v7.3.8) and backslashes in v7.3.7.

If I change 
```js
const componentFiles = getFilesMatchingGlobs(componentGlobs, rootDir, ignore)
```
to 
```js
const componentFiles = getFilesMatchingGlobs(componentGlobs, rootDir, ignore).map(f => path.resolve(f));
```

hot reloading works again.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾
