### ISSUE TITLE
Is there a way to fix prismJS synthax highlighting for JS and JSX

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1251]
We are using `react-styleguidist`, `v8.0.6`.

This is an example of documentation made with `react-styleguidist`.

We know it use prism JS, and we thought this would have been improved with the time but we still experience bad highlight:

![image](https://user-images.githubusercontent.com/1866564/51206598-fde5bc80-193a-11e9-9a69-4bd9859c71f2.png)

Source: https://yeutech-lab.github.io/react-router-dom-utils/

These days it.'s easy to find better-looking highlights quality.

**Redux**:

![image](https://user-images.githubusercontent.com/1866564/51206638-1c4bb800-193b-11e9-91d4-75b2c84f05d0.png)

**styled-components**:

![image](https://user-images.githubusercontent.com/1866564/51206750-73ea2380-193b-11e9-9dfd-50cf480fb4fa.png)

We kept the one from react-styleguidist, but after a while, it's a bit disappointing seeing this in our documentation.

Would be nice to be able to choose our highlight renderer..

Did anyone succeed to fix prims and JSX?

**Comment by sapegin** [comment]
You need to use `jsx` language, not `javascript` if you want it to highlight JSX.

**Comment by kopax** [comment]
I see, beside we need to confirm that because we have this issue at many places, see for examples all the documentations of this namespace http://github.com/bootstrap-styled because I believe there is something wrong with the synthax even for jsx, I will confirm this asap.

Also, the problem with `jsx` language is that it does work if it render, there is still no way to use JSdoc annotation and render it with the proper language without using code mirror.

```js
/**
 * @name Link
 * @description
 *
 * This link component can preload a [react-loadable](https://github.com/jamiebuilds/react-loadable#loadablecomponentpreload) chunk on **mouseOver**
 * It can also block the page change before the chunk is loaded,
 * This give control on how the page change should work.
 *
 * @example
 *
 * Usually, you would create a `<Link />` component in your application `src/components/Link/index.js` as follow:
 *
 * ```javascript
 * export default (
 *   <Link
 *    tag={A}
 *    waitChunk={true}
 *    // You can pass routes as props
 *    routes={[{ name: 'Home', component: Home, path: '/' }]}
 *    // OR a ContextConsumer that own it
 *    ContextConsumer={AppContextConsumer}
 *    onClick={actionStartLoadingIndicator}
 *    onPreload={() => console.log(`
 *      chunk load in the background on mouseover or
 *      when user click if waitChunk is true
 *    `)}
 *    onLoaded={actionStopLoadingIndicator}
 *   />
 * );
 * ```
 *
 */
```
