### ISSUE TITLE
Where does the raw code live?

### ISSUE THREAD

**Issue by lawwantsin** [styleguidist/react-styleguidist#1254]
I've searched and asked on SO.
https://stackoverflow.com/questions/54256139/how-would-i-get-the-raw-code-in-a-code-component

I'm trying to build a custom Code component so I can include a Copy to Clipboard button on the code examples.

But none of the props in `<Code/>` include the actual code.  Just a HLJS ready bunch of html markup.  How much higher do I need to go to reach the raw code so I can dump it in an input and `execCommand("copy")` on click?

Thanks.

**Comment by sapegin** [comment]
It’s possible today, feel free to send a pull request with a feature _you_ need.
