### ISSUE TITLE
2 warnings about invalid sourcemaps issued when building

### ISSUE THREAD

**Issue by skystash** [styleguidist/react-styleguidist#1256]
**`styleguidist build` returns:**
<img width="1136" alt="screenshot 2019-01-21 17 21 01" src="https://user-images.githubusercontent.com/12685308/51489704-00b03980-1da1-11e9-8669-8d5091f7bb56.png">

**`styleguidist server` runs fine:**
<img width="1136" alt="screenshot 2019-01-21 17 24 55" src="https://user-images.githubusercontent.com/12685308/51489886-83d18f80-1da1-11e9-938c-5179a79f69ca.png">

---------

It's not a priority issue but would be nice to have a clean build. I don't mind searching for a solution if anyone can point me in the right direction?

**Comment by simonedavico** [comment]
@prjctnxt did you solve this? I am having the same issue.

**Comment by sandix34** [comment]
I also have the same problem and I'm always looking for the solution

**Comment by esjaastad-isp** [comment]
Making sure this one doesn't close without something.

**Comment by fa-repo** [comment]
> @prjctnxt did you solve this? I am having the same issue.

I don't remember finding a solution (it's been a while).

The issue was closed because I thought it was spammy; which appears was a mistake (whoops).

**Comment by cttith** [comment]
Having same problem...

**Comment by YapiKamilAqil** [comment]
I am having a similar issue and I am using the default set up with Create-React-App

**Comment by YapiKamilAqil** [comment]
```
build/main.9b1c9dda.js contains invalid source map
build/bundle.5339aa43.js contains invalid source map
The comment file "build/2.ab21be89.js.LICENSE.txt" conflicts with an existing asset, this may lead to code corruption, please use a different name
```

**Comment by poteirard** [comment]
I have exactly the same issue as @YapiKamilAqil 😢

**Comment by asdeev** [comment]
I'm having this same issue as well, I've been going at this one for days and can't seem to figure out what is going on...

**Comment by YapiKamilAqil** [comment]
Well, i just ignore the logs for now the build is still servable.

**Comment by cttith** [comment]
Was able to solve this problem by explicitly creating my own babel config file and including my webpack config in the styleguide.config.js

**Comment by alexwaibel** [comment]
I'm also experiencing this issue. My project was bootstrapped using create-react-app so I'm weary of messing with webpack.

**Comment by galexandrade** [comment]
I am getting this error: `The comment file "build/main.f1f51186.js.LICENSE.txt" conflicts with an existing asset, this may lead to code corruption, please use a different name` when running `styleguidist build`.
It is failing to compile, but `styleguidist server` runs fine.

![image](https://user-images.githubusercontent.com/24475665/86167077-22a00680-bad3-11ea-8d97-1b1067a426de.png)

**Comment by TokaLazy** [comment]
Same issue for my part

**Comment by galexandrade** [comment]
We had to turn off the optimization in the styleguide config's webpack config:
```
    ...
    webpackConfig: {
         optimization: undefined
    }
```

**Comment by fagsoft1** [comment]
Hey, I fix it like this:
`webpackConfig: {
        devtool: 'eval-source-map',
...
}`

**Comment by littlespex** [comment]
Experiencing the same issue with a CRA app.

**Comment by gkekesi** [comment]
Same issue...
