### ISSUE TITLE
Upgrade react-group

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1265]
[New major release](https://github.com/sapegin/react-group/releases/tag/v3.0.0) has a few breaking changes but won't generate an unnecessary DOM node which is good.

- [ ] Update dependency in `package.json`
- [ ] Update and test all usages of `react-group` according to release notes

**Comment by dougmackenzie** [comment]
I'll take this on as a first issue, will let you know how I go :)

**Comment by sapegin** [comment]
Awesome, thanks! 👾
