### ISSUE TITLE
Links to source on docs site not working

### ISSUE THREAD

**Issue by jonascript** [styleguidist/react-styleguidist#1267]
Links to source on docs site not working

**To reproduce**
1. Go to:
https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide

2. Click on " check the source"

Link is a github 404

**Expected behavior**
Should load github page for file.

*Apologies in advance if this is not the correct forum for this bug.

**Comment by sapegin** [comment]
The link should be https://github.com/styleguidist/react-styleguidist/tree/master/src/client/rsg-components

Mind sending a pull request with a fix?

**Comment by jonascript** [comment]
Looks like this has been fixed on master already. I guess it hasn't been pushed to the actual styelguide site yet. 
https://github.com/styleguidist/react-styleguidist/pull/1219/commits/9dc529ede000550d4a083d015a05464928130f2a

**Comment by scousino** [comment]
This seems to be live on the actual site now

**Comment by shakti97** [comment]
Please mark the issue as closed

**Comment by jonascript** [comment]
thanks!
