### ISSUE TITLE
Adjacent top-level elements don't render if other code included in excerpt.

### ISSUE THREAD

**Issue by benwiley4000** [styleguidist/react-styleguidist#1269]
**Current behavior**

Multiple adjacent top-level elements don't render correctly if ~an `import` statement~ anything else is included in the code. Version 9.0.0-beta4.

For example this works:
```jsx
<div>Hello</div>
<div>World</div>
```

But this..
```jsx
import React from 'react';
<div>Hello</div>
<div>World</div>
```
produces an error:
```
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (3:0)
1 : import React from 'react';
2 : <div>Hello</div>
3 : <div>World</div>
    ^
```

**To reproduce**

I tried following your instructions to fork the example repo or my issue will be closed, but that repo is using an old version (7) of styleguidist, so it's not very helpful. :wink: 

You can reproduce easily by including the above code examples in separate markdown code fences.

**Expected behavior**

Multiple top-level elements render the same, whether ~an `import`~ additional code is used or not.

**Comment by benwiley4000** [comment]
Apparently this isn't directly related to imports. Anything at all besides React elements (such as code comments) will cause the error as well.

```jsx
// comment
<div>Hello</div>
<div>World</div>
```

```
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (3:0)
1 : // comment
2 : <div>Hello</div>
3 : <div>World</div>
    ^
```

**Comment by sapegin** [comment]
This is expected, we wrap examples in a Fragment only for convenience and when we know it won't break your code.

**Comment by JustFly1984** [comment]
In my example I had some variables defined before JSX, and I had no semicolons. Adding semicolons fixed an issue.
