### ISSUE TITLE
How can I import 'antd' or any other lib ?

### ISSUE THREAD

**Issue by justb** [styleguidist/react-styleguidist#1278]
**Version**
9.0.0-beta4

**Current behavior**
![image](https://user-images.githubusercontent.com/22002343/52940937-ac4da900-33a2-11e9-86fb-99d9246d3461.png)

**To reproduce**
![image](https://user-images.githubusercontent.com/22002343/52941040-e159fb80-33a2-11e9-950e-583914f33295.png)

**Expected behavior**
I can use antd Button in ButtonGroup

**Comment by sapegin** [comment]
The code on the screenshots is different and the error message may explain what's wrong.

**Comment by robertaird** [comment]
I'm having this same issue in version 9.0.0. I can't seem to import other components into examples, or anything from node_modules. The acorn error is thrown on all components, whether it renders successfully or not. Same thing if I try require instead of import. 
<img width="508" alt="screen shot 2019-02-21 at 10 05 34 am" src="https://user-images.githubusercontent.com/29717800/53183137-64a46880-35c0-11e9-873e-41d5b981f875.png">
<img width="565" alt="screen shot 2019-02-21 at 10 05 25 am" src="https://user-images.githubusercontent.com/29717800/53183162-6c640d00-35c0-11e9-9f7a-c16b30fdd382.png">
<img width="447" alt="screen shot 2019-02-21 at 10 05 04 am" src="https://user-images.githubusercontent.com/29717800/53183176-70902a80-35c0-11e9-8e4e-7415f558ee46.png">

**Comment by af** [comment]
I'm having the same issue as @robertaird when trying to upgrade from v8.0.6 to v9.0.0. Any import statement in my example (jsx inside a markdown file) results in this error being rendered in the browser:

```
Error: import or require() statements can be added only by editing a Markdown example file: $importName
```

(here $importName is a placeholder for whatever I tried to import). There is also an error in the console whenever this happens, screenshot below with the full traceback:

![screen shot 2019-02-21 at 10 34 47 am](https://user-images.githubusercontent.com/25241/53192899-63753a80-35c4-11e9-9b31-b8e801be6c11.png)

Note: His "double import" trick also works for me but I'm hoping not to need that, for obvious reasons :)

**Comment by ibrambe** [comment]
Similar issue here with v9.0.0:

`styleguide.config.js`
```js
module.exports = {
  moduleAliases: {
    '@mycompany/react-components': path.resolve(__dirname, 'src/components')
  }
};
```

`AppBar.md`
```
 `` `jsx noeditor
import { Text } from '@mycompany/react-components';

<AppBar>
  <Text>
    Title
  </Text>
</AppBar>;
`` `
```

Error: 
_Error: import or require() statements can be added only by editing a Markdown example file: @mycompany/react-components_

**Comment by robertaird** [comment]
I tried tracking down what was happening (under the assumption that I was doing it wrong) but I didn't have much luck. By the time the example hits [this file](https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/client/requireInRuntime.js), none of the imported filepaths are present in the 'requireMap' object. It seems like Acorn is choking on the jsx the first time around, for some reason, causing the imports in the md files to be missed by webpack(?).

**Comment by gwuhaolin** [comment]
I debug react-styleguidist and find this issuse cause by acorn getAst fail in `react-styleguidist/lib/loaders/utils/getImports.js`:
![image](https://user-images.githubusercontent.com/5773264/53280824-dc59cb00-3759-11e9-9e07-e401915b0a53.png)

**Comment by sheldonHua** [comment]
Has anyone solve this problem? I'm also getting the error:
```Error: import or require() statements can be added only by editing a Markdown example file:```
When I try to import other components into the markdown file.

**Comment by timsnadden** [comment]
For me this problem was solved by modifying `devServer` in the styleguide webpack config.

```
webpackConfig: {
	devServer: {
		headers: {
			'Access-Control-Allow-Origin': '*',
		},
	},
}
```

**Comment by santaclauze** [comment]
Confirmed. @robertaird 's super hack works. But as expressed, it is a bit 'harcore'.

Any followup on this? It seems to be quite a recurrent problem.

**Comment by timsnadden** [comment]
I have had success fixing this problem by deleting `yarn.lock` (or `package-lock.json` for npm users) and reinstalling. I'm not sure what the cause was but one of the dependencies, perhaps transitive, is updated to fix this issue

**Comment by kopax** [comment]
@timsnadden how can deleting the lock file can help solving the import issue?

I am also investigating and we dowgraded to v8.0.6 our documentation because of that. Can somebody help me point to the commint that changed the behavior in react-styleguidist? I can't find **what change** between v8 and v9

**Comment by kopax** [comment]
/cc @sapegin :+1: 

https://github.com/styleguidist/react-styleguidist/issues/1310#issuecomment-471142372
https://github.com/styleguidist/react-styleguidist/issues/1310#issuecomment-471149417

I think timsnadden got the cause, I have a similar case, can we get your opinion about it? I think you have a clue for us. We will get the reason and the fix.

**Comment by sapegin** [comment]
Maybe try to upgrade Buble and Acorn, if the problem is related to one of them. Though there's a problem with Buble — https://github.com/bublejs/buble/issues/171, the fix wasn't yet released.

**Comment by kopax** [comment]
I've been trying to update `acorn`:

```bash
mponents (testing-broken-v9)]: npm ls acorn
@bootstrap-styled/rsg-components@2.0.2 /home/dka/workspace/github.com/bootstrap-styled/rsg-components
├─┬ @rollup-umd/documentation@1.3.20
│ └─┬ documentation@9.3.0
│   └─┬ module-deps-sortable@5.0.0
│     └─┬ detective@4.7.1
│       └── acorn@5.7.3 
├─┬ eslint@5.15.1
│ └─┬ espree@5.0.1
│   └── UNMET PEER DEPENDENCY acorn@6.1.1 
├─┬ jest-cli@24.3.1
│ └─┬ jest-config@24.3.1
│   └─┬ jest-environment-jsdom@24.3.1
│     └─┬ jsdom@11.12.0
│       ├── acorn@5.7.3  deduped
│       └─┬ acorn-globals@4.3.0
│         └── acorn@6.1.1 
├─┬ react-styleguidist@9.0.4
│ └── UNMET PEER DEPENDENCY acorn@6.1.1 
└─┬ webpack@4.29.6
  └── acorn@6.1.1 
```

After `npm i acorn@6.1.1`:

```bash
npm ls acorn@bootstrap-styled/rsg-components@2.0.2 /home/dka/workspace/github.com/bootstrap-styled/rsg-components
├─┬ @rollup-umd/documentation@1.3.20
│ └─┬ documentation@9.3.0
│   └─┬ module-deps-sortable@5.0.0
│     └─┬ detective@4.7.1
│       └── acorn@5.7.3 
├── acorn@6.1.1 
├─┬ eslint@5.15.1
│ └─┬ espree@5.0.1
│   └── acorn@6.1.1 
├─┬ jest-cli@24.3.1
│ └─┬ jest-config@24.3.1
│   └─┬ jest-environment-jsdom@24.3.1
│     └─┬ jsdom@11.12.0
│       ├── acorn@5.7.3 
│       └─┬ acorn-globals@4.3.0
│         └── acorn@6.1.1 
├─┬ react-styleguidist@9.0.4
│ ├── acorn@6.1.1 
│ └─┬ buble@0.19.4
│   ├── acorn@5.7.3 
│   ├─┬ acorn-dynamic-import@3.0.0
│   │ └── acorn@5.7.3 
│   └─┬ acorn-jsx@4.1.1
│     └── acorn@5.7.3  deduped
└─┬ webpack@4.29.6
  └── acorn@6.1.1 
```

I did the same with buble, before:

```bash
npm ls buble
@bootstrap-styled/rsg-components@2.0.2 /home/dka/workspace/github.com/bootstrap-styled/rsg-components
└─┬ react-styleguidist@9.0.4
  └── buble@0.19.4 
```

After `npm i buble@0.19.6`:

```bash
npm ls buble@bootstrap-styled/rsg-components@2.0.2 /home/dka/workspace/github.com/bootstrap-styled/rsg-components
├── buble@0.19.6 
└─┬ react-styleguidist@9.0.4
  └── buble@0.19.4 
```

**Comment by kopax** [comment]
I have found a way without yarn: 

Add to your dev dependencies: 

```diff
+    "acorn": "^6.0.2",
+    "acorn-jsx": "^5.0.0",
```

Rerun `npm install` and it should be working.

**Comment by shenshanyoumu** [comment]
> I have found a way without yarn:
> 
> Add to your dev dependencies:
> 
> ```diff
> +    "acorn": "^6.0.2",
> +    "acorn-jsx": "^5.0.0",
> ```
> 
> Rerun `npm install` and it should be working.

it works for me,thanks

**Comment by EvHaus** [comment]
For me, doing a full clean re-install helped. ie:

```
rm -rf yarn.lock node_modules
yarn install
```

Seems like something in the dependencies is indeed the culprit here.

**Comment by paibamboo** [comment]
@kopax 
I think this might be the same problem of `npm` + `webpack` + `acorn`. See this [comment](https://github.com/webpack/webpack/issues/8656#issuecomment-456713191)

**Comment by kopax** [comment]
@paibamboo fixing version solved the issue for the moment. And yes it's related with `npm`+`acorn`, not sure how webpack is related.

**Comment by JonathanLehner** [comment]
I added 
+    "acorn": "^6.0.2",
+    "acorn-jsx": "^5.0.0",
to the dev dependencies, but somehow it still shows the error

**Comment by roblevintennis** [comment]
Fwiw, I tried the removal of packages and reinstall without success. The acorn tip did work though:
`yarn add --dev acorn acorn-jsx`

**Comment by elstr** [comment]
> Fwiw, I tried the removal of packages and reinstall without success. The acorn tip did work though:
> `yarn add --dev acorn acorn-jsx`

If this doesn't work try `rm -rf node_modules && npm install --legacy-bundling`

**Comment by JustFly1984** [comment]
for me solution was to add

```json
"resolutions": {
    "acorn": "6.4.0"
  }
```

to package.json
