### ISSUE TITLE
Recommendation for upgrading rsg-components from 8.0.6 to 9.0.0

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1280]
Hi and thanks again for react-styleguidist.

Congratulations for v9.0.0 release, I would like to get some advice on how to migrate one of our packages to enjoy all the newest features.

We are maintaining https://github.com/bootstrap-styled/rsg-components which is react-styleguidist UI component made with styled-components.

We usually lock react-styleguidist version and sometimes upgrade it following your changes.

We see a lot of reorganization in react-styleguidist, we use to plug these components using `resolve.alias`. 

I believe we will have to migrate everything to use v9.0.0. 

- Can we have an idea of what is gonna change in the future regarding the UI organizations ?
- Could you please share some advice and stories about the changes introduces and how we could do this migration with sens.

Thanks in advance,

**Comment by sapegin** [comment]
There's a migration guide:
https://github.com/styleguidist/react-styleguidist/releases/tag/v9.0.0

> Can we have an idea of what is gonna change in the future regarding the UI organizations ?

I don't know this myself ;-) I have no personal plans yet, so it all depends on contributions.

> Could you please share some advice and stories about the changes introduces and how we could do this migration with sens.

Checking the commit log would be the best way to learn about _all_ changes.

**Comment by kopax** [comment]
Thanks for the quick reply. I've just gone through the migration guide, and it is still unclear, what happened to the `rsg-components` folders? It seems that you throw everything away.

**Comment by sapegin** [comment]
It should be `lib/client/rsg-components`. We've just moved everything into one folder to run Babel on all files, not just client side.

https://github.com/styleguidist/react-styleguidist/tree/master/src/client/rsg-components

**Comment by kopax** [comment]
> It should be `lib/client/rsg-components`.

Great thank you, this was worrying me :)

If I can get a few last advices before proceeding to migration of https://github.com/bootstrap-styled/rsg-components/tree/master/src: 

We are really happy to see that you use the same prismjs `highlight` for all the styleguide.

This is the major reason why we want to upgrade, but also, the ES6 import in examples to make them copy/pastable is really great.

Again, thanks a lot for that release. Is v10 already scheduled or will you wait a bit before doing further changes?

> Checking the commit log would be the best way to learn about _all_ changes.

I agree but sometimes, redoing the whole portage is giving better results. We will try to update our rsg-components directory, is there any part of that directory that we should be warned on? Or should it work out of the box? I believe the Highlight component will have some change regarding the changelog, but any little working coming from you could help us get the best results.

We keep looking at the logs, but the code base we have is quite big and we try to bring every update without forgetting things.

**Comment by kopax** [comment]
@sapegin , we have found that v9 is breaking `resolveAliases` in example, using `webpackConfig.resolve.alias` also does not help.

**Comment by kopax** [comment]
I am closing in favor of #1310
