### ISSUE TITLE
[bug] npx styleguidist server -> Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.

### ISSUE THREAD

**Issue by benoitgrasset** [styleguidist/react-styleguidist#1289]
**Current behavior**

"webpack": "^4.29.5"
with a create-react-app

Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
(node:3364) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by amakely-da** [comment]
I have the exact same issue.

**Comment by evrenakar** [comment]
I have the exact same issue. :/
