### ISSUE TITLE
"Copy to clipboard" fails for non-https sites in Chrome 72

### ISSUE THREAD

**Issue by wachunga** [styleguidist/react-styleguidist#1290]
**Current behavior**

Clicking the "Copy to clipboard" button on the path line fails for non-https sites.

**To reproduce**

See https://github.com/feross/clipboard-copy/issues/30 and https://github.com/feross/clipboard-copy/issues/32

**Expected behavior**

The copy should work.

Just need to bump clipboard-copy to v3.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix! ;-)
