### ISSUE TITLE
Unable to use Node API in v9.0.1

### ISSUE THREAD

**Issue by arizonatribe** [styleguidist/react-styleguidist#1291]
**Current behavior**

I'm not sure what happened between 8.0.6 and 9.0.1, but when I updated today I'm no longer able to import certain files. At first I figured there was just some shuffling of files, but I believe it's more than that.

Following [the docs on using the Node API](https://react-styleguidist.js.org/docs/api.html) I should be able to see (at minimum) this working:

```js
const styleguidist = require('react-styleguidist');
```
But that fails now.

Looking at the `node_modules/react-styleguidist/package.json` in my project is see this for the `main` prop in `package.json`

```json
  "main": "scripts/index.js",
```

That seems to be incorrect (the `scripts/` directory is inside of `lib/` when react-styleguidist is installed into a given app).

To make this work currently I'm having to do this instead:

```js
const styleguidist = require('react-styleguidist/lib/scripts');
```

**To reproduce**

```
mkdir some-app && cd some-app
npm init -y
npm install --save-dev react-styleguidist
node
```
Then - from inside the Node R.E.P.L. - do this:
```
> require.resolve('react-styleguidist')
Error: Cannot find module 'react-styleguidist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)

```
However, if I know what file to pull in, it's fine:
```
> require.resolve('react-styleguidist/lib/client/rsg-components/Styled')
'/Users/dnunez/projects/carvana/test/node_modules/react-styleguidist/lib/client/rsg-components/Styled/index.js'
```

Alternatively, if you use the (awesome) library called [replem](https://www.npmjs.com/package/replem) you can shorten the steps-to-reproduce:

```
npm install --global replem
replem react-styleguidist
```
Which throws this error:
```
Installed into REPL context:
 - react-styleguidist@9.0.1 as reactStyleguidist
> Cannot find module '/Users/dnunez/.replem/node_modules/react-styleguidist'
```

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix! ;-)

**Comment by arizonatribe** [comment]
Really? That's all you're gonna give me? So is it a bug even, or is that like, my opinion man?
