### ISSUE TITLE
Loading .web.js files

### ISSUE THREAD

**Issue by arqex** [styleguidist/react-styleguidist#1301]
I am creating a react-native-web app, and I have some components with a specific version for the web.

Those components finish with the `web.js` extension instead of with just `.js`

With my webpack configuration I am have the extension loaded:
```resolve: { extensions: ['web.js', '.js']}```

It's working ok when building the app, but when building the style guide, doing `import Button from './Button` loads `Button.js` instead of `Button.web.js`

Thanks for this great library

**Comment by arqex** [comment]
Hey, any thoughts on this? Would you be interested in a PR with the changes?

**Comment by kopax** [comment]
@arqex did you find a way to solve this?

**Comment by andrzejpolis** [comment]
This worked for me:
```
  dangerouslyUpdateWebpackConfig(webpackConfig, env) {
    webpackConfig.resolve.extensions = ['.web.js', ...webpackConfig.resolve.extensions];
    return webpackConfig
  }
```

It's very confusing that `resolve.extensions` is merged by appending values at the end of defaults. This way you cannot control order of extensions resolution. In my opinion default values should be documented somewhere and `extensions` parameter should completely override default one not merge with it.

Default array is:
```
[ '.wasm', '.mjs', '.js',   '.jsx', '.ts',   '.tsx', '.json']
```

And would be nice if we could configure like that:
```
extensions: ['.wasm', '.mjs', '.web.js', '.js',   '.jsx', '.ts',   '.tsx', '.json']
```

Other idea is to put web.js extension in defaults.
