### ISSUE TITLE
Server start script errors when attempting to run concurrently with compile

### ISSUE THREAD

**Issue by dougmacknz** [styleguidist/react-styleguidist#1303]
**Current behavior**

Running the `npm run compile:watch & npm run test:cypress:startServer` command from https://github.com/styleguidist/react-styleguidist/blob/master/.github/Contributing.md#user-content-integration-tests-cypress results in the following:
![image](https://user-images.githubusercontent.com/1811583/53704315-deb1d880-3e6f-11e9-80b4-4af09016a82f.png)

The server start script errors out, and the compile works okay.

Running the commands in two separate terminals works fine.

I also run into a similar issue when running `npm run compile:watch & npm start`.

**To reproduce**

Run `npm run compile:watch & npm run test:cypress:startServer` from `react-styleguidist` root.

**Expected behavior**

Server should start successfully when run alongside `npm run compile`.

**Comment by sapegin** [comment]
Yeah, it used to work when the `scripts` folder wasn't babelified. Feel free to update the docs to run commands separately.
