### ISSUE TITLE
class name clash with Bulma

### ISSUE THREAD

**Issue by pervezfunctor** [styleguidist/react-styleguidist#1308]
Bulma has a class name of 'tag'. Unfortunately, it clashes with 'tag' class name used by react-simple-code-editor used by react styleguidist. This messes up code editor in react-styleguidist.

The problem does not happen with the example project. As the example project uses old version of styleguidist, which uses codemirror instead of react-simple-code-editor.

**Comment by romgain** [comment]
@pervezfunctor I'm having the same issue.

If that helps, I added this to my `styleguide.config.js` to work around it until we can figure out a long-term solution:

```js
module.exports = {
  styles: {
    StyleGuide: {
      '@global .token.tag': {
        fontSize: 'inherit',
        height: 'auto',
        lineHeight: 'initial',
        padding: 'initial',
        margin: 'initial',
        display: 'initial',
        pointerEvents: 'none',
        whiteSpace: 'pre-wrap',
        fontSize: 'inherit',
      }
    }
  }
};
```

**Comment by ianmstew** [comment]
I'm in the same boat since our components depend on a global stylesheet that inclues a `token` style.  I'm waiting on this before we migrate to 9.
