### ISSUE TITLE
Make dangling semicolon after imports optional, if possible

### ISSUE THREAD

**Issue by myles-sigsci** [styleguidist/react-styleguidist#1319]
**The problem**

Now that the components are no longer located in the global namespace (nice job by the way!), the prescribed way to import extra components is as follows:

```jsx
import { Button, List } from 'library-a'
import { Icon } from 'library-b'
;<Dropdown
  trigger={
    <Button
      purpose='neutral'
      appearance='outlined'
      iconAfter={ <Icon glyph='ArrowDropDown' /> }
    >
      Menu
    </Button>
  }
  flyout={
    <List padding='compact'>
      <List.Item>
        <a href='#1'>option 1</a>
      </List.Item>
    </List>
  }
/>
```

**Proposed solution**

Would it be possible to import in the following style instead? I feel like it would be just a little bit more clear, and would represent the actual code that consumers would want to copy-paste.

```jsx
import { Button, List } from 'library-a'
import { Icon } from 'library-b'

<Dropdown
  trigger={
    <Button
      purpose='neutral'
      appearance='outlined'
      iconAfter={ <Icon glyph='ArrowDropDown' /> }
    >
      Menu
    </Button>
  }
  flyout={
    <List padding='compact'>
      <List.Item>
        <a href='#1'>option 1</a>
      </List.Item>
    </List>
  }
/>
```

Thank you for this awesome library!

**Comment by sapegin** [comment]
Buble won't compile this code:

https://buble.surge.sh/#import%20%7B%20Button%2C%20List%20%7D%20from%20'library-a'%0Aimport%20%7B%20Icon%20%7D%20from%20'library-b'%0A%0A%3CDropdown%0A%20%20trigger%3D%7B%0A%20%20%20%20%3CButton%0A%20%20%20%20%20%20purpose%3D'neutral'%0A%20%20%20%20%20%20appearance%3D'outlined'%0A%20%20%20%20%20%20iconAfter%3D%7B%20%3CIcon%20glyph%3D'ArrowDropDown'%20%2F%3E%20%7D%0A%20%20%20%20%3E%0A%20%20%20%20%20%20Menu%0A%20%20%20%20%3C%2FButton%3E%0A%20%20%7D%0A%20%20flyout%3D%7B%0A%20%20%20%20%3CList%20padding%3D'compact'%3E%0A%20%20%20%20%20%20%3CList.Item%3E%0A%20%20%20%20%20%20%20%20%3Ca%20href%3D'%231'%3Eoption%201%3C%2Fa%3E%0A%20%20%20%20%20%20%3C%2FList.Item%3E%0A%20%20%20%20%3C%2FList%3E%0A%20%20%7D%0A%2F%3E

You can put `;` at the end of line with import, it doesn't matter. You just need one between the import and JSX.
