### ISSUE TITLE
assetsDir as an array breaks styleguidist build

### ISSUE THREAD

**Issue by ammmze** [styleguidist/react-styleguidist#1320]
**Current behavior**

When `assetsDir` is configured as an array, the `styleguide:build` script fails like this...

```bash
$ npm run styleguide:build

> react-styleguidist-example@1.0.0 styleguide:build /Users/me/projects/styleguidist-example
> styleguidist build

Building style guide...
 FAIL  Failed to compile

The "path" argument must be of type string. Received type object
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-styleguidist-example@1.0.0 styleguide:build: `styleguidist build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-styleguidist-example@1.0.0 styleguide:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

> Note: Running `npm start` or `npm styleguide` works fine. The `styleguidist server` successfully starts up without issue. And using a string value is also successful.

**To reproduce**

I've forked the example repo and made [this](https://github.com/ammmze/example/commit/310e059cc15bd9a4c8f1cf458cc0bb0fe5391a50) change and then run `npm run styleguide:build` which triggers the error.

**Expected behavior**

The build should be successful as it is when running the server.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.
