### ISSUE TITLE
How to forbid react-styleguidist to run the code block in the md file?

### ISSUE THREAD

**Issue by Sara2009** [styleguidist/react-styleguidist#1322]
In the md file, I don't want react-styleguidist to run a code block. I just want to show this code source. But now it occurs an error.

I don't want the code block(const dialog = Modal.show(config);...) to run with react-styleguidist. I just want it to run the ModalExample code block.

The md file is as blow:

Basic Usage
Modal.show(config)
```
// close dialog
const dialog = Modal.show(config);
dialog.close()
```

```
import Button from '@ui/Button/Button'
import Dialog from './Dialog';

class ModalExample extends React.Component {
    constructor(props) {
        super(props);
        this.state = {visible: false}
    }
...
```

Error: 
Uncaught ReferenceError: Modal is not defined

**Comment by tizmagik** [comment]
Hello! Have you tried adding the `static` modifier to the code block in md? https://react-styleguidist.js.org/docs/documenting.html#usage-examples-and-readme-files

**Comment by Sara2009** [comment]
> Hello! Have you tried adding the `static` modifier to the code block in md? https://react-styleguidist.js.org/docs/documenting.html#usage-examples-and-readme-files
> 
> ```
> ```jsx static
> import React from 'react';
> ```
> ```

Wow. Thank you very much. 
Your reply works well. That's just what I want.
