### ISSUE TITLE
"sections" anchor broken on configuration documentation

### ISSUE THREAD

**Issue by stonebk** [styleguidist/react-styleguidist#1324]
**Expected behavior**

Going to https://react-styleguidist.js.org/docs/configuration.html#sections should bring me to the `sections` documentation.

Going to https://react-styleguidist.js.org/docs/configuration.html and clicking on the "sections" link in the ToC should bring me to `sections` documentation.

Looks like the generated ID is incorrect:
https://react-styleguidist.js.org/docs/configuration.html#sections-1

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.

**Comment by mendrew** [comment]
We can close this one as it has been fixed by https://github.com/styleguidist/site/pull/8.

**Comment by mendrew** [comment]
Friendly ping @sapegin ☝️  https://github.com/styleguidist/react-styleguidist/issues/1324#issuecomment-498960856

**Comment by sapegin** [comment]
@mendrew Feel free to close next time — you should be able to do it ;-)
