### ISSUE TITLE
Emulate responsive behaviour

### ISSUE THREAD

**Issue by XOP** [styleguidist/react-styleguidist#133]
In the very basic implementation there is no common ability to test components against various breakpoints in `@media`-queries - by resizing the browser window or using DevTools. 
Generally, if we hide sidebar and adjust paddings of the components wrapper there is a good approximation for what we are targeting.
Do you have plans to implement the feature in some different way (iframes etc.) or should one use the above-mentioned approach to achieve this? Maybe by injecting custom CSS...

the examples of how it could look like:
![image](https://cloud.githubusercontent.com/assets/1815878/14782983/057780b4-0aed-11e6-9fce-8944f2c693b4.png)
![image](https://cloud.githubusercontent.com/assets/1815878/14782989/0cf2f4ae-0aed-11e6-8b68-fdeaf6573d96.png)

or simply open a new page of a component without wrappers?

**Comment by sapegin** [comment]
Looks useful for me. I’ll be happy to merge a pull request with this feature.

**Comment by XOP** [comment]
I'll take a look into this, but can't promise anything :(
I'm thinking about incorporating react-styleguidist for the project needs, but apparently there's no chance to 'just use it' without this feature and perhaps something else

**Comment by tizmagik** [comment]
> or simply open a new page of a component without wrappers?

I'm a fan of that approach. The responsive Chrome DevTools and in Safari are hard to beat, so I think we just simply need a clean and easy way to isolate a component without the styleguidist chrome.

**Comment by tizmagik** [comment]
I'm with you @XOP , we need this as well. Let me know where you end up or if you need any help.

I think something as simple as a `view isolated` link next to each component name that then goes to a blank page with just that example rendered and no other padding or chrome on the page would be helpful. Then use the browser's back button to go back to the full list of components. That may be a good v1 of this feature.

**Comment by operatino** [comment]
Here's the example implementation of the solution you're discussing:

https://sourcejs.com/specs/example-bootstrap-bundle/carousel/

+ isoleted view:

https://sourcejs.com/specs/example-bootstrap-bundle/carousel/?clarify=true&sections=1
https://sourcejs.com/specs/example-bootstrap-bundle/carousel/?clarify=true&tpl=clear&sections=1

**Comment by operatino** [comment]
This kind of "separate" component view page helps a lot, but solutions with placing the examples in iframes also makes sense, if on one page you would like to show different screen states. We're currently discussing similar plugins for SourceJS.

**Comment by XOP** [comment]
@tizmagik Hey man, thanks for support!
At the time I can't afford to spend any more time on this, so far we are good with our proprietary solution, constantly adding new features and improving it. So I guess there is no rush from my side for now.
But proposal stands anyhow :)

**Comment by sapegin** [comment]
@XOP @tizmagik @operatino We need your feedback in #160.

**Comment by n1313** [comment]
Can't this be done using Developer Tools in Chrome, for free?

**Comment by sapegin** [comment]
I think [Sizzy](http://sizzy.co/) integration is the right thing to do here (without adding Sizzy to the core of course). The very simple implementation (just open the current component in upcoming non-chrome mode in Sizzy) will be possible with the plugin API soon.

/cc @kitze

**Comment by kitze** [comment]
Yeah @sapegin we have to think of the right way to do this. Styleguidist will have to show the components in isolation in order for the integration to make sense.

**Comment by sapegin** [comment]
We have a basic isolated mode but it has too much chrome and stuff now. So I’m thinking about totally no-chrome mode — just all examples, or just one example.

**Comment by Jmeyering** [comment]
100% no chrome isolated makes complete sense to me and is just what I came here tonight to request. "Isolated" mode is not isolated at all.

**Comment by dkaoster** [comment]
A fairly critical feature for an implementation I've been working on is to be able to render things in iframes as well as the ability to easily resize the component to have the ability to see all the different responsive variations of the component.

I've built a very crude modification to get components to render in iframes via [`react-frame-component`](https://github.com/ryanseddon/react-frame-component) by overriding some of the rsg components, and have it more or less working.

To do this, I overrode `rsg-components/Wrapper` with a wrapper that renders a `react-frame-component` like so:

```jsx
<Frame
  style={{
    width: '100%',
    height: '100%',
    border: 'none',
  }}
  // Head contains the styles to be loaded
  head={
    <style>
      {document.appStyles}
    </style>
  }
  // Loads the font script
  initialContent={`<!DOCTYPE html><html><head><script async>${fonts}</script></head>
      <body><div></div></body></html>`}
  onLoad={() => {
    this.updateFrameHeight();
  }}
>
  {React.cloneElement(children)}
</Frame>
```

This is less than ideal for many reasons, as I have to find a way to get styles from the global DOM into the iframe, read the height of the contents of the iframe and update the iframe container accordingly, and inject the font script into the iframe context.

Unfortunately, this doesn't solve all our isolation problems. The react components are still running in the parent DOM instead of the iframe'd DOM, making things like listeners and events respond to the wrong context.

Will be working on this more in our own applications and hopefully will have something a little cleaner to PR soon.

**Comment by kevinbarabash** [comment]
In addition to testing responsive designs, iframes could help with testing components that use react-router.

**Comment by jkarttunen** [comment]
And adding visual diff tests

**Comment by frontalicious-martijn** [comment]
How about adding the css resize attribute? This way you can easily resize per component...

![resize component](https://user-images.githubusercontent.com/7541513/44081019-035dc8da-9fae-11e8-918a-6467170dc669.gif)

**Comment by frontalicious-martijn** [comment]
Can actually be added via the config :-)

```
styles: {
  Playground: {
    preview: {
      overflow: 'hidden',
      resize: 'horizontal',
    },
  },
},
```

**Comment by sapegin** [comment]
This won't help with responsive testing: media queries depends on the viewport size.

**Comment by sapegin** [comment]
@grzegorzj Do you have any performance issues when you have many (could be hundreds on one page easily) iframes on a single page?

**Comment by Betree** [comment]
I think we should re-open this, the ability to test responsiveness is quite important
