### ISSUE TITLE
Excluding all components which have no examples

### ISSUE THREAD

**Issue by danoc93** [styleguidist/react-styleguidist#1334]
By default we are including all the tsx components recursively (via a basic glob expression).

However, we have a bunch of these which are mostly helpers or wrappers around regular HTML components. Some of these are also just styles. We do not want to see these on our style guide. We do not add an md file for these.

The way our app is built means we cannot easily restructure it to add naming conventions for those elements that we want to expose to styleguidist, it is also not possible for us to move the ignores into a single folder (as we group things semantically).

I can't seem to find a way to exclude all the components that do not have a corresponding .md file. Is this possible some how?

My current solution is to manually exclude them using the 'exclude' option; however, this does not scale well as we are changing these things often. We would love this to be automatic.

**Comment by danoc93** [comment]
skipComponentsWithoutExample

**Comment by hugotox** [comment]
any luck with this? I have the same issue and `skipComponentsWithoutExample` did not work when using a glob to search for components
