### ISSUE TITLE
PR #1116 broke simple getExampleFilename customisation

### ISSUE THREAD

**Issue by eemeli** [styleguidist/react-styleguidist#1338]
**Current behavior**

Previously, the [documented `getExampleFilename` configuration](https://react-styleguidist.js.org/docs/configuration.html#getexamplefilename) allowed for just returning the path to where an examples file was expected to be found, but following #1116 a custom function now needs to return `false` or `null` if the file does not exist, because the `fs.existsSync()` check [was removed](https://github.com/styleguidist/react-styleguidist/pull/1116/files#diff-4320180057087a3668c310547c3ee1baL16) from `getExamples()`.

This change was not documented.

**To reproduce**

See example: https://github.com/eemeli/styleguidist-example/commits/get-examples

If you clone that repo, `npm install && npm start` from that branch will give you something like these errors:

```sh
./src/components/Button.js (./node_modules/react-styleguidist/lib/loaders/props-loader.js!./src/components/Button.js)
Module not found: Can't resolve '/Users/eemeli/code/rsg-example/src/components/Button.examples.md' in '/Users/eemeli/code/rsg-example/src/components'
./src/components/Placeholder.js (./node_modules/react-styleguidist/lib/loaders/props-loader.js!./src/components/Placeholder.js)
Module not found: Can't resolve '/Users/eemeli/code/rsg-example/src/components/Placeholder.examples.md' in '/Users/eemeli/code/rsg-example/src/components'
./src/components/PushButton.js (./node_modules/react-styleguidist/lib/loaders/props-loader.js!./src/components/PushButton.js)
Module not found: Can't resolve '/Users/eemeli/code/rsg-example/src/components/PushButton.examples.md' in '/Users/eemeli/code/rsg-example/src/components'
```

**Expected behavior**

Applying the changes of commit [`882f8ee`](https://github.com/eemeli/styleguidist-example/commit/882f8ee) worked on previous versions of react-styleguidist. They should still work.

To fix, there are really two options here:

1. Document the changed behaviour, and the user requirement for checking that the examples file exists before returning its path
2. Re-add the check to `getExamples()`.

**Comment by sapegin** [comment]
I don't remember why it was removed ;-)

But we have a similar condition here:

**Comment by eemeli** [comment]
The code fix itself is pretty simple and I can do that, but updating the [`getExamples` tests](https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/__tests__/getExamples.spec.js) is trickier. Any guidance on how to mock the `fs.existsSync` calls there?

**Comment by sapegin** [comment]
Historically we use real files in tests instead of mocking the file system. It's not ideal and I did mocking with https://github.com/streamich/memfs on another project. So both would be fine.
