### ISSUE TITLE
Headers conflict with navigation link IDs

### ISSUE THREAD

**Issue by konsumer** [styleguidist/react-styleguidist#1342]
**Current behavior**

I have config like this:

```js
module.exports = {
  sections: [
    {
      name: 'Introduction',
      content: 'docs/intro.md'
    },
    {
      name: 'Components',
      content: 'docs/components.md',
      sections: [
        {
          name: 'Button',
          content: 'docs/components/Button.md'
        }
      ]
    },
    {
      name: 'Concepts',
      content: 'docs/concepts.md',
      sections: [
        {
          name: 'Colors',
          content: 'docs/concepts/colors.md'
        }
      ]
    }
  ],
```

In `docs/components/Button.md` I have a `### colors` to talk about how to color buttons.

When I click on `Colors` in side-menu (from `docs/concepts/colors.md` it links to the `Button.colors` section, because it's the first item with an ID of `colors`.

Should I configure this differently, or is this a bug?

If there isn't a configuration-option, I might suggest prefixing IDs so they don't link like that (maybe navigable sections with `styleguidist-SECTION_NAME`, and inline headers with all parent sections in id: `components-button-colors`)

I also like that the nav-sections link directly by name, so maybe `styleguidist-SECTION_NAME` would make ugly nav links: `/#styleguidist-intro` is not as nice as `/#intro`, so maybe just override how headers auto-id.

**To reproduce**

I made a little [demo repo](https://github.com/konsumer/styleguidist-1342-demo).

If there is interest, I am happy to PR a solution for it.

related: [PR#318](https://github.com/styleguidist/react-styleguidist/pull/318)

**Comment by sapegin** [comment]
Yeah, I think we should prefix auto generated headings with something like I don't know, maybe `section-HEADING_NAME`, so links to components and sections are short and nice.

A pull request would be super cool, thanks!

**Comment by mendrew** [comment]
Hi all.

I've tried to fix this issue in this PR https://github.com/styleguidist/react-styleguidist/pull/1364
I hope that this is what you were talking about.
