### ISSUE TITLE
Support Hooks in examples

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1343]
**The problem**

Hooks could be a better way to use state in examples, than our custom `initialState`. But they don't work right now because we're wrapping example code in a class component, and hooks only work in a function component.

```jsx
const [primary, setPrimary] = React.useState(false);
<Button isPrimary={primary} onClick={() => setPrimary(true)}>Push me</Button>
```

**Proposed solution**

Wrap examples in a function component and pass state from the current wrapper class component as a prop.

**Alternative solutions**

1. Drop React < 16.8 support and use hooks to manage state: rewrite the current state manager as a function component with state.

2. Consider removing the `initialState` and rely on hooks only. (Breaking change.)

    2.1. Deprecate `initialState` / `setState`, update all docs and examples to hooks. Remove in the next major release.

**Additional context**

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by eragon512** [comment]
hey, I would like to work on this issue

**Comment by sapegin** [comment]
@eragon512 That's awesome! 👍

**Comment by eragon512** [comment]
Opened a PR which implements the proposed solution, as it seemed to be the simplest way to support both legacy and new applications. 

If dropping React < 16.8 support is an option, then I would be happy to refactor the wrapper class to implement hooks

**Comment by eragon512** [comment]
@sapegin Closing this issue, as it has been addressed in #1353

**Comment by hugotox** [comment]
Hello! What's the way to document components that use hooks? I'm getting the `Invalid hook call` error mentioned in the OP

**Comment by foscjos2** [comment]
@hugotox did you ever get a working solution to this?

**Comment by AshleyFang** [comment]
I have also come across this problem. Does anyone have any recommended solutions? I am willing to give them a try.

```bash
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Ribbon (webpack:///./node_modules/react-styleguidist/lib/client/rsg-components/Ribbon/Ribbon.js?:11:114)
    at div
    at StyleGuideRenderer (webpack:///./node_modules/vue-styleguidist/lib/client/rsg-components/VsgStyleGuide/StyleGuideRenderer.js?:79:23)
    at _class (webpack:///./node_modules/react-styleguidist/lib/client/rsg-components/Styled/Styled.js?:62:28)
    at StyleGuide (webpack:///./node_modules/react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuide.js?:91:29)
This may be due to an error in a component you are overriding, or a bug in React Styleguidist.

If you believe this is a bug, [please submit an issue](https://github.com/styleguidist/react-styleguidist/issues).
```
