### ISSUE TITLE
Use Styled Components themeprovider markdown

### ISSUE THREAD

**Issue by dysticus** [styleguidist/react-styleguidist#1350]
**Current behavior**

I'm not sure if it's a bug, feature request or undocumented feature, but here goes.

Our styleguide will serve as a library for multiple brands. These brands share the same components, but their design tokens differ.

According to [the docs](https://react-styleguidist.js.org/docs/thirdparties.html#styled-components) you can use styled-components ThemeProvider to provide a theme to your components. I implemented as such (wrapping wrapper in the ThemeProvider) and this works (for components).

However, in my styleguide, I also have .md files for displaying design tokens. I'd like to show only those tokens, linked to that brand. To do so, I'd like to access the theme variable from styled-components ThemeProvider props, in my markdown files. Currently I haven't found a way to do so.

Actually, it's not necessary for me to stick with this approach, if it can be accomplished another way, I'm very happy to hear so. 

**To reproduce**
(Not sure if this is really needed, as I don't know how to reproduce it 😄)
- Create any react-styleguidist project with styled components.
- Overwrite your wrapper component so you can wrap it in a ThemeProvider from styled components
- Try accessing the theme in your markdown files

**Expected behavior**

I'd like to be able to access my theme from styled-components ThemeProvider or any another way to access a variable containing my theme inside the markdown files.

Thanks!

**Comment by driedl** [comment]
I'd like this too. In my case, I would like to add a dropdown listing all available themes, then pass this theme to the ThemeProvider so all my components then render using the whatever theme is selected.

The theme dropdown is easy to add by implementing a custom StyleGuideRenderer that wraps the default and just adds the ddl component... but i dont know how to pass the value as a prop to the themeProvider dynamically with this new value...

**Comment by tisgro** [comment]
I've proposed a general solution to the problem of multiple theme support in PR #1434 – @dysticus @driedl let me know if it works for you.
