### ISSUE TITLE
Drop Node 6

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1351]
[Node 6 is dead](https://github.com/nodejs/Release) since May 1.

- [ ] Update version to Node 8 in `package.json`.
- [ ] Remove Node 6 from `.travis.yml`.
- [ ] What else? ;-)

**Comment by dhuang612** [comment]
Hi,

It looks like the PR was never merged, is this something I can work on?

**Comment by sapegin** [comment]
@danielfx90 it wasn't merged because there are no other _finished_ breaking changes and it doesn't make much sense to make a new major release just for this. Is there any particular reason you need this?

**Comment by stefanosu** [comment]
Any assistance still needed for this?

**Comment by sapegin** [comment]
@stefanosu Thank! There's a PR already that I'm going to merge and release soon ;-)
