### ISSUE TITLE
Migrate codebase to TypeScript

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1352]
**The problem**

Recently I've added Flow to some of the files (not many) but it looks like TypeScript is more favourable now among React developers. Also full codebase conversion would help us find bugs.

**Proposed solution**

Steps to do it, all can be done one by one as separate pull requests:

- [x] Add TS as an option.
    - [x] Add `typescript` as a dependencey
    - [x] Add `tsconfig.json`
    - [x] Add `@babel/preset-typescript` to Babel config (`babel.config.js`)
    - [x] Add `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` to ESLint config (`.eslintrc`)
    - [x] Update [Travis CI config](https://github.com/styleguidist/react-styleguidist/blob/4e0bd70d4cb19b944f787ac78390a0bb5e3136a0/.travis.yml#L39-L41) to run TypeScript type check as well.
- [ ] Replace existing Flow types with TS: update files with `@flow` comment and replace types inside `flow-types` with `@types/*` modules.
- [ ] Remove Flow from dependencies and configs.
- [ ] Convert all files to TS.

How I think it should work:

* Use TS only for type checking, keep Babel as a compiler.
* Keep sane imports syntax: `import React from 'react'`, instead of `import * as React from 'react'`.

Use [Tâmia](https://github.com/tamiadev/tamia) as an example: look at `.babelrc`, `tsconfig.json` and `package.json`.

~~Can we use [react-javascript-to-typescript-transform](https://github.com/lyft/react-javascript-to-typescript-transform) for mass conversion?~~ Not really: it needs too many manual changes after and removes all formatting including empty lines.

**Comment by smashercosmo** [comment]
Do you want to use TS only as a type checker?

**Comment by sapegin** [comment]
Yup, I'd like to keep Babel setup as is for now.

**Comment by goku321** [comment]
I would be happy to help :)

**Comment by sapegin** [comment]
@goku321 That would be great! I've updated he issue with some more details. Let me know if you have any more questions.

**Comment by kakadiadarpan** [comment]
@sapegin Maybe [flow-to-ts](https://github.com/khan/flow-to-ts) can help a bit in this migration. I can try it out and see how it goes 😄

**Comment by nathanredblur** [comment]
I can help too. I have experience with typescript and react. Tell me how can I start.

**Comment by sapegin** [comment]
@kakadiadarpan I've tried react-javascript-to-typescript-transform and it wasn't very useful, so would be great if you can try flow-to-ts to compare ;-)

**Comment by sapegin** [comment]
@nathanredblur That's awesome! I've added a list of steps (unless I'm missing anything) for the conversion — no need to do everything at once though ;-)

**Comment by tanvirraj** [comment]
@sapegin I love to contribute, Where I can start ?

**Comment by sapegin** [comment]
@tanvirraj That's awesome! I've added a list of steps (unless I'm missing anything) for the conversion — no need to do everything at once though ;-)

**Comment by pavandv** [comment]
@sapegin I have been working with TypeScript + React for about a year in my company.. Would be happy to help.. 

I also happen to know (almost) the internals of this project as I was going through the code to add our own UI to the style guide.

**Comment by MaxFlower** [comment]
Could you add me as well?

**Comment by sapegin** [comment]
@MaxFlower Sure! No need to ask permission ;-)

**Comment by pavandv** [comment]
@sapegin I'm working on setting up the Typescript Config.

**Comment by pavandv** [comment]
@sapegin  Created PR #1461 for setting up typescript configuration.

**Comment by elevatebart** [comment]
@sapegin, I believe you can now safely check the eslint and travis boxes.

**Comment by elevatebart** [comment]
Looked too fast once again... Sorry, my mistake, the only thing that was added was eslint plugin as a dependency without implementing it. 
I am on it. Pull Request coming ;)

**Comment by elevatebart** [comment]
After a few hours dabbling with the eslint set-up, I have a better view of where we are.
I have a few questions regarding the current implementation.

1. One unfortunately cannot have a `jsconfig.json` and a `tsconfig.json` I believe we should merge them.
2. The parameter `"allowJs": true` forces type checking on every js file, including the ones with flow typings. This will break a lot of files. I must add that the flag is not necessary if we start converting the leaves first and follow the dependency tree.
3. Testing has not been mentioned here. I have seen the benefits of writing test files in TypeScript using ts-jest. Please, please can we add ts-jest?

To present my findings, I have created a new Pull Request as draft. Please tell me what you think.
https://github.com/styleguidist/react-styleguidist/pull/1463

**Comment by pavandv** [comment]
> Replace existing Flow types with TS: update files with @flow comment and replace types inside flow-types with @types/* modules.

I'm working on this.

**Comment by sapegin** [comment]
@elevatebart Awesome, thanks! Let's continue the discussion in the PR.
