### ISSUE TITLE
[Bug] build in directory public is conflicting with create-react-app public folder

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1358]
**Current behavior**

When I do `npm run styleguide:build` it produce a `public` directory with the builded app.

I am using create-react-app and the `public` folder is already used by it.

This cause react-styleguidist build to override `public/index.html` of the create-react-app application

Is there a way to trigger the build in another folder?

**Comment by jkarttunen** [comment]
You can configure the public folder with `styleguideDir`config option.

<https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#styleguidedir>
