### ISSUE TITLE
HTML-element does not contain lang-attribute

### ISSUE THREAD

**Issue by J-Kallunki** [styleguidist/react-styleguidist#1363]
**Current behavior**

<html>-element does not contain lang-attribute

**To reproduce**

https://react-styleguidist.js.org/examples/basic/

**Expected behavior**

`<html lang="en">` for default or changed with:
```
module.exports = {
  template: {
    htmlAttributes: { lang: 'ru' }
  }
}
```

Feature already merged to `mini-html-webpack-plugin` that needs a new release and update dependecy to that (https://github.com/styleguidist/mini-html-webpack-plugin/pull/8)

**Comment by sapegin** [comment]
That's expected _for now_. I need to release the **major** version of mini-html-webpack-plugin, and then include into a **major** version of Styleguidist, because Node 6 support removal is a breaking change.
