### ISSUE TITLE
Component export not recognised if using React.memo

### ISSUE THREAD

**Issue by queicherius** [styleguidist/react-styleguidist#1366]
**Current behavior**

Right now, if there is a component exported wrapped with `React.memo`, that component gets ignored.

![2019-05-17_19-32-29](https://user-images.githubusercontent.com/4615516/57948806-90db3700-78da-11e9-8576-ece315cf498d.gif)

**To reproduce**

https://github.com/queicherius-error-reporting/example

**Expected behavior**

Components wrapped with `React.memo` to just work.

**My current workaround**

Add a `memoize` function that turns off `React.memo` for the `NODE_ENV` that styleguidist runs in.

**Comment by sapegin** [comment]
Likely should be reported at https://github.com/reactjs/react-docgen

**Comment by mendrew** [comment]
Here the issue in react-docgen: https://github.com/reactjs/react-docgen/issues/342
And PR which hasn't been merged yet: https://github.com/reactjs/react-docgen/pull/343
