### ISSUE TITLE
Preview provides empty context to rendered components

### ISSUE THREAD

**Issue by stepancar** [styleguidist/react-styleguidist#1374]
**Current behavior**

Preview renders by reactDom.render method, which not pass root react context to rendered components

https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/Preview/Preview.js#L79

**Expected behavior**

Rendered components should have the same react context as demo.

In my case I faced with this problem when switched demo theme. All except rendered components gets new theme

**Comment by sapegin** [comment]
That's expected behaviour, each example is really a separate React app. But it would be a good thing to have a way to define context for examples.

**Comment by jkarttunen** [comment]
I can take this, (Adding examples & docs for components with context)  i need this myself too.

**Comment by jkarttunen** [comment]
TL/DR;  you need to add context provider somewhere, either in component example or in component wrapper. This worked for me:


An example about using react context with a component

```jsx
import ThemeContext from '../../ThemeContext.js'

initialState = { theme: 'light' }
const toggleTheme = () => {
  setState({ theme: state.theme === 'light' ? 'dark' : 'light' })
}
;<>
  <div
    style={{
      backgroundColor: '#ccc',
      margin: '-16px -16px 16px -16px',
      padding: '16px'
    }}
  >
    <button onClick={toggleTheme}>Theme: {state.theme}</button>
  </div>
  <div>
    <ThemeContext.Provider value={state.theme}>
      <ThemeButton>Themable button</ThemeButton>
    </ThemeContext.Provider>
  </div>
</>
```
