### ISSUE TITLE
How to create playground with all components?

### ISSUE THREAD

**Issue by stepancar** [styleguidist/react-styleguidist#1376]
I try to migrate to latest styleguidist and faced that not all components available in playground.
In old versions of styleguidist we used this functionality to implemented [playground](https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=%3Ch1%3EHello,%20@sapegin%20!%3C/h1%3E)
In this playground you can use all components from arui-feather.

How can we do it now?

**Comment by FruitieX** [comment]
Hi,

I've had some success by doing the following in `setup.js`:

```
import * as MyComponentLibrary from 'path/to/component/index';

Object.assign(global, MyComponentLibrary);
```

While not the cleanest of solutions, it works. :-)

**Comment by stepancar** [comment]
@FruitieX thanks for your suggest.
We haven't entrypoint with all components.

**Comment by stepancar** [comment]
found solution.

```
const getContext = source =>
    readdirSync(source)
        .filter(name => !['lib', 'mq', 'vars', 'font'].includes(name)) // TODO: find simple way to check it's component folder
        .map(name => path.join(source, name))
        .filter(file => lstatSync(file).isDirectory())
        .reduce((prev, componentDirName) => {
            const componentSourcesFileName = componentDirName.split(path.sep).pop();
            const componentName = upperCamelCase(componentSourcesFileName);
            prev[componentName] = componentDirName;
            return prev;
        }, {});

const context = getContext(path.join(__dirname, 'src'));
```

**Comment by stepancar** [comment]
@sapegin  fyi
