### ISSUE TITLE
Can you clarify the moment in your documentation?

### ISSUE THREAD

**Issue by smff** [styleguidist/react-styleguidist#1377]
In documentation we are able to find the various way of use ";" symbol in the code examples.
For example at page https://react-styleguidist.js.org/docs/documenting.html
1)
<img width="925" alt="1" src="https://user-images.githubusercontent.com/3962132/58706933-0d324780-83bc-11e9-88e6-1cfb26541899.png">
2)
<img width="1176" alt="2" src="https://user-images.githubusercontent.com/3962132/58706934-0dcade00-83bc-11e9-916f-4c30f8da7f81.png">
3)
<img width="880" alt="3" src="https://user-images.githubusercontent.com/3962132/58706935-0dcade00-83bc-11e9-848a-cc631cbbb12c.png">
4)
<img width="1163" alt="4" src="https://user-images.githubusercontent.com/3962132/58706936-0dcade00-83bc-11e9-8fe6-ff38a3c8fa98.png">

Which way is right?
The presence of a ";" symbol before the component is it done on purpose or just a typo?
 Is any additional info about using ";" symbol related to react-styleguidist?

**Comment by sapegin** [comment]
> Which way is right?

All are right, it doesn't matter. Use Prettier.

> The presence of a ";" symbol before the component is it done on purpose or just a typo?

Try to remove it and it won't compile. 

> Is any additional info about using ";" symbol related to react-styleguidist?

This isn't related to Styleguidist in any way: that's how Buble, that we use to compile JavaScript, works.
