### ISSUE TITLE
Support for Angular

### ISSUE THREAD

**Issue by diegodesouza** [styleguidist/react-styleguidist#1382]
**The problem**

Is there a plan to support using styleguidist with Angular in the pipeline?

**Proposed solution**

Having support for Angular

**Alternative solutions**

N/A

**Additional context**

N/A

**Comment by okonet** [comment]
I think it would make sense to support as many frameworks as possible but with the current architecture I don't think this is feasible. That said, it would be great if you could experiment with Angular and let us know what's missing and how it would make sense to split styleguidist into smaller modules to allow such integrations. Also, check out [vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist)

**Comment by jkarttunen** [comment]
One related thing I'm struggling with in multi-project environment is that some folks might be using the CSS + HTML version of the components, not the react components. And I'd like to support that, as a first step into the design system. (Hey, better than nothing).
