### ISSUE TITLE
Is possible use examples typescript and execute them?

### ISSUE THREAD

**Issue by romaluca** [styleguidist/react-styleguidist#1383]
Hi, in my company we are using Typescript, and i started to use styleguidist for write guidelines of our components.

The problem is that Typescript in the example is not supported.

For every feature every component i'm writing the code in js without editor ex:
```
``jsx noeditor
initialState = { checked: false };
<OurCheckbox label="My checkbox" checked={state.checked} onChange={(value) => {    
    setState({ checked: value });
}} />
``
```

And the code in Typescript that is visible to user:
```
``tsx
import {OurCheckbox} from 'ts-components';
export default class TsCheckBoxExample extends React.Component<boolean > {

  public state = {
    checked: false
  }

  public render() {    
    return (
      <OurCheckbox label="My checkbox" checked={this.state.checked} onChange={(value: boolean) => {
         this.setState({ checked: value })
      }} />      
    )
  }
}
``
```

Do you know any better method for do that withour rewrite the code 2 times?

Thanks

**Comment by DarthVanger** [comment]
Put the code you want to show to the user into a separate component (`OurCheckboxExample`).

Create a component that accepts a component name as a prop and shows both component and it's code, using [webpack raw-loader](https://github.com/webpack-contrib/raw-loader) to get component's code as text and [React syntax highlighter](https://github.com/conorhastings/react-syntax-highlighter#readme) to highlight it:
```
import { okaidia } from 'react-syntax-highlighter/styles/prism';
const SyntaxHighlighter = require('react-syntax-highlighter/prism').default;

ComponentExampleAndSourceCode = ({ componentName }) => {
  const ComponentExample = require(`../componentExamples/${componentName}`).default;
  const sourceCodeAsText = require(`!raw-loader!../componentExamples/${componentName}`);
 
 return (
    <>
      <ComponentExample />
      <SyntaxHighlighter language='tsx' style={okaidia}>
        { sourceCodeAsText }
      </SyntaxHighlighter>
    </>
  };

export default ComponentExampleAndSourceCode;
```

Finally, in markdown include it as 
```jsx noeditor
const ComponentExampleAndSourceCode = require('../utils-for-docs-website/ComponentExampleAndSourceCode').default;
<ComponentExampleAndSourceCode componentName="OurCheckboxExample" />
```
