### ISSUE TITLE
Cannot get prop-types of imported types

### ISSUE THREAD

**Issue by aarohmankad** [styleguidist/react-styleguidist#1394]
**Current behavior**

I have an array of possible values for a prop. I use `PropTypes.oneOf(colors)`, but the generated docs show the string literal "colors" instead of enumerating the colors array.

**To reproduce**

[Modify Label component from here](https://github.com/styleguidist/react-styleguidist/tree/master/examples/basic/src/components/Label) to import possible colors from a file `colors.js`

```js
// colors.js
export default ['blue', 'red'];
```
```js
// Label/index.js
import colors from './colors.js';

Label.propTypes = {
  color: PropTypes.oneOf(colors),
};
```
![image](https://user-images.githubusercontent.com/3311321/60118694-b2c5a600-9731-11e9-8559-75ff6cb36711.png)

**Expected behavior**

Replace the `color` propType in the Label component to a hard-coded array:

```js
// Label/index.js
Label.propTypes = {
  color: PropTypes.oneOf(['blue', 'red']),
};
```
![image](https://user-images.githubusercontent.com/3311321/60118817-f28c8d80-9731-11e9-9669-96e46c080361.png)

**Comment by aarohmankad** [comment]
After more research, this turns out to be an issue with the `react-docgen` library. You can follow along with the Pull Request here: https://github.com/reactjs/react-docgen/pull/352

**Comment by pasupuletics** [comment]
@aaronmankad, mean while u can use https://github.com/siddharthkp/react-docgen-external-proptypes-handler

**Comment by y0n3r** [comment]
I'm having this same exact issue in storybook right now and it's infuriating 😡
