### ISSUE TITLE
Inline Code component background-color mismatch

### ISSUE THREAD

**Issue by nickrenfo2** [styleguidist/react-styleguidist#1398]
**Current behavior**

Currently, the default theme suggests that the `background-color` for the Code component should be `#f5f5f5` ([see here](https://github.com/styleguidist/react-styleguidist/blob/master/src/client/styles/theme.js#L24)). However, in another place, the Code component is rendered with `background: transparent;` as [seen here](https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/Code/CodeRenderer.js#L10).

**To reproduce**

This can be seen in the [default example repository](https://github.com/styleguidist/example) (no changes required).
[![Screenshot from Gyazo](https://gyazo.com/d9c622ac382e6707c4e88f55d822dfcd/raw)](https://gyazo.com/d9c622ac382e6707c4e88f55d822dfcd) for easy reference.

**Expected behavior**

I would expect that the `backround-color` for the inline Code block should be the same as the `background-color` for the full-size Code block. At the very least, the styles in the theme should reflect the styles from the component.

**Comment by sapegin** [comment]
Background on inline code blocks make text almost unreadable, so it can't be the default. But feel free to add a theme variable for that.

**Comment by jkarttunen** [comment]
Looks fine to me. Subtle enough to not be an accessibility problem, but better hint than pure typography.  (Styles lifted from github inline code styles)


![Screenshot 2019-07-26 at 18 40 07](https://user-images.githubusercontent.com/914822/61963711-e87dd900-afd4-11e9-9224-73487d227841.png)
