### ISSUE TITLE
underline in *.md file was gone,but when fill in the code section，it is correct

### ISSUE THREAD

**Issue by xudihui** [styleguidist/react-styleguidist#1400]
**Current behavior**
MD file capture:
![image](https://user-images.githubusercontent.com/15371788/61363964-76f8a900-a8b7-11e9-85d2-906daed5d9ae.png)

render capture:
![image](https://user-images.githubusercontent.com/15371788/61364157-df478a80-a8b7-11e9-9c8b-93941fff56b5.png)

without bash code section：CAP_APP_CODE=> CAPAPPCODE
in bash code section ：CAP_APP_CODE=> CAP_APP_CODE

**Expected behavior**
CAP_APP_CODE=> CAP_APP_CODE

**Comment by sapegin** [comment]
This is now Markdown supposed to work, you need to wrap your consts in backticks: `` `CAP_APP_CODE` ``.
