### ISSUE TITLE
Warning build contains invalid source map

### ISSUE THREAD

**Issue by josias-r** [styleguidist/react-styleguidist#1401]
I've setup Styleguidist with create-react-app --typescript and am now getting `WARN Compiled with warnings` with the following warnings:

```
build/main.c9fb61c8.js contains invalid source map
build/bundle.feb19782.js contains invalid source map
build/2.76ae67e6.js contains invalid source map
```

There was an issue opened with the same question but never answered: https://github.com/styleguidist/react-styleguidist/issues/1256

Any ideas where that is coming from? (not getting it when running the server)

**Comment by fosterdouglas** [comment]
Also having this identical issue.

**Comment by josias-r** [comment]
Was never resolved, I'm not using Styleguidist anymore though.

**Comment by sombreroEnPuntas** [comment]
Issue still happening :o

**Comment by gkekesi** [comment]
Still happening...
