### ISSUE TITLE
Unable to import SVG as ReactComponent

### ISSUE THREAD

**Issue by esSBbe** [styleguidist/react-styleguidist#1408]
Hi there,
trying to create a simple Readme.md example of my React component which receives a prop 'icon' which is an SVG icon imported as ReactComponent (new in create-react-app 2):

`import { ReactComponent as Warn } from './assets/svg/warn.svg`
`<MyComponent icon={Warn} />`

While the above works just fine in standard .js file I can't seem to get it working inside Readme.md. Would you be so kind and point me direction I should be looking into

EDIT: It does not throw any kind of error message, simply prints undefined when trying to console log the imported

**Comment by Hxiaotong** [comment]
I same question,are you relovsed?
