### ISSUE TITLE
Component list not shown if there are no sections

### ISSUE THREAD

**Issue by alexcanessa** [styleguidist/react-styleguidist#1417]
**Current behavior**

Since 9.1.14 is changing the logic for sections, if no `sections` are present in the configuration (I only want a flat list of components) the `<TableOfContents />` doesn't pass the `items` correctly.

**To reproduce**

Update to the latest version (9.1.14) and don't use `sections`.

**Expected behavior**

Show a flat list of components (as per <=9.1.13).

**Comment by ofilio** [comment]
Have same trouble. If `sections` length < 2 list not render.
