### ISSUE TITLE
How to make react-styleguide to support show documentation for JSDoc params?

### ISSUE THREAD

**Issue by Aminadav** [styleguidist/react-styleguidist#1424]
Whatever I'm doing I'm not able to generate docs for components that uses JSDoc.

For e.g.

The following code:

    /**
     * @param {{name:string}} props
     * */
    export function Button(props) {

    }

Should show me:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/09S8b.png

To see the props I must use propTypes

    Button.propTypes = {
      name: PropTypes.string,
    }

So, how to make `react-styleguidist` to work with JSdoc (or even kind of typescript).

A working example would be appreciate.

**Comment by j-te** [comment]
Like this:

```js
Calculator.propTypes = {
  /** Disables all controls */
  disabled: PropTypes.bool,
  /** Allows for a footer such as a message for validation */
  footer: PropTypes.node,
  /**
   * Called when currentValue state has been updated
   * @returns {Number}
   */
  onChange: PropTypes.func,
  /** Input value which updates the current value. Can be used as default value. */
  value: PropTypes.number
};
```

```js
Calculator.defaultProps = {
  disabled: false,
  onChange: () => {}
};
```

...results in:

![image](https://user-images.githubusercontent.com/34647206/64026383-90d40f80-cb36-11e9-9a0f-899d0e122b5e.png)

**Comment by NorthwesternDirector** [comment]
> Whatever I'm doing I'm not able to generate docs for components that uses JSDoc.
> 
> For e.g.
> 
> The following code:
> 
> ```
> /**
>  * @param {{name:string}} props
>  * */
> export function Button(props) {
> 
> }
> ```
> 
> Should show me:
> 
> [![enter image description here](https://camo.githubusercontent.com/4e286fba9c2fcde87cb88690768302b53da1ef0893a6dfe6abd8c7ea4accc9a2/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f30395338622e706e67)](https://i.stack.imgur.com/09S8b.png)
> 
> To see the props I must use propTypes
> 
> ```
> Button.propTypes = {
>   name: PropTypes.string,
> }
> ```
> 
> So, how to make `react-styleguidist` to work with JSdoc (or even kind of typescript).
> 
> A working example would be appreciate.



have you solved the problem？
