### ISSUE TITLE
Prop list doesn't understand array const

### ISSUE THREAD

**Issue by mr-koshkins** [styleguidist/react-styleguidist#1428]
I have such a component:

```js
import React from 'react';
import PropTypes from 'prop-types';

import * as list from './types';

const types = Object.keys(list);

const Comp = ({ type }) => <div>{type}</div>;

Comp.propTypes = {
    type: PropTypes.oneOf(types),
};

export default Comp
```
And get this in props description.
![image](https://user-images.githubusercontent.com/47605061/64360049-51b02d80-d012-11e9-86d3-5a9fe14f231b.png)

But i expect to get like this
![image](https://user-images.githubusercontent.com/47605061/64359744-a43d1a00-d011-11e9-9878-1b37ad07716f.png)

What am I doing wrong?

**Comment by apennell** [comment]
This looks like a duplicate of issue #1394

**Comment by mr-koshkins** [comment]
Thanks. I will follow #1394
