### ISSUE TITLE
Section overview on large design systems.

### ISSUE THREAD

**Issue by jkarttunen** [styleguidist/react-styleguidist#1436]
**The problem**

When documenting design systems, we want to include general design documentation and guidelines. In a DS documentation, component directory is just one major section. Eg.
1. Introduction
2. Design Principles
3. Tone of Voice
4. Images and illustrations
5. UI components

**Proposed solution**

Let's make it easier to split large design systems to independent sections. Either by enabling section collapsing or some kind of main navigation.

For example see
 http://digitalstyle.teliacompany.com/ (Collapsible sections)
and
  https://pulse.heartbeat.ua/  (main navigation)

**Alternative solutions**

Alternative solution to new feature would be example scripts, eg. for building multiple styleguidist instances, one for each section.

**Comment by MrHavard** [comment]
My team does this today with the sections configuration adding general design system documentation in one set of sections and component definitions in another and control the rendering using section depth. We've been contemplating using styleguidist this way across a mono-repo to keep the philosophy and theory of the design system separate from the practical applications of the platform components.

**Comment by elevatebart** [comment]
Collapsing sections seem to be a recurring need. 
I have done it often in customization and it is definitely doable.

1. @jkarttunen is this what you are asking for?
1. @sapegin if yes should this be behind an option?
1. when searching in the left bar should we uncollapse all sections?

**Comment by sapegin** [comment]
2. I think so, and disabled by default. For small style guides it would be a lot of unnecessary clicks.

**Comment by elevatebart** [comment]
@jkarttunen @sapegin Will get on it as soon as the ts refactoring is done.
