### ISSUE TITLE
Disable TerserPlugin to debug in production

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1442]
**The problem**

We have all our production build broken and it is unclear why (See #1440)

Because of the all compressed JS code, it is even harder to debug, because we can't see the trace.

**Proposed solution**

Add an option to disable Terser on production build.

**Alternative solutions**

Find a way not to let production build break when core dependencies change

**Comment by kopax** [comment]
> @kopax uglify is abandoned, please switch on terser-webpack-plugin https://github.com/webpack-contrib/terser-webpack-plugin

Source: https://github.com/webpack/webpack/issues/9794#issuecomment-540596331)

**Comment by sapegin** [comment]
Done in #1443.
