### ISSUE TITLE
Production build fails but dev works

### ISSUE THREAD

**Issue by rolandjitsu** [styleguidist/react-styleguidist#1444]
**Current behavior**

If I build a production build w/ `styleguidist build` it will fail w/ the following error:
```
bundle.d11af456.js:12 Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.d11af456.js:12)
    at Object.<anonymous> (bundle.d11af456.js:12)
    at n (bundle.d11af456.js:12)
    at Object.<anonymous> (bundle.d11af456.js:12)
    at n (bundle.d11af456.js:12)
    at Object.<anonymous> (bundle.d11af456.js:12)
    at n (bundle.d11af456.js:12)
    at bundle.d11af456.js:12
    at Object.<anonymous> (bundle.d11af456.js:12)
    at __webpack_require__ (bundle.d11af456.js:1)
```

**To reproduce**
1. Fork the repository: https://github.com/rolandjitsu/react-dropzone
2. Install deps w/ `yarn install`
3. Run the build w/ `yarn styleguide`
4. Open the result in a browser (build output should be in the project root `./styleguide`)

**Expected behavior**

Production build should work.

**Comment by oterral** [comment]
@rolandjitsu if it can helps . In our project, we fixed  it fixing the terser version in package.json 
```
  "resolutions": {
    "terser": "4.3.4"
  },
```

`resolutions ` works with `yarn` but there should be an equivalent for `npm` I guess

**Comment by kopax** [comment]
Related https://github.com/webpack-contrib/terser-webpack-plugin/issues/173 https://github.com/terser/terser/issues/490

**Comment by fabiosantoscode** [comment]
Very cool :) I've just fixed the issue on my end.

I would greatly appreciate if you opened up the Terser options for your users to change, as they will be armed with the required tools to post nice bug reports :)

**Comment by kopax** [comment]
It's done already @fabiosantoscode https://github.com/styleguidist/react-styleguidist/pull/1443
