### ISSUE TITLE
Broken style when using ```jsx static

### ISSUE THREAD

**Issue by karakashevivo** [styleguidist/react-styleguidist#1450]
**Current behaviour**
When I want to show a component with `  ```jsx static`, the text is no more wrapped inside the `<pre>`. 

 `overflow: auto` is fixing it, but as I understood from the documentation, there is no way to pass this code to the right place. 

In my case this issue is breaking the whole mobile version  of styleguidist and also the behaviour of some components. Any idea how this can be fixed?

<img width="534" alt="Screenshot 2019-10-16 at 17 33 56" src="https://user-images.githubusercontent.com/48553660/66934687-2a9a4200-f03b-11e9-97da-bc5619e003ac.png">

**To reproduce**
1. Add code with long lines with `  ```jsx static`
2. Shrink the browser and see the behaviour.

**Expected behavior**
The content  box to be scrollable left-right.
Or the content of the box to running down.

**Comment by kopax** [comment]
I did not notice this, is this happening in the demo?
BTW, you can edit `html-webpack-mini` plugin to inject custom css.

**Comment by karakashevivo** [comment]
Issue is fixed after the version 9.
In 9.1.16 there is still problem with long strings, which has no space and no `-`:
![image](https://user-images.githubusercontent.com/48553660/67672317-f5192100-f977-11e9-90e1-056e8cb90438.png)

**Comment by sapegin** [comment]
Looks like we should add `overflow: auto` to code examples? Feel free to send a pull request with a fix! 👾
