### ISSUE TITLE
Investigation: can't upgrade Acorn to 7.x

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1457]
I'm trying to upgrade Acorn from 6.30 to 7.0.0 (or 7.1.0) and it doesn't work:

```
SyntaxError: Unexpected token (1:6)
1 : <React.Fragment><Button>Push Me</Button></React.Fragment>;
          ^
```

```
SyntaxError: Unexpected token (3:15)
1 : import Placeholder from '../Placeholder'
2 : ;<Button>
3 :   <Placeholder />
                   ^
```

I don't see any migration guide or [changes](https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md) that may break JSX parsing. Any hints would be great here.

**Comment by malyzeli** [comment]
Probably related to #1321

**Comment by sapegin** [comment]
@malyzeli I think you're right, closing this one as duplicate.
