### ISSUE TITLE
Building a UI library - Can StyleGuidist be used to manage componants packaging lifecycle?

### ISSUE THREAD

**Issue by Vadorequest** [styleguidist/react-styleguidist#1464]
I've looked into SG, but I don't see how it helps at managing the packaging workflow of the components themselves.

I'm not sure if SG was built with this purpose in mind, and I know how time consuming managing each component one by one is.

I'm not only looking at documenting my components, I need to manage them. I'm thinking about using a dedicated repository to do that, so that I have all my UI components living under the same roof, with the ability to package and deploy them individually, as well as testing them, visualise them, play with them (playground-like). The goal is to build some kind of components library, in order to improve reusability across all my apps.

Can SG help with that? If not, what could? I've also looked at StoryBook and DocZ and none seem to be meant to manage components lifecycle.

**Comment by sethachoi** [comment]
@Vadorequest idk if you're still looking for something but it sounds like you're more describing using something like bit.dev, or a lerna monorepo supplemented by storybook or styleguidist

**Comment by Vadorequest** [comment]
Yes, I'm still looking around, not familiar at all with lerna+storybook/styleguidist, would you have some examples? Bit.dev is interesting but it seems that it's more a place to share stuff, not manage lifecycle (but I just quickly looked around and may have missed some stuff)

**Comment by thecodejack** [comment]
something like https://github.com/react-workspaces/react-workspaces-playground  ?

**Comment by Vadorequest** [comment]
I've found this article that showcases Bit and it's very similar to what I need actually.

https://blog.bitsrc.io/simplify-complex-ui-by-implementing-the-atomic-design-in-react-with-bit-f4ad116ec8db

I'll close this issue, I believe I've got enough feedback to go forward :) Thanks!
