### ISSUE TITLE
Hot reload in v10.0.0+ prohibits stopping node process 

### ISSUE THREAD

**Issue by jschmuecking** [styleguidist/react-styleguidist#1466]
**Current behavior**

When I start a styleguidist dev server, trigger a hot reload and stop the process via CTRL+C in the console, the node process does not finish and keeps blocking the 6060 port.

I tried this on two unrelated laptops under windows 7 and windows 10, both giving the same results. My colleague using a MAC OS x Mojave does not have any problems. Stopping the process there also results in the proper exit of the node process releasing the port for other processes / fresh run of styleguidist.

The problem therefore seems to be related to Windows and also does not occur when immedietly stopping the process. Version 9.2.0 works fine on both tested laptops. So the breaking change is introduced in v10.0.0 as it seems.

**To reproduce**
Windows 7 + Node v10.15.1
Windows 10 + Node v12.13.0

- Checkout the example react-styleguidist project.
- Increase the react-styleguidist version to "v10.0.0"
- npm install followed by npm start
- go to localhost:6060
- trigger a hot reload (change something benign like the button.md text
- stop the styleguidist process via CTRL+C in the console
- check with "netstat -aon | findstr 6060" that the node process is still running even though it should have been stopped

https://github.com/jschmuecking/example

**Expected behavior**

The node process should have been stopped properly after the hot-reload.

**Comment by jologz** [comment]
I recently updated ours to 10.2.0 from 9.2.0 and our engineers are using windows machines.  We are experiencing this exact error.  Also, we can only update a markdown for the first time to show the changes in chrome and any changes after that, the server won't even compiles.

We downgraded to 9.2.0

**Comment by jschmuecking** [comment]
Version 10.2.1 seems to have fixed this problem for me. Probably one of the dependencies had the issue and got fixed with the latest updates. Can you also verify that @jologz ? If yes I would close this issue.

**Comment by jologz** [comment]
It is working again for 10.2.1.  You can close this.  Thanks!
