### ISSUE TITLE
`Styles` option as a function

### ISSUE THREAD

**Issue by elevatebart** [styleguidist/react-styleguidist#1474]
When we use `styles` customization, we cannot reference anything from the theme. This means that everything that is changed has to be changed in multiple places.

It could be useful to allow developers to use a function to set styles in their config instead of a pure object. My idea was something like this:

```js
// styledguide.config.js
module.exports = {
  styles({color}){
    Table: {
      tableHead: {
        borderBottom: [[1, 'solid', color.border]]
      }
    }
  }
}
```

**Comment by sapegin** [comment]
That's a great idea!
