### ISSUE TITLE
Hot Module Reloading for theme and styles

### ISSUE THREAD

**Issue by elevatebart** [styleguidist/react-styleguidist#1475]
Whenever I want to update the styles/theme of my style guide, I have to not only reload the page but stop and restart styleguidist entirely... not perfect.

What about passing styles and themes as references to files to require?
This way we could load them using webpack and leverage HMR on a very standard way.

We could have one file for styles and one file for themes. 
It has been my experience that one wants to reference one in the other. 
We could as well have one file for both exporting theme and style as members,

**Comment by sapegin** [comment]
Not sure what you mean here, can you show an example of how it could look?

**Comment by elevatebart** [comment]
Here is how I would see it:

in `styleguide.config.js`
```js
module.exports = {
  theme: path.resolve(__dirname, './styleguide/theme.js')
}
```

then in `styleguide/theme.js`

```js
module.exports ={
  color: {
    base: '#123456'
  }
}
```

I could bake a quick PR when I am done with TypeScript

**Comment by elevatebart** [comment]
I would see the implementation of the option being a webpack alias override,
Add an extra import in this file of the non aliased theme:
https://github.com/styleguidist/react-styleguidist/blob/ef4c109bf6b7dc594346332c9091fdab3e83c9b4/src/client/styles/createStyleSheet.ts#L3-L11

Then once the alias is taken it uses the users file and can design properly with Hot Module Reload

**Comment by sapegin** [comment]
Can we hot reload the whole config instead?

**Comment by elevatebart** [comment]
No because it contains the webpack Config...

Bart Ledoux
