### ISSUE TITLE
Closing isolated view doesn't return to correct location when using sections

### ISSUE THREAD

**Issue by prevuelta** [styleguidist/react-styleguidist#1479]
**Current behavior**

When I view a component in isolated view then close it returns to root not to the component (when using sections)

**To reproduce**

View isolated component then return

**Expected behavior**

Return to component I was viewing. eg. #/Forms?id=form but returns me to #/form

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by elevatebart** [comment]
This one is not easy since it means changing how the Urls are built. 
We need to add to each component/section the calculated url, so that we can share the urls and slugs between sidebar "TableOfContents" and "IsolateButton".

@sapegin, I will try a PR. I hope it can be resolved soon.
