### ISSUE TITLE
Can I import the ESLint configuration from my project into styleguidist?

### ISSUE THREAD

**Issue by mimshwright** [styleguidist/react-styleguidist#1488]
It appears that styleguidist is using its own settings for eslint since I'm getting errors that appear when I start the server but not when I run eslint on its own. 

Is it possible to tell Styleguidist to use my local .eslintrc.json instead? Would it be possible to add this as a config parameter?

**Comment by sapegin** [comment]
Styleguidist doesn't use ESLint, it's coming from your own project somewhere, like your webpack config. 

Where do you see errors? Check which webpack config is used by running Styleguidist with `--verbose` flag.

**Comment by poteirard** [comment]
If you are using the latest `react-scripts` for building make sure you have `process.env.EXTEND_ESLINT=true`

**Comment by stepancar** [comment]
@mimshwright could you provide more information?

**Comment by Leviathan91** [comment]
Jumping on this, I think I have the same issue. Is it possible to use your own eslint file with styleguidist, without having to fiddle around with webpack? Because the react-scripts eslint is too strict.
