### ISSUE TITLE
Showing Page Not Found for Isolated Component page

### ISSUE THREAD

**Issue by piyushkadam5** [styleguidist/react-styleguidist#1492]
**Current behavior**

<img width="973" alt="not_working" src="https://user-images.githubusercontent.com/21274438/70461744-5c7dd100-1adf-11ea-90b0-c8517562e6d4.png">

Currently the Isolated Component Page is adding the folder name in the url as you can see in the screenshot..
 If I remove the "button/" from the Url the page works fine..but by default the full screen button redirecting to the above url contains the folder name from which the component is exported. 

the working url can bee seen in this..
<img width="1440" alt="Screenshot 2019-12-09 at 6 38 21 PM" src="https://user-images.githubusercontent.com/21274438/70461588-09a41980-1adf-11ea-9fd3-6034dc37d1e0.png">

can we have some configuration regarding the isolated component page...
I wasn't able to find one..
also can we able to provide the configuration like "Isolated_page:"show"/"hide"

**Expected behavior**

**Comment by piyushkadam5** [comment]
This issue Occurred when I changed the react-styleguidist version from 8.0.0  to  10.2.1

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾
