### ISSUE TITLE
The build does not work with the copy-webpack-plugin@5.1.0

### ISSUE THREAD

**Issue by Krivega** [styleguidist/react-styleguidist#1493]
**Current behavior**
The build does not work with empty `assetsDir`

**To reproduce**

1. `assetsDir` is `undefined` 
1. yarn.lock
> ...
> copy-webpack-plugin@^5.0.4:
>   version "5.1.0"
> ...
3.  run `styleguidist build `

Error in terminal:

> ValidationError: CopyPlugin Invalid Options
> 
> options should NOT have fewer than 1 items

**Expected behavior**

Build works

**Comment by jyutzio** [comment]
Your fix has solved the issue for me. 👏 Thank you.
