### ISSUE TITLE
Remove initialState/setState

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1499]
You can define state in each example using a custom initialState/setState API:

```jsx
initialState = { count: 42 }
;<Button onClick={() => setState({ count: state.count + 1 })}>
  {state.count}
</Button>
```

This was implemented long before hooks but does the same thing as hooks:

```jsx
const [count, setCount] = React.useState(42)
;<Button onClick={() => setCount(count + 1)}>{count}</Button>
```

Now the minimum supported by Styleguidist version of React supports hooks, so we can remove our custom API.

**This will be a breaking change.**

- [ ] Remove [code for initialState/setState](https://github.com/styleguidist/react-styleguidist/blob/ef4c109bf6b7dc594346332c9091fdab3e83c9b4/src/client/rsg-components/ReactExample/ReactExample.tsx#L28-L48)
- [ ] Update examples in the docs to hooks

**Comment by thecodejack** [comment]
won't this be a breaking change?

**Comment by thecodejack** [comment]
How about updating docs before breaking change?

When breaking change happens, it will be with older apps only?

**Comment by navin1551** [comment]
Hi, is this still open? It's my first time contributing and wouldn't mind taking a shot at this

**Comment by thecodejack** [comment]
Task is completed @navin1551. Pending is merge during major release

**Comment by ThomDevine** [comment]
Currently when using `useState()` in a Markdown example, if I change an initial value in the "View Code" editor, the changes are not reflected inside of my component.

Will this change let me update values in the code editor and see them reflected inside the component?  Is it different for simple values vs nested objects?

With the given example:
```
// What happens if I change "42" in the View Code editor?
const [count, setCount] = React.useState(42)
;<Button onClick={() => setCount(count + 1)}>{count}</Button>

// What if it was this instead?
const [count, setCount] = Reat.useState({value: 42})
;<Button onClick={() => setCount(count.value + 1)}>{count.value}</Button>
```
