### ISSUE TITLE
Can't override slots component

### ISSUE THREAD

**Issue by lutaev** [styleguidist/react-styleguidist#1502]
Hi there. First of all, thanks you for your amazing library.
Could you please help me? I'm sure, I'm doing something wrong. I'm trying to do something described here: https://github.com/styleguidist/react-styleguidist/issues/968 and I want to override slots component (first - configuration in `slots/index.js`).
A piece of `styleguide.config.js`, section **styleguideComponents:**
```javascript
styleguideComponents: {
  slots: path.join(__dirname, 'app/override/slots/index')
},
```
File `app/override/slots/index`:
``` javascript
import Editor from 'react-styleguidist/lib/client/rsg-components/Editor';
import Usage from 'react-styleguidist/lib/client/rsg-components/Usage';
import IsolateButton from 'react-styleguidist/lib/client/rsg-components/slots/IsolateButton';
import CodeTabButton from 'react-styleguidist/lib/client/rsg-components/slots/CodeTabButton';
import UsageTabButton from 'react-styleguidist/lib/client/rsg-components/slots/UsageTabButton';

export var EXAMPLE_TAB_CODE_EDITOR = 'rsg-code-editor';
export var DOCS_TAB_USAGE = 'rsg-usage';
export default (function () {
  var toolbar = [IsolateButton];
  return {
    sectionToolbar: toolbar,
    componentToolbar: toolbar,
    exampleToolbar: toolbar,
    exampleTabButtons: [{
      id: EXAMPLE_TAB_CODE_EDITOR,
      render: CodeTabButton
    }],
    exampleTabs: [{
      id: EXAMPLE_TAB_CODE_EDITOR,
      render: Editor
    }],
    docsTabButtons: [{
      id: DOCS_TAB_USAGE,
      render: UsageTabButton
    }],
    docsTabs: [{
      id: DOCS_TAB_USAGE,
      render: Usage
    }]
  };
});
```
So, I'm trying to import the same components as I have imported in `react-styleguidist/lib/client/rsg-components/slots/index.js`, but got a compilation error:
```
 FAIL  Failed to compile

./node_modules/react-styleguidist/lib/client/rsg-components/slots/index.js
Module not found: Can't resolve 'rsg-components/slots/CodeTabButton' in '/Users/mac/WebstormProjects/my-components/node_modules/react-styleguidist/lib/client/rsg-components/slots'
./node_modules/react-styleguidist/lib/client/rsg-components/slots/index.js
Module not found: Can't resolve 'rsg-components/slots/IsolateButton' in '/Users/mac/WebstormProjects/my-components/node_modules/react-styleguidist/lib/client/rsg-components/slots'
./node_modules/react-styleguidist/lib/client/rsg-components/slots/index.js
Module not found: Can't resolve 'rsg-components/slots/UsageTabButton' in '/Users/mac/WebstormProjects/my-components/node_modules/react-styleguidist/lib/client/rsg-components/slots'
```
It looks like in some place original `slots/index.js` file wasn't overridden.
Thanks.

**Comment by mitsuruog** [comment]
@lutaev 
Though I am not sure if I can fully understand what you want to do. but you can override individual components by doing something like this:

styleguide.config.js
```js
styleguideComponents: {
    "slots/IsolateButton": path.join(__dirname, "src/override/slots/IsolateButton"),
    // ...
}
```

and I put the example project here. please have a look.

- https://codesandbox.io/s/misty-rain-xi7o4

![misty-rain-xi7o4 - CodeSandbox](https://user-images.githubusercontent.com/1703219/75601590-f6ae4d80-5aff-11ea-80b0-d6e42f6e18ef.png)

**Comment by tehandyb** [comment]
Would be nice to be able to override the slots themselves. I had to override the Slot component to be able to use my own slots

**Comment by meeroslav** [comment]
@tehandyb I am facing the same issue. This used to work before but after migrating from v6 to v11 it's no longer possible to override the `slots`.

Care to share how you solved it via `Slot` components?

Care to share how you

**Comment by tmf** [comment]
This is still possible, just need to tweak the `styleguideComponents` field a bit:
```
styleguideComponents: {
    "slots/IsolateButton": path.join(__dirname, 'node_modules/react-styleguidist/lib/client/rsg-components/slots/IsolateButton'),
    "slots/CodeTabButton": path.join(__dirname, 'node_modules/react-styleguidist/lib/client/rsg-components/slots/CodeTabButton'),
    "slots/UsageTabButton": path.join(__dirname, 'node_modules/react-styleguidist/lib/client/rsg-components/slots/UsageTabButton'),
    slots: path.join(__dirname, 'app/override/slots/index'),
}
```

This results in the following webpack config, where the internal module resolution still works:
```
// ...
 alias: {
      'rsg-components/slots/IsolateButton': '/home/tmf/projects/my-project/node_modules/react-styleguidist/lib/client/rsg-components/slots/IsolateButton',
      'rsg-components/slots/CodeTabButton': '/home/tmf/projects/my-project/node_modules/react-styleguidist/lib/client/rsg-components/slots/CodeTabButton',
      'rsg-components/slots/UsageTabButton': '/home/tmf/projects/my-project/node_modules/react-styleguidist/lib/client/rsg-components/slots/UsageTabButton',
      'rsg-components/slots': '/home/tmf/projects/my-project/apps/components-styleguide/src/slots/index',
      'rsg-components': '/home/tmf/projects/my-project/node_modules/react-styleguidist/lib/client/rsg-components'
    }
// ...
```

I think this is due to the fact that there is an `rsg-components` _and_ a `rsg-components/slots` alias. The order is important, and we have to declare a more specific override for `rsg-components/slots/*`.

Also, keep in mind that the `export default` signature has changed in `rsg-components/slots` between v6 and v11: it's now a `function` returning an object.
