### ISSUE TITLE
v11 automatic Typescript support does not play well with 3rd party components

### ISSUE THREAD

**Issue by dysticus** [styleguidist/react-styleguidist#1508]
**Current behavior**

RSG v11's automatic Typescript support does not seem to play well with 3rd party components. 
In <v11, in combination with react-docgen-typescript, props and methods were correctly parsed after setting the propsparser property in the config. From > v11 react-docgen was upgraded so react-docgen-typescript was no longer required.

**To reproduce**

Clone https://github.com/dysticus/example . It contains 2 branches: notworking and working. Not working is with v11, working is with <v11 and react-docgen-typescript.

Start the styleguide. You'll see in the the non-functional version no props and no methods, in the working branch they do appear.

**Expected behavior**

Props and methods should be extracted for 3rd parties to, like in versions before v11.

Thanks!

**Comment by thecodejack** [comment]
I see this warning in non working branch which means `react-docgen` unable to parse the component. Can you please raise the issue with `react-docgen`?

![image](https://user-images.githubusercontent.com/1515160/71775091-c7b4a900-2fa0-11ea-8066-c0c137c12a74.png)

**Comment by thecodejack** [comment]
Did a bit a of code walkthrough and realized, `react-docgen` never supported thirdparty lib parsing. As mentioned in https://react-styleguidist.js.org/docs/thirdparties.html#how-styleguidist-works , it always parses static files we produce. But with `react-docgen-typescript`, it checks for types / interfaces and them for prop parsing. 

I don't see `react-docgen` fixing the issue anytime soon. Probable solution I can see is, suggest `react-docgen-typescript` for third party component parsing like before in documentation with the release.

What do you suggest @sapegin ?

**Comment by sapegin** [comment]
Yeah, I guess properly document what's not supported by react-docgen and supported by react-docgen-typescript would be good start.
