### ISSUE TITLE
Make docs available for all previous versions

### ISSUE THREAD

**Issue by thecodejack** [styleguidist/react-styleguidist#1512]
At present, we can show docs only for latest version of component library.

Would be awesome if there is a way for user to browse to older version of component library.

Example of implementation can be [emberjs api documentation](https://api.emberjs.com/ember/release) where you have a dropdown to select version. 

![image](https://user-images.githubusercontent.com/1515160/71777088-723cc400-2fc1-11ea-94fc-60a0dee5d9e6.png)

On top of my mind, an easy implementation can be code split the generated component library and use webpack to name chunks with version names. Only issue i can see with this is cache busting won't work.

**Comment by stepancar** [comment]
I think it's out of scope this project. You can implement your own wrapper around react-styleguidist static and provide dropdown which changes the versions of static.
