### ISSUE TITLE
How to ignore Typescript props using & operator

### ISSUE THREAD

**Issue by najisawas** [styleguidist/react-styleguidist#1523]
Have looked around the internet for a proper answer but haven't found one.

How do I ignore props added to my component using the `&` operator in Typescript?

ie.
```
import { TextFieldProps } from "@material-ui/core/TextField";

type Props = {
   /** The ID of the element */
   id: string;
   /** @ignore */
} & TextFieldProps;
```

Does not work. All of the props from TextField Props are displayed, as opposed to solely the `id` prop

**Comment by Xiphe** [comment]
I've recently build a wrapper around `react-docgen-typescript` and use that for the `propsParser` option.

It uses JSDoc tags to add filters and overwrites of props. 

This would for example only display the `id` prop in the styleguide.

```ts
import { TextFieldProps } from "@material-ui/core/TextField";

type Props = {
   /** The ID of the element */
   id: string;
} & TextFieldProps;

/**
 * @propsFilter id
 */
export function MyComp({ id, ...rest }) {
  return /* ...implementation */
}
``` 

If you're interested, I could create an npm package out of that and publish it.

**Comment by wrdsnd** [comment]
@Xiphe it would be great to see your wrapper for hiding unnecessary props. Does it support react-docgen 5 or it's only compatible with react-docgen-typescript?
