### ISSUE TITLE
Why styleguidist takes a wrong name for component?

### ISSUE THREAD

**Issue by krutoo** [styleguidist/react-styleguidist#1528]
Hi. In my components library i use stylegiudist, but it takes wrong name for component:

![image](https://user-images.githubusercontent.com/13140130/73048403-d81ebc00-3e9a-11ea-806a-05cf178c53b8.png)

Component file is located at `src/components/amount/`

This is files in catalog:

![image](https://user-images.githubusercontent.com/13140130/73048445-02707980-3e9b-11ea-96c0-2fe6154c5184.png)

`amount.jsx` file code like:
```jsx
 /* ... */ 

const DEFAULT_PROPS = { /* ... */ };

 /* ... */ 

const Amount = () => { /* ... */ };

 /* ... */ 

export default Amount;
```

How can i rename output in html?

**Comment by krutoo** [comment]
how can i resolve problem?

**Comment by mitsuruog** [comment]
@krutoo which version are you using?

**Comment by krutoo** [comment]
@mitsuruog  react-styleguidist 9.0.5

**Comment by mitsuruog** [comment]
@kidkuro would you try it on the latest version?

**Comment by krutoo** [comment]
Yes, i upgrade react-styleguidist to 11.0.5

I think this is because in my DEFAULT_PROPS (which is above component definition) i have **function properties which returns React elements**:

```jsx
// [some imports here]

const DEFAULT_PROPS = {
  // eslint-disable-next-line react/prop-types
  renderPlus: ({ size, disabled, onClick }) => (
    <Icon {/* ... */} />
  // ...
};

/**
 * [Amount JSDoc here]
 */
const Amount = () => {/* ... */};

Amount.propTypes = {/* ... */};

export default Amount;
```

**Comment by mitsuruog** [comment]
@krutoo 
hmm, I could not reproduce it. 
could you make a reproducible demo? I have a small template here.

- https://github.com/mitsuruog/react-styleguidist-issue-template

**Comment by krutoo** [comment]
@mitsuruog Yes, here is forked sandbox with reproduced issue:
https://codesandbox.io/s/nostalgic-field-x4y0r?file=/src/components/button/README.md

**Comment by mitsuruog** [comment]
@krutoo 
you have a `findAllComponentDefinitions` in your `stylegude.config.js`.
it finds all component definitions, not only the one that is exported.

```js
  resolver: reactDoc.resolver.findAllComponentDefinitions,
```

and react-styleguidist document says:

> Warning: If you export several React components as named exports from a single module, Styleguidist is likely to behave unreliably. If it cannot understand which named export to expose, you may not be able to access that export.

If it were me, I would try something like this:
-  remove `findAllComponentDefinitions` in your config
- Or move your `DEFAULT_PROPS ` component to another file

**Comment by krutoo** [comment]
ok, i will change `findAllComponentDefinitions ` thanks
