### ISSUE TITLE
Adding multiply font families in Styled component ends up with WARNING

### ISSUE THREAD

**Issue by IsmayilAghazada** [styleguidist/react-styleguidist#1529]
I'm using the latest version of React Styleguidist. 
When I upgrade version(7.3.11 -> 10.6.1 ) of React Styleguidist I faced with font-face problem of Styled component.And I couldn't use multiply font families.In console there is following warning:

<img width="1680" alt="Screen Shot 2020-01-24 at 10 57 11 AM" src="https://user-images.githubusercontent.com/48431337/73055780-fc809580-3ea6-11ea-94f6-2dce86952a3d.png">

In Safari I got that warning:
**Warning: [JSS] The string did not match the expected pattern.**

**Btw When I add only one font family it works well.**

**Comment by aqilatakishiyevpb** [comment]
**i faced with the same problem too.**

**Comment by rawen554** [comment]
Have you solved this issue?

**Comment by IsmayilAghazada** [comment]
> Have you solved this issue?

yes.I have created fonts.css added it to config file of styleguide,like the following:
```
template: {
        favicon: '/favicon.ico',
        head: {
            links: [
                {
                    rel: 'stylesheet',
                    href: './static/css/fonts.css'
                }
            ]
        }
    },
```

**Comment by rawen554** [comment]
> > Have you solved this issue?
> 
> yes.I have created fonts.css added it to config file of styleguide,like the following:
> 
> ```
> template: {
>         favicon: '/favicon.ico',
>         head: {
>             links: [
>                 {
>                     rel: 'stylesheet',
>                     href: './static/css/fonts.css'
>                 }
>             ]
>         }
>     },
> ```

Literally did the same already, thanks
