### ISSUE TITLE
How to open href of external link in a new tab (target="_blank") ?

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1531]
Hi everyone, is there a way I can make external links to open in new tab?

I saw this: https://diff.intrinsic.com/react-styleguidist/9.0.8/9.0.9 and tried with `shouldOpenInNewTab: true` but this didn't work.

**Comment by icaromh** [comment]
Hi @kopax, are you trying to open markdown links in another tab or the sidebar ones? 
This option `shouldOpenInNewTab` only works for the sidebar links.

You can write plain HTML links inside your `.md` files:
```
# title

- list

<a href="http://github.com" target="_blank">link</a>

```

[Take a look in this StackOverflow answer](https://stackoverflow.com/a/4425223)

**Comment by kopax** [comment]
Hi @icaromh and thanks. No I am not in markdown, but in menu generation, it is made from `sections` provided with the react styleguidist configuration `styleguide.config.js`.

I want to have an external link in my left menu that open in a new tab. Any idea?

**Comment by icaromh** [comment]
@kopax I'd tested on `"react-styleguidist": "^10.2.1",` using the sections like this:

```js
sections: [{
    name: "Online documentation",
    href: "https://github.com/styleguidist/react-styleguidist",
    external: true,
    shouldOpenInNewTab: true,
}]
```

The link generated was `<a class="rsg--link-29" href="https://github.com/styleguidist/react-styleguidist" target="_blank">Online documentation</a>`, and it just works fine. 

Wich styleguidist version are you using?

**Comment by kopax** [comment]
Weird, I am using react-styleguidist 9.1.2 and I can't update, is this supposed to work in 9.1.2 ?
