### ISSUE TITLE
Cannot find module 'rsg-components/StyleGuide/StyleGuideRenderer'

### ISSUE THREAD

**Issue by milobluebell** [styleguidist/react-styleguidist#1532]
what's rsg-components ????? module can not find....!

**Comment by milobluebell** [comment]
hi when i follow this:[https://github.com/styleguidist/react-styleguidist/blob/master/examples/customised/styleguide/components/SectionsRenderer.js](url)，it told me: 
```
Module not found: Can't resolve 'rsg-components/StyleGuide/StyleGuideRenderer' in '/Users/milo/Documents/oui-guidist/node_modules/react-styleguidist/lib/client/rsg-components/StyleGuide'
```

**Comment by icaromh** [comment]
> what's rsg-components ????? module can not find....!

`rsg-components` it's an alias to [`./src/client/rsg-components`](https://github.com/styleguidist/react-styleguidist/tree/master/src/client/rsg-components), you can read more [here on the docs](https://react-styleguidist.js.org/docs/development#react-components).

**Comment by icaromh** [comment]
@milobluebell About the example, it uses the version `"react-styleguidist": "^9.1.16",` are you using the major `9` as well? 

I'm not sure, but the example could outdated. You can see more info how to replace components [on this link](https://react-styleguidist.js.org/docs/configuration.html#styleguidecomponents)

**Comment by cttith** [comment]
As @icaromh pointed out the examples are using an older version of styleguidist.  The current module is stuctured differently. Add this to your webpackconfig
`resolve: {
			alias: {
				'rsg-components': path.join(__dirname, 'node_modules/react-styleguidist/lib/client/rsg-components/')
			}
		}`

**Comment by dudeinthemirror** [comment]
For me, this was caused by having the `@component` decorator in some comments. Hope it might help someone out there. I'm using the following versions :
```
"react-docgen-typescript": "^2.2.2",
"react-styleguidist": "11.2.0",
```
