### ISSUE TITLE
Error: Invariant failed: You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by dgh500** [styleguidist/react-styleguidist#1533]
I'm possibly missing something obvious but I have a component that renders <Link /> components from React-Router-Dom and imports Link:

    import { Link } from 'react-router-dom';

But relies on a parent component - the root App component - wrapping the app in a <Router> - now when I create a .md file for the component to show example usage (as per https://react-styleguidist.js.org/docs/documenting.html#usage-examples-and-readme-files ) I assume it's being tested in isolation and isn't picking up the parent's <Router>.

Is there a way to get around this ( e.g. with a dependencies / assumptions markup ) or have I either made a dumb mistake or is this more a feature request?

**Comment by mitsuruog** [comment]
@danielfx90 
Have you tried this way?

- https://react-styleguidist.js.org/docs/thirdparties.html#using-styleguidist-with-other-libraries

I guess your top-level component does not have `<Router>`. 
in this case, you should make a wrapper component to have `<Router>` and redefine the default component to replace it on `styleguide.config.js`.

something like:

```js
// styleguide.config.js
const path = require('path')
module.exports = {
  styleguideComponents: {
    Wrapper: path.join(__dirname, 'src/styleguide/Wrapper')
  }
}
```

```js
// src/styleguide/Wrapper.js
import React, { Component } from 'react'
import { BrowserRouter as Router } from 'react-router-dom';
export default class Wrapper extends Component {
  render() {
    return <Router>{this.props.children}</Router>
  }
}
```

(NOTE: I have not tested it yet. it might not work as it.)

**Comment by TheDiveO** [comment]
Well, it sort of works, but navigation fails, as React Styleguist's server won't serve on `/*`.
