### ISSUE TITLE
Please update example GIF with appropriate content 

### ISSUE THREAD

**Issue by joekarasek** [styleguidist/react-styleguidist#1534]
The example GIF is the readme contains inappropriate, un-professional  language ("Big Pink Button, Lick Me"). The client I'm working with has discovered it and is not happy. Doesn't make this project look very good. Please update ASAP.

**Comment by sapegin** [comment]
Feel free to record a new one and send a pull request.

**Comment by mitsuruog** [comment]
How about just change the button label to "push me"?
Wouldn't it be much better than before?

**Comment by mitsuruog** [comment]
Ah... it already has been changed in the example project. just need to replace the GIF.

- https://react-styleguidist.js.org/examples/basic/

**Comment by joekarasek** [comment]
Thank you!

**Comment by mitsuruog** [comment]
@joekarasek 
Ah. wait for a bit. this project is not so appropriate yet.
The GIF in the readme has not been updated. I'll try to make a new GIF later.

**Comment by mitsuruog** [comment]
I made a new GIF and tried to update somehow, but it seems no way to update for me.

@sapegin 
would you update this GIF on the README.md

https://camo.githubusercontent.com/7af8e5fc43288807978f28530656275008c5afbf/68747470733a2f2f64337676366c703535716a6171632e636c6f756466726f6e742e6e65742f6974656d732f32373142333732783130325330633035326933462f72656163742d7374796c6567756964697374372e676966

to the new one?

![animation](https://user-images.githubusercontent.com/1703219/74945569-51c6ad00-543b-11ea-8351-f4d86860893a.gif)

if you don't like the new one, feel free to make it garbage.
don't worry about me, I'll be fine. 
I hope someone makes good GIF later. haha.

Thanks.

**Comment by sapegin** [comment]
Thanks, done! 

P. S. No need for passive aggression here 🤔
