### ISSUE TITLE
React Native configuration example does not import .web.js

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1535]
I am referencing to https://github.com/styleguidist/react-styleguidist/blob/0ecaaf52e7ce68b41bd202d4fde382a9e8ccef6e/examples/react-native/styleguide.config.js

It seems that adding to the `styleguide.config.js` configuration does not allow documenting of `.web.js` components:

```json
{
  "webpackConfig": {
    "resolve": {
      "extensions": [".web.js", ".js"],
    }
  }
}
```

It seems that settings any value to `extensions: ['.web.js', '.js'],` doesn't break anything and is purely ignored.

I have verified the config returned to the styleguidist and it is here.

How can I tell react-styleguidist to require the `.web.js` first when documenting sections of components?

**Comment by kopax** [comment]
I have found that editing mysection to support `.web.js` kind of work:

```js
          "components": [
            "src/core/ui/ScrollView/index.{web.js,js}",
            "src/core/ui/utils/moveToBottom.{web.js,js}"
          ]
```

By doing this, it will import the `.web.js` and the  `.js`, while I only want the web version.

Removing `.js` within section configuration documented nothing.

**Comment by andrioid** [comment]
I got this working this morning after a very frustrating day yesterday. I'm using React App Rewired, so I already have a manual override to the webpack config. I added the following to it and then it started to import .web.ts/.web.js as it should.

```
module.exports = function override(config, env) {
    config.resolve.extensions = [
        ".web.ts",
        ".web.js",
        ".web.tsx",
        ".web.jsx",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
    ];
    ....
}
```

Then I use the `override()` command with Styleguidist like so:
```
const override = require("./config-overrides");
module.exports = {
    ....
    dangerouslyUpdateWebpackConfig(webpackConfig, env) {
        // WARNING: inspect Styleguidist Webpack config before modifying it, otherwise you may break Styleguidist
        // console.log(webpackConfig);
        const newConfig = override(webpackConfig, env);

        return newConfig;
    },
};
```

I hope this helps.
