### ISSUE TITLE
Styled Component example not working on recent version of styleguidist

### ISSUE THREAD

**Issue by pierrenel** [styleguidist/react-styleguidist#1536]
**Current behavior**

After upgrading react-styleguidist from 9.0.8 (in the examples directory) to ^10.6.1, when I build styleguidist, the theme I pass in via my ThemeProvider wrapper & the GlobalStyle I use stop working - strangely they work while in styleguidist server mode.

**To reproduce**

  1. Check out https://github.com/styleguidist/react-styleguidist/tree/master/examples/styled-components
  2. Update react-styleguidist, babel-plugin-styled-components and styled-components to the latest versions
  3. Run styleguidist build and serve the files in the styleguide directory

**Expected behavior**

on building styleguidist, the styled components theme should work like it does in dev mode.

**Comment by pierrenel** [comment]
fwiw, I've isolated it to upgrading from styled-components ^4.2.0 to ^5.0.1

**Comment by austin94** [comment]
@pierrenel I've opened an issue against styled-components that may be able to address this issue.

**Comment by pierrenel** [comment]
@austin94 I saw something related to merging props in their 5.1 changelog 🤔
