### ISSUE TITLE
PROPS & METHODS table broken styling

### ISSUE THREAD

**Issue by stonebk** [styleguidist/react-styleguidist#1538]
I'm trying to upgrade from react-styleguidist@9.2.0 to 10.6.2 and the PROPS & METHODS table styling seems to have broken.

### 9.2.0
<img width="387" alt="Screen Shot 2020-02-13 at 5 13 06 PM" src="https://user-images.githubusercontent.com/1432010/74492625-5eb82f00-4e84-11ea-8102-2eb04734c7bf.png">

### 10.6.2
<img width="322" alt="Screen Shot 2020-02-13 at 5 12 04 PM" src="https://user-images.githubusercontent.com/1432010/74492632-64157980-4e84-11ea-9bf6-12248c8d92a0.png">

**Comment by mitsuruog** [comment]
@stonebk 
hmm... I could not find any big differences.

Could you post a link to a reproducible sandbox?
 - https://codesandbox.io/s/github/mitsuruog/react-styleguidist-issue-template

The result is here. 
I am using Chrome mac for the testing.

### v9.2.0
![dawn-waterfall-59hwk - CodeSandbox](https://user-images.githubusercontent.com/1703219/75240680-172c8e00-5808-11ea-9a16-8bf7d955f61a.png)

- https://codesandbox.io/s/dawn-waterfall-59hwk

### v10.6.2
![10 6 2](https://user-images.githubusercontent.com/1703219/75240085-1e06d100-5807-11ea-80a1-ce964ac666e1.png)

- https://codesandbox.io/s/epic-ride-gvqpu
