### ISSUE TITLE
Rename `styleguideDir` to something more common like `outDir` or `buildDir`

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#1539]
**The problem**

I was searching the documentation for `outDir` and `buildDir` but could not find any mentions of neither. After a longer throughout read, I've found the `styleguideDir` that is what I was looking for.

**Proposed solution**

Since styleguidist is a build tool, it would make sense to follow build tool's mental model and use a more common name for it: `outDir`, `buildDir`, or propose your name.

**Comment by sapegin** [comment]
Feel free to send a pull request, honestly I don't see any difference between all three names.
