### ISSUE TITLE
Support for Typescript 3.7 features: Nullish coalescing & optional chaining

### ISSUE THREAD

**Issue by ollija** [styleguidist/react-styleguidist#1541]
**The problem**

React-styleguidist does not support Typescript 3.7 features.

**Proposed solution**

Upgrade Typescript to 3.7 and Babel to at least 7.7.0.

https://babeljs.io/blog/2019/11/05/7.7.0

**Comment by sapegin** [comment]
Doesn't support where? We only use TypeScript and Babel for development.

**Comment by hugotox** [comment]
Any updates here? I'm seeing a similar issue when trying to document components that use optional chaining:
```
Module parse failed: Unexpected token (9:34)
File was processed with these loaders:
 * ../../node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```
The erroring line is the nullish coalescing char, e.g.
```
const foo = bar ?? 'woooo'`
```
