### ISSUE TITLE
Tailwindcss?

### ISSUE THREAD

**Issue by bryan-opslock** [styleguidist/react-styleguidist#1547]
Has anyone gotten this to work with tailwindcss? I've tried the `postcss-loader` and for some reason it ignores all of my `@tailwind` commands

**Comment by pak11273** [comment]
Yep.  If you are using styleguidist with create-react-app then you just need add to the top of your components the path to your css:
```
import "<path to styles.css>"
```

**Comment by flieks** [comment]
it works but it loads before materialUI css and therefore is overwritten by material css..
