### ISSUE TITLE
Sections with href are always opening in new tabs

### ISSUE THREAD

**Issue by iSysProc** [styleguidist/react-styleguidist#1559]
![image](https://user-images.githubusercontent.com/17797341/76674313-ba97e400-65f9-11ea-8fa8-c3ecc4cc3071.png)

Section field 'external' don't affect on `shouldOpenInNewTab`

Maybe change this row on: `shouldOpenInNewTab: section.external && !!section.href,` ?

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by mitsuruog** [comment]
What is the correct and intended behavior?

**Comment by sapegin** [comment]
`external` should define the behavior if present. We probably can remove the magic that opens all sections with `href` in the new tab by default. At least the docs and the examples would be correct in this case:

https://react-styleguidist.js.org/docs/components.html
