### ISSUE TITLE
Set component example container width useful for React Native

### ISSUE THREAD

**Issue by aguscha333** [styleguidist/react-styleguidist#1561]
**The problem**

I am using this library for react native, so far it's working great, my only complaint is that components expand too much width-wise. I would like to set a max-width to the container of all examples so components look more like what they would look in a mobile device.

**Proposed solution**

Add a variable to the theme configuration where we can set the max-width/width of the container.

**Additional context**

I can create a container myself and import it in each example but it's not ideal, it makes code examples messier.

I tried to look at the source code and see if I could submit a PR but couldn't find my way. Also never worked with typescript

**Comment by sapegin** [comment]
You can either redefine the `Wrapper` component or use `styles` option to define width of the container.
