### ISSUE TITLE
Black text in normal conditions

### ISSUE THREAD

**Issue by ilyapishchulin** [styleguidist/react-styleguidist#1562]
**Current behavior**

Black text

**To reproduce**

https://vkcom.github.io/vkui-styleguide/#tabs
Tap "View code"
<img width="675" alt="Снимок экрана 2020-03-16 в 14 45 44" src="https://user-images.githubusercontent.com/45998835/76755461-f4e9b880-6794-11ea-993f-f4340beb5c7c.png">

And 
https://vkcom.github.io/vkui-styleguide/#panelheadercontext
<img width="832" alt="Снимок экрана 2020-03-16 в 14 47 35" src="https://user-images.githubusercontent.com/45998835/76755571-2793b100-6795-11ea-9068-4c2785064512.png">

**Expected behavior**

Normal color

**Comment by mitsuruog** [comment]
This project uses [prismjs](https://github.com/PrismJS/prism) for the code highlight.
I found an issue at the prismjs repo. this might be related to.

- [JSX \- Curly Braces in prop of an object prop break formatting · Issue \#1548 · PrismJS/prism](https://github.com/PrismJS/prism/issues/1548)

**Comment by ilyapishchulin** [comment]
Okey, thanks you
