### ISSUE TITLE
Crash with some rewritten imports 

### ISSUE THREAD

**Issue by dustinsoftware** [styleguidist/react-styleguidist#1566]
**Current behavior**

Some imports are not rewritten correctly and produce naming collisions.

![image](https://user-images.githubusercontent.com/942358/77339140-bce8f500-6d01-11ea-9327-7114f33c5778.png)

Looks like the logic in this file does not handle unique identifiers for all cases: https://github.com/styleguidist/react-styleguidist/blob/3469cbba172d9f81657b388dbffbb8fd5dd7fba4/src/client/utils/rewriteImports.ts

These imports:

```js
import Demo from './demo1/component.js';
import Demo2 from './demo2/component.js';

<Button><Demo /><Demo2 /></Button>
```

Get transformed into:
```js
const component_js$0 = require('./demo1/component.js');
const Demo = component_js$0.default || component_js$0;
const component_js$0 = require('./demo2/component.js');
const Demo2 = component_js$0.default || component_js$0;

React.createElement( Button, null, React.createElement( Demo, null ), React.createElement( Demo2, null ) )
```

**To reproduce**

Demo here: https://github.com/dustinsoftware/styleguidist-example/

**Expected behavior**

Unique identifier names are used.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.

This will also go away after #1553.
