### ISSUE TITLE
Can't import svg file, Cannot find module '../svg/coinmarketcap.svg'.

### ISSUE THREAD

**Issue by Hxiaotong** [styleguidist/react-styleguidist#1569]
![image](https://user-images.githubusercontent.com/18079307/77733139-4f123580-7041-11ea-9a5d-6b2d5c50ce60.png)

**Comment by Hxiaotong** [comment]
![image](https://user-images.githubusercontent.com/18079307/77733202-6b15d700-7041-11ea-8c15-69829867c9a0.png)

**Comment by mitsuruog** [comment]
@Hxiaotong 
I think this does not a style guide issue. I guess your project setup has some issues.
In general, TypeScript needs to have some steps to load SVG. 
See this stackoverflow first.

- https://stackoverflow.com/questions/44717164/unable-to-import-svg-files-in-typescript

Also, you might need to add `file-loader` on your webpack settings to load SVG. 
See also my sandbox here.

- https://codesandbox.io/s/react-styleguidist-svg-v5bgy

**Comment by sapegin** [comment]
The error is coming from Jest, not Styleguidist.
