### ISSUE TITLE
Adding SVGs to Components as ReactComponent

### ISSUE THREAD

**Issue by fakeheal** [styleguidist/react-styleguidist#1574]
_There's a [similar issue posted here](https://github.com/styleguidist/react-styleguidist/issues/1408), but it's been closed with no responses. The minor difference between my issue and the one already posted is that I get an error in styleguidist._

----------------------

## Current behavior

Components that have been passed [SVG as ReactComponent](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs) in `create-react-app`s  fail to render. 

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `LabelWithIcon`.

## To reproduce

Clone: https://github.com/fakeheal/example & run `npm install` and then `npm start` or use this code:

**LabelWithIcon.js**:

```jsx
import React from 'react';
import './LabelWithIcon.css';

export default function LabelWithIcon({ Icon, text }) {
	return (
		<div className="label-with-icon">
			<Icon className="icon" />
			{text}
		</div>
	);
}
```

**LabelWithIcon.md**:

> Label with Icon:
> 
> ```jsx
> import {ReactComponent as Logo} from '../logo.svg'; //this is react's logo that comes with CRA
> <LabelWithIcon icon={<Logo />} text="I'm with icon" />
> ```

## Expected behavior

Styleguidist to render the Component with the SVG passed.

**Comment by kopax** [comment]
I already have this in my style guide and it's not related to react styleguidist at all..
