### ISSUE TITLE
Failed at the libyaml@0.2.5 install script

### ISSUE THREAD

**Issue by Bennes** [styleguidist/react-styleguidist#1576]
**Current behavior**

yp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\modules\node_global\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\modules\\node_global\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodejs\modules\node_cache\_npx\14628\node_modules\styleguide\node_modules\libyaml
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libyaml@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libyaml@0.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\modules\node_cache\_logs\2020-04-12T11_32_52_640Z-debug.log
Install for [ 'styleguide@latest' ] failed with code 1

-----------------------------------------------------------------------------

when I npm i -g libyaml

\node_modules\libyaml\binding.cc(69): error C2143: 语法错误: 缺少“;”(在“<”的前面)

**Comment by mitsuruog** [comment]
@bennam 
you use `styleguide`, not `react-styleguidist`.

**Comment by Bennes** [comment]
> @bennam
> you use `styleguide`, not `react-styleguidist`.

oh,my god! Thank you so much
