### ISSUE TITLE
Props & Method Shape Console Warning: <div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by ryanespin** [styleguidist/react-styleguidist#1577]
**Current behavior**

A console warning is appearing for shape descriptions under the Props & Methods table:
```
<div> cannot appear as a descendant of <p>.
    in div (created by TableRenderer)
```

**To reproduce**

Add comments to parts of a shape.  Click Props & Methods.  The description area will return with a p tag with div tags nested inside for each commented shape.

**Expected behavior**

A console warning should not appear if the dom elements were changed.  Either changing the p or the div to a different tag.

**Comment by mitsuruog** [comment]
@ryanespin 
Would you give me your props and version info?
I could not reproduce it. I am using `react-styleguidist@11.0.5`
