### ISSUE TITLE
Import multiple example files for a component

### ISSUE THREAD

**Issue by yeeaaagz** [styleguidist/react-styleguidist#1578]
Was reading the doc on getExampleFilename. Can it return an array instead of a string? 

I didn't see anything related. I have a few examples for some components that are really large. So instead of componentName.jsx --> componentName.example.md, I'd like to do componentName.jsx --> componentName.example1.md, componentName.example2.md , etc

Is possible or good suggestion?

**Comment by mitsuruog** [comment]
@yeeaaagz 

You can add just one more additional example file.

https://react-styleguidist.js.org/docs/documenting.html#external-examples-using-doclet-tags

Component file:

```jsx
/**
 * Component is described here.
 *
 * @example ./README.extra.md
 */
export default class Button extends React.Component {
  // ...
}
```

The folder would look something like this.

```
Button.jsx
README.md <--- Default
README.extra.md <--- Additional file
```
