### ISSUE TITLE
Using typescript in playground

### ISSUE THREAD

**Issue by gargroh** [styleguidist/react-styleguidist#1579]
Anyone having any idea how can i write TS code in playground(i am able to compile TS files and render them in example), but i want to compile/run TS in browser. 

Example, this piece of code should be able to render   - 

```tsx
const a: any = 100;
<button>{a}</button>;
```

Let me know if it is currently possible. Thanks

**Comment by gargroh** [comment]
Please bot dont close it 😄

**Comment by gargroh** [comment]
Please bot please don't close it 😄, this may turn into requirement.

**Comment by gargroh** [comment]
Still valid..

**Comment by gargroh** [comment]
Talking to myself, this https://github.com/styleguidist/react-styleguidist/pull/1700 will help us in achieving the same

**Comment by a-maggi** [comment]
Hey @gargroh, were you able to solve this problem in the end?
