### ISSUE TITLE
Prototype Pollution Vulnerability

### ISSUE THREAD

**Issue by PriyankaBhise** [styleguidist/react-styleguidist#1587]
Low             Prototype Pollution                                           
                                                                                
  Package         yargs-parser                                                  
                                                                                
  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2              
                                                                                
  Dependency of   react-styleguidist [dev]                                      
                                                                                
  Path            react-styleguidist > webpack-dev-server > yargs >             
                  yargs-parser                                                  
                                                                                
  More info       https://npmjs.com/advisories/1500                             
                                                                                
found 1 low severity vulnerability in 285538 scanned packages

**Comment by gbhasha** [comment]
Here is the snyk report : https://snyk.io/test/npm/react-styleguidist
