### ISSUE TITLE
Nested divs in markdown are rendered incorrectly

### ISSUE THREAD

**Issue by cincospenguinos** [styleguidist/react-styleguidist#1589]
**Current behavior**

**To reproduce**

1. Nest sets of divs three levels deep
2. Observe that the divs are incorrectly nested

[An example of this issue is found here](https://github.com/styleguidist/example/pull/7)

**Expected behavior**

The layout in the document is exactly to that represented in the file

**Comment by cincospenguinos** [comment]
I found a workaround by using a `span` instead of a `div`. This breaks the semantics of HTML, but it at least allows me to move forward.

**Comment by b2whats** [comment]
Make a minimal example
