### ISSUE TITLE
How to show the documentation of a complex prop-type object using React-styleguidist and JSDoc?

### ISSUE THREAD

**Issue by MohamedWagih96** [styleguidist/react-styleguidist#1590]
As the title says, How can I document a prop-type object like the following:

    chart: PropTypes.arrayOf(
        PropTypes.shape({
          /** Displayed title */
          title: PropTypes.string,
          /** Raw data */
          data: PropTypes.shape({
            /** how to document this? */
            labels: PropTypes.arrayOf(PropTypes.string),
            /** and this? */
            datasets: PropTypes.arrayOf(
              /** and this? */
              PropTypes.shape({
                /** and this? */
                data: PropTypes.arrayOf(PropTypes.number),
                /** and this? */
                backgroundColor: PropTypes.arrayOf(PropTypes.string),
              }),
            ),
          }),
        }),
      ).isRequired,

So far what is shown is only the `title` and the `labels` properties I can't go any deeper, Is there a way around this? I already tried the `@property` tag and it didn't work.

**Comment by mitsuruog** [comment]
**Result:**

![React_Styleguidist_Issue_Template_Style_Guide (2)](https://user-images.githubusercontent.com/1703219/81818997-b3de0c80-9569-11ea-8e23-ea5f704f7ad1.png)

react-docgen could parse the nested props property. but the UI part seems not to handle it recursively. 

```js
[
  {
    "description": "",
    "displayName": "Button",
    "methods": [],
    "props": {
      "chart": {
        "type": {
          "name": "arrayOf",
          "value": {
            "name": "shape",
            "value": {
              "title": {
                "name": "string",
                "description": "Displayed title",
                "required": false
              },
              "data": {
                "name": "shape",
                "value": {
                  "labels": {
                    "name": "arrayOf",
                    "value": {
                      "name": "string"
                    },
                    "description": "how to document this?",
                    "required": false
                  },
                  "datasets": {
                    "name": "arrayOf",
                    "description": "and this?",
                    "value": {
                      "name": "shape",
                      "value": {
                        "data": {
                          "name": "arrayOf",
                          "value": {
                            "name": "number"
                          },
                          "description": "and this?",
                          "required": false
                        },
                        "backgroundColor": {
                          "name": "arrayOf",
                          "value": {
                            "name": "string"
                          },
                          "description": "and this?",
                          "required": false
                        }
                      }
                    },
                    "required": false
                  }
                },
                "description": "Raw data",
                "required": false
              }
            }
          }
        },
        "required": true,
        "description": ""
      }
    }
  }
]
```

I am not sure it is intended behavior or bug. so I want to hear someone others' opinions.

**Comment by MohamedWagih96** [comment]
Ok thanks a lot I'll be waiting for any updates hopefully soon enough :D

**Comment by isaacbuckman** [comment]
This looks similar to #350.  I agree that this would be useful.

**Comment by syntacticsolutions** [comment]
Can we make it so that complex prop types show up as links and we show those props in separate pages?

**Comment by syntacticsolutions** [comment]
I'm happy to do a pull request for that functionality.
