### ISSUE TITLE
I'm getting a build error when running styleguidist build command.

### ISSUE THREAD

**Issue by asdeev** [styleguidist/react-styleguidist#1592]
When I do the `styleguidist server` command, it runs fine, but when I run the `styleguidist build` command, it is failing. I keep getting errors similar this:

`The comment file "build/vendors~main.898e6618.js.LICENSE.txt" conflicts with an existing asset, this may lead to code corruption, please use a different name`

Here's a link to my [Webpack Config](https://github.com/asdeev/new-project-template-rts/blob/dev/webpack.config.js
)

It seems like it is having some issues with the Terser plugin, but I can't seem to figure out what setting to use to stop the error. I would be extremely grateful if I can get some help to have this resolved!

**Comment by mac89** [comment]
Did you find a solution for this? Having the same issue.

**Comment by asdeev** [comment]
Hi @mac89 , it was an issue with my Webpack config file. It seemed there was some process in there which did not play nicely with Styleguidist. I just added a webpackConfig field to my styleguidist.config.js file instead with the following:

`  webpackConfig: {
    module: {
      rules: [
        // Babel loader will use your project’s babel.config.js
        {
          test: /\.(js|ts|jsx|tsx)$/,
          exclude: /node_modules/,
          use: 'babel-loader',
        },
        // Other loaders that are needed for your components
        {
          test: /\.(sa|sc|c)ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
      ],
    },
  },`
