### ISSUE TITLE
Sections with numbers in the name don't work

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1594]
**Current behavior**

The URL changes to `http://localhost:6061/#/4.%20Design%20Tokens` but no navigation happens. There's an error in the browser console:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at getRouteData (getRouteData.js:119)
    at renderStyleguide (renderStyleguide.js:46)
    at render (index.js:46)
    at eval (index.js:60)
    at Module../node_modules/react-styleguidist/lib/client/index.js (main.bundle.js:3855)
    at __webpack_require__ (main.bundle.js:726)
    at fn (main.bundle.js:101)
    at eval (client:4)
    at Object.0 (main.bundle.js:13010)
    at __webpack_require__ (main.bundle.js:726)
```

**To reproduce**

1. Create a section with a number in the name (for example, `4. Design Tokens`).
2. Run Styleguidist
3. Try to navigate to this section

**Expected behavior**

The section is open.

**Comment by mitsuruog** [comment]
@sapegin 
which version are you using?
I tried to reproduce it by the latest version `11.0.6`. but the URL format of the sections seems been changed, and I can not reproduce it. the navigation works for me.

**styleguide.config.js**

```
module.exports = {
  ...
  sections: [{
    name: '1.Documentation',
    content: 'src/docs/Document.md',
  }, {
    name: '2. Des ign',
    content: 'src/docs/Design.md',
  }, {
    name: "Components",
    components: "src/components/**/*.{js,jsx}",
  }]
};
```

**Result:**
<img width="890" alt="スクリーンショット 2020-05-17 11 02 17" src="https://user-images.githubusercontent.com/1703219/82134043-f3d51600-982d-11ea-80ba-72edc3164088.png">


**The URL for the section:**

`http://localhost:6060/#section-2-des-ign`

or am I missing something?

**Comment by sapegin** [comment]
Interesting: I had some 10.x version. Upgraded to 11.0.6. The error is gone but the navigation doesn't work: the URL changes but not the page contents ;-/ I also have `pagePerSection: true`. Looks like some regexp ignores numbers.
