### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by estevanmaito** [styleguidist/react-styleguidist#1597]
Sorry if this is the wrong place.

I can't support you with money, but I would like to thank everyone involved in this project.

Building big projects these days, with so many packages involved, usually is a matter of trying dozens of tutorials and different ways to get to the desired results, and you guys, made something so powerful, but yet so simple to configure.

I love what I do and live for the next _AHA!_ moment, and adding some lines of code (20 if you count every line break) and seeing so much done, made my day, and I'm certain that the results of this is happy users (other developers, as I'm also doing OSS) in the end.

You're part of something that make people's life easier, and subsequently better.

Thank you. ❤

**Comment by sapegin** [comment]
Hey Estevan! Thank you very much for your kind words! 🤗

**Comment by pke** [comment]
I am also still coming back to react-styleguidist and if I can get it to work with a react-native TypeScript app, I no longer have to write `stories` ;)
