### ISSUE TITLE
Adding underline to Link component via styles config?

### ISSUE THREAD

**Issue by rdhelms** [styleguidist/react-styleguidist#1600]
**Current behavior**

I wanted to add an underline to my styleguide's links by using the `styles` config option, but I can't seem to target the Link component.

**To reproduce**
```
    styles: {
        Link: {
            link: {
                textDecoration: 'underline',
            },
        },
    },
```

https://github.com/rdhelms/example

**Expected behavior**

I expected targeting the `Link` component via `styles` to allow me to style my styleguide's links, but I seem to be unable to do so.

**Comment by mitsuruog** [comment]
@rdhelms you can put the underline by doing something like this:

```js
styles: {
    Link: {
      link: {
        '&, &:link, &:visited': {
          textDecoration: 'underline',
        },
      },
    },
},
```

and you can see the details. Here is the original styling.

- https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/Link/LinkRenderer.tsx#L9-L13

**Comment by rdhelms** [comment]
Wow, interesting...when it didn't work I just assumed I was targeting the wrong thing, but I didn't think about the possibility that the theme styles were simply overriding the config styles. That makes me realize that this also would have worked:
```
    styles: {
        Link: {
            link: {
                textDecoration: 'underline !important',
            },
        },
    },
```

Is it expected that the theme styles would have a higher priority than the config styles? This is definitely enough for me, but I wonder if there's a way to save anyone else some future confusion. Maybe either a bit more guidance in the documentation (like a link to the `rsg-components` folder rather than just mentioning using the react dev tools to find component names?) or even making it so that config styles take a higher priority than theme styles seems more intuitive to me - but I understand that's a bit subjective.

**Comment by mitsuruog** [comment]
I have been answering a similar question recently.
but right now it's just an override to the existing style. 
However, it would better to be able to change the intended style with a straight way.

**Comment by mitsuruog** [comment]
and you can send a pull request whatever you want to change the document. 
I could understand your point and it may be the best thing we can do now to avoid some future confusion without major changes.
