### ISSUE TITLE
https://react-styleguidist.js.org/examples/basic/ is giving 404

### ISSUE THREAD

**Issue by halkeye** [styleguidist/react-styleguidist#1601]
**Current behavior**

https://react-styleguidist.js.org/examples/basic/

Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**To reproduce**

goto https://react-styleguidist.js.org/examples/basic/

**Expected behavior**

See the example repo

**Comment by sapegin** [comment]
Yeah, forgot to set it up with the new site ;-/
