### ISSUE TITLE
JSDoc @param not displaying arrays

### ISSUE THREAD

**Issue by isaacbuckman** [styleguidist/react-styleguidist#1611]
I am having some trouble setting the type of an `@param` to a `string[]`
```
/**
* @param{string[]} baz Argument of type string[]
* @param {string} bar Argument of type string
*/
```
![image](https://user-images.githubusercontent.com/34870239/84347166-d1f65700-ab7f-11ea-9e58-c0e3ae4541a3.png)
I expected it show that the type of `baz` is a `string[]`. Similar to #802, `string[]`, `String[]`, `Array.<string>`, etc. do not seem to be working either.

It looks like the type name is being rendered here:
https://github.com/styleguidist/react-styleguidist/blob/b409045d8f51363c7bf50d4e9b5ff9072b830d21/src/client/rsg-components/Argument/ArgumentRenderer.tsx#L52

When the type is a `string`, doctrine is giving us `{ type: 'NameExpression', name: 'string' }` so we can get `type.name`.

When the type is a `string[]`, doctrine is giving us:
```
{
  type: 'TypeApplication',
  expression: { type: 'NameExpression', name: 'Array' },
  applications: [ { type: 'NameExpression', name: 'string' } ]
}
```

As a side note, it might be nice to put each argument on a newline.

Would love to hear your thoughts and submit a pull request with some of these changes.

**Comment by sapegin** [comment]
Yeah, all good points! Feel free to send a pull request! 👾
