### ISSUE TITLE
'styleguidist@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by qalqi** [styleguidist/react-styleguidist#1612]
**Current behavior**
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/styleguidist - Not found
npm ERR! 404
npm ERR! 404  'styleguidist@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**To reproduce**

`npx styleguidist server`

when accessed 
https://registry.npmjs.org/styleguidist

```json
{"error":"Not found"}
```

Tested in windows and mac environments

**Comment by mitsuruog** [comment]
@qalqi 
This project name is `react-styleguidist` in npm not `styleguidist`.

**Comment by qalqi** [comment]
https://github.com/styleguidist/react-styleguidist/blob/master/docs/CLI.md#commands

**Comment by mitsuruog** [comment]
Are you sure `react-styleguidist` is installed? 

`npm install --save-dev react-styleguidist`

In my environment, I can start it successfully with the above `npx` command tho. 🤔

**Comment by qalqi** [comment]
```
  "scripts": {
    "start": "styleguidist server",
    "start:npx": "npx styleguidist server"
},
  "devDependencies": {
    "react-styleguidist": "^11.0.6"
  },
```

`npm run start` working
`npm run start:npx` not working

**Comment by sapegin** [comment]
This was never supported and never mentioned in the readme.

**Comment by qalqi** [comment]
the whole point of using npx is not to npm install. Either don't mention npx or support npx without local installation.

**Comment by qalqi** [comment]
it's not about being correct, rather being useful. npx in styleguidist library has no relevance or use. In fact having npx added unnecessary confusion and cli breaking up. 

great library nevertheless.

**Comment by cjones26** [comment]
Not to resurrect an old topic, but I agree with @qalqi -- referencing npx in the documentation really doesn't make sense.

**Comment by rahul3883** [comment]
In my case, without local installation, `npx styleguidist server` works for node v14.2 (npm v6.14.4) but not for node v15.14 (npm v7.7.6).
