### ISSUE TITLE
where can i see all the styleguide.config.js settings?

### ISSUE THREAD

**Issue by dianaaceves** [styleguidist/react-styleguidist#1617]
I want to change the whole look but I can't find anywhere to see what options are available.
I've only found a few things in individual examples, but nowhere to find them all.
Thanks!

**Comment by mitsuruog** [comment]
@dianaaceves 
Have you checked this document yet?
https://react-styleguidist.js.org/docs/configuration

**Comment by dianaaceves** [comment]
Yes, I have reviewed all the documentation, but (sorry 🙏 😔) I don't know how to access certain properties to change the styles.
For example, I tried to apply what you say in the image to change the style to h4 sections but it doesn't work.
<img width="296" alt="Screenshot 2020-06-25 at 09 05 40" src="https://user-images.githubusercontent.com/7044207/85672367-1aa32980-b6c3-11ea-9c2d-f6c454bacdb6.png">
<img width="604" alt="Screenshot 2020-06-25 at 08 55 20" src="https://user-images.githubusercontent.com/7044207/85672384-1ecf4700-b6c3-11ea-8e17-0262e54ed2cd.png">

**Comment by mitsuruog** [comment]
@dianaaceves Is the problem you want to solve here the same as the one you are asking here?

- Color of links in sidebar and main #1618

**Comment by dianaaceves** [comment]
Yes! sorry. :)

**Comment by mitsuruog** [comment]
If it's already resolved, would you close this issue?
