### ISSUE TITLE
Color of links in sidebar and main

### ISSUE THREAD

**Issue by dianaaceves** [styleguidist/react-styleguidist#1618]
Hi!
I need the color of the links in the sidebar to be different from the main content. How can I set different colors to the sidebar links?
Thanks!

**Comment by mitsuruog** [comment]
@dianaaceves 
Could you show me an image that what you want to do?

**Comment by dianaaceves** [comment]
Sure! I'll tell you what I need:
- Different color for sidebar links: In the configuration I only find how to set the color for all the links.
- Different colors to the different headings: a color for the h2, another color for the h3, and another color for the h4. I've tried to put it inside those variables but it doesn't do anything.
I'd tried several things, but I don't find the [solution.]
Thank you very much for your quick response. 🙏
<img width="1265" alt="Screenshot 2020-06-25 at 08 33 38" src="https://user-images.githubusercontent.com/7044207/85670201-f2b2c680-b6c0-11ea-87aa-ff91027ea947.png">

**Comment by mitsuruog** [comment]
About customizing sidebar links, take a look at my previous answer.

- Adding underline to Link component via styles config? #1600

About customizing heading colors, add the next property on your `styleguide.config.js`.

```js
  styles: {
    Heading: {
      heading2: {
        color: "red"
      }
    }
  },
```

You can see the details style of the Header component here.

- https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/Heading/HeadingRenderer.tsx#L8-L33

**Comment by dianaaceves** [comment]
Thanks for your quick response. :-)
I'm sorry, but I don't understand what you mean by "take a look at my previous answer". I can't find any answer that explains how to modify only the styles of the links in the sidebar. If I do what you say in issue #1600 00, all the links are changed, not just the ones in the sidebar.
Thank you!

**Comment by mitsuruog** [comment]
@dianaaceves you are right.
I can not find a smart good way to do this tho, but you can change the sidebar style by doing something like this.

```js
  styles: {
    ComponentsList: {
      item: {
        "& a": {
          color: [["red"], "!important"],
        },
      },
    },
```

**Comment by dianaaceves** [comment]
Great! Thanks for your help. :-)
