### ISSUE TITLE
Problems with jss @global styles

### ISSUE THREAD

**Issue by dianaaceves** [styleguidist/react-styleguidist#1619]
I added some styles for my components using jss @global, as indicated in the documentation, but when I do, the selectors are included in a general rule where a lot of unwanted styles are applied to them. In my case, the h4 doesn't inherit the text-align center from the parent because that css rule is overwriting it.
How can I add some global styles without them being added in that strange rule?
Thank you sooo much!

![Screenshot 2020-06-25 at 16 36 34](https://user-images.githubusercontent.com/7044207/85742413-8311fb00-b703-11ea-877d-02988322c4ec.png)
![Screenshot 2020-06-25 at 16 36 48](https://user-images.githubusercontent.com/7044207/85742418-83aa9180-b703-11ea-9882-9bce2550f4fd.png)
![Screenshot 2020-06-25 at 16 45 49](https://user-images.githubusercontent.com/7044207/85742426-860ceb80-b703-11ea-8ea1-c08c83ece9fb.png)

**Comment by dianaaceves** [comment]
Hi again, nothing about this? If we can't change this behavior, we'll probably have to leave Styleguidist and use another Styleguide for our library, because I'm having to force strange styles to prevent these styles from being applied.
Thanks!

**Comment by apennell** [comment]
If I understand correctly, your code is something like:
```html
<section class="center">
  <h4>Text</h4>
</section>
```
```css
.center {
  text-align: center;
}
h4 {
  text-align: initial;
}
```
Is that right? If that's the case, it's not an issue with styleguidist, that's how CSS works. An element isn't going to look at its parent's CSS settings if the property is explicitly set on that element. According to the dev tools screenshot you included, you've set `text-align: initial` on `h4`.

If that's not true, can you include the exact code you have when you say "I added some styles for my components using jss @global"?

**Comment by dianaaceves** [comment]
Hi, thanks for your response. My problem is not with CSS, I'm a CSS expert 😅.
The problem is when we use the @global to style components as you say in the docs (picture 0). When a tag is included in global styles (picture 1), this tag is included in a large CSS rule with lots of properties (picture 2) that are applied to this element, and the original styles are broken.
Text-align: initial is inside that CSS rule I say. That styles are not from our code.

<img width="627" alt="0" src="https://user-images.githubusercontent.com/7044207/88453618-ec9f3980-ce68-11ea-9f8f-51982a8c43e0.png">
![2](https://user-images.githubusercontent.com/7044207/88453620-ee68fd00-ce68-11ea-9911-faea776e0ab8.png)
<img width="598" alt="1" src="https://user-images.githubusercontent.com/7044207/88453621-ef9a2a00-ce68-11ea-9851-972488680dc8.png">

**Comment by dianaaceves** [comment]
Hi! Can you tell me something about this? Thank you very much.
