### ISSUE TITLE
Embed styleguide into another docs site?

### ISSUE THREAD

**Issue by borekb** [styleguidist/react-styleguidist#1620]
I love Styleguidist for its Markdown-based approach, the result docs are nice and useful. But we also have other parts of the documentation, e.g., long-form content, a REST API docs etc., and I'm wondering whether someone has experience stitching it together inside a single output. For example, could we use Docusaurus for long-form content and Styleguidist to build the API Reference section?

<img width="1180" alt="Screenshot 2020-06-26 at 15 38 47" src="https://user-images.githubusercontent.com/101152/85863834-ff6c1300-b7c3-11ea-832a-f692ff85c835.png">

A few questions I have around this:

1. Is this even technically possible? I didn't take a look too much into the generated HTML output, maybe it has some routing rules hardcoded in it that would make this difficult?
2. Does any official integration like this exist? Are there even examples of sites that would be doing this?
3. If the two points above discourage or even make impossible to integrate the generated styleguide with a larger docs site, how is Styleguidist itself for writing long-form documentation, or generally maintaining the whole docs site? Good idea or not? (I still don't know what we'd do with the REST API documentation if we wanted to integrate it into a single site.)

Thanks for a great docs system by the way!

**Comment by mitsuruog** [comment]
I haven't tried it, but here's what I would think if I tried to do the same thing.

Styleguidist has a feature called `section`. Using this, I can include any markdown file in Styleguidist.

- https://react-styleguidist.js.org/docs/components#sections

so if the Docusaurus document can be output in markdown format, I would save the file in a folder somewhere in the Styleguidist project and integrate this into the Styleguidist via `section`.

I make the design system documentation in a markdown and integrate it into Styleguidist.
In my opinion, it's handy to have all the necessary documentation in one place.

**Comment by borekb** [comment]
In my case, Docusaurus would be the main site, Styleguidist just the embedded API reference.

**Comment by mitsuruog** [comment]
As far as I know, Styleguidist is a react web application in its entirety, so it would be difficult to use Docusaurus as the main site.
