### ISSUE TITLE
Wrong union description with TypeScript

### ISSUE THREAD

**Issue by alextewpin** [styleguidist/react-styleguidist#1621]
**Current behavior**
When using TypeScript unions, react-styleguidist isn't providing any description. Moreover, is shows annoying empty div.

<img width="580" alt="Screenshot 2020-06-26 at 17 31 05" src="https://user-images.githubusercontent.com/1542068/85868602-2d0c8880-b7d3-11ea-9781-f32bc5cf3130.png">

**To reproduce**
Use TypeScript and add description to any union field. Demo: https://codesandbox.io/s/goofy-forest-zmeiy

**Expected behavior**
Unwrapped union description or at least no empty div.

**Version**
11.0.8

**Comment by mitsuruog** [comment]
You can hover your mouse over the field for a few seconds to see the actual value, but I can understand the fact that more people don't realize it.

<img width="553" alt="スクリーンショット 2020-07-03 22 43 39" src="https://user-images.githubusercontent.com/1703219/86475298-5d2dcb80-bd7f-11ea-9043-67f48af491ea.png">

So... we can change this, but first, we need to decide what kind of UI we want. 
Here's my idea. Does anyone have any other good ideas?

1. Show the actual value instead
<img width="621" alt="スクリーンショット 2020-07-03 22 45 46" src="https://user-images.githubusercontent.com/1703219/86475721-2906da80-bd80-11ea-836b-2902688eda52.png">

2. Show the actual value below the description
<img width="554" alt="スクリーンショット 2020-07-03 22 47 45" src="https://user-images.githubusercontent.com/1703219/86475730-2e642500-bd80-11ea-9686-5411ff1ed172.png">

FYI @sapegin what do you think?

**Comment by alextewpin** [comment]
Yeah, I know that I can hover on `union`, that's a cool feature. I'm actually bothered with ugly empty space between table rows. As far as I know, when parsing prop-types union there is actual description, like `One of: red, blue`. But not in this case.

Pic. 2 is fine I guess. Union description could be quite long, so putting it in type column may look sloppy.

**Comment by sapegin** [comment]
I think unions can be very very long, and improving tooltips could be a better solution in general — showing a nice HTML tooltip where we can format code on multiple lines, instead of a `title`, which, I agree, isn't the best and easily discoverable UI pattern.

**Comment by sapegin** [comment]
There are many places that could be improved with tooltips:

![image](https://user-images.githubusercontent.com/70067/86486450-994f3500-bd5b-11ea-9eb1-0190e57117d1.png)

![image](https://user-images.githubusercontent.com/70067/86486505-b97ef400-bd5b-11ea-99dd-7f0a8f208cd0.png)

**Comment by mitsuruog** [comment]
here is my design idea. 
to solve the un-discoverable UI, I would like to put an icon next to the property. 
what do you think?

<img width="656" alt="スクリーンショット 2020-07-08 23 15 09" src="https://user-images.githubusercontent.com/1703219/86929616-ffc7bf00-c170-11ea-8d67-96090730ca90.png">

**Comment by sapegin** [comment]
This looks good!

A couple of comments:

1. I think we don't need an underline anymore, an icon is enough to show that this thing is interactive.
2. The whole thing (text + icon) should be hoverable, otherwise, the hoverable area would be too small and too difficult to use for some folks.

**Comment by mitsuruog** [comment]
sounds good! 
if we were to implement this tooltip, do you have any preferred libraries? or would you prefer to implement it from scratch?

**Comment by sapegin** [comment]
Nope, but I'd prefer a library if it won't bring too many dependencies (like another CSS in JS library ;-) and it must be accessible with a keyboard and a screen reader.
