### ISSUE TITLE
Avoid Nesting of tabs when only one component is available in sections

### ISSUE THREAD

**Issue by DhruvMehndhiratta** [styleguidist/react-styleguidist#1622]
Current behavior
When I am passing only one component in sections array then also it's creating a nested tab for that, that is not desirable Can anyone let me know if there is any workaround for the same so that I can avoid that.
<img width="268" alt="bug" src="https://user-images.githubusercontent.com/36534155/86040940-80e0d100-ba62-11ea-9185-4e75bb9b1923.png">

To reproduce
Pass only one component in sections array.
```
 sections: [
        {
          name: 'Alert',
          components: './src/components/Alert/index.js',
        }
]
```
Expected behavior
It should not create a separate nesting of the tab if there is more than one component then, in that case, its good to have nesting of the tab but when we have only one component child then that's looking kind of weird

Version
11

**Comment by apennell** [comment]
With the above code, you're explicitly defining a section called "Alert" and creating the nesting. If you don't want separate sections defined (ie, the nesting), then you can remove the `sections: []` part from the config and instead just have `components: './src/components/**/[A-Z]*.js',` to automatically generate a list of all components matching that file structure. This will render a list of all components with no nesting. If you want it nested under the label "Components,":
```
sections: [
  {
    name: 'Components',
    components: './src/components/**/[A-Z]*.jsx'
  }
],
```

**Comment by DhruvMehndhiratta** [comment]
> With the above code, you're explicitly defining a section called "Alert" and creating the nesting. If you don't want separate sections defined (ie, the nesting), then you can remove the `sections: []` part from the config and instead just have `components: './src/components/**/[A-Z]*.js',` to automatically generate a list of all components matching that file structure. This will render a list of all components with no nesting. If you want it nested under the label "Components,":
> 
> ```
> sections: [
>   {
>     name: 'Components',
>     components: './src/components/**/[A-Z]*.jsx'
>   }
> ],
> ```

Hey Annie is there any way we can only use sections but don't have nesting where its not required because in some cases I want nesting and in some cases it doesn't required nesting on the same sidebar let me give you an example let say under Form we can have multiple items in nesting like checkbox, radio, textarea but in case of Alert component we don't want any nesting because its single component and doesn't depend on any other component. Is there a way to achieve that with Alphabetical order maintenance. Currently what is happening Alert is also taking one extra nesting even its not desirable.

**Comment by apennell** [comment]
I think you could do something like:
```js
sections: [
  {
    name: 'Components',
    components: './src/components/**/[A-Z]*.jsx',
    sections: [
      {
        name: 'Form',
        components: './src/components/Form/**/[A-Z]*.jsx'
      }
    ]
  }
],
```
That assumes a directory structure like this:
```
--/components
  --/Alert
    --Index.js
  --/Form
    --/Input
      --Input.js
```

**Comment by leizhao-coupa** [comment]
I have the same question. @apennell I tried your suggestion, but it doesn't work. With your code above, it will only show `Form` in ui, it won't show `Alert`.

**Comment by apennell** [comment]
@leizhao-coupa Can you please share your directory structure and your config? If the locations of `Alert` matches `'./src/components/**/[A-Z]*.jsx', then it should show at the top level of `Components`. Ah although I did just notice that in the code I pasted, I was only using `.jsx` but I used `.js` in the directory structure examples. If you copied me exactly, you'll need to make sure the file types match!

**Comment by leizhao-coupa** [comment]
@apennell sure. Thanks for your reply. I've already change the file match to my local, but it's still not working. I am using `tsx`, here's my file structure:

I export the section in another file and use this in `styleguide.config.js`:

Sections:

![sections](https://user-images.githubusercontent.com/55112170/89814528-207c8f00-daf8-11ea-82ec-4e7d85593222.png)

Here's my file structure:

![src](https://user-images.githubusercontent.com/55112170/89814772-8832da00-daf8-11ea-81fa-2859714f40de.png)


And this is what rendered in styleguide:

![styleguide](https://user-images.githubusercontent.com/55112170/89814804-9254d880-daf8-11ea-855f-b962b4380d8d.png)

**Comment by leizhao-coupa** [comment]
Do we have any updates here?

**Comment by leizhao-coupa** [comment]
Do we fix this?
