### ISSUE TITLE
Failed to compile... From basic installation !

### ISSUE THREAD

**Issue by Mariodandre** [styleguidist/react-styleguidist#1625]
**Current behavior**

Hello

I just followed the basic installation in my preact project :
[](https://react-styleguidist.js.org/docs/getting-started)

My project is a very basic preact project;
I edited the config as mentionned here [](https://react-styleguidist.js.org/docs/cookbook/)
"How to use react styleguidist with preact ?"

But... It does not work. I have dozens of lines like "module not found : can't resolve react"

**To reproduce**

Here is what happens with **npx styleguidist build** :
I'm sorry I'm not going to post my entire project here.
It is just a very basic preact project.

```
./node_modules/markdown-to-jsx/dist/esm.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/markdown-to-jsx/dist'
./node_modules/react-group/index.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-group'
./node_modules/react-icons/lib/esm/iconBase.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-icons/lib/esm'
./node_modules/react-icons/lib/esm/iconContext.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-icons/lib/esm'
./node_modules/react-simple-code-editor/lib/index.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-simple-code-editor/lib'
./node_modules/react-styleguidist/lib/client/rsg-components/Argument/ArgumentRenderer.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-styleguidist/lib/client/rsg-components/Argument'
./node_modules/react-styleguidist/lib/client/rsg-components/Arguments/ArgumentsRenderer.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-styleguidist/lib/client/rsg-components/Arguments'
./node_modules/react-styleguidist/lib/client/rsg-components/Code/CodeRenderer.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-styleguidist/lib/client/rsg-components/Code'
./node_modules/react-styleguidist/lib/client/rsg-components/Components/Components.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-styleguidist/lib/client/rsg-components/Components'
./node_modules/react-styleguidist/lib/client/rsg-components/Components/ComponentsRenderer.js
Module not found: Can't resolve 'react' in '/home/user/test/node_modules/react-styleguidist/lib/client/rsg-components/Components'
```

**Expected behavior**

Your project to work....

**Comment by apennell** [comment]
Have you tried googling this issue? There are lots of results for different packages that are likely applicable here. It's most likely an issue with your react version/installation/configuration. I recommend removing package-lock.json and re-running `npm install` then try building again. If that doesn't work, you'll need to post your package.json at a bare minimum, as the error output alone isn't enough to debug your project config for you.
