### ISSUE TITLE
Error when configuration of template attribute is function

### ISSUE THREAD

**Issue by huyinglin** [styleguidist/react-styleguidist#1638]
When I write the template attribute as function, it will not work. I looked at the relevant source code and found that although he judged whether it was a function, he did not execute the function.

Code is here:
https://github.com/styleguidist/react-styleguidist/blob/967ba9e5bbb0e81092f15fa8bc4dd809e1e367fe/src/scripts/make-webpack-config.ts#L33

**Comment by mitsuruog** [comment]
@huyinglin 
What code did you actually give them? 
Could you create a reproducible sample or share a configuration file?

I'm not too familiar with this part of the code tho, but it doesn't seem to be necessary to execute it here, as this `config.template` will be functionally executed later in the plugin.

- https://github.com/styleguidist/mini-html-webpack-plugin#html-minification
