### ISSUE TITLE
Title Color is Black instead of White after Styleguidist build

### ISSUE THREAD

**Issue by allindeveloper** [styleguidist/react-styleguidist#1640]
**Current behavior**
Title Color shows White on my local before building

**To reproduce**

After updating the style like so
```js
module.exports = {
  serverPort: 6070,
  title: 'VGG UI-UX TOOLKIT DOCUMENTATION',
  theme: {
    color: {
      base: '#013444',
      link: '#51B64B',
      linkHover: '#2992D0',
      sidebarBackground: '#013444',
    },
    fontFamily: {
      base: '"Open Sans", sans-serif',
    },
  },
  styles: {
    Logo: {
      logo: {
        color: 'white',
        animation: 'blink ease-in-out 300ms infinite',
      },
      '@keyframes blink': {
        to: { opacity: 0 },
      },
    },
  },

```
and after running `npm run styleguide:build`
The title color was now `black` instead of `white`

**Expected behavior**

The title color supposed to the white after running `npm run styleguide:build`

**Comment by mitsuruog** [comment]
hmm... works fine for me.

![VGG-UI-UX-TOOLKIT-DOCUMENTATION](https://user-images.githubusercontent.com/1703219/91561962-5d110d00-e977-11ea-9c2d-860378772af4.png)

Version: 11.0.8
