### ISSUE TITLE
Optional Chaining and null coalescing not working

### ISSUE THREAD

**Issue by rlesniak** [styleguidist/react-styleguidist#1660]
**Current behavior**
Latest version of Styleguide uses Babel v.7.9.0. Since of v7.8.0 babel supports optional chaining (https://babeljs.io/blog/2020/01/11/7.8.0) but when I use it `obj?.prop` in styleguide environment app doesnt start and throws error

```js
Module parse failed: Unexpected token (20:36)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   id: getConversationId({
|     appId: conversation.app.id,
>     contactId: conversation.contact?.id
|   }),
|   contactId: conversation.contact?.id,
```

**To reproduce**

https://github.com/rlesniak/example/commit/8fdeeac2b22bda85cdd28fffb8c745c07aeda766

**Expected behavior**

Should work with that features

**Comment by MoltenCoffee** [comment]
I believe this is an issue with React-docgen, [as seen here](https://github.com/reactjs/react-docgen/issues/463).
The[ workaround suggested there](https://github.com/reactjs/react-docgen/issues/463#issuecomment-668150783) (by @mjhenkes ) is to use specific versions of @babel/core and @babel/parser, but that hardly seems like a proper resolution, especially when using styleguidist..

**Comment by mjhenkes** [comment]
+1 My work around is not great.

**Comment by sapegin** [comment]
We only use Babel to compile Styleguidist code, if you see any warning like this, they are coming from your project.

**Comment by MoltenCoffee** [comment]
I believe this is not completely true, as it's Babel/ast-types as used by React-docgen. Which still perhaps does not make it an issue with styleguidist necessarily, as it has been present [in issues with storybook](https://github.com/storybookjs/storybook/issues/11883) as well.

However, I do think this is still an issue and shouldn't be closed, but the only fix is [for this issue in ast-types](https://github.com/benjamn/ast-types/issues/383) to be fixed, react-docgen updating its dependencies and then styleguidist as well.
