### ISSUE TITLE
security vulnerability in serialise-javascript in < v3.1.0 used by copy-webpack-plugin v5.1.0

### ISSUE THREAD

**Issue by Aaditya-Sahay** [styleguidist/react-styleguidist#1663]
The package serialise-javascript has seen a new security advisory, which requires libraries using it to update to a version beyond v3.1.0.
You can find the advisory here: https://github.com/advisories/GHSA-hxcc-f52p-wc94

react-styleguidist depends upon copy-webpack-plugin versions ^5.1.0, which in turn depends upon an older version of serialise-javascript, namely v2.12.0.
This can be fixed by changing the version of copy-webpack-plugin from ^5.1.0 to any of the latest versions, ideally ^6.0.3

It would be great to get this updated as its throwing off some warnings in a few places.

Happy to file a PR if needed.

**Comment by Aaditya-Sahay** [comment]
Nevermind, just noticed that this PR fixes it: https://github.com/styleguidist/react-styleguidist/pull/1658

**Comment by sapegin** [comment]
The pull request is merged.
