### ISSUE TITLE
[Bug] "Right Click + Translate to français" => break the documentation and crash 

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#1668]
**Current behavior**

In Google Chrome, I am translating the page with `Right + Click` + `Translate to français`, navigating with the left menu will cause fatal error and break the UI.

![image](https://user-images.githubusercontent.com/1866564/90844818-13b43280-e365-11ea-8dcd-ddda9f36ab07.png)

```bash
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Mi (http://mp.yth.rocks/backoffice/build/bundle.efd3dd9c.js:33:87477)
```

**To reproduce**

Translate any styleguide to a different language and click on multiple link until one break

**Expected behavior**

I expect the site to work

**Comment by sapegin** [comment]
Works fine for me ;-/ One thing that might be related and worth fixing anyway is missing `lang` on `<html>`.
