### ISSUE TITLE
defining custom component names with @visibleName broken?

### ISSUE THREAD

**Issue by ThomasRoest** [styleguidist/react-styleguidist#1669]
**Current behavior**

Adding a custom name does not seem to work anymore

**To reproduce**

```
/**
 * @visibleName Input:Text
 */
```

https://react-styleguidist.js.org/docs/documenting#defining-custom-component-names

**Comment by sapegin** [comment]
Seems to work: https://react-styleguidist.js.org/examples/basic/#pushbutton

**Comment by ThomasRoest** [comment]
was an issue in react-docgen-typescript https://github.com/styleguidist/react-docgen-typescript/issues/287
