### ISSUE TITLE
Is there ability to change side panel navigation color ?

### ISSUE THREAD

**Issue by Mioleris** [styleguidist/react-styleguidist#1672]
Hi, is there ability to change background color of navigation side panel ?
Tried this but with no luck. Only code tag changes color.
```
  styles: {
    Code: {
      code: {
        color: '#c0341d',
        backgroundColor: '#fbe5e1',
        borderRadius: '3px',
        padding: '0 5px',

      },
    Sidebar: {
      sidebar: {
        backgroundColor: '#ffffff',
        width: '300px',
      },
    },
  },
```

**Comment by mitsuruog** [comment]
![React-Styleguidist-Style-Guide](https://user-images.githubusercontent.com/1703219/91710535-6096d500-ebbf-11ea-8a56-ecaaad3834fe.png)

@Mioleris Close! the Sidebar is not an isolated component. please try this.

```js
	styles: {
		StyleGuide: {
			sidebar: {
				backgroundColor: '#ffffff',
				width: '300px',
			},
		},
	},
```

**Comment by Mioleris** [comment]
@mitsuruog thank you!
It worked 👍
