### ISSUE TITLE
Add support for JSDoc @default

### ISSUE THREAD

**Issue by stonebk** [styleguidist/react-styleguidist#1693]
It would be nice to be able to define the props table default value using the JSDoc `@default` or `@defaultvalue` tag:
https://jsdoc.app/tags-default.html

**Comment by sapegin** [comment]
What's the use case in comparison to showing the actual default value?

**Comment by stonebk** [comment]
A couple use cases:

1. If you are using functional components with ES6 [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) instead of React's defaultProps (defaultProps will [eventually by deprecated](https://twitter.com/dan_abramov/status/1133878326358171650)).
2. We sometimes leave the defaultProp as undefined and instead set the default within the component -- this allows us to know if the prop was explicitly set on the component or if it the component should use the default value. When using defaultProps, there is no way to know if the prop is a default or if it was explicitly set.

**Comment by sapegin** [comment]
1. Long term this should be handled by react-docgen, otherwise, you're duplication the values.

2. This again results in the duplication, but I don't know your reasons for doing this.

Anyway, feel free to send a pull request.
