### ISSUE TITLE
using @visibleName with spaces does not work

### ISSUE THREAD

**Issue by ThomasRoest** [styleguidist/react-styleguidist#1694]
**Current behavior**

using @visibleName with spaces results in the following error `SyntaxError: Missing initializer in const declaration`

**To reproduce**

```
/**
 * @visibleName Input:  Password
 */
```

related #1675

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by mitsuruog** [comment]
![React-Styleguidist-Example-Basic-Style-Guide](https://user-images.githubusercontent.com/1703219/94939089-9b689180-050c-11eb-81c1-b9901e91252c.png)

I can't reproduce it. 

@ThomasRoest 
could you make a minimum reproducible sample? I need more info.

- https://codesandbox.io/s/github/mitsuruog/react-styleguidist-issue-template

**Comment by ThomasRoest** [comment]
seems to happen in `evalInContext` in https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/client/evalInContext.ts

the extra spaces cause syntax errors? In the body arg.

example `body` with visibleName with spaces

```
/**
 * @visibleName Input:  Text
 */

const React$0 = require('react');
const React = React$0.default || (React$0['React'] || React$0);
const Input  Text$0 = require('./InputText.tsx');
const Input  Text = Input  Text$0.default || (Input  Text$0['Input  Text'] || Input  Text$0);
{
			const react$0 = require('react');
const React = react$0.default || react$0;
const __InputText$0 = require('./InputText');
const InputText = __InputText$0.InputText;

var Example = function () {
	var ref = React.useState("example");
	var value = ref[0];
	var setValue = ref[1];
	return React.createElement( InputText, { value: value, setValue: setValue });
};
return (React.createElement( Example, null ));
		}
```
