### ISSUE TITLE
Unability to document methods of functional component

### ISSUE THREAD

**Issue by tomas-hartman** [styleguidist/react-styleguidist#1699]
**Current behavior**

With functional component, I am unable to generate documentation for inner methods. There is, on the other hand, the possibility to do so with class components.

**To reproduce**

1. class component example & [result](https://user-images.githubusercontent.com/44980733/95348586-7aae8c00-08be-11eb-9648-5c86c7627d32.png):

```js
import React, { Component } from 'react';

export default class ComponentClass extends Component {
  /**
   * Method - it does this and that and it is very important for 
   * the overall functionality and understanding of the component
   *
   * @public
   * @param {Array} params some array
   * @returns {String}
   */
  method(params) {
    return 'some output';
  }

  render() {
    return <div>{this.method()}</div>;
  }
}
```

2. functional component example & [result](https://user-images.githubusercontent.com/44980733/95348685-8e59f280-08be-11eb-855e-2e0a199861f7.png):

```js
import React from 'react';

export default function ComponentFunction() {
  /**
   * Method one with an arrow function
   * @param {string} param Some param
   * @public
   */
  const method = (param) => {
    return 'Jean Valjean was innocent all the time and you knew!';
  };

  /**
   * Method two with a function keyword
   * @param {string} param Some param of other method
   * @public
   */
  function method2(param) {
    return 'Hello how are you today?';
  }

  return (
    <div>
      {method2()} {method()}
    </div>
  );
}
```

**Expected behavior**

I should be able to use either `@public` or other notation for both kinds of components, with the same results.

**Comment by sapegin** [comment]
These methods aren't accessible outside of the component (when the class public methods are), so they aren't the component's public API. It doesn't make sense to generate documentation for methods component consumers can't access.
