### ISSUE TITLE
"Show source code" button

### ISSUE THREAD

**Issue by tomas-hartman** [styleguidist/react-styleguidist#1701]
**The problem**

There is no easy way to quickly display components' source code out of the box and when the styleguidist is set up to do so, it's impossible to collapse the code. Therefore, trying to link the source code to a component is a very frustrating job. (If there is any easy solution - especially to collapse the code, let me know, I haven't found any.)

**Proposed solution**

Parser that parses examples should accept `collapse` flag, that would tell parser, that the block should be collapsible the same way as "Show Code". It could look like:

```
*  ```jsx { "file": "./Pagination.jsx" } collapse
*  ```
```

or something like:

```
*  ```jsx { "file": "./Pagination.jsx", "mode": "collapse" }
*  ```
```

And the result would work just like:

![obrazek](https://user-images.githubusercontent.com/44980733/95761710-00f71380-0cad-11eb-9b1e-ebe70e5b5740.png)

or 

![obrazek](https://user-images.githubusercontent.com/44980733/95763401-43215480-0caf-11eb-9624-fe78615bbea9.png)

**Alternative solutions**

There could also be optional config setting such as `sourceCodeMode` (similar to `exampleMode` etc.) and `sourceCode` that would look like:

```
sections: [
    {
      name: 'Page',
      content: 'docs/readme/styleguide/pages.md',
      components: 'assets/Pages/Page.jsx',
      sourceCode: 'assets/Pages/Page.jsx',
      sourceCodeMode: 'collapse | hide | expand'
    }
]
```

The difference from content would be that source code should be displayed under separate subheading "Source Code" and should display highlighted source code in some serif font.

**Additional context**

The possibility to display source code out of the box would enable to use styleguidist as a better tool for code documentation and would overcome difficulties with documenting (and learning) components' inner logic.

**Comment by tomas-hartman** [comment]
Also this post https://stackoverflow.com/questions/59264060/how-can-i-show-external-file-in-a-view-code-block addresses the same problem. When `settings.static` is ommited from the [Styleguidist's example code](https://react-styleguidist.js.org/docs/cookbook/#how-to-display-the-source-code-of-any-file), it shows "View Code" button correctly, but results in incorrectly evaluated code like in this screenshot: 

![obrazek](https://user-images.githubusercontent.com/44980733/95764478-d018dd80-0cb0-11eb-8bde-599d4403bbef.png)

This makes me think, that allowing new flag "collapse" in ComponentName.md that would not evaluate the code, but only collapse it, might be an easy and efficient solution.

**Comment by sapegin** [comment]
I guess you could use `<details>` for that.

https://raw.githubusercontent.com/component-driven/component-driven-development/master/src/exercises/1-Introduction/Readme.md

**Comment by tomas-hartman** [comment]
I've finally tried it and it is actually a very interesting solution. I'd still like to have something more "built in", but this is definitely useful. I'd suggest adding this tip to `Cookbook`.
