### ISSUE TITLE
Dev Server crash when upgrade to 11.1.2

### ISSUE THREAD

**Issue by lyz810** [styleguidist/react-styleguidist#1714]
**Current behavior**

run script `styleguidist server`, after reload page, the dev server is crash

**To reproduce**
1.upgrade to 11.1.2 or 11.1.1, run styleguidist server and open styleguidist in chrome
2.Open chrome console panel
3. type `new WebSocket('ws://localhost:6060/sockjs-node')` and press enter
4. repeat step3 twice 
5. server crash

I found the reason: 
https://github.com/styleguidist/react-styleguidist/issues/1705#issuecomment-726536041

I think this should be config in https://github.com/styleguidist/react-styleguidist/blob/master/src/scripts/create-server.ts#L12, no in user webpack.config.js

**Expected behavior**
server don't crash

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by henit** [comment]
Seems like same issue here: ECONNRESET right after styleguidist builds (Compiled successfully.) and is opened in the browser, leading to socket communication.

Running on node 14.14.0, npm 6.14.8

If I downgrade to react-styleguidist 11.1.1, no errors.
