### ISSUE TITLE
Cannot wrap a styleguidist component using `styleguideComponents`

### ISSUE THREAD

**Issue by stonebk** [styleguidist/react-styleguidist#1716]
**Current behavior**

(using `react-styleguidist@11.1.0`)

I was trying to use [`styleguideComponents`](https://react-styleguidist.js.org/docs/configuration#styleguidecomponents) to customize the Playground component, however I run into the following error:

```
 FAIL  Failed to compile

./node_modules/react-styleguidist/lib/client/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'rsg-components/Playground/PlaygroundRenderer' in '/Users/brians/zgit/constellation/node_modules/react-styleguidist/lib/client/rsg-components/Playground'
```

I followed the example of [wrapping a Styleguidist component](https://github.com/styleguidist/react-styleguidist/blob/master/examples/customised/styleguide/components/SectionsRenderer.js).

My styleguide.config.js (note: Wrapper works but Playground does not):

```js
    styleguideComponents: {
        Playground: path.join(__dirname, 'src/styleguidist/CustomPlayground'),
        Wrapper: path.join(__dirname, 'src/styleguidist/ThemeWrapper'),
    },
```

My CustomPlayground.js

```js
import React from 'react';
import Playground from 'react-styleguidist/lib/client/rsg-components/Playground/Playground';

const CustomPlayground = React.forwardRef((props, ref) => {
    console.log(props);
    return (
        <div className="foo">
            <Playground ref={ref} {...props} />
        </div>
    );
});

export default CustomPlayground;
```

I should also note that it worked when I wrapped `PlaygroundRenderer`, but not `Playground`.

**To reproduce**

I tried to reproduce with the [customized style guide example](https://github.com/styleguidist/react-styleguidist/tree/master/examples/customised), but that is broken as well. First because it doesn't like the `styles` config:

```
Something is wrong with your style guide config

styles config option should be object, received function.

Example:

{
  styles: {
    Logo: {
      logo: {
        fontStyle: 'italic'
      }
    }
  }
}

Learn how to configure your style guide:
https://react-styleguidist.js.org/docs/configuration.html#styles
```

After removing that from the example, I get a similar "Module not found" error:

```
 FAIL  Failed to compile

./styleguide/components/SectionsRenderer.js
Module not found: Can't resolve 'react-styleguidist/lib/client/rsg-components/Sections/SectionsRenderer' in '/Users/brians/git/react-styleguidist/examples/customised/styleguide/components'
```

**Expected behavior**

I expect that the [customized style guide example](https://github.com/styleguidist/react-styleguidist/tree/master/examples/customised) works and that I can wrap the Playground component with my own code.

**Comment by pkmnct** [comment]
I am running into this same issue attempting to override the Playground:

Module not found: Error: Can't resolve 'rsg-components/Playground/Playground' in '../node_modules/react-styleguidist/lib/client/rsg-components/Playground'
