### ISSUE TITLE
Type description tooltip isn't spaced properly in Firefox

### ISSUE THREAD

**Issue by alextewpin** [styleguidist/react-styleguidist#1723]
**Current behavior**

Type description tooltip isn't spaced properly in Firefox.
<img width="978" alt="Screenshot 2020-12-02 at 17 03 22" src="https://user-images.githubusercontent.com/1542068/100883093-fb55c700-34c0-11eb-9a12-1add23cac246.png">

**Expected behavior**

Same table in Chrome:
<img width="975" alt="Screenshot 2020-12-02 at 17 07 12" src="https://user-images.githubusercontent.com/1542068/100883036-e8db8d80-34c0-11eb-8c19-5fc4257e5d8c.png">

**Comment by mitsuruog** [comment]
Which version of firefox actually are you using?
I could not reproduce it. I might have missed something though.

<img width="808" alt="スクリーンショット 2020-12-03 20 11 20" src="https://user-images.githubusercontent.com/1703219/101004400-e3a33f00-35a3-11eb-8f90-00c30ff09b2f.png">

react-styleguidist: 11.1.4
Firefox: 83.0 (Mac: Big Sur)

**Comment by alextewpin** [comment]
@mitsuruog same as you, but on Catalina. It seems like not all tables are affected. Here is live example: https://whale.cargoonline.ru/#!/DateRangePicker

**Comment by mitsuruog** [comment]
Thanks. I've seen it now.
The only firefox seems to have a problem with inline-flex, but I don't find the reason so far.

**Comment by mitsuruog** [comment]
I've sent a PR.
