### ISSUE TITLE
playground link it not working

### ISSUE THREAD

**Issue by webmas0124** [styleguidist/react-styleguidist#1725]
![Screen Shot 2020-12-04 at 9 32 27 AM](https://user-images.githubusercontent.com/57678421/101101190-c312cd80-3613-11eb-9e83-f29cd28814eb.png)

If I click this link I am getting the below issue.

![Screen Shot 2020-12-04 at 9 32 06 AM](https://user-images.githubusercontent.com/57678421/101101227-d887f780-3613-11eb-8903-74963dc5e97c.png)

**Comment by mitsuruog** [comment]
@webmas0124 Would you create a code sandbox?

https://codesandbox.io/s/github/mitsuruog/react-styleguidist-issue-template
