### ISSUE TITLE
Following gettting started guide things don't work properly when you install react-styleguidist

### ISSUE THREAD

**Issue by JGFMK** [styleguidist/react-styleguidist#1736]
**Current behavior**
**To reproduce**
`node -v`
v14.15.3
`npm -v`
7.3.0

Follow install guide:
https://react-styleguidist.js.org/docs/getting-started/
`npm -i -D  webpack  react-styleguidist`
This installed webpack v5.11.0
This installed react-styleguidist 11.1.5
Yields the following output:

npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   peer react@">=16.8" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN     dev react-styleguidist@"*" from the root project
npm WARN   5 more (react-dom, @tippyjs/react, markdown-to-jsx, react-group, react-icons)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0" from react-simple-code-editor@0.10.0
npm WARN node_modules/react-simple-code-editor
npm WARN   react-simple-code-editor@"^0.10.0" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   peer react-dom@">=16.8" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN     dev react-styleguidist@"*" from the root project
npm WARN   1 more (@tippyjs/react)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.0.0" from react-simple-code-editor@0.10.0
npm WARN node_modules/react-simple-code-editor
npm WARN   react-simple-code-editor@"^0.10.0" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

---
`npm update`

npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   peer react@">=16.8" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN     dev react-styleguidist@"^11.1.5" from the root project
npm WARN   5 more (react-dom, @tippyjs/react, markdown-to-jsx, react-group, react-icons)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0" from react-simple-code-editor@0.10.0
npm WARN node_modules/react-simple-code-editor
npm WARN   react-simple-code-editor@"^0.10.0" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   peer react-dom@">=16.8" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist
npm WARN     dev react-styleguidist@"^11.1.5" from the root project
npm WARN   1 more (@tippyjs/react)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.0.0" from react-simple-code-editor@0.10.0
npm WARN node_modules/react-simple-code-editor
npm WARN   react-simple-code-editor@"^0.10.0" from react-styleguidist@11.1.5
npm WARN   node_modules/react-styleguidist

---

`npm ll --depth=9>nl.txt`
npm ERR! code ELSPROBLEMS
npm ERR! invalid: react@17.0.1 /Users/jgf/Desktop/Notes/JavaScript/React/fullstack-react-code/advanced-components/components-cookbook/node_modules/react
npm ERR! invalid: react-dom@17.0.1 /Users/jgf/Desktop/Notes/JavaScript/React/fullstack-react-code/advanced-components/components-cookbook/node_modules/react-dom

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgf/.npm/_logs/2020-12-27T12_09_09_155Z-debug.log
~/Desktop/Notes/JavaScript/React/fullstack-react-code/advanced-components/components-cookbook>

[nl.txt](https://github.com/styleguidist/react-styleguidist/files/5744527/nl.txt)

--

**Expected behavior**
---

- No warnings.
- **chokidar 3** when using Node 14.15.3, latest Node. 
  - That will get rid of fsevent stuff at same time.

---
You don't need a demo repo to run 2 commands!
---
(I do have nvm installed on a Mac, so I can swap out versions of node or npm - But I don't want audit issues)

Advice please. Thanks
---
When I Googled on: "npm WARN Found: react@17.0.1" I came upon this post:
https://stackoverflow.com/a/64539759/495157
The dependencies on that post seem quite different to your package.json

`npm install --legacy-peer-deps` was the advice there...

But that didn't solve things..
Still gettting:
npm ERR! code ELSPROBLEMS when I use `npm list --depth=9`
I have attached the log file too that came with the ELSPROBLEMS:
[log.txt](https://github.com/styleguidist/react-styleguidist/files/5744573/log.txt)
That seems to point to:
invalid: react-dom@17.0.1
Maybe this is related?:
https://github.com/facebook/react/issues/20082

https://stackoverflow.com/questions/64730868/invalid-hook-call-but-not-really

https://reactjs.org/warnings/invalid-hook-call-warning.html

---

Right I think I have deduced the issue:
nl.txt - shows  react-simple-code-editor 0.10.0
It has a dependency on react/react-dom ^16.0.0 in the package.json
From Sep 2017
https://github.com/facebook/react/blob/master/CHANGELOG.md#1600-september-26-2017

There is a version 0.11.0. 
https://www.npmjs.com/package/react-simple-code-editor
https://github.com/satya164/react-simple-code-editor
It uses yarn from what I can tell.. which I am personally not too familiar with.
https://github.com/satya164/react-simple-code-editor/blob/master/yarn.lock
react-dom@^16.6.0:
react@^16.6.0:

https://github.com/satya164/react-simple-code-editor/issues/75

So the question becomes: When did you upgrade to react-17? What version will work in harmony with react-simple-code-editor?
Is that dependency a requirement? Could it be removed or made optional so as to not break the install?
It also seems obvious the author has not had time to update things in a long time.
React 16.6: Oct 2018
https://github.com/facebook/react/blob/master/CHANGELOG.md#1660-october-23-2018
react-simple-code-editor Latest commit 7bb8daa on 30 Sep 2019

v10 Sep 30, 2019
https://github.com/satya164/react-simple-code-editor/commits/73b57bf4d548257890f9ed0ee83ee37ec099b256/package.json
v11 Jan 17, 2020

---

PS: It seems odd yarn says explicitly ^16.6.0 ... yet the npm warnings give ^16.0.0.. Maybe it's down to the `devDependencies:` vs `peerDependencies:`.  (the latter I don't recall having seen before.. Maybe some downstream lower level dependency stuff?) See below.

https://nodejs.org/es/blog/npm/peer-dependencies/

---

The `npm update` causes react-simple-code-editor to appear in node_modules folder *after* the initial failures from the `npm -i -D` install.
<img width="1680" alt="Screenshot 2020-12-28 at 11 07 54" src="https://user-images.githubusercontent.com/14791808/103210244-0ef82000-48fd-11eb-8fb8-2453d0994e97.png">

---

See also:
https://stackoverflow.com/questions/65843175/how-can-i-get-react-styleguidist-to-install-correctly-and-get-past-the-peer-depe

**Comment by tamlyn** [comment]
As noted on the SO post, this is caused by npm 7's new feature to install peer dependencies automatically. The short term solution is to opt out with 

    npm install --legacy-peer-deps

The longer term solution probably requires `react-simple-code-editor` and others to modify their peer dependencies to allow future versions of React, e.g. `>=16` instead of `^16`. I suspect this is going to cause problems all over the React ecosystem.
