### ISSUE TITLE
npm install react-styleguidist produces ERESOLVE on dep tree

### ISSUE THREAD

**Issue by methodbox** [styleguidist/react-styleguidist#1745]
**Current behavior**

Unable to resolve dep tree.

Error output:
```bash
➜ npm install --save-dev react-styleguidist
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8" from react-styleguidist@11.1.5
npm ERR!   node_modules/react-styleguidist
npm ERR!     dev react-styleguidist@"*" from the root project
npm ERR!   peer react@"17.0.1" from react-dom@17.0.1
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@">=16.8" from react-styleguidist@11.1.5
npm ERR!     node_modules/react-styleguidist
npm ERR!       dev react-styleguidist@"*" from the root project
npm ERR!     peer react-dom@">=16.8" from @tippyjs/react@4.1.0
npm ERR!     node_modules/@tippyjs/react
npm ERR!       @tippyjs/react@"4.1.0" from react-styleguidist@11.1.5
npm ERR!       node_modules/react-styleguidist
npm ERR!         dev react-styleguidist@"*" from the root project
npm ERR!   4 more (@tippyjs/react, markdown-to-jsx, react-group, react-icons)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-simple-code-editor@0.10.0
npm ERR! node_modules/react-styleguidist/node_modules/react-simple-code-editor
npm ERR!   react-simple-code-editor@"^0.10.0" from react-styleguidist@11.1.5
npm ERR!   node_modules/react-styleguidist
npm ERR!     dev react-styleguidist@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/devmonkey/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/devmonkey/.npm/_logs/2021-02-22T17_43_28_789Z-debug.log
```
This was produced by just doing `npm install` w/a previously working `package.json` in an existing project. I reproduced the issue by creating an empty directory, running `npm init`, then `npm install --save-dev webpack` then `npm install --save-dev react-styleguidist` and had the same results.

NOTE:  Using `--force, or --legacy-peer-deps` as suggested in the error did not resolve the issue.

I realize the error is referencing the React dep on `peer react@"^16.0.0" from react-simple-code-editor@0.10.0` however, I did not experience this just a few days ago with my same dependency of React 17.0.1 for my project.

**To reproduce**

I **did not fork** your repo because you **cannot** reproduce this issue by doing so.  You simply need to run `npm install react-styleguidist` (or in my case, `npm install --save-dev react-styleguidist`) to reproduce this issue. I've provided a link below for a demo repo.

NOTE: I **manually** added the dependency in `package.json` because it is not added due to the `npm` error.

https://github.com/methodbox/styleguidist-bug-demo

**Expected behavior**

I expected `npm install react-styleguidist` to install the node module without errors.

**Comment by methodbox** [comment]
It looks like this is likely related to one of multiple peer dep-related open issues (most already with the Bug tag) with npm 7.x itself.
Example:  https://github.com/npm/cli/issues/2744
The many issues related:  https://github.com/npm/cli/issues?q=is%3Aopen+label%3A%22Release+7.x%22+peer

Downgrading to the latest 6.x release of 6.14.11 resolves the issue.

Not sure if you guys want to leave this open until that's resolved in npm? Version 6.x is now considered legacy, so likely many are upgrading to 7.x 7.5.4 is the latest stable, so this is likely to become a bigger issue until it's resolved on their end.

**Comment by slikts** [comment]
Using the `--force` flag allows getting past the error, but then starting just exits silently.

![image](https://user-images.githubusercontent.com/137872/111547702-36cf8500-8782-11eb-8a4e-43db3225ba9f.png)

The project was created with just `npx react-create-app styleguidist-test`.

**Comment by slikts** [comment]
`--force` allowed getting past the `ERESOLVE`, but the getting started guide doesn't work anyway, since it says:
> We couldn’t find any components using these patterns:
But no patterns are listed, and the project is just a fresh `create-react-app` install.

**Comment by BossBele** [comment]
+1
