### ISSUE TITLE
CSF files support: TypeScript and ECMAScript Next support

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1748]
CSF support (#1497) is being implemented as part of switching internals to Mdx (#1712) in #1720.

This issue is my quick research on how to support TypeScript and ECMAScript Next (optional chaining and that kind of stuff) in CSF files.

Here are the options I can think of so far:

* **Acorn** (_current option but updated to the latest version_): solves ECMAScript Next but no TS support.
* **Sucrase + Acorn**: nope, Sucrase supports TS but transpiles too much (JSX and new syntax, for example), so we can't use its output in the examples.
* **Acorn-loose**: it's parsing the code but the AST is all wrong.
* **Babel** (_I haven’t tried it yet_): should be the most bulletproof way but we’ll need to migrate all the code to it, and we use Acorn on the client because of its small size and probably should continue doing so.

The last option seems to be the only solution.

**Comment by okonet** [comment]
Quickly scanning trough the https://astexplorer.net available parser options I found the following parser to be working with TS basic example:

- [babel-eslint9-9.0.0](https://github.com/babel/babel-eslint)
- [@typescript-eslint/parser-4.1.0](https://typescript-eslint.io/)
- [typescript-4.0.3](https://www.typescriptlang.org/)

but only the last two having TS specific AST (`TSTypeAnnotation`)

**Comment by sapegin** [comment]
`@babel/parser` works too but we need to enable `typescript` plugin (and disable `flow` plugin since they don't work together). I don't think we need data about types in the AST but `@babel/parser` has that too.

**Comment by sapegin** [comment]
The `@babel/parser` seems to work:

![image](https://user-images.githubusercontent.com/70067/111586622-6651b200-87c1-11eb-8a97-74f8c1cdc085.png)
