### ISSUE TITLE
Breakage on build between Webpack 5.21.2 and 5.23.0

### ISSUE THREAD

**Issue by jasonwilliams** [styleguidist/react-styleguidist#1786]
**5.21.2**

```
Building style guide...
Style guide published to:
****
```

**5.23.0**

```
Building style guide...
TypeError: Cannot read property 'options' of null
TypeError: Cannot read property 'options' of null
    at commandBuild (/user/project/node_modules/react-styleguidist/lib/bin/styleguidist.js:115:42)
    at Object.<anonymous> (/user/project/node_modules/react-styleguidist/lib/bin/styleguidist.js:71:5)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

The issue seems to stem from https://github.com/styleguidist/react-styleguidist/blob/master/src/scripts/build.ts#L5-L13 on 5.21.2 it returns a `Compiler` object, on 5.23 it returns `null`.

```
_webpack.default(_makeWebpackConfig.default(config, 'production'), (err, stats) => {console.log(stats)})
>> null

webpack.default(_makeWebpackConfig.default(config, 'production'))
>> Compiler {hooks: {…}, webpack: ƒ, name: undefined, parentCompilation: undefined, root: Compiler, …}
```

It doesn't seem to like the callback

**Reproduce**
Install Webpack 5.23.0 and run `styleguidist build`

Version: 11.1.5

**Comment by marcisp** [comment]
Save issue here.

**Comment by marcisp** [comment]
@jasonwilliams did you manage to resolve that issue? :)

**Comment by jasonwilliams** [comment]
@marcisp sadly not but I hope to look into it soon. Feel free to investigate and add anything you find here it will be useful.

**Comment by jasonwilliams** [comment]
Interestingly i can't reproduce this when building against master, only on 11.1.6

**Comment by lusq010** [comment]
I got same problem, while my webpack version is 5.21.2 and react-styleguidist 11.1.5. Is there any new progress on this issue? SOS！

**Comment by jasonwilliams** [comment]
I know this may not help your situation,  it I moved to storybook in the end. I think it’s unlikely this will get fixed

**Comment by kliph-gladly** [comment]
This issue was not resolved for me on `react-styleguidist` version `11.2.0` .  I ended up upgrading from Webpack `5.57.1` to Webpack `5.75.0` which resolved the issue for me.  I did not investigate further to see which particular version of Webpack resolves this issue.
