### ISSUE TITLE
Use with vite or snowpack

### ISSUE THREAD

**Issue by FelixIncerta** [styleguidist/react-styleguidist#1843]
We use React and removed webpack so we cannot run our styleguidist server anymore.

Any idea how we could still run it with https://vitejs.dev/ ?
This thing is much faster then webpack for development.

Thanks

**Comment by ThanhPhat1080** [comment]
Hi @FelixIncerta The styleguidist mentioned use with non-webpack config here: https://react-styleguidist.js.org/docs/webpack#non-webpack-projects.
For now, you still need webpack to help styleguidist load your project.
