### ISSUE TITLE
Extra syntax highlighting

### ISSUE THREAD

**Issue by vallsv** [styleguidist/react-styleguidist#1857]
Hi,

**The problem**

I would like to highlight other languages than the subset enforced by `styleguidist`, in instance `yaml`.

I am new to js world, but I did check `src/loaders/utils/highlightCode.ts` and it sounds like `styleguidist` only provides a subset of the available `prismjs` highlighters.

I guess you do it to reduce the size of the client side code? or the loading time? I am not an expert.

**Proposed solution**

Could it be possible to provide a kind of configuration field to manually allow to request to include other languages?
So what, per project people could tune the expected list.

**Alternative solutions**

Or maybe you are anyway interested in including `yaml` by default?

What do you think?

**Comment by drewsynan** [comment]
I ran into this issue too, and as a work-around I put this code at the top of my `styleguide.config.js` file.

```js
const Prism = require('prismjs');
require('prismjs/components/prism-python');
```

in your case I think you'd want to `require('prismjs/components/prism-yaml')`

**Comment by vallsv** [comment]
Sounds interesting.
Ill take a look.
Thanks a lot.
