### ISSUE TITLE
Embed CSS with jsx example

### ISSUE THREAD

**Issue by vallsv** [styleguidist/react-styleguidist#1858]
Hi,

**The problem**

I would like to know if it is possible to create JSX code block embedding CSS style.

I did try a lot of thing but i guess it is not possible.

Basically:

<pre>
```
`jsx

&lt;div class="foo">Fooooo&lt;/div>
```
</pre>

including the formatting for `foo`.

**Proposed solution**

What i really could like is display it to the user too as source block.
But this could be added with a duplicated block.

<pre>
```jsx css="some/file.css"

&lt;div class="foo">Fooooo&lt;/div>
```
</pre>

**Alternative solutions**

What could be a bit more explicit is to provide the 2 code blocks and link then together to be able to describe the rendering. No idea if such thing is doable.

<pre>
```jsx css="#1"

&lt;div class="foo">Fooooo&lt;/div>
```

```css id="#1"

.foo {
    color: pink;
}
```
</pre>

What do you think about such things?

**Comment by malcolm-kee** [comment]
I think there is no good solution on this unless you use CSS-in-JS.

I had implemented in `react-showroom` (an alternative similar to Styleguidist) to use HTML to achieve what you want.

Take a look here: https://react-showroom.js.org/getting-started/documenting-others#html-support

**Comment by vallsv** [comment]
Sounds really nice.
