### ISSUE TITLE
Next.js / TS Webpack Config: Error on interface declaration

### ISSUE THREAD

**Issue by EvilTeliportist** [styleguidist/react-styleguidist#1918]
I'm building a React project with Next.js, and trying to use `react-styleguidist` to generate autodocs. However, I can't seem to get  the two to play nice. I'll drop config files (`tsconfig.json`, `.babelrc`, `styleguid.config.js`) below. I've already installed `babel` according to [the getting started guide](https://react-styleguidist.js.org/docs/webpack#nextjs), but still no luck. The error I'm getting is `odule parse failed: The keyword 'interface' is reserved (5:0) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.` on a typescript interface declaration I'm using for component props. I feel like this is something with the babel configuration? Any help would be appreciated :).

styleguide.config.js:
```
module.exports = {
  propsParser: require('react-docgen-typescript').withCustomConfig('./tsconfig.json').parse,
  webpackConfig: {
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
      ],
    },
  },
  sections: [...],
};
```
.babelrc:
```
{
  "presets": ["@babel/preset-react"]
}
```
tsconfig.json:
```
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "rules": {
    "max-line-length": [true, 120]
  },
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "rootDir": ".",
    "outDir": "build",
    "allowJs": true,
    "skipLibCheck": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext"
  },
  "include": ["src/**/*.tsx", "test/**/*.tsx", "images", "styleguide.config.js"]
}
```
Example of interface that it's failing on:
```
interface BannerProps {
  /** If set to true, no logo is shown. */
  noImage?: boolean;
  /** If set to true, no text is shown. */
  noText?: boolean;
  /** Passthrough for wrapper div props */
  wrapperProps?: React.HTMLAttributes<HTMLDivElement>;
  /** Passthrough for next/image Image props */
  imageProps?: ImageProps;
}
```

**Comment by EvilTeliportist** [comment]
Also worth noting, I've tried both `@babel/preset-react` and `@babel/preset-typescript`, both with the same issue.

**Comment by gauthamlal** [comment]
@EvilTeliportist hey, were you able to solve this issue?
