### ISSUE TITLE
Do not show function sources in props list

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#197]
If default prop value is a function it renders as its source which is not very nice especially if the function is long.

Simple solution: just write “Function” instead of the code.

Perfect solution: show highlighted or at least formatted code in a tooltip.

![image 2016-10-12 at 10 33 31 am](https://cloud.githubusercontent.com/assets/70067/19303083/82ff7866-9067-11e6-8e0d-f50ee5fa1792.png)

**Comment by sullenor** [comment]
What you think about using function name or `Anonymous function` in case if name was not provided?

**Comment by tizmagik** [comment]
I think it would be great to show the function signature, imagine seeing:

```
renderButton     func    ({ item, isActive, isDisabled, onClick })
```

**Comment by sapegin** [comment]
Function name with a signature in tooltip would be the best if it’s possible.

I think `Function` is much more clear than `Anonymous`.

**Comment by okonet** [comment]
The function name and signature would be very nice. I doubt it should be displayed in a tooltip. Instead, I'd say, it should go into the description field.

**Comment by n1313** [comment]
Fixed in v5
