### ISSUE TITLE
Can react-styleguidist support React18 new features?

### ISSUE THREAD

**Issue by Fangfanghao** [styleguidist/react-styleguidist#2027]
If we want to support React18 new features in react-styleguidist, we have to replace 
**ReactDOM.render** 
to 
**createRoot**

and replace 
**unmountComponentAtNode**
with 
**unmount**

Do we have a plan to suppport this?

**Comment by aParadowski** [comment]
Id like to second this. We're upgrading our component library to 18 and getting these errors in our console locally now. We can thankfully leave `react-styleguidist` on 17 for the time being but would love to be able to be on the latest and greatest.

**Comment by ThomasRoest** [comment]
I can look into it, perhaps after https://github.com/styleguidist/react-styleguidist/pull/1996 is merged

**Comment by ThomasRoest** [comment]
https://github.com/styleguidist/react-styleguidist/releases
