### ISSUE TITLE
Update the package to support react@18

### ISSUE THREAD

**Issue by premsai2030** [styleguidist/react-styleguidist#2062]
I was unable to see components when I was trying to run the server 
and 
I know it's very hard to stop using this package([https://github.com/wojtekmaj/enzyme-adapter-react-17](url)), the owners have to migrate all the test cases from enzyme to something called RTL(react testing library) 

According to @wojtekmaj

- https://github.com/wojtekmaj/enzyme-adapter-react-17/issues/40
- https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl

Please try to update as soon as possible with the latest react@18

**Comment by ThomasRoest** [comment]
see https://github.com/styleguidist/react-styleguidist/releases

**Comment by premsai2030** [comment]
Thanks for upgrading @ThomasRoest
