### ISSUE TITLE
static propTypes Unexpected token

### ISSUE THREAD

**Issue by aris-b** [styleguidist/react-styleguidist#218]
Hi, 

I am getting this error 
```ERROR in ./views/components/.....jsx
Module parse failed: /Users/aris/project/front/views/components/.....jsx Unexpected token (19:21)
You may need an appropriate loader to handle this file type.
| class xxx extends React.Component {
|
|     static propTypes = {
|         propOne: React.PropTypes.func,
|         propTwo: React.PropTypes.bool,
 @ ./~/react-styleguidist/loaders/styleguide.loader.js!./~/react-styleguidist/src/index.js 77:10-76
 @ ./~/react-styleguidist/src/index.js
 @ multi main
```

I have a working-in-production react-webpack stack and i am loading all my loaders from my webpack configuration:

styleguide.config.js
```
    title: 'Styleguide',
    components: './views/components/**/*.jsx',
    serverPort: 3005,
    updateWebpackConfig(webpackConfig) {
        webpackConfig.module.loaders.concat(configuration.module.loaders);
        return webpackConfig;
    }
```

I have a .babelrc file which includes stage-0 of ES7 and also I have a separate config file for babel loader in my webpack config.

PS: I am using Webpack 2.1.0-beta.25

**Comment by sapegin** [comment]
Looks fine for me. Would you mind making an example as [described here](../blob/master/Issue_Template.md)?

**Comment by stinoga** [comment]
I have a similar problem to this. Spread operators seem to not work in certain filetypes for me. In this case it's the `.es6` filetype:
```
ERROR in ./source/common/misc/HvAPI.es6
Module parse failed: /home/rstinogle/hv/webclient/app/products/source/common/misc/HvAPI.es6 Unexpected token (235:38)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (235:38)
```

In my styleguide config:
```js
{
  test: /\.(es6|jsx)?$/,
  include: [
    dir,
    '/home/rstinogle/hv/webclient/app/products/node_modules/react-styleguidist/src'
  ],
  exclude: /(node_modules|bower_components)/,
  loader: 'babel?cacheDirectory=true&presets[]=es2015&presets[]=react&presets[]=stage-2'
},
```

**Comment by sapegin** [comment]
@stinoga Please, don’t include any Styleguidist pathes into your own loaders.

And I can’t reproduce it. Please make an example project.

**Comment by stinoga** [comment]
@sapegin Fixed mine in the example project. Thanks!

**Comment by sapegin** [comment]
@stinoga Could you share the solution? It might help @aris-b ;-)

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.

**Comment by n1313** [comment]
I had this issue when I misconfigured my include/exclude paths and the imported file with spread operator was not "covered" by my loaders.
