### ISSUE TITLE
Changing paths to `main.css` and `bundle.js`

### ISSUE THREAD

**Issue by stinoga** [styleguidist/react-styleguidist#219]
Is there a way to change the generated paths to these files, or remove them altogether? My app uses a static path and cache hashes to call files, so I'd need to have them in the paths in `index.html`. Either that or remove the calls and re-add them manually via a custom template.

**Comment by sapegin** [comment]
You can change Styleguidist’s Webpack config via `updateWebpackConfig`. Run `styleguidist server --verbose` to check the actual config.

So you can replace `HtmlWebpackPlugin` with your own, like without `inject` option:
https://github.com/sapegin/react-styleguidist/blob/master/scripts/make-webpack-config.js#L69-L73

**Comment by stinoga** [comment]
@sapegin That seems to work, but not I get this error: `style-guide.bundle.js:51 Uncaught Error: Cannot find module "./StyleGuide.js"`. Is this because I changed the path to the bundle js file? Seems odd that it would call any other js file relative to it's location, especially since `./StyleGuide.js` is in the npm module.
