### ISSUE TITLE
Default / base Webpack config

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#222]
Similar to what [Storybook has](https://getstorybook.io/docs/react-storybook/configurations/default-config) but more explicit and not all-or-nothing:

```js
const path = require('path');
const loaders = require('react-styleguidist/loaders');
module.exports = {
  title: 'React Style Guide Example',
  components: 'lib/components/**/[A-Z]*.js',
  webpackConfig: {
    loaders: [
      loaders.babel,
      loaders.css,
      {
        // Some custom loader
      },
    ],
  },
};
```

CLI tool (#208) should generate config similar to create-react-app by default.

**Comment by MoOx** [comment]
I think a good approach would be to consume existing webpack by default and inject yourself styleguidist requirement. Less configuration out of the box. You can still validate user config (like for include etc).

**Comment by sapegin** [comment]
I really don’t like this idea. But if anyone could implement it I’d like to see ;-)

1. Hard to find user config automatically (but I’m going to try with CLI).
2. Not everybody uses Webpack.
3. We don’t require `include` or `exclude` anymore in the upcoming 5.0.0.

**Comment by MoOx** [comment]
1. webpack.config.js by default or from CLI args.
2. hum well in no config or no CLI arg, then skip this :)
3. so it's even easier?

**Comment by MoOx** [comment]
Let's me develop my idea: people wants stuff that works out of the box, no config (or really minimal stuff like a folder path) should be enough for your project (see CRA or next.js). I think I did this mistake with Phenomic: I want everything to be customisable so people needs to configure before using it: generally a bad idea, people want to try with minimal effort before actually using a tool.
Also supporting tools without any user effort should be made when doable. For example now Phenomic support Glamor or Aphrodite out of the box, nothing to do from your side if we can do it. I know it requires some work but it will make your project more easy to try. I honestly tried some others, but never happy. styleguidist is slow and have other problems, but it works! Having setup more easy will bring more users, so more contributors on the long run :)

**Comment by sapegin** [comment]
1. It could be `webpack.config.dev.js` or anything else. I want to implement auto configuration for [CLI](https://github.com/styleguidist/react-styleguidist/issues/208) but I’m not sure that it could be good enough for default behavior. But if we have a working implementation we could think about that.

2. In this case we still need Webpack loaders to process user’s files. That’s why I like the idea of basic loaders. CLI could setup them as well it the project doesn’t depend of Webpack.

3. Yes, basically in 5.0.0 you could pass any loaders of existing project and they would work because we do not have any loaders except JSON anymore. And JSON would be automatically added if you do not pass one.

**Comment by sapegin** [comment]
I totally agree with you! I know that Styleguidist configuration is a pain in the ass and I believe 5.0.0 would make it much simpler. Not yet just works without any effort like you describe but already it’s a huge step forward.

I doubt a bit this “when doable” in this case ;-)

If you have any more specific ideas on how it should work (user’s Webpack config resolution, merging, etc.) could you please describe that in a new issue?

/cc @okonet as a huge fan of this idea :shipit:

**Comment by okonet** [comment]
I agree it should work out of the box without the config for common use cases. Advanced setup should be handled as well via passing arguments or having a simple cosmiconfig.

**Comment by sapegin** [comment]
I totally agree that robots should do the work, not humans. But can anyone describe how exactly it could work? Or even try to implement it?

If it could be done reliably enough I’d be happy to make it the default behavior.

**Comment by aaronjensen** [comment]
I could see styleguidist split into a few pieces.

1. A React Component library (`styleguidist`) that has a `Styleguide` component that takes a `config` prop. That config would basically be what the `styleguide-loader` exports.
2. A `styleguidist-loader` which you would point to a config file, i.e. `styleguide!./styleguide.config.js`. This would export the necessary structure for the `Styleguide` component in 1.
3. A `styleguidist-cli`package that serves the purpose of the "works out of the box" experience with sensible defaults. It would have the same defaults that webpack does and the same flags for overriding the webpack config. 

1 & 2 would allow anyone to add something like:

```js
import styleguideConfig from 'styleguidist!styleguide.config.js'
import Styleguide from 'react-styleguidist'

// ...
<Styleguide config={styleguideConfig} />
...

For webpack users, I think this would require 0 webpack config changes because it is using a loader manually as above. The styleguidist-loader package could contain its additional loaders and use those with hard coded paths so they do not require webpack config changes either.

This isn't fully thought through and I'm probably missing something, but it's a direction I'm excited about.

**Comment by sapegin** [comment]
@aaronjensen I’m afraid it’s much more complicated than you think and more complicated than what @MoOx and @okonet are suggesting. It could make Styleguidist more flexible but won’t make initial setup much simpler.
