### ISSUE TITLE
New "Open isolated" encroaches on components

### ISSUE THREAD

**Issue by aaronjensen** [styleguidist/react-styleguidist#235]
![monosnap 2016-11-17 08-14-21](https://cloud.githubusercontent.com/assets/8588/20397227/d9b47844-ac9d-11e6-8879-5b8d0d182f50.png)

Maybe it should just be moved down next to Show code?

**Comment by sapegin** [comment]
It was there and I didn’t like it. Maybe on top of the box?

**Comment by aaronjensen** [comment]
Sure, it doesn't really matter to me as long as it is out of the way.

**Comment by n1313** [comment]
<img width="421" alt="screen shot 2016-11-22 at 00 10 02" src="https://cloud.githubusercontent.com/assets/632081/20490204/11f03330-b048-11e6-8339-ecf4a72081a5.png">

Hmmm... Do you like it? I'm not sure if I like it this way.

**Comment by aaronjensen** [comment]
It looks like it would still encroach on longer text above the example. I think that there either needs to be:

1. more margin above each example so there's enough room for it.
2. more padding within each example
3. moved down below the example where there is already enough space (though it's certainly a different type of action than "Show code')
4. made less obtrusive (maybe just the arrow, the meaning of which is made known by the primary "Open isolated") and left where it is but given a translucent white background

**Comment by sapegin** [comment]
Can we replace both open links with an icon? And probably put them near component title on hover and near Show code button on hover (and not like button, just an icon with a tooltip).

**Comment by aaronjensen** [comment]
I'd be fine w/ that.

**Comment by n1313** [comment]
Do you have any particular icons in mind? Something like font-awesome, or custom ones?

**Comment by sapegin** [comment]
I think this one from Font Awesome would work:

![image 2016-11-22 at 9 40 42 am](https://cloud.githubusercontent.com/assets/70067/20517133/0bc90e1c-b09a-11e6-8fd3-8786d8a579c4.png)

But we need an SVG, not web font for just one icon.

**Comment by n1313** [comment]
Won't an inline base64-encoded png do instead of a separate svg file?

**Comment by sapegin** [comment]
Not in 2016 ;-) You can inline SVG as well, it’s much easier: just put in a React component.

**Comment by sapegin** [comment]
Should be fixed in [5.4.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.4.0).
