### ISSUE TITLE
Add ids to component containers

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#238]
I would like to ask you to add unique ids to component containers, something like `<div id={ name + '-container' }>`. It would help me have better CSS selectors in my visual testing suite: `#ComponentName-container .ReactStyleguidist-Playground__preview` instead of using `:nth-of-type()`. 

I understand that I can do it by having a custom component like https://github.com/sapegin/react-styleguidist/blob/master/examples/customised/styleguide/components/ReactComponent/index.jsx, but it will make updating styleguidist more difficult: I don't want to monitor upstream for changes in that file.

I also understand that isolated view exists but I can't use it for my task because I'm not using a webserver to host my docs for phantomjs, but feed them directly as `file:///` which makes navigating to #!/ComponentName a bit complicated.

(I can make the change myself and send a PR later if you so prefer)

**Comment by sapegin** [comment]
PR would be great! But please check #207, you may need to change your code after I finish it.

**Comment by n1313** [comment]
Any time estimates on that change?

**Comment by sapegin** [comment]
As soon as I can ;-) The JSS migration is almost finished (will push tonight probably) but there are more changes planned for the next major release — #223.

I’d suggest adding IDs to container and preview so you won’t use any class names in your queries. In that case JSS won’t break your code and I could merge your PR earlier. Would that solve your problem?

**Comment by n1313** [comment]
Hmm... My suite does the following: it iterates over every component, and then takes screenshots of every code block in the examples section of that component. The screenshots are then compared with baseline screenshots. I would like to have a consistent class name on the preview containers.

**Comment by sapegin** [comment]
Then maybe ID for each component and generic class name like `rsg--preview` for each preview?

**Comment by n1313** [comment]
That would be perfect, yes.

**Comment by sapegin** [comment]
Then I’ll be happy to merge you PR! 💥
