### ISSUE TITLE
Fonts & Colors (questions)

### ISSUE THREAD

**Issue by stubar** [styleguidist/react-styleguidist#241]
Just starting using this library for our styleguide / pattern library and am really loving it.  
I have a couple of questions...

What I would like to have is a colour palette and a list of fonts.  These aren't components per se, more instructions as to when to use certain colour combinations and fonts.  My first thought is to create a 'fonts-colors.jsx' component which is purely for this illustration and not to be used in the production site.  Is this what you would recommend or is there a better approach to this?

Secondly, the style guide is likely to be used as a reference by 3rd parties who don't necessarily use react, it would be good to have the option of showing the html source code as well as the JSX code, is this possible?

**Comment by aaronjensen** [comment]
> My first thought is to create a 'fonts-colors.jsx' component which is purely for this illustration and not to be used in the production site. Is this what you would recommend or is there a better approach to this?

This is basically what we do.

**Comment by sapegin** [comment]
I’d add a section with a Markdown file and show colors and fonts in examples. Can’t show an example now but I’m going to try that soon for my project.

> it would be good to have the option of showing the html source code as well as the JSX code, is this possible?

I think it‘s possible to implement. Would be cool if you have time to experiment with that. I have a rough idea how it could be done.
