### ISSUE TITLE
Remove general lodash require?

### ISSUE THREAD

**Issue by aaronjensen** [styleguidist/react-styleguidist#249]
As mentioned in #136, lodash is required and included globally for use within examples. I personally don't use this and don't care to pay the 100kb+ price in size and load time. Would it be possible to make this optional or just not include it and let people require what they want in examples? 

Is there currently a hook to add globals like this? If so, I'd probably like to use it for a few other things.

- [x] Find working solution to provide context modules.
- [x] Replace global React/Lodash with it.
- [x] Add an option to easily add globals.
- [x] Remove Lodash at all.
- [x] Update docs.

**Comment by sapegin** [comment]
Probably it‘s a good idea. But probably current way to optionally enable it is a bit too complicated. You need to add a JS file to entries like this:

```js
globals._ = require('lodash');
```

**Comment by sapegin** [comment]
But probably we can use `webpack.DefinePlugin` for that and make an easy config option like that: 

```js
globals: {
  _: require('lodash'),
}
```

I’d use that too! Not sure that `globals` is the best name.

**Comment by sapegin** [comment]
But don’t compare ungzipped sizes, they are not that important ;-)

**Comment by aaronjensen** [comment]
I've never used `webpack.DefinePlugin` for anything but constants, but maybe that'd work. I think the entries is more straight forward. It's what I'm doing today for some other stuff.

ungzipped sizes are important for runtime afaik. The more code that's there, gzipped or not, the more it needs to execute which will slow startup.

**Comment by sapegin** [comment]
I think it should be `webpack.ProvidePlugin `: https://github.com/madewithlove/webpack-config/blob/fcf39f3b31378b59f31c3353f6973801a5f53e8e/src/plugins/provide.js

**Comment by aaronjensen** [comment]
I'm not sure that will work for the case we want. It doesn't actually set them globally, it makes them available as free variables w/in modules, which our examples are not.

**Comment by sapegin** [comment]
Looks like it works fine. I’ve added a todo list to the issue. Do you want to work on that?

**Comment by oliverturner** [comment]
An alternative would be to use [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) to automate the module extraction: possibly less onerous.

**Comment by sapegin** [comment]
We can’t use Babel for user’s code and especially for examples. Styleguidist itself already use crerry-picking everywhere.

**Comment by oliverturner** [comment]
got it: good catch :)

**Comment by aaronjensen** [comment]
@sapegin 4ae9927 doesn't work at all for me:

![react style guide example 2016-11-23 07-30-23](https://cloud.githubusercontent.com/assets/8588/20567739/bf56a62e-b14e-11e6-8357-b23151418111.png)

**Comment by sapegin** [comment]
Very strange. Why does it work for me then? ;-}

**Comment by aaronjensen** [comment]
I'm guessing because of the new build step. If you didn't compile after making the change it'd still look like it works.

I think that what we actually want to do is add `React` to the execution context. I've not yet wrapped my head around the way that it all works, but that'd be the best imo. That way we wouldn't pollute the global namespace.

Furthermore, the config option to add "globals" should maybe be called `context` and add those things to the context as well rather than globally:

```js
context: {
  _: 'lodash',
  foo: 'foo',
}
```

**Comment by sapegin** [comment]
You're genius! I forgot to start the compiler 🐙

And I agree on both points: about context and about the name.

**Comment by sapegin** [comment]
Before:

```
❯ gz examples/basic/styleguide/build/bundle.js
Original: 2.35 MB
Gzipped:  499 kB (21.29%)
```

After:

```
❯ gz examples/basic/styleguide/build/bundle.js
Original: 1.81 MB
Gzipped:  403 kB (22.31%)
```

Almost 100 KB gzipped!

**Comment by sapegin** [comment]
And with fixed UglifyJS:

```
❯ gz examples/basic/styleguide/build/bundle.js
Original: 580 kB
Gzipped:  174 kB (30.02%)
```

**Comment by aaronjensen** [comment]
Very nice!
