### ISSUE TITLE
Errors trying to run examples

### ISSUE THREAD

**Issue by benjamingrobertson** [styleguidist/react-styleguidist#250]
This project looks awesome, and I'm really hoping we can adopt it in our workflow. I've been struggling today to get it set up with one of our current projects, so I decided I'd pull down the examples and try those.

I followed the instructions for the [basic example](https://github.com/styleguidist/react-styleguidist/tree/master/examples/basic), but I get the following error when running `npm run styleguide-server`:

```
ERROR in Unexpected token {
 @ ./~/react-styleguidist/src/index.js 40:18-48 81:1-84:3
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  578 kB       0       
    chunk    {0} index.html 540 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./~/react-styleguidist/scripts/templates/index.html 562 bytes {0} [built]
        [1] ./~/lodash/lodash.js 539 kB {0} [built]
            cjs require ./../../../lodash/lodash.js [0] ./~/html-webpack-plugin/lib/loader.js!./~/react-styleguidist/scripts/templates/index.html 1:8-46
        [2] (webpack)/buildin/module.js 241 bytes {0} [built]
            cjs require module [1] ./~/lodash/lodash.js 1:0-41

```

Webpack version is 1.13.3. 

`localhost:3000` displays `Cannot GET / `

I would really appreciate any help getting up and running. Thanks again for an awesome project!

Ben

**Comment by sapegin** [comment]
Looks like you have the same issue as https://github.com/styleguidist/example/issues/1, but I can’t reproduce it.

**Comment by benjamingrobertson** [comment]
@sapegin Thanks for pointing me over there. Switching from node 5.11.0 to 7.0.0 resolved the issue for me.
