### ISSUE TITLE
Isolated examples do not work inside Markdown documents

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#251]
Style guide config:

```js
module.exports = {
    sections: [
        {
            name: 'UI Guidelines',
            content: 'docs/UiGuidelines.md',
        },
        // ...
      ],
}
```

All examples in this Markdown file have isolated view links like this: `http://localhost:3000/#!/undefined/1`.

**Comment by n1313** [comment]
Should this be closed now, @sapegin?

**Comment by sapegin** [comment]
Yeah. GitHub will close it automatically anyway as soon as commit will be in master ;-)
