### ISSUE TITLE
Server never respond and 100% CPU consumed by node

### ISSUE THREAD

**Issue by MoOx** [styleguidist/react-styleguidist#253]
I can't share the code, I didn't find what is doing that yet, but webpack (or styleguidist process) seems to never finish. With 4/5 components, it works, but as soon as I add a folder with around 20/30 components, it's unusable and my cpu is dying. Any pointers on how I can debug this?

**Comment by sapegin** [comment]
Unfortunately I have no other ideas than to try to find which component causes it. 30 isn’t a big number so it shouldn’t be because of the number, then it’s probably one or few unusual components.

**Comment by MoOx** [comment]
FYI this simple snippet kill react-docgen https://github.com/reactjs/react-docgen/issues/140
