### ISSUE TITLE
Handling nested components

### ISSUE THREAD

**Issue by stinoga** [styleguidist/react-styleguidist#259]
What is the best way to handle two components that are usually nested? In my case I have two component files, and they are nested like so:

```jsx
<Panel>
  <PanelHeader title="Open the pod bay doors">HAL</PanelHeader>
  I'm sorry, Dave. I'm afraid I can't do that.
</Panel>
```

Do I put an example in each component, and add import statements? If so, where is the best place to do that? I noticed if not I obviously get an import error:
`ReferenceError: PanelHeader is not defined`

**Comment by sapegin** [comment]
I did it like that: https://github.com/styleguidist/react-styleguidist/blob/master/docs/FAQ.md#how-to-add-custom-js-and-css

And inside this JS:

```js
global. PanelHeader = require('./PanelHeader').default;
```

But I’m sure we can think of a better solution.

**Comment by sapegin** [comment]
Or if you don’t use `skipComponentsWithoutExample` you can just not write examples for `PanelHeader`. You’ll have props list for it and it will be available globally.

**Comment by stinoga** [comment]
Interesting. I was also thinking about putting both`Panel` and `PanelHeader` into the same file, since they will always be used together. I tried that using this setup:
`resolver: require('react-docgen').resolver.findAllComponentDefinitions,`

It seemed to work, but I get an error:
```
Warning: flattenChildren(...): Encountered two children with the same key, `.0:$/home/rstinogle/hv/webclient/app/products/source/common/components/Panel=1jsx`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by sapegin** [comment]
Does it want key in your code or somewhere in Styleguidist?

**Comment by stinoga** [comment]
@sapegin Yeah, it wants a key in my example code. Fixes the error, but stinks because then people are adding keys into their components when they pattern match off of the style guide :(

**Comment by stinoga** [comment]
Actually, no. I take that back. It looks like individual keys may be needed in the Styleguidist code.

**Comment by frontend-3** [comment]
@sapegin does this `global.PanelHeader = require('./PanelHeader').default;` really work? I was trying but I had this error `unexpected token import`  when I try to restart webpack

**Comment by sapegin** [comment]
@frontend-3 Looks like you don’t setup babel-loader for the file you’re trying to import.

**Comment by frontend-3** [comment]
@sapegin I'm trying this:

```js
const path = require('path');
module.exports = {
  // ...
  updateWebpackConfig(webpackConfig) {
    webpackConfig.entry.push(path.join(__dirname, 'path/to/script.js'));
    webpackConfig.entry.push(path.join(__dirname, 'path/to/styles.css'));
    global.AddIcon = require('./src/assets/icons/add-icon.svg');
    return webpackConfig;
  },
};
```

I'm using react-svg-loader 🤔

**Comment by sapegin** [comment]
@frontend-3 First I’d suggest to update to the [5.0 RC](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.0.0-rc.1). Second to make a demo as [described here](../blob/master/Issue_Template.md) because I’m not really sure what you’re trying to do in this config and don’t see `react-svg-loader` anywhere in you config.

**Comment by frontend-3** [comment]
Hey @sapegin I just found this [section](https://github.com/styleguidist/react-styleguidist/blob/master/docs/FAQ.md#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples) on FAQ, I used in that way and worked perfectly ✨

**Comment by ohtanya** [comment]
@stinoga did you end up resolving this issue? I was able to import `PanelHeader` within my `Panel` but I'm losing the props for `PanelHeader`. Are you able to display the props for both components?
