### ISSUE TITLE
Use findAllExportedComponentDefinitions as default resolver

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#260]
Default [react-docgen](https://github.com/reactjs/react-docgen) resolver fails when you export multiple components:

```js
export class MultiSelect extends Component {}
export default Dimensions()(MultiSelect);
```

We recommend to use `findAllComponentDefinitions` instead but it breaks as I understand when you have multiple components in a file but not export them directly:

```js
export default class Form extends Component {}
Form.Section = function() {}
Form.Buttons = function() {}
```

`findAllExportedComponentDefinitions` works fine for me in both cases (and do not break for any other 60 components). Are there any drawbacks? Am I missing something?

**Comment by madjam002** [comment]
I was using `findAllExportedComponentDefinitions` with my PR (#283) and it works just fine with various files exporting default and named components.

**Comment by sapegin** [comment]
@madjam002 Awesome! It will be in 5.0.0 by default.
