### ISSUE TITLE
Object references are broken in examples state

### ISSUE THREAD

**Issue by AoDev** [styleguidist/react-styleguidist#261]
Hi, here is a simple example that you can copy as is and try in the styleguide.

It shows three buttons, one is "active". (red, green, blue)
When one is clicked, it is updating the example state so that the active item is a reference to some item in a list (array of objects).

The example fails because it seems that the state update mechanism clones objects or does anything that breaks references. This is a problem for any component example that relies on object references. But, they work correctly in the "real world".

```js
const items = [
  {id: 'red'},
  {id: 'green'},
  {id: 'blue'}
]

initialState = {activeItem: items[0]}

// update state, logs item clicked showing the reference is broken
function setActive (item) {
  console.log(item, item === items[0], item === items[1], item === items[2])
  setState({activeItem: item})
}

<div>
  <button type="text" onClick={setActive.bind(null, items[0])}>red {items[0] === state.activeItem ? 'active' : ''}</button>
  <button type="text" onClick={setActive.bind(null, items[1])}>green {items[1] === state.activeItem ? 'active' : ''}</button>
  <button type="text" onClick={setActive.bind(null, items[2])}>blue {items[2] === state.activeItem ? 'active' : ''}</button>
</div>
```

Note: It is broken right from the start when it is set in the initialState and also later when the state is updated.

**Comment by sapegin** [comment]
It might be because we’re `eval`ing examples’ code. But `setState` is just a normal `setState` of a component that wraps example.

Anyway I’d avoid such code in any “real world” app — that looks very unreactish for me. Store an item ID in the state, it works fine.

**Comment by AoDev** [comment]
@sapegin 
This is a contrived example simply to illustrate the problem.

And I don't know what you mean by Reactish, since a big point of React optimization is based on checking references in the render tree. Hence from the start and until now they have created and improved the pureRender mixin -> shallowCompare -> pureComponent.

I don't think it's a good idea to limit styleguidedist to what you think is the right way. If you don't want to handle this case at least a note should be added that any reference in examples won't work.

**Comment by sapegin** [comment]
If you think it’s a bug please send a pull request with a fix or improved docs.

**Comment by AoDev** [comment]
@sapegin I send a PR with docs updated with a note about this issue. Let me know if it's ok there or if any change is needed.
