### ISSUE TITLE
Unexpected token { in v4.4.x

### ISSUE THREAD

**Issue by tomsowerby** [styleguidist/react-styleguidist#268]
Migrating from v4.1.0 to v4.4.3 we started getting errors when running the server:

ERROR in Unexpected token {
 @ ./~/react-styleguidist/src/index.js 40:18-48 81:1-84:3

Same error back to v4.4.0.
Rolled back to v4.3.3 and all works fine.
I couldn't see any migration guide notes on the release.

Config if pretty basic:

    module.exports = {
	title: 'components',
	components: './src/**/*.js',
	skipComponentsWithoutExample: true,
	serverPort: '3005',
	styleguideDir: './docs',
	updateWebpackConfig(webpackConfig) {
		const node_modules = path.resolve(__dirname, "node_modules");
		webpackConfig.module.loaders.push(
			{
				test: /\.js$/,
				exclude: node_modules,
				loader: 'babel'
			},
			{
				test: /\.scss$/,
				exclude: node_modules,
				loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass?includePaths[]=./node_modules'
			},
     .... etc etc

Thanks.

**Comment by sapegin** [comment]
Are you using Node 4 or 5? This issue was reported several times but I still can‘t reproduce it.

**Comment by sapegin** [comment]
Thanks for the exact version where it was introduced, I could reproduce it finally!

**Comment by tomsowerby** [comment]
Witnessed using the following:
Node v4.5.0
Npm v2.15.9

**Comment by sapegin** [comment]
Thanks for detailed bug report, should work in 4.4.3.

I’ll add tests to prevent that later.

**Comment by tizmagik** [comment]
What was the issue?

**Comment by sapegin** [comment]
@tizmagik Syntax not supported in Node 4/5, check the commit.

**Comment by tizmagik** [comment]
Oh I see. I thought we transpiled, maybe we should?

**Comment by sapegin** [comment]
We transpile only browser code. Node 4+ supports enough features. We should just test that ;-)

**Comment by tizmagik** [comment]
Ah gotcha 👍

Another option is to also run server code through babel but behind babel-preset-env. Might not be worth it if it was just these few lines that were incompatible, but testing against older versions of node in CI would help catch these in the future, so that's good 👌

**Comment by sapegin** [comment]
It makes everything more complicated with a very tiny benefit ;-)
