### ISSUE TITLE
Ability to display source code of the component

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#269]
During my work on [react-dropzone styleguide](http://react-dropzone.netlify.com/), which isn't a conventional styleguide, one of the missing pieces is an ability to inline the source code of the examples into the styleguide.

So, in my case, the config looks like this (excerpt):

```js
module.exports = {
  title: 'react-dropzone',
  showCode: false,
  sections: [
    {
      name: 'Installation',
      content: 'README.md'
    },
    {
      name: 'PropTypes',
      components: './src/index.js'
    },
    {
      name: 'Examples',
      components: './examples/**/*.js',
      context: {
        Dropzone: './src/index'
      }
    }
  ]
};
``` 

The idea is to display examples and allow opening them in the isolation mode. But one of the important things I'd like to achieve is to have example's code inlined into the documentation. Right now this is only possible by having it twice — once in `/examples/**/index.js` and one more time in `/examples/**/Readme.md` inside the code block with `jsx` type (so it won't get evaluated).

It would be great to have an option for each `section` that would allow inlining the source code of component's file to the styleguide.

Worth mentioning, that I don't want this to be editable, just a raw contents rendered with code highlight. This should be easy to achieve with `raw-loader`. Although it might be interesting to experiment with editable source code as well.

**Comment by okonet** [comment]
Another idea would be to have some special markup for the markdown that would add the source code of the component as a code block below it.

**Comment by okonet** [comment]
Random file? I'm not sure I get this.

**Comment by sapegin** [comment]
Instead of rendering only component‘s source, which looks very specific and rare, just allow to specify a path.

**Comment by okonet** [comment]
Yes, that would work as well!

**Comment by sapegin** [comment]
[](./file.js)

**Comment by okonet** [comment]
After some 1x1 discussion, it seems that the most appropriate and flexible way would be to have some extended markdown syntax that would allow inlining the contents of the linked file. So, the user would write something like `> ../path/to/my/file.js` and it would render file contents using code fence block.

There are few open questions like:

1. What this marker should look like?
1. How to determine the syntax of the file? Should user define it?
1. It would be great if those links would still work on GitHub as well

**Comment by okonet** [comment]
One of the possible solutions could be as simple as having a fence block with the path to a file that should be inlined.

![2016-12-27 at 11 43](https://cloud.githubusercontent.com/assets/11071/21498086/c3411724-cc29-11e6-90a9-7f737b9af659.png)

**Comment by sapegin** [comment]
What if we use links with something [like this](https://kramdown.gettalong.org/syntax.html#block-ials)? Not sure Remark supports it.

**Comment by okonet** [comment]
I really like how https://github.com/interactivethings/catalog handles it and I believe we should approach it in a similar way (specimens).

**Comment by sapegin** [comment]
Yep, that would work too. And could solve other issues too. The only con is that it would render as just text on GitHub.

**Comment by sapegin** [comment]
One more requirement:

4. Specify how to show a file: as a highlighted source or as a rendered example.

**Comment by gregorskii** [comment]
This would work great for inlining external CSS as well.

**Comment by sapegin** [comment]
So do we have any ideas how it should look? I’d like to include this feature in the next major release.

**Comment by okonet** [comment]
What do you mean by "look"? API-wise? I think it would be great to have a fenced block with some additional parameters like file path to highlight for example. Front matter as a format should work just fine. As for remark parsing — I think it can be extended?

**Comment by sapegin** [comment]
Yes, API. So something like this would work?

    ```js // { "file": "./foo/bar.js" }
    ```

In this case we could reuse @stepancar code from #511. But I’m not sure it would work with non-JS code.

**Comment by okonet** [comment]
I'd prefer front matter YAML format TBH since this make it more human readable.  I've commented on #511

**Comment by n1313** [comment]
This seems like a good candidate for a plugie, with appropriate support from RSG core API or in some other roundabout way.

**Comment by sapegin** [comment]
@n1313 I think you’re right and it shouldn’t be hard to implement support for any custom modifiers.

**Comment by sapegin** [comment]
🍕 [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0-beta.1) beta is out!!  🍕

**Comment by sapegin** [comment]
🍕 [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0) is out!!!! 🥓
