### ISSUE TITLE
Don't display `Props` heading if there are no props defined

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#270]
Right now the heading `Props` is always visible no matter if there are Props defined or not.

![2016-12-27 at 11 35](https://cloud.githubusercontent.com/assets/11071/21497931/9f28e746-cc28-11e6-9646-edfd09d5e3cd.png)

It should only be visible if there are props defined. 

Additionally, it would be great to have an option related to each `section` that would allow disabling Props section whatsoever.

**Comment by sapegin** [comment]
Should be very easy to fix: https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/ReactComponent/ReactComponentRenderer.js#L22-L25

**Comment by sapegin** [comment]
Fixed in 302cce73db7e27889ac7445adb0c2aca90a5d546.
