### ISSUE TITLE
print out values of `PropTypes.oneOf`

### ISSUE THREAD

**Issue by chrisdrackett** [styleguidist/react-styleguidist#289]
This is currently done with shape and its really nice. Right now if you use `oneOf` the only thing shown in type is `enum`, it would be great to be able to see the supported values.

**Comment by sapegin** [comment]
Yeah, and I believe it’s not very difficult to make. It would be very cool if you have time and will to try it and send a pull request ;-)

**Comment by chrisdrackett** [comment]
yeah, I have that on my list, figured I would post here in case someone gets to it before me :)

**Comment by AoDev** [comment]
Hello, I was checking if I could help.

I found this issue and I am not sure what you mean. I already have the values in my styleguide, in the description column. (One of 'default', 'danger')

It looks like there is nothing to do here?

<img width="613" alt="screen shot 2017-01-31 at 21 13 21" src="https://cloud.githubusercontent.com/assets/1526150/22482659/3bf115b6-e7fa-11e6-8092-fbc8311785f8.png">

**Comment by n1313** [comment]
@chrisdrackett the values of `oneOf` are already being printed, so not sure what issue you are describing here. Are you talking about `oneOfType`?

**Comment by sapegin** [comment]
`objectOf` is supported in 5.x beta. Closing this for now. Feel free to reopen with more details.
