### ISSUE TITLE
Static Assets? 

### ISSUE THREAD

**Issue by lapidus** [styleguidist/react-styleguidist#291]
I would like to include a couple of images in the documentation.
How would i need to tweak the webpackConfig to allow something like the below?
```
Markdown file
![image](static/image.png)
```

**Comment by sapegin** [comment]
Have you tried `assetsDir` option?

https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md

**Comment by lapidus** [comment]
Oups, that is embarrassing ... Can't understand how I overlooked it, but thank you!
