### ISSUE TITLE
Missing support for webpack2 config with `rules`

### ISSUE THREAD

**Issue by avaly** [styleguidist/react-styleguidist#292]
Using webpack2 with a custom config which uses `module.rules` instead of `module.loaders` fails to load.

The issue is due to webpack loading either `rules` or `loaders`, but not both: https://github.com/webpack/webpack/blob/v2.2.0/lib/NormalModuleFactory.js#L46

And `react-styleguidist` only exports `loaders`: https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js#L82

See demo: https://github.com/avaly/react-styleguidist-example/tree/webpack2-rules

**Comment by sapegin** [comment]
It shouldn’t be a problem in the 5.0.0 beta. Could you please try it? 

https://github.com/styleguidist/react-styleguidist/releases/tag/5.0.0%40beta.9

**Comment by avaly** [comment]
Indeed, it does work with the latest beta: https://github.com/styleguidist/example/pull/2

As a workaround for folks who are on react-styleguidist <=4.* :

```js
updateWebpackConfig(webpackConfig, env) {
  webpackConfig.module.rules = webpackConfig.module.loaders.concat([
    // your custom rules here
  ]);
  webpackConfig.module.loaders = [];
  return webpackConfig;
}
```
