### ISSUE TITLE
LoaderOptionsPlugin plugin in user  webpack config can break Styleguidist

### ISSUE THREAD

**Issue by avaly** [styleguidist/react-styleguidist#293]
According to the latest 5.0.0 beta at https://github.com/styleguidist/react-styleguidist/releases/tag/5.0.0%40beta.9, `updateWebpackConfig` is deprecated.

**If this method is removed** in future versions, the following issue will preset it self: using a custom webpack2 config with a `LoaderOptionsPlugin` specifing some custom options for loaders will override the internal plugin which is used for the `styleguidist` options.

Demo repo: https://github.com/avaly/react-styleguidist-example/tree/webpack2-styleguidist5-loader-options-plugin
Important lines: https://github.com/avaly/react-styleguidist-example/blob/webpack2-styleguidist5-loader-options-plugin/styleguide.config.js#L26-L30
Output: https://gist.github.com/avaly/07c0cb7f249cbf46d113bbd4154104ac

A simple workaround would be to use https://github.com/frontainer/webpack-loader-options-merge inside `updateWebpackConfig`, since it's the only place we have access to the internal styleguidist webpack config.

**Comment by sapegin** [comment]
That’s why I’ve added this warning ;-) Even if we never deprecate `updateWebpackConfig` it’s good to solve as many use cases as possible without it. 

I think merging is the right way to solve the issue. We‘re doing some custom merging of plugins anyway.

**Comment by sapegin** [comment]
Should be fixed in `react-styleguidist@5.0.0-beta.10`. Please try if you have time 🦄

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
