### ISSUE TITLE
Conflict: Multiple assets emit to the same filename build/bundle.js

### ISSUE THREAD

**Issue by aaronjensen** [styleguidist/react-styleguidist#294]
With `"react-styleguidist": "^5.0.0-beta8"` and my webpack.config.js, I get this:

```
$ yarn run start:styleguide
yarn run v0.19.1
$ styleguidist server
Style guide server started at:
http://localhost:3000

Error when parsing client/app/components/molecules/FileUpload.js
SyntaxError: Unexpected token (32:27)

Failed to compile.

Error in chunk vendor [entry]
build/bundle.js
Conflict: Multiple assets emit to the same filename build/bundle.js
```

Here is my config: https://gist.github.com/aaronjensen/dae58ad57efc7f12921d4cb148b618ae

**Comment by aaronjensen** [comment]
Ok, I've tracked it down to my `CommonsChunkPlugin`

**Comment by sapegin** [comment]
So, should we rename `bundle.js` to `rsg-bundle.js`?

**Comment by sapegin** [comment]
You have quite a lot of stuff in your config — would be cool to make Styleguidist work with it without any hacks.

**Comment by aaronjensen** [comment]
I'm not sure that'd matter. I just can't use CommonsChunkPlugin the way that I was. The way that styleguidist handles the `webpackConfig` option caused me some confusion:

`webpackConfigFile` automatically excludes `entry` and `output` but when supplying a `webpackConfig` does not, I'm responsible for that, so when I do that, it helps, but then my `CommonsChunkPlugin` wants to build a bundle for `vendor` even though it's not there. I believe it not being there is why it's trying to write to `bundle.js`. It'd be a useless bundle if it wrote it, so I'm just removing that plugin.

I'm not sure how to make it work automatically. I suppose you could strip out any `CommonsChunkPlugin`s

**Comment by aaronjensen** [comment]
With these changes to my webpack config it seems to work:

```js
  if (options.styleguide) {
    config.entry = [
      path.join(clientDir, 'app/polyfills'),
      path.join(clientDir, 'app/style/base'),
      path.join(clientDir, 'styleguide/bootstrap'),
    ]
    delete config.output
    config.plugins = config.plugins.filter(
      plugin => !(plugin instanceof webpack.optimize.CommonsChunkPlugin))
  }
```

**Comment by sapegin** [comment]
It always strips `output` but allows you to use `entry` in `webpackConfig`  so you can add polyfills and other things.

Yeah, if ignoring `CommonsChunkPlugins` doesn‘t make things worse we can do that.

**Comment by sapegin** [comment]
Should be fixed in `react-styleguidist@5.0.0-beta.10`. Please try if you have time 🦄

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.

**Comment by dujingya** [comment]
configureWebpack: {
        plugins: [
            new CompressionWebpackPlugin({
                filename: '[path][base].gz',
                algorithm: "gzip",
                test: new RegExp("\\.(" + productionGzipExtensions.join("|") + ")$"), //匹配文件名
                threshold: 10240, //对10K以上的数据进行压缩
                minRatio: 0.8,
                deleteOriginalAssets: false //是否删除源文件
            })
        ]
    },
改成这样就可以了，      filename: '[path][base].gz',
