### ISSUE TITLE
PropTypes.oneOf in combination with a description results in render warnings.

### ISSUE THREAD

**Issue by ZwaarContrast** [styleguidist/react-styleguidist#297]
When adding comment above a propType defined with the oneOf type, that results in render warnings.

Warning.
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of 'Group'. It was passed a child from PropsRenderer. See https://fb.me/react-warning-keys for more information.`

Check out the forked example here:
https://github.com/ZwaarContrast/example

`Heading.propTypes = {  
    /**  
     * This will result in a render warning  
     */  
    size: PropTypes.oneOf( ['small', 'medium', 'large'] ),  
}
`

**Comment by kulakowka** [comment]
I have this problem too.

Versions of my packages:

```
"dependencies": {
    "react-scripts": "^0.8.5",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-styleguidist": "beta"
  },
```

**Comment by roychoo** [comment]
This is an issue with react-group. I have created a pr with react-group. https://github.com/sapegin/react-group/pull/1

**Comment by n1313** [comment]
Thanks @roychoo! The PR's been merged into react-group.

To anyone having this issue on RSG 4.6.3: update dependencies of RSG (or simply delete and reinstall it) to pick up the new version of react-group to have this issue resolved.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
