### ISSUE TITLE
Is it possible to disable the screen clearing in v5?

### ISSUE THREAD

**Issue by aaronjensen** [styleguidist/react-styleguidist#301]
We run several apps at once during dev in a single terminal. Styleguidist's screen clearing is disruptive to that. Is it possible to disable it and have it go back to how it was before?

**Comment by sapegin** [comment]
It’s not difficult to make an options for that. But if that annoys many people we could just remove it ;-)

https://github.com/styleguidist/react-styleguidist/blob/next/bin/styleguidist.js#L12

**Comment by aaronjensen** [comment]
I'd be good w/ removing it. I also miss the build timing.

**Comment by sapegin** [comment]
I have no strong preference. But if I have to choose between removal and a new options, I’d choose removal ;-)

**Comment by n1313** [comment]
I also would like to have this removed or be an on/off option.

**Comment by tizmagik** [comment]
+1 for removing

**Comment by sapegin** [comment]
No console clearing anymore ;-)

Let me know if we can improve UI further.
