### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#302]
I’m going to make a proper site for Styleguidist after 5.x release, so a proper logo would a very nice addition.

Unfortunately I have no ideas of my own ;-£

/cc @okonet

**Comment by n1313** [comment]
For reference: https://github.com/WebAssembly/design/issues/112

**Comment by sapegin** [comment]
And one more for reference: https://github.com/okonet/react-dropzone/issues/343

**Comment by sapegin** [comment]
For some reason octopus represents in my mind idea of many components gathered together. But not cute one like on GitHub logo but evil or mischievous octopus like on a tattoo or metal band logo. Or a bit close to PostCSS logo in style.

**Comment by nhavar** [comment]
Superquick like 5 minute example that I want to play around with and do some more variations of

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg8"
   version="1.1"
   viewBox="0 0 210 297"
   height="297mm"
   width="210mm">
  <defs
     id="defs2" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     id="layer1">
    <path
       transform="scale(1,-1)"
       d="m 58.6874,-7.1100034 -22.77967,-1e-7 -22.77967,-10e-8 11.389835,-19.7277724 11.389835,-19.727774 11.389835,19.727773 z"
       id="path4487"
       style="opacity:1;fill:#ffffff;stroke:#d40000;stroke-width:0.98490268;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1;stroke-dasharray:none;stroke-dashoffset:0;paint-order:normal" />
    <path
       id="path4485"
       d="M 35.876068,0.25594619 C 28.363442,0.25580419 22.273211,7.4480272 22.27328,16.32008 c 0.0058,3.825332 1.167433,7.522642 3.27577,10.426756 6.700723,-6.301605 13.468492,-6.805469 20.669012,0 2.10274,-2.906708 3.25874,-6.603748 3.26027,-10.426756 7e-5,-8.8718138 -6.08985,-16.06393781 -13.602264,-16.06413381 z"
       style="opacity:1;fill:#000000;stroke:none;stroke-width:1.48985291;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1;stroke-dasharray:none;stroke-dashoffset:0;paint-order:normal" />
    <path
       style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M 0.94875884,33.319303 C 12.998467,24.689707 30.854552,34.534323 34.60775,24.608902 c 1.077836,-2.850361 0.355046,-2.019618 0.355046,-2.019618 -1.2924,9.150361 -25.2028292,1.464385 -34.01403716,10.730019 z"
       id="path4495" />
    <path
       id="path4497"
       d="M 3.3275528,39.09534 C 13.035699,27.896354 33.749942,35.162693 35.087951,24.63605 35.472197,21.613031 34.962796,22.589284 34.962796,22.589284 35.83736,31.788987 9.7381268,28.032163 3.3275528,39.09534 Z"
       style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
    <path
       style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M 6.6094938,45.950431 C 14.355513,33.314587 35.822467,35.191767 35.420985,24.588028 35.305683,21.542869 34.962796,22.589284 34.962796,22.589284 37.330062,31.522113 11.124544,33.987837 6.6094938,45.950431 Z"
       id="path4505" />
    <path
       id="path4507"
       d="M 0.20030784,28.859462 C 12.941736,21.288372 29.851326,33.611503 34.436892,24.042122 c 1.316873,-2.748114 0.525904,-1.982005 0.525904,-1.982005 -2.06766,9.006898 -25.1935592,-1.681513 -34.76248816,6.799345 z"
       style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
    <g
       transform="matrix(-1,0,0,1,135.87285,-49.136905)"
       id="g4542">
      <path
         style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         d="m 64.637747,82.456208 c 12.049708,-8.629596 29.905793,1.21502 33.658991,-8.710401 1.077836,-2.850361 0.355046,-2.019618 0.355046,-2.019618 -1.2924,9.150361 -25.202829,1.464385 -34.014037,10.730019 z"
         id="path4530" />
      <path
         id="path4532"
         d="m 67.016541,88.232245 c 9.708146,-11.198986 30.422389,-3.932647 31.760398,-14.45929 0.384246,-3.023019 -0.125155,-2.046766 -0.125155,-2.046766 0.874564,9.199703 -25.224669,5.442879 -31.635243,16.506056 z"
         style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
      <path
         style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         d="M 70.298482,95.087336 C 78.044501,82.451492 99.511455,84.328672 99.109973,73.724933 98.994671,70.679774 98.651784,71.726189 98.651784,71.726189 101.01905,80.659018 74.813532,83.124742 70.298482,95.087336 Z"
         id="path4534" />
      <path
         id="path4536"
         d="m 63.889296,77.996367 c 12.741428,-7.57109 29.651018,4.752041 34.236584,-4.81734 1.316873,-2.748114 0.525904,-1.982005 0.525904,-1.982005 -2.06766,9.006898 -25.193559,-1.681513 -34.762488,6.799345 z"
         style="fill:#000000;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
    </g>
  </g>
</svg>

**Comment by sapegin** [comment]
@nhavar Thanks! I’ve edited your comment — now it has an image ;-)

**Comment by theodorosploumis** [comment]
Hi, I could help with this if you like. I am not a logo designer but I like creating logos and graphics for open source projects. Should I proceed?

Thanks in advanced!

**Comment by sapegin** [comment]
@theodorosploumis Sure! Do you have any ideas already?

**Comment by theodorosploumis** [comment]
Will come back asap with some proposals.

**Comment by theodorosploumis** [comment]
I was thinking about something like this. A **butterfly combined with the React logo**. Some logos are not pixel perfect but for initial proposals they are OK. Personally I prefer most No1 and No5.

![proposals_1-8](https://cloud.githubusercontent.com/assets/1315321/24518488/d831070c-158a-11e7-84f3-f9513aaba1ee.png)

**Comment by SaraVieira** [comment]
![rs](https://cloud.githubusercontent.com/assets/1051509/25406737/aa0d6508-29ff-11e7-843f-765783ac41e0.png)

You guys like ?

Used a free logo that only needs credit and changed according to my idea

**Comment by SaraVieira** [comment]
![rs2](https://cloud.githubusercontent.com/assets/1051509/25406837/0a13fa16-2a00-11e7-9147-e204455a4e6a.png)

**Comment by SaraVieira** [comment]
![res2](https://cloud.githubusercontent.com/assets/1051509/25406883/32ec37f0-2a00-11e7-92db-0d9b7a19a5e1.png)


I made him more evil

**Comment by sapegin** [comment]
@SaraVieira Cool, I like it! 🐊

**Comment by SaraVieira** [comment]
@spagin Awesome! Let's get some more feedback then :)

**Comment by n1313** [comment]
> a free logo that only needs credit

Where is this logo from?

**Comment by sapegin** [comment]
Yeah, I’m also interested in licensing and attribution. It may be an issue.

**Comment by SaraVieira** [comment]
I checked and here is their license: http://file000.flaticon.com/downloads/license/license .it says we can change it and use it wherever we want. 

And the website:http://www.flaticon.com/free-icon/octopus_371706#term=octopus&page=1&position=6

**Comment by sapegin** [comment]
Sounds a bit complicated for a logo that can be used anywhere: http://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-

(And I actually like your version more ;–)

**Comment by SaraVieira** [comment]
It does , but I think the idea is just to put a link on the footer, or just use mine :)

**Comment by sapegin** [comment]
Maybe you can redraw it using the original as inspiration? That would solve the issue and we’d have an original logo ;-)

**Comment by okonet** [comment]
Yay for having an original logo.

I'd also spend some more time exploring the typography part. Generally, I think the logo (sign) is enough for OSS projects since it will be problematic to use on GitHub and still keep the type as text.

**Comment by SaraVieira** [comment]
Okay , most of it I already redraw , as you can see from the link there were a lot of retouches on it , it is original , not just a copy and paste so I can work a little more in it and make it more unique is that okay @sapegin @okonet ?

Maybe the typo can go , right ?

**Comment by sapegin** [comment]
Sounds good! For the text I think we need to choose I nice readable font and use it everywhere on a site.

@okonet @SaraVieira I’ll need your help with the site: especially colors, typography, etc. Will show you something soon ;-)

**Comment by SaraVieira** [comment]
![rs4](https://cloud.githubusercontent.com/assets/1051509/25434111/ed848fcc-2a82-11e7-8f46-24f8dc663a28.png)

Simpler version

**Comment by sapegin** [comment]
I actually liked that I don’t know what behind the legs ;-) I’d rather remove dots on the head. But that’s just option of an amateur. What @okonet would say? ;-)

**Comment by SaraVieira** [comment]
That is a fast change I can put them side by side 👍 

One sec

**Comment by SaraVieira** [comment]
![group 3](https://cloud.githubusercontent.com/assets/1051509/25434334/cc0c494c-2a83-11e7-9b5e-60a7bdb0704e.png)

Comparision of with or without dots

**Comment by SaraVieira** [comment]
![type](https://cloud.githubusercontent.com/assets/1051509/25434423/29ae4ac8-2a84-11e7-8106-76112748fe44.png)

Some type ideas , I used raleway that is a free font and can be used on the website easily

**Comment by okonet** [comment]
Some comments from me:

![2017-04-26 at 18 05](https://cloud.githubusercontent.com/assets/11071/25444330/016f06d4-2aab-11e7-8f8a-eac2677566c5.png)

I'm not sure about the second row of legs and about the secondary color. Can you try drawing separate legs (octopus should have 8, right?) and different colors perhaps?

**Comment by SaraVieira** [comment]
Great feedback @okonet !

I will take a look at that as soon as I get home :)

If you want to play with it and have sketch I shared it on dropdbox: https://www.dropbox.com/s/ld2z44umba1fu3c/rs.sketch?dl=0

**Comment by okonet** [comment]
@sapegin I like those dots on the head. 

Some suggestions: 
- Try to add suckers to the arms
- More armssss :)
- Less evil look probably?

**Comment by sapegin** [comment]
@okonet Now I like them too ;-) 

And I like the idea of extra legs — would fill empty “armpits” after removal of the “back legs”.

**Comment by SaraVieira** [comment]
https://www.dropbox.com/s/60ghwby45ah523o/Screenshot%202017-04-26%2022.40.05.png?dl=0

Is this beter ? @sapegin @okonet

**Comment by sapegin** [comment]
I think it’s a bit too busy now — maybe make legs thinner? 🐙

**Comment by okonet** [comment]
Yes, it's definitively a step back. I'd try placing arms lower.

**Comment by okonet** [comment]
We should probably match 🐙 emoji colors :)

**Comment by sapegin** [comment]
I actually like this turquoise color… but, wait, isn’t it the same as in React logo? ;-)

**Comment by sapegin** [comment]
But I like combination of turquoise and orange anyway ;-)

![](https://s-media-cache-ak0.pinimg.com/originals/e5/6b/a6/e56ba656c14c26ef0f29a5693dfb92cc.jpg)

**Comment by SaraVieira** [comment]
Yes, the torquise is the react color 💃 

My sketch skills are being put to the test here :p

**Comment by sapegin** [comment]
We’re all learning that’s why we do open source ;-)

**Comment by SaraVieira** [comment]
https://www.dropbox.com/s/hktwcx7li4ogsbb/Screenshot%202017-04-27%2010.48.35.png?dl=0

Something like this side ?

**Comment by okonet** [comment]
I was more thinking about something like this:

![2017-04-27 at 12 14](https://cloud.githubusercontent.com/assets/11071/25478863/14567370-2b43-11e7-8a37-a81d957fa6dd.png)

**Comment by SaraVieira** [comment]
I fell like the first legs are too thin, what do you think @sapegin ?

**Comment by SaraVieira** [comment]
you took his mean eyes :(

**Comment by okonet** [comment]
Sorry was just a draft :)

I've simplified the Sketch file a bit if it helps: https://www.dropbox.com/s/yozmu8h7mhh4onn/rs.sketch?dl=0

Just an idea: by looking at it, I'm wondering if arms could mimic RS (react-styleguidist) somehow.

**Comment by SaraVieira** [comment]
> Just an idea: by looking at it, I'm wondering if arms could mimic RS (react-styleguidist) somehow.

What do you mean by this ?

**Comment by SaraVieira** [comment]
https://www.dropbox.com/s/ukvc2umjp1e4y0q/Screenshot%202017-04-27%2011.27.03.png?dl=0 I think arms like this make it look a little fuller.

And great job making this simpler :D

**Comment by SaraVieira** [comment]
https://www.dropbox.com/s/kt6b07xh0w2e6x3/Screenshot%202017-04-27%2011.37.31.png?dl=0

**Comment by okonet** [comment]
@SaraVieira can you please upload images directly to GitHub (drag-n-drop them). Clicking links is pain and it would be great to have different versions visible in this thread without need top open separate tabs.

To the latest version: it still feels too busy to me. Can it be simplified even further?

**Comment by sapegin** [comment]
> ![](https://photos-4.dropbox.com/t/2/AACHei8PhgsXjnY87pLT_zK_Opf3P6634mqTuQHojdkvDA/12/662330129/png/32x32/3/1493308800/0/2/Screenshot%202017-04-27%2011.27.03.png/EP3TlrMFGCEgAigC/_pfBv_Jx8C4YeD0gdQEnwkDB63lusLbaKdiuTOJuJXk?dl=0&size=2048x1536&size_mode=3) 

I think this one is very close but need a bit of polishing. Maybe make this inner legs more round?

**Comment by okonet** [comment]
I could polish it a bit later if @SaraVieira don't mind :)

**Comment by SaraVieira** [comment]
@okonet Of course I don't mind , use them sketch skills 🎉

**Comment by okonet** [comment]
Okay, spent some time on it tonight. Thoughts?

![2017-04-28 at 22 58](https://cloud.githubusercontent.com/assets/11071/25547164/38eb360c-2c66-11e7-94bf-f7498817a566.png)

**Comment by sapegin** [comment]
Cooool! Super clean and he’s (or is it a girl?) smiling now :-) I also like it more in one color. (Do we want to use React color or something else?)

**Comment by okonet** [comment]
It's an evil smile, you know 😈

I think the reference to React through color is good.

**Comment by sapegin** [comment]
Just notices that eyes are transparent — was that intentional?

**Comment by SaraVieira** [comment]
That looks amazing @okonet ! I think we may have a winner here 🎉

**Comment by okonet** [comment]
Eyes: no, it was not. Need to fix. 

Sara: thanks to you! I would not do this if you haven't started working on it. And since It's not a competition but a collaboration you deserve same credit for it! 👏

**Comment by okonet** [comment]
And I just realized we met in Amsterdam recently 🙌

**Comment by SaraVieira** [comment]
@okonet thank you! I'm trying to improve them sketch skills, I'm a not designer but I really like to work in stuff so it's awesome I helped :D

Yes we did, I was the girl that chased you and asked if we could use lint staged with flow :p
Such a small world!

**Comment by sapegin** [comment]
Looks like everyone was at React Amsterdam except me 😢

**Comment by SaraVieira** [comment]
@sapegin I'll be in Amsterdam again from 15 to 21 of may, we should meet there :D
Ill be speaking at codemotion amsterdam

**Comment by sapegin** [comment]
@SaraVieira So far I’m going to ReactiveConf in Bratislava in October ;-)

**Comment by SaraVieira** [comment]
@sapegin Why not speak about styleguidist there ?

**Comment by sapegin** [comment]
I’m going to start from local meetups — big conferences are too scary 👨🏻‍🌾

**Comment by SaraVieira** [comment]
@sapegin My first talk was at front ends so don't fear 😃

**Comment by olegshilov** [comment]
New logo reminds me Hydra logo from Agents of S.H.I.E.L.D. series (=
![image](https://cloud.githubusercontent.com/assets/930121/25559647/db0f074c-2d47-11e7-80e0-033c8a81c7c3.png)

**Comment by SaraVieira** [comment]
That's not even a bad thing, I'm actually impressed :p
The bad boys of atyoeguides xD

**Comment by SaraVieira** [comment]
@spagin Is the logo decided?

**Comment by okonet** [comment]
Just FIY: I'd like to polish it a bit more.

**Comment by SaraVieira** [comment]
I think maybe we should work on typography a little too since we will be working the website later

**Comment by sapegin** [comment]
That’s what I have so far, pretty drafty though ;-)

![image 2017-05-01 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/70067/25577889/d6b7a10e-2e69-11e7-8f0c-73121f2caa59.png)

Will share the code in a few days I think so you could play with it.

**Comment by okonet** [comment]
I've spent some more time tonight. It feels that we're close to me.

Decided to play with colors a bit. Can revert to the blue one if this is too much but I thought the resemblance with the 🐙 emoji wouldn't hurt.

![logo](https://cloud.githubusercontent.com/assets/11071/25596975/6520f8e8-2ecc-11e7-91bc-445844c6241e.png)

Here is also my take on typography. I'm using https://fonts.google.com/specimen/Montserrat since it's has the Open Font License:

![logotype](https://cloud.githubusercontent.com/assets/11071/25596979/6732fc80-2ecc-11e7-933e-a4e1dce1d3df.png)

Feedback is appreciated!

**Comment by sapegin** [comment]
I sill prefer the blue one ;-) But I like this gradient background though ;-)

I’ve tried the Montserrat on a home page:

![screencapture-localhost-6601-1493707089301](https://cloud.githubusercontent.com/assets/70067/25606646/d05c20c4-2f12-11e7-8034-c277e9c47933.png)

Any feedback?

**Comment by okonet** [comment]
Okay, back to blue.

![logo](https://cloud.githubusercontent.com/assets/11071/25609282/d6911876-2f1e-11e7-9f71-3b957bd5556f.png)

![logotype](https://cloud.githubusercontent.com/assets/11071/25609286/dbbe1a24-2f1e-11e7-8daf-376544b2a933.png)

I've tried another font for the typography: https://fonts.google.com/specimen/Bree+Serif Feels more cheerful to me.

I don't really like the Monteserrat as a main font. I think a good sans-serif or serif would fit better. Check out the pairing section on Google Fonts.

**Comment by sapegin** [comment]
@okonet Awesome! I like more curvy legs ;-) Could you send me an SVG — I’d try to put it on a main page as well as other font.

**Comment by SaraVieira** [comment]
@okonet The blue with the gradient looks amazing! Great work 

@sapegin about the website I thinks it needs more spacing between the sections :/

**Comment by sapegin** [comment]
> I thinks it needs more spacing between the sections :/

@SaraVieira yeah, I think you’re right ;-)

**Comment by SaraVieira** [comment]
@sapegin Are you designing this in the browser or using any software?

**Comment by okonet** [comment]
It's now official: https://github.com/styleguidist/brand 🙌

I'm closing this one.

**Comment by SaraVieira** [comment]
@okonet Holly crap! We should totally get stickers!

**Comment by sapegin** [comment]
> Are you designing this in the browser or using any software?

All in the browsers, so it’s a real site already ;-)

> Holly crap! We should totally get stickers!

Yes!!!

**Comment by SaraVieira** [comment]
@sapegin Ready for GH pages anytime! Awesome!
