### ISSUE TITLE
Render different example markup than what is in example markdown?

### ISSUE THREAD

**Issue by reintroducing** [styleguidist/react-styleguidist#303]
An odd title, I know, but allow me to explain.  Some of our components require a rather extensive setup inside of a parent and some other components to be present (picture a modal, requires a button to open it, state management from the parent for isOpen or not, etc). We typically show example code as an App.jsx component that has all of the imports and everything spelled out to show complete usage. Because of all the extra items in there, we can't just throw that in the markdown file and it will work (or will it?).

Our thought was to have it encapsulated in an Example.jsx component that renders that out and then in the markdown file we would do this:
```
Renders a Modal.

    <Example blah="foo" ...etc />
```

I think that would work to show the component properly but then of course our source code markup is that of the example component, not of the contents of whats inside of Example.jsx which is the code we want to show as usage.

Is there a way to do this currently?

**Comment by sapegin** [comment]
I see two workaround for that:

1. Just put everything you need into an example code, add comment and stuff.
2. Use regular syntax-highlighted code to show the important pieces.

![image 2017-02-02 at 5 05 00 pm](https://cloud.githubusercontent.com/assets/70067/22557119/c114d870-e969-11e6-9fa4-de693f54f354.png)

![image 2017-02-02 at 5 05 37 pm](https://cloud.githubusercontent.com/assets/70067/22557138/d519a4d6-e969-11e6-9562-4d78dfad3243.png)

**Comment by reintroducing** [comment]
@sapegin If I'm understanding you correctly, the Table example has that code in the markdown file and you just added comments around imports and such so as not to interfere.

The Form example, you put the code directly somewhere as markdown, is that also in the markdown file? 

Can you show me the code used to generate these two examples?

**Comment by sapegin** [comment]
> f I'm understanding you correctly, the Table example has that code in the markdown file and you just added comments around imports and such so as not to interfere.

Yep. 

> The Form example, you put the code directly somewhere as markdown, is that also in the markdown file?

It is but in a fenced block with a language, so it‘s rendered not as a playgound. Like the last example [here](https://raw.githubusercontent.com/styleguidist/react-styleguidist/master/examples/basic/lib/components/Button/Readme.md).

**Comment by reintroducing** [comment]
Perfect, makes perfect sense, thank you!

**Comment by reintroducing** [comment]
I guess last question though. Because the example visibly generated is coming from the markdown file, is it possible to hide the example code that would then display on a case by case basis? I want examples that don't need a complex setup to show code properly but for these that require more setup and will be in a fenced code block i want to hide the example code that generates the actual example and only show the fenced block.

**Comment by sapegin** [comment]
It‘s not possible now but it‘s something I‘d like to have. The problem is to find the right API for this. We’ll need to extend Markdown somehow, but we don’t want to completely break rendering of Markdown files on GitHub and in code editors. It will be probably a braking change as well. 

Related issues: #257, #269.

**Comment by reintroducing** [comment]
thank you, i'll watch those issues.
