### ISSUE TITLE
5.0.0-beta.9: JSS Dependencies Complain About "Unknown [Babel] Plugin" When Omitting `include` Properties in Rules

### ISSUE THREAD

**Issue by kohlmannj** [styleguidist/react-styleguidist#304]
I've prepared [a reduced test case repo](https://github.com/nytpi/styleguidist-5.0.0-beta-babel-issues-rtc) for this issue.

- Reproducible demo: [nytpi/styleguidist-5.0.0-beta-babel-issues-rtc](https://github.com/nytpi/styleguidist-5.0.0-beta-babel-issues-rtc)
- Style guide config: [styleguide.config.js](https://github.com/nytpi/styleguidist-5.0.0-beta-babel-issues-rtc/blob/master/styleguide.config.js)
- Webpack: 2.2.1
- OS X 10.11.6

When using a custom Webpack config with rules that omit `include` properties, in particular for the JavaScript source files rule, it seems that several of Styleguidist's JSS dependencies cannot find certain Babel plugins.

Assumed workaround: add `include` properties to `rules` configs. Would be nice to omit `include` if possible, though.

Please let me know if there are other details I've failed to provide! Thanks!

**Comment by sapegin** [comment]
There are two things:

1. You should either `include` your code or `exclude` `node_modules` in your babel-loader. Otherwise you will have problems like this (see also warning about Lodash — it will just slow down your build in the best case).
2. JSS shouldn’t publish `.babelrc` to npm, I’ll make an issue there.

**Comment by kohlmannj** [comment]
@sapegin Thanks for the speedy reply!

Re (1): I suspect I'm misunderstanding the Webpack best practice for building projects with external non-ES5 dependencies. I'll look further into this and see what's best for my real project; thanks for confirming this problem for me.

Re (2): oh good, glad this particular issue wasn't just my babel-loader rule alone.

**Comment by sapegin** [comment]
1. If you have something that needs transpiling in `node_modules` it complicates config a bit ;-) I add list of this dependencies and my own code in `include` of babel-loader. [Like this](https://github.com/tamiadev/tamia-build/blob/master/config/webpack.config.js#L112-L128).

**Comment by sapegin** [comment]
(I also highly recommend @bebraw’s [book on Webpack](http://survivejs.com/) :—)

**Comment by sapegin** [comment]
JSS PR for reference: https://github.com/cssinjs/jss/pull/415

**Comment by kohlmannj** [comment]
Closing this issue since (1) I have obvious ideas about a workaround, really by way of config best practices (2) the JSS PR has been filed. Thanks again @sapegin, super helpful!
