### ISSUE TITLE
Ordered lists look like unordered lists

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#313]
In `next` branch, list items in both unordered and ordered lists are indicated by discs (as opposed to discs and decimal numbers).

**Comment by sapegin** [comment]
Must be another overisolation issue with jss-isolate ;-)

**Comment by sapegin** [comment]
Should be fixed in react-styleguidist@5.0.0-beta.11.

**Comment by n1313** [comment]
And it is.
