### ISSUE TITLE
How to add custom media-queries?

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#314]
...in the `next` branch? I can add custom styles by using `styles` property of the config, as described in the documentation, but adding `'@media (max-width: 800px)': { ... }` there doesn't seem to work.

**Comment by sapegin** [comment]
I’m not sure what exactly are you doing and why it doesn’t work but there are some examples:

https://github.com/styleguidist/react-styleguidist/blob/next/src/styles/theme.js#L15
https://github.com/styleguidist/react-styleguidist/blob/next/src/rsg-components/StyleGuide/StyleGuideRenderer.js#L40-L44

**Comment by n1313** [comment]
Ok, I see the problem now. According to JSS docs (https://github.com/cssinjs/jss/blob/master/docs/json-api.md), media queries go like this:

```
const styles = {
  button: {
    width: 100
  },
  '@media (min-width: 1024px)': {
    button: {
      width: 200
    }
  }
}
```
So here we have `styles['@media (min-width: 1024px)'].button { width: 200 }`. And this approach *didn't* work for me.

Using your example as a guide I wrote this:

```
const styles = {
  button: {
    width: 100,
    '@media (min-width: 1024px)': {
      width: 200
    }
  }
}
```
Here we have `styles.button['@media (min-width: 1024px)'] { width: 200 }`. And this *did* work.

Not sure if this is a bug in RSG implementation of JSS, or JSS has incorrect documentation. Or maybe I did something wrong. Anyway, I'm happy now.

**Comment by sapegin** [comment]
We’re using jss-nested: https://github.com/cssinjs/jss-nested#use-at-rules-inside-of-regular-rules

**Comment by n1313** [comment]
Then the "we're using JSS Syntax" link in the documentation (https://github.com/styleguidist/react-styleguidist/blob/next/docs/Configuration.md) should be corrected.

**Comment by n1313** [comment]
Since JSS and JSS-nested have different, mutually exclusive, syntaxes when it comes to nested selectors, the docs should be pointing at JSS-nested documentation, not JSS's. Let me send a PR...

**Comment by sapegin** [comment]
There are other plugins that changes syntax like camelizing selectors, etc. So probably better to list all plugins.
