### ISSUE TITLE
Including custom CSS in beta

### ISSUE THREAD

**Issue by schneck** [styleguidist/react-styleguidist#317]
Hi,

I'm, using styleguidist 5beta, and I'm having problems including my custom sass file.

### styleguide.config.js:

```
const path = require('path');

module.exports = {
    title: 'My Style Guide',
    serverPort: 3001,
    skipComponentsWithoutExample: true,
    webpackConfigFile: path.resolve(__dirname, './webpack.styleguidist.js'),  // eslint-disable-line
    components: path.resolve(__dirname, 'src/**/*.jsx')  // eslint-disable-line
};
```

### webpack.styleguidist.js:

```
var path = require('path');
var webpack_config = require('./webpack.config');

var WebpackStyleguidist = Object.assign({}, webpack_config);
WebpackStyleguidist.entry.push(path.join(__dirname, 'src', 'sass', 'styles.scss'));  // eslint-disable-line
WebpackStyleguidist.entry.unshift('babel-polyfill');

module.exports = WebpackStyleguidist;
```
Webpack version: 1.13.1
macOS, Chrome 56.

The sass file exists (I dumped the path), and the application finds it, only staleguidist doesn't.
Any idea?

**Comment by sapegin** [comment]
Would you mind making an example as [described here](../blob/master/Issue_Template.md).

**Comment by sapegin** [comment]
I see. `entry` will be ignored for `webpackConfigFile` as described in the docs. Use `webpackConfig` for that.

https://github.com/styleguidist/react-styleguidist/blob/next/docs/FAQ.md#how-to-add-custom-js-and-css

**Comment by schneck** [comment]
Great, that solved the problem. I don't find this in the docs, however. Maybe it would be a good idea to add this particular issue in the paragraph you mentioned.

Anyway, thanks for this great tool and your support!

**Comment by sapegin** [comment]
I’ve added a whole new page about webpack: https://github.com/styleguidist/react-styleguidist/blob/next/docs/Webpack.md

(Make sure you browse docs in the `next` branch.)

**Comment by schneck** [comment]
Ah I see - sorry for the fuzz and thanks again.
