### ISSUE TITLE
Code that I have to write in examples is different from "real" React code

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#324]
Code examples are very useful as a part of documentation. They allow the reader to see how the "theory" of a component is applied in practice, and are the most useful when they can be easily put into a real application. With react-styleguidist, this works quite well in many cases: you write your code exactly as it should be written and your reader can just copy-paste it into their app and get it working.

Unfortunately, it doesn't work for more complex components that require some sort of external "scaffolding" to work, or for complicated setups, for example, with HOCs and theming. RSG has `initialState` and `setState` which work great but cannot be copy-pasted into a real React application: they have to be rewritten into some sort of constructor method and `this.setState` calls.

Don't get me wrong here though, I'm not saying that RSG is buggy or does its job poorly. It works great, I'm quite happy that I don't have to write all the `import React from 'react';` fluff around most of my components most of the time and can just plop a short JSX one-liner and see it "just work". The task of rendering arbitrary code is *hard*, and it is even harder if you want to have some sort of magical balance between writing short code and writing complicated code. But it would be great if the code in my examples was closer to what my users have to write in their projects.

I don't have a solution at hand and I don't even know if there _is_ a solution for this issue, given all the restrictions that RSG has. So let's talk about this, maybe? Does anybody here have this problem, and how do you deal with it? Is there anything that could be added to RSG to make it even better in this regard?

**Comment by sapegin** [comment]
I don’t know a good way to solve this. So far I use comments and define component classes inside examples:

```jsx
/*
import TableProvider from 'kao/components/TableProvider';
import * as sort from 'kao/util/sort';
import { Header, Body } from 'reactabular-table';
import orderBy from 'lodash/orderBy';
*/
class SortTable extends React.Component {
  constructor() {
    super();
    const sortable = sort.sort({
      getSortingColumns: () => this.state.sortingColumns,
      onSort: selectedColumn => {
        this.setState({
          sortingColumns: sort.byColumn({
            sortingColumns: this.state.sortingColumns,
            selectedColumn
          })
        });
      }
    });
    this.state = {
      sortingColumns: {},
      columns: [
        {
          property: 'name',
          header: {
            label: 'Name',
            formatters: [sort.header(sortable)],
          },
        },
        {
          property: 'color',
          header: {
            label: 'Color',
            formatters: [sort.header(sortable)],
          },
          cell: {
            formatters: [fixtures.getColorName],
          },
        },
        {
          property: 'male',
          header: {
            label: 'Male',
            formatters: [sort.header(sortable)],
          },
          cell: {
            formatters: [male => male && <Icon type="check" />],
          },
        },
        {
          property: 'weight',
          header: {
            label: 'Weight',
            formatters: [sort.header(sortable)],
          },
          cell: {
            formatters: [weight => `${weight} g`],
          },
          props: {
            className: 'text-right',
          },
        },
      ],
      rows: fixtures.rows,
    };
  }
  render() {
    const { columns, rows, sortingColumns } = this.state;
    const sortedRows = sort.sorter({
      columns,
      sortingColumns,
      sort: orderBy
    })(rows);
    return (
      <TableProvider columns={columns}>
        <Header />
        <Body rows={sortedRows} rowKey="id" />
      </TableProvider>
    );
  }
}
<SortTable />
```

![image 2017-02-14 at 11 20 32 am](https://cloud.githubusercontent.com/assets/70067/22925060/9de93110-f2a7-11e6-8876-438b9c620bd8.png)

**Comment by okonet** [comment]
Yeah, that's annoying. Can we create a custom babel plugin that would strip off imports in examples if not needed?

**Comment by sapegin** [comment]
There’s not Babel on frontend. And I think this behavior would be very confusing because for example you can use `require` in example and it will work.

**Comment by okonet** [comment]
> There’s no Babel on the frontend.

So, how is the rest of the code being transpiled to ES5?

> you can use require in example and it will work

Oh, probably I misunderstand the problem then. Why is `import` and `export` aren't working then?

**Comment by sapegin** [comment]
> So, how is the rest of the code being transpiled to ES5?

With [Buble](http://buble.surge.sh). We can’t use Babel because it’s way too huge.

> Oh, probably I misunderstand the problem then. Why is import and export aren't working then?

Because `require` is just a function that return a module, included in the bundle on the build step.

**Comment by okonet** [comment]
Gotcha. Thanks for clarifying.

**Comment by roychoo** [comment]
though it might not be the best way, and it might print relative path instead of the modules path that client is going to write.

https://github.com/nerdlabs/react-docgen-imports-handler

**Comment by sapegin** [comment]
Can we do anything here? Update the docs or something for example? If not I’d close it.

**Comment by stereobooster** [comment]
Any plans to support `import` in the code instead of `require()`? Related: https://gitlab.com/Rich-Harris/buble/issues/59

**Comment by stereobooster** [comment]
Have similar issue. Source code https://github.com/stereobooster/react-mapbox-gl/tree/styleguidist

```
Error when parsing ../src/marker.tsx: TypeError: Cannot read property 'getText' of undefined

It usually means that react-docgen cannot parse your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues

Failed to compile.

Error in ../src/cluster.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 26:29-187

Error in ../src/map.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 33:29-183

Error in ../src/popup.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 47:29-185

Error in ../src/projected-layer.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 54:29-195

Error in ../src/scale-control.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 61:29-193

Error in ../src/zoom-control.tsx
Module build failed: TypeError: Cannot read property 'methods' of null
 @ ./~/react-styleguidist/loaders/styleguide-loader.js!./~/react-styleguidist/lib/index.js 68:29-192

```

**Comment by sapegin** [comment]
@stereobooster We can discuss it as soon as Buble implements them ;-) So far I don’t see we can do anything here.

**Comment by sapegin** [comment]
Try the new [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0-beta.1) beta — it may solve some of this issue.

**Comment by n1313** [comment]
@sapegin could you please explain this a bit? I read the release notes but I didn't see how it is related.

**Comment by sapegin** [comment]
I guess I mean importing examples from files.

**Comment by n1313** [comment]
I think some time ago I have seen someone here pasting an example that used real React code, they wrote an entire component in markdown with class declaration, render method, all the good stuff. I can’t find it, but I think it was @okonet. I’ll try recreating that myself and will close this ticket if it works.

**Comment by sapegin** [comment]
There’s one in my comment at the very beginning of this issue ;-)

**Comment by n1313** [comment]
I guess I misunderstood what that means back at the time.

**Comment by n1313** [comment]
It works! Wow. Very nice. Is this documented anywhere?

**Comment by sapegin** [comment]
I'm not sure, in any case worth documenting it more ;-)

**Comment by n1313** [comment]
Yes, it is documented. https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md#writing-code-examples.
