### ISSUE TITLE
RSG puts components into global namespace

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#325]
All components that are loaded into the styleguide are put into the `global` namespace, so I think it is possible to accidentally overwrite properties of `window` with an unfortunately named component.

**Comment by sapegin** [comment]
The good solution would be to extend code that we use for the `context` option. But it’d be tricky ;-)

**Comment by n1313** [comment]
For historical purposes [here's](https://github.com/styleguidist/react-styleguidist/commit/d07e825e00720f71cf4aea348f1bb12b9dab58b2) my initial stab at this issue. It works but is a bit too dirty of a hack.

**Comment by rcline** [comment]
@n1313 That really doesn't look that hacky to me.  Is there any side effects I am not seeing?

I would love to see this get added!  (Currently having to rename my `Image` component so that it doesn't conflict with `window.Image` :( )

**Comment by sapegin** [comment]
@rcline Doesn’t look super hacky to me now, and I’m sure we can avoid a global variable here. Feel free to send a pull request for that ;-)

**Comment by rcline** [comment]
@sapegin It looks like this code has been changed/moved.
https://github.com/styleguidist/react-styleguidist/blob/d07e825e00720f71cf4aea348f1bb12b9dab58b2/src/rsg-components/Preview/Preview.js#L54-L56

Any direction on where to look to make a similar change? (passing in namespaced components to a `with ()` context call)

**Comment by sapegin** [comment]
Not sure which code has been moved where ;-) 

I think the right place to do it is here: 

https://github.com/styleguidist/react-styleguidist/blob/916e173ecfeb29d89085ed0eddfbefc9f49afb7a/loaders/examples-loader.js#L22-L23

But it’ll require some experiments, you’ll need to move props-loader call there I think:

https://github.com/styleguidist/react-styleguidist/blob/fc6a3ba0a0167de92a8c0c2a7e16d2ae7a3d190a/loaders/utils/processComponent.js#L35

**Comment by kopax** [comment]
I am also having that issues, I'm not sure if I understand the fix, did anybody tried @sapegin solution?

**Comment by linde12** [comment]
Yup. This makes things very difficult when your library has dependencies to third party code. E.g. in my specific case i have a dependency to a component which in turn depends on a component named `Object` resulting in React saying "Object.defineProperty is not a function"

**Comment by ZxBing0066** [comment]
Is there an option to simply ignore components expose to the global? like this below add a `doNotExposeToGlobal` option to section?

```js
// src/utils/globalizeComponents.js
export default function globalizeComponents(sections) {
	sections.forEach(section => {
		if (section.components && !section.doNotExposeToGlobal) {
			section.components.forEach(globalizeComponent);
		}
		if (section.sections) {
			globalizeComponents(section.sections);
		}
	});
}
```

Or add an `functional` option `shouldComponentsExposeToGlobal` to the config.

config in styleguide:
```js
// styleguide.config.js
{
	shouldComponentsExpostToGlobal: function(name) {
		return ["Number", "Object", "String"].findIndex(v => v === name) < 0;
	}
}
```

change source code:
```js
// src/utils/globalizeComponent.js
export default function globalizeComponent(component) {
	if (!component.name || (config.shouldComponentsExpostToGlobal && !config.shouldComponentsExpostToGlobal(component.name)) ) {
		return;
	}

	global[component.name] = getComponent(component.module, component.name);
}
```

**Comment by mirague** [comment]
Facing the same issue with a custom component `Image`. Now it no longer works to create an actual `window.Image` instance.
