### ISSUE TITLE
Are private (or protected, or hidden) props possible?

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#331]
In some cases a component might have a prop that should not be accessed by the user. It could be useful to hide this prop from the documentation or mark it in some other way.

An example of this would be a container component that is wrapped in Redux `connect()` with props that are managed by react-redux. I have a number of props that must be declared on the component for action dispatch to work and should not be tampered with by a user.

**Comment by sapegin** [comment]
How about [`@ignore` JSDoc tag](http://usejsdoc.org/tags-ignore.html)?

/cc @kof

**Comment by kof** [comment]
@sapegin `@ignore` sounds exactly right! Just tried, we currently render it as text in description field, I assume rs needs to handle this prop?

**Comment by sapegin** [comment]
@kof Yup! ;-)
