### ISSUE TITLE
Define a separate attribute for accessing user rendered components

### ISSUE THREAD

**Issue by kof** [styleguidist/react-styleguidist#334]
Right now class names are misused for that purpose.  The reasoning is - classes used internally for styling should be a private implementation detail of sg, they shouldn't be used at the same time for accessing containers for [visual testing](https://github.com/styleguidist/react-styleguidist/issues/238). It makes a false assumption for a user that he should override styles using class names.  It is better to use the default generateClassName function which generates unique class names, to make the intent clear.

In order to give a user an access to the container through the dom, we can use for e.g. a 'data-container' attribute with a specified container name or even path.

**Comment by n1313** [comment]
@kof can this be closed?

**Comment by kof** [comment]
We can remove the custom generateClassName now, right? https://github.com/styleguidist/react-styleguidist/blob/next/src/styles/setupjss.js#L9

**Comment by sapegin** [comment]
@kof Yeah, I think so. Will be happy to merge a PR ;-)
