### ISSUE TITLE
Cannot make it work with i18n HoC

### ISSUE THREAD

**Issue by VP42** [styleguidist/react-styleguidist#335]
I try to use react-styleguidist with some components that are using react-i18n to get translated. 

Unfortunately, there seems to be a problem in my `example.component.md` file as I always get an `TypeError: Cannot read property 'getFixedT' of undefined` error.

Anyone already faced a similar issue?

Thanks a lot!

**Comment by sapegin** [comment]
Have you tried [this solution](https://github.com/styleguidist/react-styleguidist/blob/master/docs/FAQ.md#how-to-change-the-layout-of-a-style-guide)?

**Comment by VP42** [comment]
Awesome! Sorry I missed that and thanks again :)

**Comment by lookapanda** [comment]
@sapegin wha is *this* solution? The link has become invalid (404).

**Comment by sapegin** [comment]
@lookapanda I’ve updated the link.
