### ISSUE TITLE
No information about new beta releases: hard to debug

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#340]
There is no publicly available information about when new beta releases are published on npm and what changes are in them (or at least I couldn't find it). The version field in package.json is not updated, so there are no release commits. There are no git tags after beta 9. 

My current problem: something that happened in beta 12 breaks my phantomjs tests (the screenshots are off position, this works perfectly in beta 11). Without knowing what was released as beta 12, or when betas 11 and 12 were released, it becomes very hard for me to debug the problem. 

Help?

**Comment by sapegin** [comment]
Yup, that’s my mistake, sorry ;-| I think 468cf75 and c095643 were the only changes.

**Comment by okonet** [comment]
Can you setup semantic release for the beta probably?

**Comment by sapegin** [comment]
[Better](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.0.0-beta.15)? ;-)

Far from perfect but better than nothing. With semantic-release it‘s not easy as I understand.
