### ISSUE TITLE
Use custom build of the highlight.js to reduce its bundle size

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#341]
According to https://twitter.com/samccone/status/837173944293568512 providing only needed languages to highlight.js can reduce its bundle size significantly. Seems like a low hanging fruit to optimize since SG should only support JS/JSX.

<img width="679" alt="2017-03-02 at 16 16" src="https://cloud.githubusercontent.com/assets/11071/23513307/d57403f8-ff63-11e6-9604-6d90f04062e0.png">

**Comment by sapegin** [comment]
We don’t have highlight.js in the bundle, it’s all server side ;-)

**Comment by sapegin** [comment]
And actually it should support any language you define for fenced code block. At least HTML, for example.

**Comment by okonet** [comment]
Server-side? Can you elaborate please?

**Comment by sapegin** [comment]
We send HTML from webpack loader, so we don’t have highlight.js on the frontend.
