### ISSUE TITLE
Add gzip compression option for webpack2 dev-server

### ISSUE THREAD

**Issue by kumarabhishek** [styleguidist/react-styleguidist#346]
Add compress option for webpack2 dev server as part of react-styleguidist config.
Refer https://webpack.js.org/configuration/dev-server/#devserver-compress for details

**Comment by okonet** [comment]
Why would you need the compression for dev mode? At the same time I can see how compression can be beneficial for the production env though. Please feel free to create a PR that adds it in production only.

**Comment by sapegin** [comment]
@okonet He means gzip for dev-server, not bundle minification.

I don’t know how useful gzip is for development ;-) Probably won’t harm anyway so feel free to send a pull request.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
