### ISSUE TITLE
Excessive number of class names on <code> elements

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#348]
I see an excessive number of class names on my `<code>` elements in beta15.

This markdown:

![capture](https://cloud.githubusercontent.com/assets/632081/23780926/c177d5ba-0584-11e7-894e-9f664e9bd98c.PNG)

generates this HTML in beta15:

![capture2](https://cloud.githubusercontent.com/assets/632081/23780928/c87b4054-0584-11e7-9bc4-397f2585a6dd.PNG)

and in beta14:

![capture3](https://cloud.githubusercontent.com/assets/632081/23780975/1bf97caa-0585-11e7-8558-cb84d02b2774.PNG)

**Comment by sapegin** [comment]
wow such markdown much css

**Comment by sapegin** [comment]
I’ve sent a pull request to markdown-to-jsx: https://github.com/probablyup/markdown-to-jsx/pull/96

**Comment by n1313** [comment]
Thanks!

**Comment by sapegin** [comment]
Out in [5.0.0-rc.1](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.0.0-rc.1).
