### ISSUE TITLE
PhantomJS fails to run bundle.js in beta15

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#349]
This example https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js when run against a documentation that is generated by beta15 produces a screenshot of a blank template page, and produces a correct screenshot of rendered documentation if it is generated by beta14. I don't see any errors in the output (I've added a `page.onConsoleMessage` handler and I see my test console.log call). Judging by the time it takes to do so in beta14, the javascript bundle is not executed in beta15 (the rasterize script takes the screenshot immediately and exits, and adding a 20 second timeout doesn't help). I'm using phantomjs 2.1.1 (globally installed, prebuilt).

**Comment by n1313** [comment]
This can be reproduced in the rsg repo:

1. checkout the pre-beta15 code
2. npm i, npm run compile, npm start
3. `$ phantomjs rasterize.js http://localhost:6060/ output.png`
=> good screenshot

1. checkout latest code from `next`
2. npm i, npm run compile, npm start
3. `$ phantomjs rasterize.js http://localhost:6060/ output.png`
=> empty page

By repeating this for every commit in beta15 I have found that the problem is introduced by a change somewhere in the recent [markdown refactoring](https://github.com/styleguidist/react-styleguidist/commit/6683aa420b03fc3508cdef922fbc0bb3e5a014d7) commit.

**Comment by sapegin** [comment]
Maybe markdown-to-jsx itself has something that doesn’t work in PhantomJS. This kind of regressions are very annoying. Do you have any ideas how we can test that?

**Comment by sapegin** [comment]
Or maybe it’s [includes](https://github.com/styleguidist/react-styleguidist/commit/6683aa420b03fc3508cdef922fbc0bb3e5a014d7#diff-96aada9841909adde39d26f026ac7889R12)?

**Comment by sapegin** [comment]
What do you think about [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat)?

**Comment by n1313** [comment]
Sorry, I have no clue.

If you want to test compatibility with phantomjs, then you could take screenshots of the docs as a part of the test suite and compare them to a previous state (with backstopjs, for example).

**Comment by sapegin** [comment]
Sounds complicated ;-/ though we already try to run builds with PhantomJS to check if they work.

**Comment by n1313** [comment]
If you're talking about the tests/phantoms.js then as far as I understand it doesn't really check much except for making a successful http request to localhost.

**Comment by sapegin** [comment]
It will fail in case of JS error but that’s all it can ;-|

**Comment by n1313** [comment]
Well, it _is_ possible to make a better test for phantomjs compatibility, the question is -- is this needed? How big is this a priority for the project?

**Comment by sapegin** [comment]
At least to reduce number of bug reports from you ;-)

**Comment by sapegin** [comment]
OK eslint-plugin-compat is nice to have but it only found `fetch` in one of examples ;-£

**Comment by sapegin** [comment]
I’ve even tried to add something like `Chrome 11` to `browserslist` ;-?

**Comment by sapegin** [comment]
Nope, it’s not `includes`, then maybe something in the markdown-to-jsx…

**Comment by sapegin** [comment]
Yup, it was `includes` ;-?

**Comment by n1313** [comment]
I'm afraid phantom-js has its own set of ideas of things worthy of support, and does not match any other "real" browser. I have found it to behave closer to an IE10 or something like that, to be honest.

Thanks for the fix!

**Comment by sapegin** [comment]
Out in [5.0.0-rc.1](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.0.0-rc.1).
