### ISSUE TITLE
support Environment Variables

### ISSUE THREAD

**Issue by chrisdrackett** [styleguidist/react-styleguidist#352]
Trying to use `REACT_APP_*` as described here: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables and I can't seem to get them to work in the style guide. Any work arounds you know about?

**Comment by sapegin** [comment]
Which version of Styleguidist are you using? 4.x or 5.0.0 beta? I don’t have much experience with CRA so a [demo project](../blob/master/Issue_Template.md) would be very helpful to debug.

**Comment by chrisdrackett** [comment]
I'm on 5.0 beta. I'll look into doing a demo project

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
