### ISSUE TITLE
Add auto-completion to code editor

### ISSUE THREAD

**Issue by pke** [styleguidist/react-styleguidist#355]
Since styleguidist already knows about a components props would it be hard to integrate a code-completion/suggestion feature to the example HTML editor? I mean if there is a pluggable solution out there.

**Comment by sapegin** [comment]
I think I’ve seen some auto completion implementation for CodeMirror but not sure it’d be easy to implement for our use case. Anyway feel free to experiment — sounds like a nice feature if it won’t make code more complicated ;-)

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this ;-)
