### ISSUE TITLE
Error parsing objects in example markdown

### ISSUE THREAD

**Issue by imathews** [styleguidist/react-styleguidist#359]
First of all, thank you for this wonderful tool; it's really helped our component development process.

I'm running into an issue where colons in my readme.md are tripping up the parser:   

![screen shot 2017-03-16 at 1 34 22 pm](https://cloud.githubusercontent.com/assets/5659375/24017451/5306174a-0a4d-11e7-8223-75e1879b9322.png)

This works as expected when I populate the object using non-colon syntax:    

![screen shot 2017-03-16 at 1 34 37 pm](https://cloud.githubusercontent.com/assets/5659375/24017473/6f6524c6-0a4d-11e7-8ab4-6fa706610ad9.png)

Also, as a less critical note, it seems that missing semicolons also trips up the parser:   

![screen shot 2017-03-16 at 1 37 13 pm](https://cloud.githubusercontent.com/assets/5659375/24017548/bb18aa78-0a4d-11e7-89cd-b58c91a46173.png)

I'm on Webpack `2.2.1`, Styleguidist `5.0.0-rc.1` (though I tried on `beta.13` and `beta.15` as well). See below for my styleguidist config:
```js
{
	components: `${__dirname}/javascripts/@(containers|components)/**/index.jsx`,
	skipComponentsWithoutExample: true,
	serverPort: 9000,
	require: [
		`./javascripts/helpers/logger.js`,
		`./stylesheets/index.styl`,
		`./stylesheets/styleguidist.styl`,
	],
}
```

**Comment by n1313** [comment]
I've seen this behavior when missing a semicolon on a statement that directly precedes some JSX breaks the example, too.

**Comment by sapegin** [comment]
The first snippet:

```jsx
const a = { b: 42 };
<Foo a={[a]}></Foo>
```

I think @kof has this issue before but we couldn’t find a way to fix it. This is something weird.

The second snippet:

```jsx
const a = 42
<Foo a={a}></Foo>
```

Looks like this is correct behavior. Both [Buble](https://buble.surge.sh/#const%20a%20%3D%2042%0A%3CFoo%20a%3D%7Ba%7D%3E%3C%2FFoo%3E) and [Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=const%20a%20%3D%2042%0A%3CFoo%20a%3D%7Ba%7D%3E%3C%2FFoo%3E%0A) show an error, so it’s not in Styleguidist somewhere.

**Comment by imathews** [comment]
Thanks @sapegin. Second snippet is no big deal, more of an FYI for others. The first snippet is definitely a pain for us; is there anything I can do / provide to help to better debug?

**Comment by sapegin** [comment]
The problem with the first snippet is that I can’t reproduce the error:

![](http://wow.sapegin.me/3z1D081m1f2U/Image%202017-03-17%20at%207.36.04%20PM.png)

If could make a demo as [described here](../blob/master/Issue_Template.md) that would be awesome.

**Comment by imathews** [comment]
I went ahead and forked the repo and tried to reproduce in the basic example, and I can't for the life of me get it to reproduce the error... even after making my webpack and styleguide configs identical, and installing the same dependencies... (obviously missing something, but I tried).

_However_, I have been able to isolate this error in my own project; the issue boiled down to the webpack.config.js `resolve.modules`. In my project, I have 
```js
resolve: {
    modules: [
        `${__dirname}/node_modules`,
    ],
}
```
If I comment out this block, everything works fine. I don't really have any idea _why_ this is happening, but maybe can help us to better diagnose.

**Comment by sapegin** [comment]
Looks like you have different versions of Buble in you dependencies. What `npm list buble` says?

**Comment by imathews** [comment]
```
npm list buble
redivis-assets@1.1.56 /Users/ian/dev/redivis/assets
└─┬ react-styleguidist@5.0.0-rc.1
  └── buble@0.15.2 
```

Which is the same result that I get when running `npm list buble` in my fork of react-styleguidist/examples/basic, which is working fine...

**Comment by sapegin** [comment]
Do you have anything in `ls -a node_modules/buble/node_modules`? My only guess that one of dependencies of your project has older version of one one of Buble’s dependencies, and when you modify module resolution in your webpack config Buble receives this older version from the root `node_modules` instead of `node_modules/buble/node_modules`.

**Comment by imathews** [comment]
Yup that was it — specifically an old version of `acorn` was required by `jade@1.11.0` and was installed at the top of `node_modules`. Jade was an old dependency that we weren't even using, so that was a quick fix, though I would've expected npm to handle this properly...

**Comment by n1313** [comment]
Impressive!

**Comment by sapegin** [comment]
npm handles this when you don’t override the default behavior in webpack config ;-)

**Comment by fdaciuk** [comment]
@imathews did you solve it? Could you share what did you do? =)

**Comment by n1313** [comment]
@fdaciuk I would guess he removed the unneeded dependency from his project and pruned/updated node_modules.

**Comment by fdaciuk** [comment]
Thanks @n1313! I'm overriding the default webpack behavior, and that is the cause of my issue :|

**Comment by imathews** [comment]
@fdaciuk — yea I ended up being to solve this pretty quickly by removing the dependency that was requiring the old version of acorn. You can try an `npm ls` to get a sense of what might be requiring the old version of acorn. You'll also want to empty node_modules and rerun `npm install`
