### ISSUE TITLE
How to use external libraries in README.MD examples?

### ISSUE THREAD

**Issue by inferusvv** [styleguidist/react-styleguidist#360]
I have my own component and external inside (Recharts in this example)

In project I write:

`import { LineChart, Line } from 'recharts';`

How to add this import to README.MD file? I am getting `ReferenceError: LineChart is not defined`.
I've tried to add library as entry point, but it doesn't work and I still getting `ReferenceError`

**Comment by n1313** [comment]
Try adding recharts to your styleguidist config: https://github.com/styleguidist/react-styleguidist/blob/next/docs/Configuration.md#require

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you have more questions.

**Comment by eduardoinnorway** [comment]
Confirm that require in webpack config works for external libraries
