### ISSUE TITLE
Change default Port Number

### ISSUE THREAD

**Issue by zz-james** [styleguidist/react-styleguidist#366]
For some reason port 6060 seems unreachable on my server (but 3000 works for example when I run using create-react-app script) since I probably wont run both together is it possible to change the 6060 to 3000 since I know at least that port is working. I looked around in the config and searched through folders but can't see where the port number is set. 
many thanks

**Comment by zz-james** [comment]
found in 
 react-styleguidist/scripts/schemas/config.js

**Comment by sapegin** [comment]
We also have nice docs: https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#serverport — no need to search in the code ;-)

**Comment by zz-james** [comment]
Thanks - that's the nicest RTFM reply I've had 👍
