### ISSUE TITLE
Help Wanted : running styleguidist (in development) on shared http server

### ISSUE THREAD

**Issue by zz-james** [styleguidist/react-styleguidist#367]
I have an react app created with create-react-app on our linux http server and when I run the development server (using npm start) this works fine on the domain at port 3000.

However I can't seem to get react-styleguidist dev server to launch in a way that is access able to the outside world, the project runs and there is no errors but the server is not accessible at 6060.

At first I thought this was due to the port number - but changing the port number to 3000 (which works for react script that was installed by create-react-app) it still doesn't work.

I checked to see what the difference between the two was using netstat and the result is

root@ws1:~# netstat -an | grep 3000 | grep -i listen
tcp6       0      0 :::3000                 :::*                    LISTEN

root@ws1:~# netstat -an | grep 6060 | grep -i listen
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN  <-- this one isn't available

I have a feeling this is a simple enough configuration change in the server configuration but as I am new to node.js (and don't have a lot of time!!) I was wondering if someone knew what I needed to change to make the app accessible?

Many Thanks
James

**Comment by sapegin** [comment]
Try to change `serverHost` to `0.0.0.0`.

**Comment by zz-james** [comment]
This works.

THANK YOU
