### ISSUE TITLE
Locating markdown via doclet tag: @example, isn't working anymore.

### ISSUE THREAD

**Issue by KatGr** [styleguidist/react-styleguidist#370]
Hi,
I just updated to the latest version of react-styleguidist but now it  can't find markdown files using doclet tags anymore. It worked perfectly fine before the update and I didn't change a thing :/

It only shows "Add example to this component".

My doclet comment looks like this:

```
 /**
  * Some basic-card.
  *
  * @example ./../doku/Card.md
  */
```
It also prints the "Some basic-card".

Was there any change for doclets or is it just not working anymore?

**Comment by sapegin** [comment]
It’s obviously a bug ;-)
