### ISSUE TITLE
Unable to access styleguide outside of local machine

### ISSUE THREAD

**Issue by green-arrow** [styleguidist/react-styleguidist#373]
In `scripts/schema/config.js`, the default `serverHost` is set to `localhost`. When using this host with express, it means that only the local machine can access the site. If users want to connect from another device, like a phone or a table, to test the style guide, they are unable to unless setting the `serverHost` manually to `0.0.0.0`.

Is this a case where the default should be changed to `0.0.0.0` to accommodate this use case, or should it just be left up to the user?

**Comment by sapegin** [comment]
Chrome had issues with this but looks like it works fine now, so we could change it.
