### ISSUE TITLE
Components don't display in IE10

### ISSUE THREAD

**Issue by chardos** [styleguidist/react-styleguidist#375]
I'm trying to view my styleguide in IE10 to make sure everything displays correctly however I'm seeing this:

![image](https://cloud.githubusercontent.com/assets/4082442/24732779/723a62be-1ab6-11e7-92bb-0fb414cd055d.png)

Not sure of the root cause, will have to investigate at some point.

**Comment by sapegin** [comment]
I’m not sure [Buble](https://buble.surge.sh/) supports it. We’re officially support (at least we try ;–) IE11 but pull requests to improve support are welcome ;-)

**Comment by chardos** [comment]
No worries
