### ISSUE TITLE
What is version 4.7.0?

### ISSUE THREAD

**Issue by MoOx** [styleguidist/react-styleguidist#378]
I were currently using `^4.6.3` in my package.json. I saw that 5.x is out but don't want to upgrade yet (time). I used `yarn upgrade` this morning and see that styleguidist is now not happy with my config, like if I were using 5.x...
I cannot find in releases/changelog a reference this version. Is this normal that a minor version brings breaking change?

**Comment by sapegin** [comment]
It was a mistake and I immediately unpublished this version, so yarn shouldn’t offer this version for upgrade. 4.7.0 was identical to 5.0.0.

**Comment by MoOx** [comment]
How I ended up being able to have it?

**Comment by sapegin** [comment]
Maybe you were unlucky to update before it was unpublished. Could you reproduce it now?

**Comment by sapegin** [comment]
Looks like unpublishing doesn’t work ;-(

**Comment by sapegin** [comment]
Now it’s unpublished.
