### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by kulakowka** [styleguidist/react-styleguidist#380]
I updated the react to version 15.5.0 and saw an error in the console:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

We need to update components to use [prop-types](https://www.npmjs.com/package/prop-types) package. More info in official blog: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

```javascript
// Before (15.4 and below)
import React from 'react';

class Component extends React.Component {
  render() {
    return <div>{this.props.text}</div>;
  }
}

Component.propTypes = {
  text: React.PropTypes.string.isRequired,
}

// After (15.5)
import React from 'react';
import PropTypes from 'prop-types';

class Component extends React.Component {
  render() {
    return <div>{this.props.text}</div>;
  }
}

Component.propTypes = {
  text: PropTypes.string.isRequired,
};```

**Comment by handonam** [comment]
With the update to using the `PropTypes` package, this also leads to the documentation showing "custom" in the "type" field, and nothing in the "default" field.  At least for me anyway.

**Comment by sapegin** [comment]
@kulakowka Would you mind sending a pull request? ;-)

@handonam You mean updating in your components, not in Styleguidist itself (this issue is about Styleguidsit’s component but thanks for mentioning it anyway ;–)

**Comment by kulakowka** [comment]
@sapegin yes, i can do it
