### ISSUE TITLE
Example of "Editor Alias" for ```example code fence?

### ISSUE THREAD

**Issue by motleydev** [styleguidist/react-styleguidist#382]
The title more or less explains it, I know this is not an issue with the package, but I was curious if you had more information on how to alias an editor's code fence syntax to javascript? So that when I add the \`\`\`example I get \`\`\`javascript ~~(omitting the third tick for obvious reasons)~~ :)

I am specifically using Visual Studio Code but maybe there's a generic abstraction that explains how to do this?

Thanks!

**Comment by sapegin** [comment]
I’ve never tried it personally ;-/

**Comment by sapegin** [comment]
In [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0-beta.1) (now in beta) you can you use `js`, `jsx` or `javascript` languages with fenced code blocks for interactive examples.
