### ISSUE TITLE
Render preview in Iframe

### ISSUE THREAD

**Issue by stepancar** [styleguidist/react-styleguidist#384]
For some components we need to render component in iframe to demostrate responsibility, body styles loader. For example, page component or maybe footer/header.
For this case wee need to load component and it dependencies (styles and another components).
I tried to wrap your Preview with own implementation which just render to ifrme, but styles loaded in parent window context, but i need to loade it to iframe.
Could you help me please

**Comment by kulakowka** [comment]
https://github.com/ryanseddon/react-frame-component

**Comment by stepancar** [comment]
@kulakowka, I already tried this component, but it not allow to use any styleloader

**Comment by kulakowka** [comment]
@stepancar try to use [JSS](https://github.com/cssinjs/jss) %)

**Comment by stepancar** [comment]
@kulakowka, it's not a solution for common task, cause not all developers can switch their components to jss. As I understand , more right, and more complex solution is build preview scripts separately to static and load it in iframe

**Comment by okonet** [comment]
@stepancar you can create your own Preview component and use it with SG: https://github.com/styleguidist/react-styleguidist/blob/master/examples/customised/styleguide.config.js#L51

**Comment by sapegin** [comment]
I’d try to avoid iframes ;-) 

![](http://wow.sapegin.me/0509270m1y0L/Screen%20Recording%202017-04-12%20at%2010.14%20AM.gif)
