### ISSUE TITLE
Better copy for the empty state message

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#387]
Right now, if SG wasn't able to locate components at the provided paths, it will try to locate them in the default path. If this also fails, the empty message will be displayed saying:

`We couldn't find any components defined in your style guide config or using the default pattern src/components/**/*.js.`

I believe this is a bit confusing since it displays only the default path explicitly. This made me think my config wasn't read by SG. Reading the whole message carefully explained it but I think this can be improved by showing the list of all paths where SG was trying to locate components:

```
We looked at following paths:
- [path 1 from user config]
- [path 2 from user config]
- [fallback default path]
but couldn't find any components. Please make sure you have your components there and try again.
```

**Comment by sapegin** [comment]
Yeah, that was the plan, just didn’t have time to implement it yet ;-) It won’t use the default value if you have your own patterns in the config.

**Comment by okonet** [comment]
So this means the message is even more confusing then :)

**Comment by sapegin** [comment]
Yeah 😬

**Comment by sapegin** [comment]
Call it MVP ;-)

**Comment by KumarKelashMeghwar** [comment]
I have the same error issue. How to make it work? I have added --config config/styleguidist.config.js but still getting same I dont know wh
![Screenshot (80)](https://user-images.githubusercontent.com/58991510/178105493-0a3cee7e-e788-4ae4-8378-640bc59813c9.png)
y

`this is my config file


        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: "babel-loader",
        },
      ],
    },
  },
};

`
