### ISSUE TITLE
Support for flowtype exact object notation

### ISSUE THREAD

**Issue by joris974** [styleguidist/react-styleguidist#390]
I receive a parsing error when using the [exact object notation](https://flow.org/en/docs/types/objects/#toc-exact-object-types) in my props types in Flow.

```js
/* @flow */

import React from "react"

type Props =
  {| foo: string |}

class Foo extends React.Component<void, Props, void> {
  render() {
    return "test"
  }
}
```
The error I receive when running `styleguidist server` is 
```
Error when parsing foo.js: SyntaxError: Unexpected token (6:3)
```
It works like a charm when removing the exact object notation:
```js
type Props =
  { foo: string }
```

Is there a special config to make this work with the exact object notation?

**Comment by sapegin** [comment]
I’m afraid [react-docgen](https://github.com/reactjs/react-docgen) doesn’t support it, try to file an issue there.
