### ISSUE TITLE
Support @param in props description

### ISSUE THREAD

**Issue by ankri** [styleguidist/react-styleguidist#393]
I was looking for a solution to have `@param` support in my props description, not only in public methods. My use case is that I want to document the parameters of my `PropType.func` props so the user of my component can see the arguments I will pass along to the function he provides.

Sadly react-docgen does not apply any specific treatment to the docblock of propTypes. [react-docgen#141](https://github.com/reactjs/react-docgen/issues/141). That's why you have to write your own parser for that.

I have a solution [here](https://github.com/ankri/react-styleguidist/tree/props-with-tags/examples/customised)

I added a custom [propsParser](https://github.com/ankri/react-styleguidist/blob/props-with-tags/examples/customised/styleguide.config.js#L49) and [PropsRenderer](https://github.com/ankri/react-styleguidist/blob/props-with-tags/examples/customised/styleguide/components/PropsRenderer.js#L186) to the `customised` example.

Code:
```javascript
/**
 * Gets called when the user clicks on the button
 *
 * @param { SyntheticEvent } event The react synthetic event
 * @param { Array } allProps All the props of Button
 */
onClick: PropTypes.func,
```
Output:
![image](https://cloud.githubusercontent.com/assets/2842920/24984062/6d3b624c-1feb-11e7-92e0-74d13f35dac3.png)

It should be trivial to add other tags like `@return`, `@see` or `@deprecated`.

---

I want to give back to this awesome project and I'm sure some people would benefit from this functionality. What should I do? Open a PullRequest? Create a new example? Add the code snippets to the `Cookbook.md`?

I would love to see `@param` support in the default version of the styleguidist but you would need the custom `propParser` for that and I do not know whether replacing the propsParser is the right way. You could also run `doctrine` on the `props.description` inside the `PropsRenderer` but that would be kind of ugly in my opinion. What do you guys think?

**Comment by sapegin** [comment]
I think it’d be a good feature! We already do some description parsing [here](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/utils/getProps.js#L37) so I’d start there ;-)

**Comment by okonet** [comment]
@sapegin that's a lot of copy-paste. Should we include it by default?

**Comment by ankri** [comment]
Thanks to @sapegin's tip I am working on a PR right now.

So far I have implemented support for
- [X] `@param`
- [X] `@deprecated`
- [ ] `@see`

Do you have suggestions for other [tags](http://usejsdoc.org/)?

**Comment by sapegin** [comment]
@okonet That’s exactly what I’m suggesting ;-)

**Comment by sapegin** [comment]
And I’ve pointed you to a wrong place, it should be [here](https://github.com/styleguidist/react-styleguidist/blob/32345a0b4bac346acec8d9cfa05a7d8f1b14760b/loaders/utils/getProps.js#L48-L58) ;-)

**Comment by sapegin** [comment]
This was released in [5.2.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.2.0).

**Comment by einarlove** [comment]
Why was `@return` not included in this feature?

**Comment by ankri** [comment]
I forgot to add `@return` on `props`, my bad.  Public methods do support `@return`.

A PR has been created that adds `@return` for props: #684
