### ISSUE TITLE
Q: contextTypes

### ISSUE THREAD

**Issue by kevinfez** [styleguidist/react-styleguidist#396]
react-docgen has a [pull request](https://github.com/reactjs/react-docgen/pull/130) about parsing contextTypes, but I was wondering if this project has any plans to parse them on its own or would wait for react-docgen to officially support it.

contextTypes snippet for fun:

```js
MyComponent.contextTypes = {
    /** some super detailed description, that doesn't show up */
    myFunc: PropTypes.func,
};
MyComponent.propTypes = {
    /** some super detailed description, that does show up */
    myPrimitive: PropTypes.string,
};
```

**Comment by sapegin** [comment]
No, we’re not parsing code and relying on react-docgen for 95% of hard work. So I’d wait for this PR and then send a PR to Styleguidist ;-)

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen or send a PR when react-docgen is merged ;-)
