### ISSUE TITLE
Using `import()` in a component produces parse / syntax errors

### ISSUE THREAD

**Issue by kohlmannj** [styleguidist/react-styleguidist#397]
- Your style guide config: [`styleguide.config.js`](https://github.com/nytpi/styleguidist-v5.0.6-webpack-dynamic-import-parse-error/blob/master/styleguide.config.js)
- Webpack version: 2.4.1
- Styleguidist version: 5.0.6
- Operating system, browser and version: macOS Sierra 10.12.4, Safari 10.1
- Reproducible demo: [nytpi/styleguidist-v5.0.6-webpack-dynamic-import-parse-error](https://github.com/nytpi/styleguidist-v5.0.6-webpack-dynamic-import-parse-error)

When running `yarn run start` with the demo repo, I see the following output:

<details>
<summary><code>yarn run start</code> error messages</summary>

```bash
$ yarn run start
yarn run v0.23.2
$ styleguidist server
Style guide server started at:
http://localhost:6060


Error when parsing lib/components/Button/Button.jsx: SyntaxError: 'import' and 'export' may only appear at the top level (10:8)


Error when parsing lib/components/RandomButton/RandomButton.jsx: SyntaxError: Unexpected token (25:30)

Compiled successfully!
```
</details>

–

When viewing the styleguide in-browser, the two components using `import()`, `<Button>` and `<RandomButton>` do not appear in the styleguide.

–

This problem does not occur when using `System.import()`, but my understanding is that Webpack now prefers `import()`, so I'd like to convert these usages in my (internal) component library.

**Comment by sapegin** [comment]
Looks like [react-docgen](https://github.com/reactjs/react-docgen) doesn’t support it, try to file an issue there.
