### ISSUE TITLE
Error parsing files containing template string literals with interpolation

### ISSUE THREAD

**Issue by forabi** [styleguidist/react-styleguidist#398]
Using interpolation in template string literals (for things like theming in `styled-components`) produces the following error:

```
Compiling…

Error when parsing src/components/Button/index.tsx: SyntaxError: Unexpected token (6:34)
```

Removing the interpolation fixes the issue but it prevents theming the component.

Webpack version: 2.3.3
`styleguide.config.js`:

```js
module.exports = {
  components: 'src/components/**/*.ts*',
};
```

Example file:
```ts
import * as React from 'react';
import styled from 'styled-components';

const RoundedButton = styled.button`
  border: 2px solid transparent;
  margin: ${props => (props.theme as Theme).formControlMargin};
  border-radius: 25px;
  padding: 0.5rem 1rem;
  text-transform: uppercase;
  text-align: center;
  background-image: linear-gradient(to right, #F06664 0%, #e82669 100%);
  color: white;
  cursor: pointer;
`;

type Props = {
  icon?: JSX.Element;
} & React.HTMLAttributes<HTMLButtonElement>;

const Button = ({ icon, children, ...rest }: Props) => {
  return (
    <RoundedButton {...rest}>
      {icon}
      {children}
    </RoundedButton>
  );
};

export default Button;

```

**Comment by n1313** [comment]
RSG only supports components that can be parsed by [react-docgen](https://github.com/reactjs/react-docgen). As far as I can see, it does not support typescript (and [doesn't plan to](https://github.com/reactjs/react-docgen/issues/67)), and I am not sure if they support tagged template literals.

**Comment by forabi** [comment]
As far as I understand, RSG uses the Webpack pipeline so components are first transpiled to JS by Webpack and only then they are processed by RSG. Some TS components are already listed in my RSG. Only those with template strings cannot be processed.

**Comment by sapegin** [comment]
No, react-docgen works with source files. You should use [react-docgen-typescript](https://github.com/pvasek/react-docgen-typescript).

**Comment by forabi** [comment]
@sapegin So how come some TS components are parsed and displayed in my styleguide? That's weird.

**Comment by sapegin** [comment]
Rendering components (webpack) is not the same as parsing sources for props documentation (react-docgen).
