### ISSUE TITLE
Requires/Imports in Markdown

### ISSUE THREAD

**Issue by stinoga** [styleguidist/react-styleguidist#400]
What is the best way to use `require` or `import` in section markdown files?

We have sections in our style guide that use CSS modules, which we need to import to use, for example:

**markdownFile.md**
```
import l from '../../common/style/layout.css';

<div className={l.class}>
```
FYI, we aren't on v5 yet. Using the latest v4 version.
Thanks!

**Comment by sapegin** [comment]
You can only use `require` in examples: https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md#writing-code-examples

**Comment by SerdarSanri** [comment]
@sapegin I am not sure why this issue is closed. The example link you posted also refers to using imports but using imports in examples throws `"import is not supported (1:0)"` error.

**Comment by sapegin** [comment]
Imports _are_ supported in 9.0.0.
