### ISSUE TITLE
Broken link in Documenting.md

### ISSUE THREAD

**Issue by kohgpat** [styleguidist/react-styleguidist#407]
Hello, I just found broken link in Documenting.md (https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md) file in the repo.

> Note: See examples of documented components in our demo style guide.

To be exactly "See examples" link in this quote.

Thank you for the project!

Sincerely,
Nikolay.

**Comment by sapegin** [comment]
Thanks, fixed!

Please submit a pull request right away next time — it’s faster then filing an issue ;-)
