### ISSUE TITLE
Add Server restart warning when no Readme.md file is present

### ISSUE THREAD

**Issue by SaraVieira** [styleguidist/react-styleguidist#408]
Issue:

When I am creating a new component and no Readme.md file is present it gives me the warning to create a file but then when I do I need to restart the server for it to work.

Maybe adding a message telling the person to restart would be great

**Comment by sapegin** [comment]
Would you mind sending a pull request? ;-)

**Comment by SaraVieira** [comment]
https://github.com/styleguidist/react-styleguidist/pull/409 💃

**Comment by sapegin** [comment]
See it already — awesome! 👾

**Comment by SaraVieira** [comment]
@sapegin What do you think about adding jest test to the lintstaged ?

**Comment by sapegin** [comment]
How would that work? lint-staged works only with changed files — does Jest support that?

**Comment by SaraVieira** [comment]
I found this article about it: 
https://benmccormick.org/2017/02/26/running-jest-tests-before-each-git-commit/

It totally works:
https://www.dropbox.com/s/0nm6f764amgj1wu/Screenshot%202017-04-25%2020.27.38.png?dl=0

**Comment by sapegin** [comment]
That’s interesting! If it’s fast enough we may try to add it: make sense for open source.

**Comment by SaraVieira** [comment]
I can add it and you test it , for small changes it's pretty fast :)

**Comment by sapegin** [comment]
Deal ;-)
