### ISSUE TITLE
jss-isolate vs theming

### ISSUE THREAD

**Issue by timsnadden** [styleguidist/react-styleguidist#410]
It appears that jss-isolate is clobbering the theming functionality. I modified the 
[basic example](https://github.com/timsnadden/react-styleguidist/tree/jss-isolate-issue) and added a base colour and font to the styleguidist config.

```
	...
	theme: {
		base: 'pink',
		font: 'Papyrus',
	},
	...
```

The font is being applied but the colour is being overridden by jss-isolate to use `color: initial`.

**Comment by timsnadden** [comment]
For my own project I forked react-styleguidist to use jss with [jss-preset-default](https://github.com/cssinjs/jss-preset-default). This doesn't include jss-isolate.

**Comment by sapegin** [comment]
We need jss-isolate so it’s not an option. We just need to use color explicitly everywhere.

**Comment by timsnadden** [comment]
`fontFamily: 'inherit'` is added to the jss setup. One option is to also add `color: 'inherit'`. If this breaks the intended isolation model of jss-isolate then fontFamily should probably be pulled out of there and added explicitly to each rsg component as well. I see that a new version of jss-isolate has just been released too so `setupjss.js` could be updated to remove the customisations.

**Comment by sapegin** [comment]
`font-family` inheritance was added to pass `font-family` from `body` to user’s components. We shouldn’t rely on style inheritance in Styleguidist UI.

**Comment by sapegin** [comment]
So there are to separate issues:

* Ability to pass some styles (like `font-family`) from `body` to user’s components.
* Isolation of Styleguidist UI from any user styles.

**Comment by timsnadden** [comment]
See #418

**Comment by sapegin** [comment]
Out in [5.1.9](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.1.9).
