### ISSUE TITLE
Module not found: Error: Can't resolve 'markdown-to-jsx'

### ISSUE THREAD

**Issue by kulakowka** [styleguidist/react-styleguidist#413]
Today I started the styleguidist and got an error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'markdown-to-jsx' ...
```
This probably happened because of the [markdown-to-jsx package update to 5.3.0](https://github.com/probablyup/markdown-to-jsx/releases)

I was able to fix the problem by installing the package in my project

```
npm i markdown-to-jsx@5.2.0
```

However, this should not be considered as a solution.

------

About my package.json:
```json
"react-styleguidist": "5.1.1",
```

**Does anyone have a similar error?**

**Comment by n1313** [comment]
Yep, markdown-to-jsx v5.3.0 is broken: https://github.com/probablyup/markdown-to-jsx/issues/104.

**Comment by sapegin** [comment]
Let’s wait for this PR: https://github.com/probablyup/markdown-to-jsx/pull/105

If they won’t merge it today, I’ll fix the previous version in our dependencies.

**Comment by sapegin** [comment]
~~Hacked~~ temporarily fixed in [5.1.6](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.1.6).

**Comment by ryosuke-hujisawa** [comment]
how about hisi ?

```
npm install markdown
import Markdown from 'markdown';
```

**Comment by u1810291** [comment]
I have tried the above suggestions and deduced that after running a command
> npm install markdown
and importing from 
> import ReactMarkdown from 'markdown';
it finally worked for me
