### ISSUE TITLE
[question] How to require webpack config if it's in ES6?

### ISSUE THREAD

**Issue by varya** [styleguidist/react-styleguidist#419]
My webpack config is written in ES6. I require it in `styleguide.config.js` as the documentation suggests. But this give an error when running:

```
  › npm run styleguide

> varya.me@2.0.0 styleguide /Users/varya/WebDev/Personal/varya.github.com
> styleguidist server

/Users/varya/WebDev/Personal/varya.github.com/src/config/webpack.js:1
(function (exports, require, module, __filename, __dirname) { import { join } from 'path'
```

What is the right way to require ES6 webpack config?

**Comment by sapegin** [comment]
I’d suggest you to rewrite it without `import`s. Most of other ES6 features are supported by Node 6+.

**Comment by sapegin** [comment]
[babel-register](https://babeljs.io/docs/usage/babel-register/) in style guide config should work too but I haven’t tried it.

**Comment by varya** [comment]
I tried `es6-require`. It works. But not sure if it can be officially recommended. Anyways, I guess issue can be closed. Thank you :-)

**Comment by sapegin** [comment]
The recommended way is rewriting ;-)

> Note: Babelified webpack configs (like webpack.config.babel.js) are not supported. We recommend to convert your config to native Node — Node 6 supports many ES6 features.
