### ISSUE TITLE
Help with building

### ISSUE THREAD

**Issue by stepancar** [styleguidist/react-styleguidist#420]
Hello!
I can't install project dependencies
error An unexpected error occurred: "https://registry.yarnpkg.com/@semantic-release/condition-travis/-/condition-travis-5.0.2.tgz: Request failed \"404 Not Found\"".
The same with npm.
Maybe you know what's happening? 
Whats's yarn/ npm/ node you use?
what's registry you use?

**Comment by sapegin** [comment]
What exactly are you doing?

**Comment by stepancar** [comment]
@sapegin
$ yarn
or
$ npm i

**Comment by sapegin** [comment]
Where? In the `master` branch?

Just did 

```
rm -rf node_modules
yarn
```

works fine.

**Comment by sapegin** [comment]
And I can download file from your error message so it’s most probably network issues or something was wrong with npm.

**Comment by stepancar** [comment]
I can download it too by direct link
Hm, looks like i faced with the same issue
 https://github.com/yarnpkg/yarn/issues/2738

**Comment by sapegin** [comment]
Yeah, looks like a Yarn issue. Not sure we can do anything on our side ;-(

**Comment by stepancar** [comment]
@sapegin, thank you!
