### ISSUE TITLE
Upgrade jss-isolate to v3.0.0

### ISSUE THREAD

**Issue by lukehedger** [styleguidist/react-styleguidist#427]
Dependency `jss-isolate@2.0.1` is causing a Yarn warning:

```
warning "jss-isolate@2.0.1" has incorrect peer dependency "jss@^6.0.0".
```

v3.0.0 of `jss-isolate` depends on `jss@^7.0.0`, which should fix the warning.

Happy to submit PR if no unintended consequences expected.

**Comment by sapegin** [comment]
Yeah, it wasn’t yet published when I did update to JSS 7. PR will be good of course but it’s a bit more complicated, ideally:

1. Update jss-isolate to 3.0.0 (it’s not used anywhere in the code now, see 2).
2. Remove [our fork](https://github.com/styleguidist/react-styleguidist/tree/master/src/styles/jss-isolate) (but keep in mind that the list of non-inherited properties was removed from jss-isolate, so we need to keep a list from our fork)
3. Try [jss-increase-id-specificity](https://github.com/iamstarkov/jss-increase-id-specificity), it should solve issues like the hide code button on [this style guide](https://react.feedly.com/).

I’ll be happy to merge pull request(s) for any of these ;-)

**Comment by kof** [comment]
> but keep in mind that the list of non-inherited properties was removed from 

I never published the version non-inherited props list, I guess you started using it from the master. 

Also I will soon work on the next version of jss-isolate which will bring them back in a better quality using a database + isolation against cascades.

**Comment by sapegin** [comment]
> I never published the version non-inherited props list, I guess you started using it from the master.

That’s exactly what I said ;-)
