### ISSUE TITLE
Indent sub components in menu?

### ISSUE THREAD

**Issue by eduardoinnorway** [styleguidist/react-styleguidist#428]
Just started and really like the setup, but I have a huge amount of components so I have grouped them, for example

-Header
--Logo
--Toggle
-Foo

Is there a way to make the menu indent automatically for my subcomponents with some decorator or something? Would be cream on the top of one could add a toggle also :)

**Comment by n1313** [comment]
There is no toggle but you may want to use [sections ](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Components.md#sections) for grouping.

**Comment by sapegin** [comment]
And you can generate sections based on folders.

**Comment by eduardoinnorway** [comment]
Thanks, this actually solves the issue, just make more sections and group more.
