### ISSUE TITLE
webpack dependecy issue

### ISSUE THREAD

**Issue by Sashkan** [styleguidist/react-styleguidist#439]
I'm using ```react-create-app```. As mentionned in the documentation, I installed StyleGuidist using 

```
npm install --save-dev react-styleguidist webpack@1`

```
When starting the StyleGuide server, I get the following critical error:
```
webpack.validateschema is not a function
```

Server immedialty crashes. I thought it might come from webpack somehow missing, so I used the other way around:

```
npm install --save-dev react-styleguidist react react-dom webpack
```

which raises the following non-critical error:
```
Uncaught ReferenceError: Invalid left-hand side in assignment
```
Which apparently comes from these lines in the module:
``` js
if (typeof !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()).ensure !== 'function') {
	!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()).ensure = function (d, c) {
		return c(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
	};
}
```
Now the 2nd error is not critical, server keeps running, but only render a blank page. Did I miss something ? I'm using the Typescript addon, config seems to be fine.

**Comment by sapegin** [comment]
How are you installing CRA with TypeScript? Could you help me reproduce it?

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more data.
