### ISSUE TITLE
position: relative causes component position to be wrong

### ISSUE THREAD

**Issue by magicmark** [styleguidist/react-styleguidist#441]
Hi, thanks for this awesome project!

I'm writing a hovercard component that uses absolute positioning. When rendering it in a styleguidist example, the component breaks, because it takes its initial position values from a parent div with `position: relative` specified. (http://i.imgur.com/Q4iwmIT.png)

Any suggestions as to how to get around this? Thanks again!

(To give more context, here's what it looks like 'broken': http://i.imgur.com/UCwxeKd.png. You can see the offset is being calculated from the parent div, rather than the body as expected.)

**Comment by sapegin** [comment]
I think we could get rid of `position: relative` as soon as we finish #426.

**Comment by sapegin** [comment]
Should be fixed in [5.4.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.4.0).
