### ISSUE TITLE
Documenting pure functions and utilities

### ISSUE THREAD

**Issue by Giulico** [styleguidist/react-styleguidist#445]
Hello,
I'm using this tool since a couple of day and I really like it! :) 

Trying to keep my project as "functional" as possible, I tend to use many pure functions. I wonder if there's a way to document those pure functions with react-stylguidist.

I noticed the waring in my console:
`Warning: app/assets/js/shared/utils.js matches a pattern defined in ”components” or “sections” options in your style guide config but doesn’t export a component.`

Do I need to use two js documentation engines?

Thank you

**Comment by sapegin** [comment]
Styleguidist is not a JS documentation engine, now it works for react component. I’d recommend you to use something like [Documentation.js](http://documentation.js.org/) and include generated Markdown as a section in Styleguidist.

**Comment by kopax** [comment]
@sapegin I've just tried some test with the link you given documentation.js and it is satisfying for our use case.

I have one only probleme, with the `@example` within the JSdoc, for instance : 

```
/**
 * @public
 * Create the documentation configuration
 * @name createConfig
 * @param {Object} config for react-styleguidist user configuration
 * @param {Object} options for this extensions
 * @example
 * // returns config
 * createConfig({}, {});
 * @returns {Object} react-styleguidist configuration object
 */
```

I was expecting to just have markdown generated, instead I got this surprise: 

![image](https://user-images.githubusercontent.com/1866564/49271467-56065380-f4a0-11e8-951b-64480610c22e.png)

react-styleguidist is taking the generated markdown and try to run an example which can be a good if you I would know how to make it work by default.

- Is it possible to disable the live demo and just allow edition?
- Is it possible to add `createConfig` to global scope automatically?
- Is it possible for the non react doc to hide the preview if the return is null?
- Disable the feature for some functions

Thanks in advance.

**Comment by evrenakar** [comment]
> Styleguidist is not a JS documentation engine, now it works for react component. I’d recommend you to use something like [Documentation.js](http://documentation.js.org/) and include generated Markdown as a section in Styleguidist.

What do you plan to do about React hooks?

**Comment by kopax** [comment]
What do you mean?

**Comment by evrenakar** [comment]
How do i implement styleguidist when using react hooks?

**Comment by yutin1987** [comment]
I think we need reopen this issue, when it is hooks function, will get not component issues,
but hooks is a method in react component.

![螢幕快照 2020-04-25 下午4 08 04](https://user-images.githubusercontent.com/2505934/80274705-fea8f900-870e-11ea-809f-52c4f6919303.png)

**Comment by maclejean** [comment]
Documenting pure function and util js  is necessary,please

**Comment by laytong** [comment]
I have a workaround i'm using for now, but would prefer it auto picked up my hooks in the same way it does components 

in my config I added
```
{
    name: 'Custom Hooks',
    components: '<directory-to-hooks>/**/*.js',
},
```
And then co-located an *.examples.md file with examples that just import and use the hook
```jsx
import useToggle from './use-toggle.js';
const Component = props => {
    const [isOpen, toggle] = useToggle(false)
    return (
        <React.Fragment>
            <h1>this is {isOpen ? 'OPEN' : 'CLOSED'}</h1>
            <button onClick={toggle}>Toggle me</button>
        </React.Fragment>
    )
}
<Component />
```
