### ISSUE TITLE
Write examples in JavaScript/Typescript

### ISSUE THREAD

**Issue by marty-wang** [styleguidist/react-styleguidist#449]
It seems that the way to create examples is to embed example code in markdown files. I am wondering if it is possible to write examples in JavaScript/TypeScript. The benefit is that we can leverage type checking and  refactoring will be a lot easier.

**Comment by sapegin** [comment]
The only way to do it now is to `require` external files from Markdown but it’s ugly and style guide users won’t see the source.

This would be a nice to have feature if you have any ideas how that would look. Some related issues: #257, #269, #324.

**Comment by sapegin** [comment]
Actually #269 is about exactly this problem so let’s keep all discussion there.
