### ISSUE TITLE
Need to include components from another project

### ISSUE THREAD

**Issue by Nosherwan** [styleguidist/react-styleguidist#453]
we maintain our common components in another project, normally that is included via npm link in main projects.
I have created a project for react-styleguidist, now How can I include the common components in it.

**Comment by sapegin** [comment]
Could you elaborate what exactly you want to achieve? Do you want to use these component or do you want to show them in the style guide?

**Comment by Nosherwan** [comment]
I want to show them in the style guide that has its own project

**Comment by Nosherwan** [comment]
I want to show them in the style guide that has its own project.
I suppose instead of giving a static location via config like so:

```javascript

module.exports = {
	components: '../sws-ui-common/react/shared/components/**/*.js'
    }

```
I would like to provide the path via require or something along those lines:

```javascript

module.exports = {
//this wont work but just to explain
	components: require('../sws-ui-common/react/shared/components/**/*.js')
}

```

**Comment by sapegin** [comment]
That’s what I would try to do.

**Comment by Nosherwan** [comment]
so you are suggesting only the static location woulr work for components, and not dynamic?

**Comment by sapegin** [comment]
I don‘t know what you mean by static and dynamic location. Something like this should work:

```js
module.exports = {
	components: require.resolve('sws-ui-common').replace('index.js', '') + /react/shared/components/**/*.js'
}
```

**Comment by Nosherwan** [comment]
Tried that but I get the following error:
`Error: Cannot find module 'sws-ui-common'`
Seems like require.resolve && require are unable to find the npm linked module.

**Comment by sapegin** [comment]
I don’t really understand why you use npm links, for your use case installing an npm package from Git seems more appropriate. If nothing works you’d probably have to hardcode a path.

**Comment by Nosherwan** [comment]
No worries seems like hardcoding the path is the only solution for us at the moment. We do not publish our packages to npm, hence we use npm link to include them in other projects.

**Comment by sapegin** [comment]
You can install an npm package from Git, that’s what we do ;-) `npm link` is supposed to be used for testing only.

**Comment by tuchk4** [comment]
I am working with lerna and one of the packages is styleguidist and its configs.
I need to include components from dependencies. Like this
```js
{
  name: 'Inputs',
  components: [
    '@company/ui/src/components/TextInput/index.tsx',
    '@company/ui/src/components/NumberInput/index.tsx',
    '@company/ui/src/components/TextArea/index.tsx',
  ],
}
```

But this does not work. There are two solution to fix it

### 1.  Use require resolve

```js
{
  name: 'Inputs',
  components: [
      require.resolve('@company/ui/src/components/TextInput/index.tsx'),
      require.resolve('@company/ui/src/components/NumberInput/index.tsx'),
      require.resolve('@company/ui/src/components/NumberInput/index.tsx'),
  ],
}
```

### 2 Patch [src/loaders/utils/getComponentFiles.js](https://github.com/styleguidist/react-styleguidist/blob/34f3c83e769542157c72d0e055ad8850d22b6001/src/loaders/utils/getComponentFiles.js)

```diff
+ function getResolvedFiles(components) {
+   const rest = [];
+   const resolved = [];
+   components.forEach(component => {
+     const path = require.resolve(component);
+     if (path) {
+       resolved.push(path);
+     } else {
+       rest.push(component);
+     }
+   });
+ 
+   return  [resolved, rest];
+ }

module.exports = function getComponentFiles(components, rootDir, ignore) {
  if (!components) {
    return [];
  }

+ const [resolved, rest] = getResolvedFiles(components);

  // Normalize components option into an Array
-  const componentGlobs = getComponentGlobs(components);
+  const componentGlobs = getComponentGlobs(rest);

  // Resolve list of components from globs
  const componentFiles = getFilesMatchingGlobs(componentGlobs, rootDir, ignore);

+  return [...resolved, ...componentFiles];
-  return componentFiles;
};
```



First solution is more simple but not so expected as the second. 

Anyway developing with monorepo is very popular way now and thats why I suggest to add something like `Using with monorepo` section to docs.
