### ISSUE TITLE
Unknown plugin "transform-es3-member-expression-literals" 

### ISSUE THREAD

**Issue by eduardoinnorway** [styleguidist/react-styleguidist#454]
Updated my styleguidist and now I get, when I try to "yarn styleguide":

Module build failed: ReferenceError: Unknown plugin "transform-es3-member-expression-literals" specified in "/Users/foo/IdeaProjects/foo/node_modules/jss-default-unit/.babelrc" ..

**Comment by sapegin** [comment]
You have the same issue as #304:

1. Do not run Babel on `node_modules`.
2. I’ll send a PR to jss-default-unit to remove `.babelrc` for their package.
