### ISSUE TITLE
Using devtools with react-stylegudist

### ISSUE THREAD

**Issue by benedyktdryl** [styleguidist/react-styleguidist#456]
Hi, 

I know that `devtools` are ignored along with some other configuration keys.

**My question is:**

- Is there any particular reason for that? Is it breaking `react-stylegudist` entirely or there are some edge cases?
- Can we disable ignoring somehow or you will consider PR with disabling it optionally feature?
- Is there kind of recipe for having sourcemaps on development when using your library? 

Thanks for your time!

**Comment by sapegin** [comment]
For `devtools` it should not be necessary, so feel free to send a pull request ;-)

**Comment by benedyktdryl** [comment]
So I should go with optional disabling ignoring or I can just remove devtools from ignored keys list?

**Comment by sapegin** [comment]
@n1313 Did you want to be able to change `devtools`? What should we do for production build?

**Comment by n1313** [comment]
Hmmm, no, I don't think devtools matters for what I do.

**Comment by sapegin** [comment]
@n1313 Sorry, it was @cef62 ;-)

**Comment by benedyktdryl** [comment]
Any updates on that? 

CC: @cef62 @sapegin

**Comment by sapegin** [comment]
I think it should explicitly disable `devtool` in production, otherwise it would complicate style guide configuration and will be easy to miss.
