### ISSUE TITLE
webpack 2 with parser rules requireEnsure breaks react-styleguidist

### ISSUE THREAD

**Issue by oieduardorabelo** [styleguidist/react-styleguidist#463]
Hi guys!

I searched in the issues with these keywords: `require`, `ensure`, `require.ensure`, and nothing related to my problem came in the result. 

**I already fixed it**, but, I did a bit of googling, and there's no issues/topics with that, so, my intention here is to share my findings. For someone searching about it, or facing the same problem.

### My problem

I was working in a project and implementing `react-styleguidist`, when I tried to run it, this was the error:

![screen shot 2017-06-01 at 5 16 31 pm](https://cloud.githubusercontent.com/assets/829902/26665490/1e519bea-46ee-11e7-8a2f-2c570ffc84b1.png)

Not that helpful, right?! My `styleguide.config.js`:

```javascript
module.exports = {
  components: 'client/presentation/**/*.jsx',
};
```

Pretty simple, so, what is happening?

Deep down in the webpack config chain (you know `merge`, `merge`, `import` and `merge` hahaha), and stuck in the base configuration, I found this declaration in the webpack config:

![screen shot 2017-06-01 at 5 20 20 pm](https://cloud.githubusercontent.com/assets/829902/26665550/9b547ebe-46ee-11e7-8faa-a76f507d4e27.png)

Since `react-styleguidist` relies in the webpack syntax for `require.ensure`, looking in the documentation for the [`Rule.parser`](https://webpack.js.org/configuration/module/#rule-parser), it shows this declaration just turn off that syntax, and no error message is defined/throw by `react-styleguidist` or even webpack to help with that.

Was just a few hours to find it, but, maybe someone else can run in the same problem.

Would be interesting the "check" the webpack config to see if this rule is there, and display a better message.

Thanks!

**Comment by sapegin** [comment]
Thanks for a detailed bug report! I’ll think what we can do to improve this ;-)

**Comment by oieduardorabelo** [comment]
@sapegin I could make a PR's using [babel-plugin-syntax-dynamic-import](https://www.npmjs.com/package/babel-plugin-syntax-dynamic-import) to fix this bug,

since is just one file using `require.ensure`, I don't know if worth it,

another question I've is: which of them, webpack or react-styleguidist, should throw a warning about the disabled syntax?

**Comment by sapegin** [comment]
@oieduardorabelo I don’t really understand what this plugin does an how it would solve the issue.

I think we should fix the “polyfill” so it won’t fail silently at least:

```js
/* istanbul ignore if  */
// FIX: require.ensure polyfill for tests
// Can’t make it work from tests, it shouldn’t be in the app code.
if (typeof require.ensure !== 'function') {
	require.ensure = (d, c) => c(require);
}
```

**Comment by sapegin** [comment]
We don’t have the piece of code I’ve mentioned in the previous comment so I suppose this isn’t relevant anymore.

I’m closing this for now. Feel free to reopen if you still have this issue.
