### ISSUE TITLE
Adding custom handler is not listing components in webpage

### ISSUE THREAD

**Issue by pasupuletics** [styleguidist/react-styleguidist#465]
Adding a custom handler causes not to generate/list the components, server is up and running on configured port, but it is not listing any components in left nav(no console errors in the browser). once I remove `handlers` attribute from config its working fine. As per styleguidist [docs](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md) which is valid. Any thoughts....

Below is the sample code.

##### styleguide.config.js
```javascript
{
  ...,
  "handlers": componetPath => require('react-docgen').defaultHandlers.concat((doc, path) => {
    //some custom logic or empty function as is.
  })
}
``` 

CC: @sapegin

**Comment by sapegin** [comment]
Please make an example as [described here](../blob/master/Issue_Template.md).

**Comment by pasupuletics** [comment]
@sapegin, this issue got resolved after adding display handler along with my custom handler. It's better to document this specific step or else better to incorporate in stypeguidit itself. I mean if handlers attribute is configured then we should also contact display handler to existing handlers. Thanks for you time and stuleguidist is awesome.

**Comment by sapegin** [comment]
The docs are [already mention](https://react-styleguidist.js.org/docs/configuration.html#handlers) it, feel free to send a pull request though.

**Comment by pasupuletics** [comment]
@sapegin , You mean do you want me to create pull request for the below scenario:
  Concating `react-docgen-displayname-handler` handler to be part of stylegudist(internal implim) when user configured `handlers` property? please confirm I am more happy to do that.

**Comment by sapegin** [comment]
I’m wondering if it can break existing style guides. I think it would be better to remove mentions of HOCs in the docs and check if component has `displayName` in props-loader.
