### ISSUE TITLE
index.js matches a pattern but doesn’t export a component

### ISSUE THREAD

**Issue by lucasfeliciano** [styleguidist/react-styleguidist#466]
I'm having problems to add `index.js` component export

components/listings/Seller/Seller.js
```js
import React from 'react'
import PropTypes from 'prop-types'

const Seller = props => {
  return (
    <div>
      <img src={props.avatarURL} />
      <h4>{props.name}</h4>
      <p>{props.ticketSoldCount}</p>
    </div>
  )
}

Seller.propTypes = {
  name: PropTypes.string.isRequired,
  avatarURL: PropTypes.string.isRequired,
  ticketSoldCount: PropTypes.number
}

export default Seller
```

components/listings/Seller/index.js
```js
import Seller from './Seller'

export default Seller

```

`Warning: components/listings/Seller/index.js matches a pattern defined in ”components” or “sections” options in your style guide config but doesn’t export a component.`

**Comment by sapegin** [comment]
You need to exclude `index.js` from you style guide: https://react-styleguidist.js.org/docs/components.html (see the first example).

**Comment by lucasfeliciano** [comment]
That works, but then the path doesn't show what I would expect

`components/listings/Seller/Seller.js` instead of `components/listings/Seller`

**Comment by sapegin** [comment]
Then change it: https://react-styleguidist.js.org/docs/configuration.html#getcomponentpathline

**Comment by lucasfeliciano** [comment]
That is pretty smart :)
Thank you

**Comment by sapegin** [comment]
Would be cool to add Algolia search to the site ;-)
