### ISSUE TITLE
Do not overwrite NODE_ENV

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#468]
`NODE_ENV` variable is [explicitly set](https://github.com/styleguidist/react-styleguidist/blob/master/bin/styleguidist.js#L105-L107) in the CLI — it should not overwrite any existing value the same way it’s don in [webpack config](https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js#L20), so you should be able to run Styleguidist like this:

`NODE_ENV=foo styleguidist server`

**Comment by sapegin** [comment]
Has PR: #474.

**Comment by stepancar** [comment]
@sapegin, it should be closed
