### ISSUE TITLE
Add eslint-plugin-import

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#469]
* [ ] Add [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import)
* [ ] Steal rules from [Airbnb config](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js)

**Comment by SaraVieira** [comment]
I gots this @sapegin 👍

**Comment by sapegin** [comment]
@SaraVieira Awesome!

**Comment by SaraVieira** [comment]
@sapegin why isn't the eslint file in js ?

**Comment by sapegin** [comment]
JSON is much easier to [automate](https://github.com/sapegin/mrm) and it’s not that complicated to use JS ;-)

**Comment by SaraVieira** [comment]
Never thought of it that way , just curiosity really :)

330 problems (330 errors, 0 warnings) -> This may take a while :p

**Comment by sapegin** [comment]
What kind of problems it found? Maybe we should just change the config ;-)

**Comment by SaraVieira** [comment]
Most of them are this : 'rsg-components' should be listed in the project's dependencies. Run 'npm i -S rsg-components' to add it

**Comment by sapegin** [comment]
You can’t “fix” that, it’s a feature ;-) We should probably add it to `external-module-folders` (they are not external though but I don’t see a better way).

**Comment by okonet** [comment]
Just add them to `devDependencies` exclusion list like here: https://github.com/okonet/eslint-config-okonet/blob/master/index.js#L47-L61

**Comment by sapegin** [comment]
@okonet That’s probably better, thanks!

**Comment by SaraVieira** [comment]
None if the worked and even if I turn the feature off I keep getting:

```
/Users/saravieira/Projects/react-styleguidist/src/rsg-components/TableOfContents/TableOfContentsRenderer.js
  3:20  error  Unable to resolve path to module 'rsg-components/Styled'  import/no-unresolved
  3:20  error  Missing file extension for "rsg-components/Styled"  
```

**Comment by sapegin** [comment]
Looks like we need [a webpack resolver](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) here.
