### ISSUE TITLE
Copy path button

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#471]
To be able to quickly copy import statements. Something like this:

![image 2017-06-07 at 3 51 27 pm](https://user-images.githubusercontent.com/70067/26881923-3197404c-4b99-11e7-813e-f9df9f8bc6dc.png)

* [ ] Choose an icon, [MdContentCopy](https://gorangajic.github.io/react-icons/md.html) should be good enough
* [ ] Add a button using [copy-text-to-clipboard](https://github.com/sindresorhus/copy-text-to-clipboard)

**Comment by n1313** [comment]
This looks like a great candidate for a plugin.
