### ISSUE TITLE
Make logging customizable

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#472]
Right now Styleguidist uses `console.log` to show some potentially useful messages like:

```
No webpack config found. You may need to specify "webpackConfig" option in your style guide config:
https://github.com/styleguidist/react-styleguidist/blob/master/docs/Webpack.md
```

We should do it only when Styleguidist is started from CLI, not from the API (or tests). Would be nice to be able to customize the logging somehow — I don’t really know what would be the right approach — maybe pass a logging function ~~everywhere~~ or something like that.

**Comment by sapegin** [comment]
This look very close: https://github.com/js-cli/glogg

**Comment by adityavohra7** [comment]
Not having `react-styleguidist` output anything when its tests run definitely makes sense, but I wonder if there are situations wherein people may want the API to output stuff similar to what the CLI does? 

Say I wanted to abstract away or package up my JS infra (build + configs), sort of like what `create-react-app` does, and provide the consumers of this JS infra package with an npm run script like `start-workbench`, which under the hood uses the `react-styleguidist` API. 

Having this run script output warnings or compilation errors would definitely be useful, and would only be possible if the API had output (I think?). Though at the same time this `start-workbench` script could just shell out to the `react-styleguidist` CLI, or it could re-implement some of the output forwarding of the CLI [implemented here](https://github.com/styleguidist/react-styleguidist/blob/master/bin/styleguidist.js#L197). So I'm not sure 😅

**Comment by sapegin** [comment]
@adityavohra7 That’s exactly what I want to do! I just not sure about the API and implementation. 

Probably pass a logger object to the API like this:

```js
const styleguide = styleguidist({
  components: './lib/components/**/*.js',
  logger: {
    error: msg => console.error(msg)
  }
});
```

**Comment by sapegin** [comment]
There’s a PR: #510.
