### ISSUE TITLE
Replace PhantomJS with headless Chrome

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#473]
We have a [script](https://github.com/styleguidist/react-styleguidist/blob/master/test/phantom.js) that loads a production build of a style guide and checks that there’s no JavaScript errors. We run in [on Travis CI](https://github.com/styleguidist/react-styleguidist/blob/master/.travis.yml#L46-L53) to check that production bundles actually work.

Now the script uses PhantomJS which has some issues like always out of date WebKit version and most likely it will [not be supported](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) anymore. 

The new [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) looks like a better and future friendly alternative.

There are wrappers like [](https://github.com/OnetapInc/chromy) that should make interaction with Chrome easier.

**Comment by n1313** [comment]
https://github.com/OnetapInc/chromy

**Comment by sapegin** [comment]
Haha, I forget to link it in the latest sentence ;-)

**Comment by sapegin** [comment]
There’s even better candidate: https://github.com/GoogleChrome/puppeteer

**Comment by devsnek** [comment]
I can have a PR for this done in a few hours if no one else is interested

**Comment by sapegin** [comment]
@devsnek Sounds great!
