### ISSUE TITLE
Theme font in examples

### ISSUE THREAD

**Issue by bluetidepro** [styleguidist/react-styleguidist#475]
**Here is two example screenshots:**

<img width="506" alt="screen shot 2017-06-07 at 7 10 39 pm" src="https://user-images.githubusercontent.com/410701/26906882-0cc194f4-4bb5-11e7-9c0b-fe17b7b6f1c7.png">
<img width="502" alt="screen shot 2017-06-07 at 7 13 30 pm" src="https://user-images.githubusercontent.com/410701/26906945-6f3fd76c-4bb5-11e7-846d-825b19cd4fc6.png">

**In my config, it looks like:**

```
  theme: {
    color: {
      link: 'firebrick',
      linkHover: 'salmon',
    },
    fontFamily: {
      base: [
        '"Proxima Nova"',
        'proxima-nova',
        '"Helvetica Neue"',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
    }
  },
```

As you can see, the font is being applied to the docs, but not the example. Is that intended that the font in the theme is not applied to the examples? Or is this a bug?

**Comment by sapegin** [comment]
Theme is a style guide UI theme, it should no affect you app’s code (that would be a bug ;–)

More info here: https://react-styleguidist.js.org/docs/development.html
