### ISSUE TITLE
Integration with other CSSinJS libraries like fela

### ISSUE THREAD

**Issue by aga5tya** [styleguidist/react-styleguidist#478]
I'm trying to get styleguidist integrated to render [fela](https://github.com/rofrischmann/fela) derived components. What i have now is that i could get the components to render styles by injecting custom template and an alias that has fela's provider component wrapping children.(ref to cookbook redux example)

I'm stuck with the following:
1) When i export a component created by react-fela binding, it says no components are exported by the matched files.

```js
// src/components/Button/Button.js
import React from 'react';
import { createComponent } from 'react-fela'


const BtnStyle = (props) => ({
	width : '300px',
	height : '50px',
	color : (props.color || 'white'),
	border : 'none',
	borderRadius : '3px',
	background : '#888'
})

const Button = createComponent(BtnStyle, 'button')

export default Button
```
However this works when i wrap it onto another stateless component and then export, also this creates an ```<undefined __source="[object Object]"><button class="bms-a bms-b bms-c bms-d bms-e bms-f bms-g">Hello</button></undefined>``` wrap when seen in react tools, but issue 2 exists.

2) For some reason the styles generated by fela is always the last variant (props's state) called in the markdown files. I'm mounting the style node using the wrapper that has fela provider via aliasing.
for.e.g. if i have `<Button/>` and `<Button color="white" />` its always white (above sample) instead of variants.

However, when i go to isolation mode, it renders its state just fine but can't exit the isolation mode, gives me ```main.bundle.js:44380 Uncaught TypeError: Cannot read property 'type' of undefined``` from the playground component.

Could someone please point me in the right direction.

@rofrischmann @sapegin your thoughts on this?

**Comment by raavanan** [comment]
I am facing the Same issues

**Comment by Guru107** [comment]
I tried integrating with `glamor` getting the same issue

**Comment by sapegin** [comment]
Could you please make an example as [described here](../blob/master/Issue_Template.md)? It will require some debugging ;-)

**Comment by aga5tya** [comment]
@sapegin , I'm on it, will push to a repo in some time.

**Comment by aga5tya** [comment]
@sapegin I have pushed the [repo](https://github.com/aga5tya/styleguidist-fela/tree/master) sample. Also missed out to add an important info, i have been setting this up with preact-compact. Not sure if this issue depends on it.

https://github.com/aga5tya/styleguidist-fela/tree/master

**Comment by aga5tya** [comment]
@sapegin,, the see that aliasing the wrapper isn't injecting the context. It's always undefined and fela needs this context to render components created or to render style classNames. Doesn't the wrapper enclose each component or am i missing something ? Took similar approach to the redux example from cookbook.

**Comment by sapegin** [comment]
That’s how it supposed to work ;-| I’ll try to debug it a bit later.

**Comment by aga5tya** [comment]
@sapegin ,, second point i mentioned, was because the fela renderer was reinitialized on each component mount. Making it a single instance fixes the issue and different styles are injected. Still wondering why first point is happening. I'l update the sample repo in a moment.

**Comment by aga5tya** [comment]
@sapegin I have pushed the code that replicates this at https://github.com/aga5tya/styleguidist-fela/tree/export-fela-components, kindly let me know what i am doing wrong, whenever you are free and time permits. For now i am wrapping them and using these.

**Comment by sapegin** [comment]
@aga5tya It works for me without any warnings and I see some styled components. Am I missing something?

**Comment by sapegin** [comment]
@Guru107 Could you please make an example as [described here](../blob/master/Issue_Template.md) for Glamor?

**Comment by sapegin** [comment]
@aga5tya I think you’re doing the right thing now, that’s the recommended way of using Styled components as well: https://react-styleguidist.js.org/docs/cookbook#how-to-use-react-styleguidist-with-styled-components

**Comment by aga5tya** [comment]
@sapegin Awesome. Thanks for documenting this. 👍 🎉

**Comment by sapegin** [comment]
I’ve linked your example from the docs — https://react-styleguidist.js.org/docs/thirdparties.html#fela

Thank you very much!
