### ISSUE TITLE
5.4.0 not pulling propTypes doc any more

### ISSUE THREAD

**Issue by stefanheine** [styleguidist/react-styleguidist#480]
I just updated from 5.3.2 to 5.4.0 and realized that all the propTypes doc is missing.

this is a part of my jsx code:

```
/**
 * Button
 */

const Button = React.createClass({
  propTypes: {
    /**
     * One of the available color types. Currently unset, 1, or 2.
     */
    accent: React.PropTypes.oneOfType([
      React.PropTypes.number,
      React.PropTypes.string
    ]),
```

This is how it looks in 5.4.0:
![image](https://user-images.githubusercontent.com/19835327/26965910-30a28402-4cf8-11e7-98c4-838efb713f58.png)

This is how it looks in 5.3.2:
![image](https://user-images.githubusercontent.com/19835327/26965984-8aeeeaa4-4cf8-11e7-98cc-6085a9f1867b.png)

**Comment by a-ignatov-parc** [comment]
Props and methods are now hidden by default under "PROPS & METHODS" button. Try to press it or add [`showUsage`](https://react-styleguidist.js.org/docs/configuration.html#showusage) param in `styleguide.config.js` to restore old behaviour ;)

**Comment by okonet** [comment]
I just realized that upgrading my projects will basically break how they look so this should have been a major bump IMO.

**Comment by sapegin** [comment]
I think major / minor here is very subjective here. We may change it in the future if it annoys majority of the users and we find a better way to solve issues with props visible by default.

**Comment by a-ignatov-parc** [comment]
@okonet this is what you should expect when you set you dependency with wildcard on minor updates (`^`). So if you expect consistency you should or set wildcard only to patch versions (`~`) or use version lock (`yarn.lock` or something similar).

**Comment by stefanheine** [comment]
> Props and methods are now hidden by default under "PROPS & METHODS" button. Try to press it

I didn't even realize that this was a button - I just assumed this to be a headline/ placeholder only.

>  or add showUsage param in styleguide.config.js to restore old behaviour ;)

setting `showUsage: true` doesn't make any difference. the `showCode` parameter works ok, though.

**Comment by sapegin** [comment]
> I just assumed this to be a headline/ placeholder only.

Try to hover on it ;-) It looks and behaves the same as the code button in examples.

> setting showUsage: true doesn't make any difference.

This should be fixed in [5.4.1](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.4.1).

**Comment by stefanheine** [comment]
> Try to hover on it ;-) It looks and behaves the same as the code button in examples.

I'll get used to it... it was just not intuitive initially.

> This should be fixed in 5.4.1.

thanks for the quick fix. working ok now.

**Comment by sapegin** [comment]
I’m still not 100% sure that hiding them by default is the best solution. Probably we should improve developer experience in isolated mode (there are too much unnecessary thing on the screen) and revisit this decision.

**Comment by okonet** [comment]
I agree. I don't really like additional toggle button on screen for each component.

**Comment by sapegin** [comment]
It will stay anyway ;-) but the default value could be changed.

**Comment by sapegin** [comment]
Closing this for now — we may revisit it in the future.
