### ISSUE TITLE
Global font setting isn't appied in props & methods section

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#481]
In the new collapsable props & methods table default user agent font is being used instead of the theme one.

![2017-06-09 at 11 06](https://user-images.githubusercontent.com/11071/26968851-e04243d8-4d03-11e7-8290-661879c14379.png)

**Comment by sapegin** [comment]
Yeah, looks like `fontFamily` is missing somewhere ;-|

**Comment by SaraVieira** [comment]
@okonet I'm not being able to reproduce this locally :(

It's super weird that only some of them are missing the font :(

**Comment by okonet** [comment]
You can reproduce it in my repo: https://github.com/okonet/react-dropzone/blob/master/styleguide.config.js

**Comment by sapegin** [comment]
One more:

![image 2017-06-10 at 5 41 25 pm](https://user-images.githubusercontent.com/70067/27004121-157e9d8e-4e04-11e7-9974-a2c05dc117e0.png)

**Comment by sapegin** [comment]
Should be fixed in [5.4.2](https://github.com/styleguidist/react-styleguidist/releases/tag/v5.4.2).
