### ISSUE TITLE
input::placeholder selector breaks display in Chrome 55

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#491]
Some elements of UI are looking weird in Chrome 55 (Windows) because of this [`input::placeholder`](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/TableOfContents/TableOfContentsRenderer.js#L28) selector. It should either be vendor-prefixed or separated from the rest.

**Comment by sapegin** [comment]
The problem is that it breaks jss-isolate, because of that unsupported pseudo element Chrome 55 discards the whole jss-isolate selector: 

```css
… .input-0-68, .input-0-68::placeholder, .list-0-71… {}
```

So we need to disable isolation for rules with ``:

```
'&::placeholder': {
  isolate: false
  // ...
}
```
