### ISSUE TITLE
Using JSDocs @example without an example file breaks compilation

### ISSUE THREAD

**Issue by ambidexterich** [styleguidist/react-styleguidist#493]
We use JSDocs to generate API documentation which includes some React components. When those components contain `@example` doclets for JSDocs purposes, react-styleguidist compilation errors out with `Module not found: Can't resolve 'true' in <PATH_TO_COMPONENT>`.

Example:
```
/**
 * Creates a button input
 * @example
 * <Button>Click Me</Button>
 */
```

I traced the problem to a truthy check one [line 57](https://github.com/styleguidist/react-styleguidist/blob/ab32c5cb33e2c02e3fab3b09439317d5b8005ed4/loaders/utils/getProps.js#L57) in `loaders/utils/getProps.js`. 
```javascript
if (doc.doclets.example) {
	    doc.example = requireIt(`!!${examplesLoader}!${doc.doclets.example}`);
	    ...
```
react-docgen returns `true` in this scenario which react-styleguidist then tries to pass to `examples-loader.js` which fails.

At first I thought a simple check like `doc.doclets.example && typeof doc.doclets.example != 'boolean'` would fix the problem but JSDocs also supports this format:

```
/**
 * Creates a button input
 * @example <caption>JSX</caption>
 * <Button>Click Me</Button>
 */
```
But this also breaks compilation. Is there anyway to make react-styleguidist ignore examples that aren't follow by a path?

**Comment by sapegin** [comment]
I think your fix should be enough, what’s the error *with* this fix?

**Comment by sapegin** [comment]
I think we need to validate the path (`<caption>JSX</caption>`) and check existence of the file (and show useful warning in that case).

**Comment by ambidexterich** [comment]
The fix _without_ `<caption>` doesn't cause an error. The fix _with_ `<caption>` errors with `Module not found: Can't resolve '<caption>JSX</caption>`

**Comment by sapegin** [comment]
Yup, I’ve reread your comment and wrote my second comment after that ;-)

**Comment by ambidexterich** [comment]
I have a fix for this that checks that the example file actually exists, I will issue a pull request once I get the test working properly

**Comment by sapegin** [comment]
@ambidexterich Awesom!
