### ISSUE TITLE
Auto fence @example without a path to an example file

### ISSUE THREAD

**Issue by ambidexterich** [styleguidist/react-styleguidist#497]
When an @example doclet has an example and not a path to a file:
```
/**
 * A button example
 * @example
 * <Button>My Text</Button>
 */
```
The contents of the example gets appended to the description which causes strange rendering

![image](https://user-images.githubusercontent.com/675222/27232145-e6bb919a-5282-11e7-8617-d8ac02ce7c09.png)

If you add the fence as part of example as is supported, JSDocs will render the fence inside it's own code block.

Adding the fence to code blocks automatically will allow proper rendering it both cases.

**Comment by sapegin** [comment]
Would you mind send a pull request for that? Doesn’t look very complicated you already know what to do ;-)

**Comment by ethanh1223** [comment]
Looks like PR was merged -- this closed?

**Comment by sapegin** [comment]
@ethanh1223 Yup :shipit:
