### ISSUE TITLE
inst.render is not a function for React 0.14

### ISSUE THREAD

**Issue by xli1000** [styleguidist/react-styleguidist#498]
I am using react-styleguidist on an app that's on React 0.14.9 and I get an exception where it looks for a render method on a stateless component. 

The style guide starts correctly but the page throws the following and does not render:
```Uncaught TypeError: inst.render is not a function```

and also gives the warning:
```Warning: JsDoc(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.```

It only happens for React 0.14 (which seems to still be supported according to the `package.json`). The reason seems to be that React 0.14 does not allow a stateless component to return `null`, whereas several RSG stateless components can return `null`. 

When I modify those RSG components to return `<span />` instead of `null`, the issue is resolved.

* react-styleguidist version: 5.4.4
* Webpack version: 2.6.1
[Fork with the issue](https://github.com/xli1000/example)

**Comment by sapegin** [comment]
Yeah, we should be fare and update the `package.json` — React 15 is more than year old anyway. Thanks for the bug report!
