### ISSUE TITLE
how to override examples-loader

### ISSUE THREAD

**Issue by stepancar** [styleguidist/react-styleguidist#507]
I want to override examples-loader. How to do this?

**Comment by sapegin** [comment]
Could you please explain the use case? Most likely you could use [resolveLoader](https://webpack.js.org/configuration/resolve/#resolveloader) to put your own loader in front of the Styleguidist’s one.

**Comment by stepancar** [comment]
@sapegin, I need in mardown eslint plugin for lint examples.
It required point language for exampe 'js | jsx | javascript | node'. But styleguidist render preview of example if code block haven't language. I need to override styleguidist examples-loader for preprocess .md files.

**Comment by sapegin** [comment]
We’re actually going to change that soon — https://github.com/styleguidist/react-styleguidist/milestone/6, you can help make it happen sooner ;-)

**Comment by stepancar** [comment]
close issue, because not actual
