### ISSUE TITLE
Document Actions and Reducers (redux)

### ISSUE THREAD

**Issue by hmontes** [styleguidist/react-styleguidist#508]
Can i document actions and reducers? (Redux)

This is because we have a lot of actions. We want to put easily in the docs instead of search in the code for any action or reducer.

Thank you

**Comment by hmontes** [comment]
Okey. Temp solution.

1. Create a doc folder in your actions and reducers folder.

2. Create a Markdown of your files. Example. Actions/doc/ModalActions.md

```
## closeModal

This action close all the  open Modals
```

3. Put this in styleguide.config.js

```
sections: [
    {
      name: 'Actions',
      sections: [
        {
          name: 'Modal',
          content: 'src/actions/doc/ModalActions.md'
        },
        {
          name: 'Another actions',
          content: 'src/actions/doc/SideMenusActions.md'
        },
      ]
    }
  ]
```

Is not the ideal but works.

**Comment by n1313** [comment]
I think for now documenting your non-component code such as Redux actions with Markdown (manually or by using something like https://github.com/jsdoc2md/jsdoc-to-markdown/) is your only option. RSG is primarily focused on dealing with individual components and not React-Redux apps as a whole, but I can see how this could be a useful future feature.

**Comment by sapegin** [comment]
Yeah, generating Markdown documents with something like [documentation.js](http://documentation.js.org/) is the best way for now.
