### ISSUE TITLE
Remove webpack 1 support

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#512]
**This is a breaking change.**

**That’s a lot of work but most of the items are relatively easy and could be done separately, that’s why this issue is marked as easy — ping me if you have any questions.**

Webpack 1 is deprecated in Styleguidsit (#499) — no complaints so far ;-)

* [x] Remove webpack conditions from `make-webpack-config.js`
* [x] Remove webpack conditions from `.travis.yml`
* [x] Remove warning from `ensureWebpack` function
* [x] Replace `require.ensure` with [import()](https://webpack.js.org/guides/code-splitting-async/#dynamic-import-import-)
* [x] Remove [cacheable](https://webpack.js.org/guides/migrating/#cacheable) from loaders
* [x] Update webpack-dev-server
* [x] Update react-dev-utils
* [x] Remove json-loader from dependencies
* [x] Update min webpack version const
* [x] Disable ES modules in babel-preset-env
* [x] Update webpack-blocks instructions in the docs
* [x] Get rid of loaders package (?)
* [x] Reread [migration guide](https://webpack.js.org/guides/migrating/) ;-)

Do not remove support until:

* [x] Create React App supports webpack 2 
* [ ] [webpack-blocks 1.0](https://github.com/andywer/webpack-blocks/tree/release/1.0) final release
* [x] [Webpack 3](https://github.com/webpack/webpack/releases) final release

**Comment by sapegin** [comment]
@andywer Any estimates on webpack-blocks 1.0 final release?

**Comment by andywer** [comment]
No concrete one, but we are quiet close. Let's say about one more month maybe 😉

The release candidate will be out very soon and that's pretty much the deprecation of webpack-blocks 0.x.

**Comment by sapegin** [comment]
🍕 [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0) is out!!!! 🥓
