### ISSUE TITLE
Not re-building when new component is added

### ISSUE THREAD

**Issue by Jmeyering** [styleguidist/react-styleguidist#514]
If I add a new component to my components directory, react styleguidist does not recompile until I change some other file that it previously known about.

Is there any way around this issue or is this simply a side effect of how the file watcher works

If there isn't, is there any way to manually trigger a change, without opening an unrelated file and making a edit?

**Comment by n1313** [comment]
I think this is just how file watching works. Another way would be to restart it, but that's probably slower than forcing a re-read by modifying a known file.

**Comment by sapegin** [comment]
Yeah, sometimes it does, sometimes it doesn’t, I’m not really sure why and how to fix that it it’s possible at all.

**Comment by sapegin** [comment]
I don’t think we can fix this now, so I’m closing this for now. Feel free to reopen or send a pull request if you know how to fix it.
