### ISSUE TITLE
Support Vagrant with VirtualBox

### ISSUE THREAD

**Issue by esphen** [styleguidist/react-styleguidist#515]
Hi,

I just tried to make styleguidist work with Vagrant, and it mostly works. There is a pretty deal-breaking issue with hot reloading, however.

When using the VirtualBox provider (which most people do because it's cross-platform) in Vagrant, you need to set `devServer: { poll: true }` for it to work because file system events do not work properly. See https://webpack.js.org/guides/development-vagrant/. This is not possible to set in styleguidist because of the way the server config is merged. See [create-server.js](https://github.com/styleguidist/react-styleguidist/blob/master/scripts/create-server.js#L15-L17).

I tried patching the file to include `poll: true`, and then it works just fine. It seems trivial to support this usecase by changing the config merging to the following:

```js
const webpackDevServerConfig = Object.assign({}, webpackConfig.devServer, {
		noInfo: true,
		compress: true,
		clientLogLevel: 'none',
		hot: true,
		quiet: true,
		watchOptions: Object.assign({}, {
			ignored: /node_modules/,
		}, webpackConfig.devServer ? webpackConfig.devServer.watchOptions : {}),
		contentBase: config.assetsDir,
		stats: webpackConfig.stats || {},
});
```

Shall I make a PR for this, or do you propose another solution?

**Comment by sapegin** [comment]
Yeah, PR is a great idea! I think we can use webpack-merge here instead of manually merging `watchOptions`.
