### ISSUE TITLE
Default prop values don't show when using Flow for typing props

### ISSUE THREAD

**Issue by adityavohra7** [styleguidist/react-styleguidist#518]
Here's my component file:
```javascript
import React from 'react';
import PropTypes from 'prop-types';

export default function Temp ({foo = 'hi'}) {
    return <button>foo</button>;
};

Temp.propTypes = {
    /** description of prop foo */
    foo: PropTypes.string
}
```
And here's what its "PROPS & METHODS" table looks like:
![screen shot 2017-06-27 at 1 22 44 pm](https://user-images.githubusercontent.com/1359298/27608292-c2531fc8-5b3b-11e7-9200-e0b466eab7f0.png)

I'd like to use Flow to type component props. So here's what I tried:
```javascript
// @flow

import React from 'react';

export default function Temp ({foo = 'hi'}: Props) {
    return <button>foo</button>;
};

type Props = {
    /** description of prop foo */
    foo: string
}
```
The "PROPS & METHODS" table now looks like:
![screen shot 2017-06-27 at 12 59 28 pm](https://user-images.githubusercontent.com/1359298/27607358-7c18c77c-5b38-11e7-8cfc-d629128f4c66.png)

Notice that `foo` is now labelled as "Required". 

I also tried using `defaultProps` instead of the default destructuring:
```javascript
// @flow

import React from 'react';

export default function Temp ({foo}: Props) {
    return <button>foo</button>;
};

type Props = {
    /** description of prop foo */
    foo: string
};

Temp.defaultProps = {
    foo: 'hi',
};
```
The "PROPS & METHODS" table still looks like:
![screen shot 2017-06-27 at 1 04 43 pm](https://user-images.githubusercontent.com/1359298/27607593-36041e34-5b39-11e7-941b-1b2693f1f4fa.png)

Here's my styleguide config:
```javascript
'use strict';

const findPortSync = require('find-port-sync');
const os = require('os');
const path = require('path');
const cwd = process.cwd();

module.exports = {
    components: `${path.resolve(cwd, './src/components')}/**/[A-Z]*.js`,
    getComponentPathLine(componentPath) {
        return path.relative(cwd, path.resolve(__dirname, componentPath));
    },
    getExampleFilename(componentPath) {
        return path.join(path.dirname(componentPath), 'README.md');
    },
    webpackConfig: require('../webpack'),
    serverHost: os.hostname(),
    serverPort: findPortSync(),
    showUsage: true,
};
```
Other details:
```
$ ./node_modules/.bin/webpack --version
3.0.0

$ uname -a
Linux dev36-devc 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 GNU/Linux
```
[Here's the example repo](https://github.com/adityavohra7/example/tree/flow_default_props_bug) with the changes to reproduce this issue.

**Comment by sapegin** [comment]
Thanks for a detailed bug report! I’ll take a look later but I’m afraid it may be a react-docgen issue.

**Comment by adityavohra7** [comment]
Okay this was my bad 😥

When I do the following, it works as expected:
```javascript
// @flow

import React from 'react';

export default function Temp ({foo = 'hi'}: Props) {
    return <button>foo</button>;
};

type Props = {
    /** description of prop foo */
    foo?: string
}
```
I just had to type `foo` as a [maybe type](https://flow.org/en/docs/types/maybe/). Which makes sense I guess haha. Using `defaultProps` works too! Closing this issue. Apologies for the noise.

**Comment by adityavohra7** [comment]
Actually, reopening this issue because Flow seems to have issues with annotating `props` that are in `defaultProps` with maybe types 😔

 Here is some discussion: [1660](https://github.com/facebook/flow/issues/1660) and [3512](https://github.com/facebook/flow/issues/3512).

**Comment by sapegin** [comment]
If it’s a Flow issue then we can’t fix it on our side and probably should close this issue ;-)

**Comment by adityavohra7** [comment]
Totally fair, [this comment](https://github.com/facebook/flow/issues/1660#issuecomment-302469877) recommends suppressing the error until its fixed in Flow. Closing!

**Comment by karmeleon** [comment]
Now that the linked Flow issues are resolved, can this issue be reopened? Styleguidist still has this bug.

**Comment by sapegin** [comment]
@karmeleon Feel free to send a pull request. I don’t know what can we do to fix that on our side.

**Comment by adityavohra7** [comment]
Here's [the relevant issue](https://github.com/reactjs/react-docgen/issues/221) in react-docgen!
