### ISSUE TITLE
Run console.clear() when components are reloaded

### ISSUE THREAD

**Issue by birjolaxew** [styleguidist/react-styleguidist#519]
It's a bit irritating to see an error in your console and not know if it's from the current component that was hot-loaded in or from an older version.

This would be solved by running `console.clear()` once a component has been reloaded (or if multiple components are being reloaded, after they're all reloaded).

**Comment by sapegin** [comment]
Sounds like a good feature. Feel free to send a pull request ;-)

**Comment by ethanh1223** [comment]
@sapegin Brand new to open-source and trying to get my first few commits with you guys, so bear with me :)

I've played with a few options and clearing the console seems to work best in the PlaygroundRenderer. When re-compiling multiple components, errors from prior compilations are cleared but errors from _all_ components in current compilation are visible. 

Any objections to this method? Tried to submit a PR but linter doesn't allow for "console" statements in the Component :(

**Comment by sapegin** [comment]
@ethanh1223 Awesome! 🍕

I think [Preview](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Preview/Preview.js) would be a better place.

For ESLint you need to disable this check for a specific line:

```js
console.clear(); // eslint-disable-line no-console
```

Conscious use of `console.log` is OK, ESLint guards us from committing accidental debug code ;-)

**Comment by wayspurrchen** [comment]
Is it possible to disable this functionality on-demand? I want to try to develop against components directly within my styleguidist server, and runtime errors that I want to diagnose and fix are cleared whenever I refresh the page.
