### ISSUE TITLE
jsdocs for methods using arrow functions

### ISSUE THREAD

**Issue by peterlenagh** [styleguidist/react-styleguidist#520]
jsdocs for methods written using arrow functions aren't pulled through currently.

works:
```js
/**
 * Insert text at cursor position.
 *
 * @param {string} text
 * @public
 */
insertAtCursor(text) {
  // ...
}
```

doesn't work:
```js
/**
 * Insert text at cursor position.
 *
 * @param {string} text
 * @public
 */
insertAtCursor = (text) => {
  // ...
};
```

**Comment by stepancar** [comment]
@peterlenagh , it's a limitation of http://buble.surge.sh/guide/ which we use

**Comment by sapegin** [comment]
We’re using Buble on client side only, so it must be limitation of either react-docgen that we use to extract this documentation.

**Comment by stepancar** [comment]
https://github.com/reactjs/react-docgen/issues/190
