### ISSUE TITLE
Empty output on compile error

### ISSUE THREAD

**Issue by gaearon** [styleguidist/react-styleguidist#521]
CRA shows build errors in the browser:
![screen shot 2017-06-28 at 2 25 49 pm](https://user-images.githubusercontent.com/810438/27639314-b7701bce-5c0d-11e7-83ad-b15e904f068d.png)

It would be nice if RS could do the same instead of showing a blank screen:
![screen shot 2017-06-28 at 2 24 16 pm](https://user-images.githubusercontent.com/810438/27639325-c144cd8e-5c0d-11e7-934f-113959369093.png)

**Comment by sapegin** [comment]
That would be nice indeed! Is it possible to reuse this code? We already using some packages from CRA.

**Comment by gaearon** [comment]
The build overlay is currently tightly integrated with our webpack client. You can try using that client: https://github.com/facebookincubator/create-react-app/tree/master/packages/react-dev-utils#webpackhotdevclient

**Comment by sapegin** [comment]
OK, I’ll try as soon as we get rid of webpack 1 support (#512) ;-)

**Comment by sapegin** [comment]
Looks like it just works in 6.x after react-dev-tools update:

![image 2017-08-11 at 9 36 09 am](https://user-images.githubusercontent.com/70067/29204659-9d26cda2-7e78-11e7-84f3-11813651c6fe.png)
