### ISSUE TITLE
Improve printing of objects as `defaultProps`

### ISSUE THREAD

**Issue by esphen** [styleguidist/react-styleguidist#524]
Hi,

Before continuing, I would just like to say that I love react-styleguidist. it's an amazing product, very well put together. We evaluated many styleguide-libraries, but yours was by far the better in terms of producing something that was easy for the team to consume while working.

On to the issue at hand. My suggestion is quite simply to improve the rendering of `defaultProps` that are shapes. In the image below, you see that in this very simple example, it is breaking over several lines in a not very appealing way due to RSG falling back to rendering it as a string.

![screen shot 2017-07-03 at 21 26 43](https://user-images.githubusercontent.com/5845924/27805666-5ac4f976-6036-11e7-955b-0fbb8282a1ef.png)

In this example, it's not **that** bad - but in another project I am working on, I would like to pass an object with several large strings and many properties, and it looks absolutely awful. The cell ends up taking too much space, and is generally unappealing - so we opted for not using `defaultProps` for our configuration objects for now. That's not to say that we don't **want** to.

What I propose is that the `defaultProps` field is rendered as the string `shape` or `Object` when an object is passed, and then on hover, focus or click, a popover is opened next to the string with the pretty printed corresponding `defaultProp` object.

Is this currently possible? Do you like the idea? I looked into the code, but it seems that the default `propsParser` does not return an immediately useful `defaultValue`. It would have to be parsed for it to be pretty printed. See below:

```js
{ type: { name: 'shape', value: {} },
  required: false,
  description: '',
  defaultValue: { value: '{\n    foo: \'bar\'\n}', computed: false },
  tags: {} }
```

**Comment by sapegin** [comment]
> What I propose is that the defaultProps field is rendered as the string shape or Object when an object is passed, and then on hover, focus or click, a popover is opened next to the string with the pretty printed corresponding defaultProp object.

That’s a good idea and we’re already doing this for functions! So that would already increase usability here. Would you mind sending a pull request with this print?

>  It would have to be parsed for it to be pretty printed.

Do you have any ideas how to do that? Or some time to experiment? ;-)

**Comment by esphen** [comment]
> That’s a good idea and we’re already doing this for functions!

Cool, didn't know that!

>> It would have to be parsed for it to be pretty printed.

> Do you have any ideas how to do that? Or some time to experiment? ;-)

I may have some time to look at this at some point, but I need to know if there are any corner cases I need to keep in mind. Do I need to handle other `propParsers` or otherwise alternative output syntaxes? Anything else you can think of?

**Comment by sapegin** [comment]
I don’t think so. If someone has its own `propParsers` it should return data in the same format, otherwise nothing will work ;-)

https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Props/PropsRenderer.js#L65-L80
