### ISSUE TITLE
Code-Editor won't work: "There are multiple modules with names that only differ in casing"

### ISSUE THREAD

**Issue by misantronic** [styleguidist/react-styleguidist#527]
When starting the server, I get the following error:

```
Warning in ./node_modules/react-codemirror/lib/Codemirror.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /node_modules/react-codemirror/lib/Codemirror.js
    Used by 1 module(s), i. e.
    /node_modules/react-styleguidist/lib/rsg-components/Editor/Editor.js
* /node_modules/react-codemirror/lib/codemirror.js
    Used by 2 module(s), i. e.
    /node_modules/react-codemirror/lib/Codemirror.js
```

This leads to a problem with the code-editor:

![screen shot 2017-07-05 at 14 41 10](https://user-images.githubusercontent.com/6033531/27864726-04ee4c68-6190-11e7-90d6-a8380bb0e4e7.png)

![screen shot 2017-07-05 at 14 42 38](https://user-images.githubusercontent.com/6033531/27864776-3b6cd746-6190-11e7-9428-41c66d375255.png)

I am on a mac with a case-insensitive filesystem. We tested this on a linux with a case-sensitive filesystem and it works.

- Your style guide config
```
module.exports = {
	components: 'scripts/main/apps/react/components/**/Button.tsx',
	propsParser: require('react-docgen-typescript').parse
};
```
- Webpack version.
`3.0.0`
- Operating system, browser and version if it’s a layout bug.
`macOS Sierra 10.12.4`

**Comment by sapegin** [comment]
Looks like it’s a react-codemirror issue: https://github.com/JedWatson/react-codemirror/issues/108

**Comment by misantronic** [comment]
I opened an issue:
https://github.com/JedWatson/react-codemirror/issues/123

**Comment by smashercosmo** [comment]
This is pretty critical issue. May be as a workaround we can temporally downgrade react-codemirror?

**Comment by sapegin** [comment]
@smashercosmo Feel free to send a pull request if that would solve the issue.

**Comment by sapegin** [comment]
There’s an unmerged PR at react-codemirror: https://github.com/JedWatson/react-codemirror/pull/124

**Comment by smashercosmo** [comment]
Yeah, I saw the PR, but react-codemirror is not under active development
