### ISSUE TITLE
[idea] Fence with js to get highlighting on github

### ISSUE THREAD

**Issue by kof** [styleguidist/react-styleguidist#529]
I was thinking lately what could we do to allow having ```js and still to know when it is an sg example and when not and one idea came in mind - magical comment same like @flow or esilnt is using

E.g.

```js
// @sg
someJsCodeEvaluatedBySgAndHighlightedAsJs()
```

```js
jsCodeNotEvaluatedBySg()
```

**Comment by sapegin** [comment]
It’s almost done and will be released as a new major version very soon: https://github.com/styleguidist/react-styleguidist/issues/517 ;-)
