### ISSUE TITLE
Display component name in <title> when opening a component in isolated mode

### ISSUE THREAD

**Issue by n1313** [styleguidist/react-styleguidist#531]
I spend most of my time with RSG switching between a handful of components in isolated mode. Unfortunately, page title doesn't change when I do that, so my browser history consists of the same page name repeated many times. Not very helpful. I would like my page `<title>` to display component name when I open it in isolated mode: `React Style Guide Example - Button` or something similar.

**Comment by n1313** [comment]
https://github.com/gaearon/react-document-title?

**Comment by sapegin** [comment]
That’s an amazing idea! I’m using react-document-title and can recommend it.

> React Style Guide Example - Button or something similar.

“Button — React Style Guide Example”, otherwise you won’t see component names if you have many open tabs ;-)

**Comment by n1313** [comment]
I'm not too familiar with react-document-title -- would it be difficult to make it add/remove the component name prefix and leave the static "React Style Guide Example" part untouched? There isn't much documentation in the repo.

**Comment by sapegin** [comment]
It should be something like that:

```js
const title = isolated ? `${name} — RSG` : 'RSG';
<DocumentTitle title={title}>
  ...
</DocumentTitle>
```

But maybe it’s an overkill for our case, react-document-title is good when you nest components with different titles (the deepest one wins).

**Comment by sapegin** [comment]
Probably it’s better to just set title here: https://github.com/styleguidist/react-styleguidist/blob/master/src/index.js#L67

**Comment by n1313** [comment]
The problem also is that the static part can be customised by the user, so it can't be hardcoded.

**Comment by sapegin** [comment]
But that’s a config option that we can pass to the frontend.

**Comment by n1313** [comment]
Actually, it is already there: https://github.com/styleguidist/react-styleguidist/blob/master/src/index.js#L70 :) Let me make a quick stab at this.
