### ISSUE TITLE
Remote stylesheet

### ISSUE THREAD

**Issue by adambowles** [styleguidist/react-styleguidist#534]
Is it possible to import a remote stylesheet?

I'm migrating from [bluekit](https://github.com/blueberryapps/react-bluekit) and there I was able to include a remote stylesheet in the HTML, so I could use a custom webfont.

I know this is technically possible using the `styles` directive in `styleguide.config.js`, but I don't want a 350kb config file, nor a local copy of the stylesheet.

**Comment by n1313** [comment]
Would [modifying the template file](https://react-styleguidist.js.org/docs/configuration.html#template) to include that stylesheet work?

**Comment by adambowles** [comment]
Yeah that's done it
