### ISSUE TITLE
Change line-height from normal to inherit

### ISSUE THREAD

**Issue by gaastonsr** [styleguidist/react-styleguidist#536]
**styleguide.config.js**
```js
const path = require('path');

module.exports = {
  title: 'BSA React Web Components',
  sections: [
    {
      name: 'Introduction',
      content: 'docs/Introduction.md',
    },
    {
      name: 'Reboot',
      content: 'docs/Reboot.md',
    },
    {
      name: 'Components',
      components: 'src/**/[A-Z]*.js',
    },
  ],
  require: [
    path.join(__dirname, 'docs/assets/styles/index.less'),
  ],
  assetsDir: 'docs/assets',
  webpackConfig: {
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
          query: {
            presets: ['es2015', 'stage-3', 'react'],
          },
        },
        {
          test: /\.css$/,
          loaders: ['style-loader', 'css-loader'],
        },
        {
          test: /\.less$/,
          use: [
            'style-loader',
            'css-loader',
            {
              loader: 'less-loader',
              options: {
                sourceMap: true,
              },
            },
          ],
        },
      ],
    },
  },
};
```

webpack version: ^3.0.0
OS, browser version: OS X, Chrome 58.0.3029.110 (64-bit)

Hi! I like react-styleguidist a lot.

I'm trying to set up a page where I showcase how headers, lists and other elements look by importing the library (and its stylesheet).

Currently it looks like this 

![screen shot 2017-07-07 at 3 40 44 pm](https://user-images.githubusercontent.com/2997285/27976451-339d2262-632c-11e7-9165-b6db437cbc5c.png)

If I change [this div](https://github.com/styleguidist/react-styleguidist/blob/a010018f6672af81332018399fc0e595e81d4b24/src/rsg-components/Playground/PlaygroundRenderer.js#L26) `line-height` from `normal` to `inherit` it looks how I would expect it to.

![screen shot 2017-07-07 at 3 43 34 pm](https://user-images.githubusercontent.com/2997285/27976531-86521b66-632c-11e7-93ff-3e2cb7e0bd61.png)

Could we change it so the default style for line-height is inherit?

**Comment by SaraVieira** [comment]
@gaastonsr I got you bro, doing the PR

**Comment by gaastonsr** [comment]
Thanks sis!
