### ISSUE TITLE
Preview not updating when editing initialState.

### ISSUE THREAD

**Issue by kumarabhishek** [styleguidist/react-styleguidist#545]
When changing initialState in code editor, its not updating the preview.
For example in code editor of Button let's write following:
```js
initialState={v: 'Hello'};
<Button>{state.v}</Button>
```
Now when we edit code to following, it does not reflect in Button preview:

```
initialState={v: 'Hello1'};
<Button>{state.v}</Button>
```

**Comment by kumarabhishek** [comment]
It seems I do not have permission to push. Getting following error:

```bash
~/dev/react-styleguidist $ git push origin preview-fix
ERROR: Permission to styleguidist/react-styleguidist.git denied to kumarabhishek.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by kumarabhishek** [comment]
@sapegin I got fix for https://github.com/styleguidist/react-styleguidist/issues/519 also. If you provide me privilege, i will include even this fix in same PR.

**Comment by n1313** [comment]
@kumarabhishek please fork the repo, push your fix to a branch in your fork and send a PR from your fork to the main repo.

**Comment by sapegin** [comment]
@kumarabhishek Thanks! There’s a PR for #519 already: #544.
