### ISSUE TITLE
skipComponentsWithoutExample Docs Clarification

### ISSUE THREAD

**Issue by reintroducing** [styleguidist/react-styleguidist#547]
I'm using the 6.0.0 beta 2 and i had `skipComponentsWithoutExample` set to true. When looking at the docs I'm seeing this line:

`Ignore components that don’t have an example file (as determined by getExampleFilename). These components won’t be accessible from other examples unless you manually require them.`

In one of my examples for a Form component I wanted to use a FormElementError component (which doesn't have its own example.md file) but it was erroring because of this. I thought that by including all my components in the `components` that these would work. When you specify you have to require them manually, I think some clarification is necessary, as to how you'd do that, as it's not very clear to me and the `require` option in the config seems like its meant more for third party items. 

What, then, would be the best way to require a component that doesn't have a corresponding md file so that it can be used in other component's example md files?

**Comment by reintroducing** [comment]
disregard, just discovered the cookbook and saw this: https://github.com/styleguidist/react-styleguidist/blob/master/docs/Cookbook.md#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples

**Comment by reintroducing** [comment]
Actually, I just tried this and got the following:
`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of PreviewComponent.`

Here is my example file:
```
    const Tab = require('./Tab');
    const TabContent = require('./TabContent');
    const TabNavigation = require('./TabNavigation');
    const TabPanel = require('./TabPanel');

    <Tabs>
        <TabNavigation>
            <Tab label="Tab 1">Tab 1 Title</Tab>
            <Tab label="Tab 1">Tab 2 Title</Tab>
            <Tab label="Tab 1">Tab 3 Title</Tab>
            <Tab label="Tab 1">Tab 4 Title</Tab>
        </TabNavigation>
        <TabContent>
            <TabPanel>Tab Content 1</TabPanel>
            <TabPanel>Tab Content 2</TabPanel>
            <TabPanel>Tab Content 3</TabPanel>
            <TabPanel>Tab Content 4</TabPanel>
        </TabContent>
    </Tabs>
```

All of these components live in the same directory. What am I doing wrong?

**Comment by reintroducing** [comment]
ugh, had to add `.default` to the require.

**Comment by timbergus** [comment]
Thanks, @reintroducing. I was starting to bump my head against the table. I feel so dumb 😩
