### ISSUE TITLE
Doc is not getting updated when changes are not from react component file

### ISSUE THREAD

**Issue by pasupuletics** [styleguidist/react-styleguidist#551]
@sapegin , I have a scenario that react component imports `propTypes` from external file and doc is not getting generated which is expected, And I have written a [react-docgen](https://github.com/reactjs/react-docgen) custom handler, which would generate a doc for external `propTypes` and everything went smooth. Now the issue with live reload, When I made any changes to external `propTypes` file changes are reflecting on live example, but documentation is not getting updated as as react-docgen [parse](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/props-loader.js#L28) method is not invoking(props-loader.js) unless changes are from actual react component file. Is there any way to invoke [parse](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/props-loader.js#L28) method(props-loader.js) when a change is not form actual react component file?

##### Example:
```javascript
import React from 'react';
import propTypes from './button-proptypes'

export default class Button extends React.component{
...
}

Button.propTypes = propTypes;
```
##### button-proptypes.js
```javascript
import PropTypes from 'prop-types';

export const propTypes = {
/*Type of a button*/
propA: PropTypes.oneOf(['simple', 'primary'])
propB: ...
}
```

When I made any changes to `button-proptypes.js` live reload is working fine, but documentation is not getting Updated.

**Comment by sapegin** [comment]
Maybe `contextDependencies` could help here: https://react-styleguidist.js.org/docs/configuration#contextdependencies

**Comment by pasupuletics** [comment]
@sapegin , Thanks for your quick response, But configuring `contextDependencies` didn't serve my purpose. But I got the root cause that the issue with webpack HMR(not really an issue, its an expected behaviour). HMR has enabled for all the files and working as expected. When component file changes  webpack re-builds and pushes updated file into browser same happens for external imported files as well. 

Is there any possibility to update doc/props property when any of the component dependent file gets changed? I mean when react component gets updated webpack invokes `props-loader` and pushes changes to browser like wise, can we invoke the same for component dependent files too?

**Comment by sapegin** [comment]
Could you try to implement it? I don’t really understand how it should work ;-|

**Comment by pasupuletics** [comment]
Sure @sapegin will give it a try. Could you please clarify me on below:
When component file changes how the props-loader.js is pitching in(might be because of HMR), could you please help me to find where that peace of code reside(actual logic).

**Comment by pasupuletics** [comment]
@sapegin , As you mentioned `contextDependencies` works for us with the minimal changes to `props-types.js`. We should introduce below peace of code to `props-loader.js` as you already did it for [styleguide-loader.js](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/styleguide-loader.js#L59)
```JS
if (config.contextDependencies) {
  config.contextDependencies.forEach(dir => this.addContextDependency(dir));
}
```

Thanks for being with me and for your timely responses, you are AWESOME.

**Comment by sapegin** [comment]
Could you send a pull request with this change?

**Comment by pasupuletics** [comment]
Sure @sapegin, will issue a PR ASAP.

**Comment by pasupuletics** [comment]
@sapegin , I have created [PR](https://github.com/styleguidist/react-styleguidist/pull/557) as per over conversation, please take a look.
