### ISSUE TITLE
First example doesn't use a code fence

### ISSUE THREAD

**Issue by dchambers** [styleguidist/react-styleguidist#553]
This tiny doc issue caused me to waste loads of time, so maybe it will help others. The first example of [documenting your components](https://react-styleguidist.js.org/docs/documenting.html) doesn't currently use a code fence, and although this did work for me, it prevented the styles from working. I spend hours after that fighting with Webpack config when it was actually just as simple as putting the component inside a code fence.

Anyway, thanks for a great tool 👍

**Comment by sapegin** [comment]
I’m not sure what you’re talking about, because there’s absolutely no difference between indented code blocks and fenced without a language.

Please make a demo project that we can debug based on this repo https://github.com/styleguidist/example if you think there’s a bug somewhere.

**Comment by dchambers** [comment]
HI @sapegin, maybe Im doing something stupid then since I didn't even know code blocks could be indented like that, but [here's a repo](https://github.com/dchambers/styleguidist-cra-test/commits/master) to show how using that style of code block doesn't work for me.

Thanks 👍

**Comment by sapegin** [comment]
It’s 4 spaces, not 2 ;-)

**Comment by sapegin** [comment]
And it’s better to use fenced blocks, we’re changing all example to use them in the next major release: https://github.com/styleguidist/react-styleguidist/blob/six/docs/Documenting.md#usage-examples-and-readme-files

**Comment by dchambers** [comment]
Doh, thanks @sapegin!
