### ISSUE TITLE
Nested section titles have the same font size

### ISSUE THREAD

**Issue by dylankiss** [styleguidist/react-styleguidist#554]
I am using the following `styleguide.config.js`:

```javascript
const { createConfig } = require('@webpack-blocks/webpack2');
const typescript = require('@webpack-blocks/typescript');

module.exports = {
  title: 'Foo Style Guide',
  sections: [
    {
      name: 'Introduction',
      content: 'docs/Introduction.md'
    },
    {
      name: 'Documentation',
      sections: [
        {
          name: 'Sample Section',
          content: 'docs/SampleSection.md'
        },
        {
          name: 'Other Sample Section',
          content: 'docs/OtherSampleSection.md'
        },
      ]
    },
    {
      name: 'UI Components',
      components: 'src/ts/components/**/*.tsx'
    }
  ],
  webpackConfig: createConfig([
    typescript()
  ]),
  resolver: require('react-docgen').resolver.findAllComponentDefinitions,
  propsParser: require('react-docgen-typescript').parse
};
```

I have two nested sections: `Sample Section` and `Other Sample Section`. When my docs get rendered, the titles of these nested sections have the same font size as their parent section titles. I would expect these to be smaller. Is there an easy way I can change that? 

<img width="958" src="https://user-images.githubusercontent.com/5985577/28779311-f1f5840a-7602-11e7-9cb3-e5d943fb8c05.png">

<img width="1122" src="https://user-images.githubusercontent.com/5985577/28779419-5a9b9ae4-7603-11e7-87a4-4747fd56da7e.png">

**Comment by sapegin** [comment]
Feel free to send a pull request to fix that ;-)

**Comment by dylankiss** [comment]
@sapegin Took a shot for a simple fix, by only making the top level sections "primary". It's good enough for me.
