### ISSUE TITLE
example/basic is did not work by default.

### ISSUE THREAD

**Issue by konojunya** [styleguidist/react-styleguidist#559]
I thought about trying the example.

but did not work by default.

I think `babel-core` is necessary for the `package.json`

<img width="481" alt="2017-08-01 19 27 33" src="https://user-images.githubusercontent.com/12035578/28821348-0b4d1f88-76f0-11e7-85e9-d2f4f48e74bb.png">

webpack version and `styleguide.config.js` is [example/basic](https://github.com/styleguidist/react-styleguidist/tree/master/examples/basic)

**Comment by sapegin** [comment]
You’re right, should be fixed now ;-)
