### ISSUE TITLE
v6+ "static" requirement is breaking GitHub Enterprise 2.7 markdown rendering

### ISSUE THREAD

**Issue by aversini** [styleguidist/react-styleguidist#560]
I know it's a long shot because the issue is only on GitHub enterprise...

Our RSG configuration loads our README.md file as an introduction section, and then loads all our components API examples. Here is an extract of our configuration:
```js
sections: [{
  name: 'Getting started',
  content: 'README.md'
},
{
  name: 'Components',
  components: `${constants.srcRoot}**/[A-Z]*.jsx`
}]
```

In our README.md file, we have the following lines:
<pre>
You can then import our components:

```js
import {Button, Panel} from 'our-library';
```
</pre>

As of RSG 6.x, these lines are now trying to be interpreted as a React component with a playground... This fails obviously. While adding the "static" flag next to the "js" lang fixes the API rendering, it breaks the markdown rendering in our GitHub Enterprise v2.7.

Here is what GitHub does with this "static" flag:

No flag:

```js
import {Button, Panel} from 'our-library';
```

With static flag:

<pre>
```js static import {Button, Panel} from 'our-library';
</pre>

2 questions: are you aware of this issue, and more importantly is there a way to disable this new feature at a global level, something like an opt-in? Or limiting it to just component files. Thank you!

I also tried to simply use back-ticks with no lang, but RSG is trying to compile these as React component as well... Shouldn't this be limited to js, jsx and javascript?

**Comment by sapegin** [comment]
And I still don’t understand how exactly it breaks rendering in GitHub Enterprise.

**Comment by aversini** [comment]
> Do you really format it like this, in one line?

No, this was my attempt to show how GitHub Enterprise is rendering our lines.

Basically adding "static" next to "js" is having an effect on GHE where 3 lines are all merged into one.

As for the updateExample option, it creates the same issue on GHE. Basically, adding anything after the lang tag is breaking the markdown rendering 😢

**Comment by sapegin** [comment]
I mean you can add any modifiers *inside* updateExample.

**Comment by aversini** [comment]
Oh got it! Yes let me try that avenue! Thanks

**Comment by aversini** [comment]
@sapegin so I tried to use updateExample, using 2 different approaches:

1. if lang is set to `js`, `jsx` or `javascript`, change the lang to `coffeescript` or `typescript`
2. if lang is set to `js`, `jsx` or `javascript`, set `settings.static` to true

The first approach works: it prevents RSG from interpreting code fences marked with these lang as a React component, and the code highlighting is almost the same as with the original lang. It's not perfect, but it allows me to not having to update my non-react markdown files.

The second approach is working too, and it seems like it would be the best approach: on one hand I don't have to update my non react markdown files to be compatible with RSG, but RSG allows me to make them compatible on the fly. 
Here is the code I tried.

```js
updateExample(props) {
  const {settings, lang} = props;
  if (lang === 'javascript' || lang === 'js' || lang === 'jsx') {
    settings.static = true;
    return {
      content: props.content,
      settings,
      lang
    };
  }
  return props;
},
```

I will probably go ahead with solution #2.
Question for you, do you foresee any future incompatibility with RSG roadmap?

**Comment by sapegin** [comment]
Not really if we won’t find any serious issues with the new approach.

Would you mind adding this example to the docs?

**Comment by aversini** [comment]
Great, thanks! Yes I can do that. Do you prefer I add that to the cookbook or as a second example to `updateExample`?

**Comment by sapegin** [comment]
I’d add it as an example to the `updateExample`, thanks!

**Comment by aversini** [comment]
Will do, PR coming up...
