### ISSUE TITLE
showCode do not work well

### ISSUE THREAD

**Issue by konojunya** [styleguidist/react-styleguidist#561]
I thought about trying `showCode` , but it was not adapted even if I set the configuration to `styleguide.config.js`.

I found the following two things.
Is there something missing?

If you are writing in the document, please let me know.

I have read this document [docs/configuration#showcode](https://react-styleguidist.js.org/docs/configuration.html#showcode)

>showCode
>
>Type: Boolean, default: false
>
>Show or hide example code initially. It can be toggled in the UI by clicking the Code button after each example.

1. I can not see the code by default even with `showCode: true`

example: [konojunya/styleguidist-example](https://github.com/konojunya/styleguidist-example)

- forked: [styleguidist/example](https://github.com/styleguidist/example)
- webpack version: `^3.4.1`
- styleguide.config.js

```js
module.exports = {
  title: 'React Style Guide Example',
  defaultExample: true,
  showCode: true,
  components: './lib/components/**/[A-Z]*.js',
  webpackConfig: {
    module: {
      loaders: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
        },
        {
          test: /\.css$/,
          loader: 'style-loader!css-loader?modules&importLoaders=1',
        }
      ]
    }
  },
};
```

2. Working but do not work properly.

example: [konojunya/styleguidist-example-typescript](https://github.com/konojunya/styleguidist-example-typescript)

<img width="957" alt="2017-08-02 10 37 29" src="https://user-images.githubusercontent.com/12035578/28855272-f6b96cac-7776-11e7-99f0-46571fa6a363.png">
<img width="951" alt="2017-08-02 10 38 01" src="https://user-images.githubusercontent.com/12035578/28855273-f6bc0084-7776-11e7-8575-60e01a9eeddf.png">

- webpack version: `^3.3.0`
- styleguide.config.js

```js
const path = require('path');

process.noDeprecation = true;

module.exports = {
  showUsage: true,
  showCode: false,
  resolver: require('react-docgen').resolver.findAllComponentDefinitions,
  highlightTheme: 'material',
  getComponentPathLine: componentPath => {
    const name = path.dirname(componentPath).match(/.*\/(.*)$/);
    const dir = path.dirname(componentPath);
    return `import ${name[1]} from '${dir}';`;
  },
  getExampleFilename: componentPath => path.dirname(componentPath) + "/README.md",
  sections: [
    { name: 'Atoms', components: './src/components/atoms/**/index.tsx' }
  ],
  template: './styleguide/template.ejs',
  dangerouslyUpdateWebpackConfig: (webpackConfig, env) => {
    webpackConfig.output.filename = 'build/bundle.js'
    return webpackConfig;
  },
  webpackConfig: require('./styleguide/config'),
  styleguideComponents: {
		Logo: path.join(__dirname, 'styleguide/components/Logo.jsx'),
  }
}
```

**Comment by sapegin** [comment]
The first bug should be fixed now.

I’m not sure how to reproduce the second: seems to work fine in your repo.

**Comment by konojunya** [comment]
>The first bug should be fixed now.

👍 

>I’m not sure how to reproduce the second: seems to work fine in your repo.

Normal:
1. `git clone git@github.com:konojunya/styleguidist-example-typescript.git`
2. `npm i`
3. `npm run styleguide:build or npm run styleguide`
4. show your browser index.html or [localhost:6060](http://localhost:6060)

Bug:
1. `git clone git@github.com:konojunya/styleguidist-example-typescript.git`
2. `npm i`
3. change `showCode: true` in `styleguide.config.js`
4. `npm run styleguide:build or npm run styleguide`
5. show your browser index.html or [localhost:6060](http://localhost:6060)

**Comment by sapegin** [comment]
Please try with 6.0.6 and see if it fixes both issues or just the first one.

**Comment by konojunya** [comment]
thank you.
first issue is resolved 💯 
but, second one is not solved 😢

**Comment by sapegin** [comment]
You’re using react-styleguidist 5.5.9, please try with 6.0.6.

**Comment by konojunya** [comment]
not yet :(

https://github.com/konojunya/styleguidist-example-typescript/blob/master/package.json#L22

**Comment by sapegin** [comment]
Should be fixed in the next patch release.
