### ISSUE TITLE
Default prop evaluated in global scope

### ISSUE THREAD

**Issue by stcherenkov** [styleguidist/react-styleguidist#564]
[This commit line](https://github.com/styleguidist/react-styleguidist/commit/ded79c82cf1e609bf7e0f07cc820743927ceda32#diff-bf5c71c0b1dcaa51081c3d9b36ba5c00R103) introduced a bug: we have default object-like value in local scope (inside IIFE, in example), but styleguidist is evaluating it in global scope and eval throws.

Possible solution is to wrap eval in try-catch statement with rendering default value as "Object" when no global variable is available.

**Comment by esphen** [comment]
Hi, thanks for reporting. That's a good point, we didn't think of that. I can fix this tonight

**Comment by esphen** [comment]
Should be fixed in 63b3369, will be a part of the next version @sapegin releases

**Comment by sapegin** [comment]
@esphen Thanks! Fixes are released automatically, so expect a new version in ~10 minutes ;-)
