### ISSUE TITLE
The borderRadius, maxWidth, and sidebarWidth theme config variables cannot be overridden

### ISSUE THREAD

**Issue by kidkuro** [styleguidist/react-styleguidist#566]
The `borderRadius`, `maxWidth`, and `sidebarWidth` theme config variables cannot be overridden.

- Styleguidist version 6.0.8 
- Webpack version 3.0.0
- Applicable styleguide config:
  ```
  module.exports = {
    theme: {
      maxWidth: 1300
    }
  }
  ```

in `styles/createStyleSheet.js` it has:
```
import merge from 'lodash/merge';
...
import * as theme from './theme';
...
var mergedTheme = merge(theme, config.theme);
```
[lodash merge](https://lodash.com/docs/4.17.4#merge) will attempt to modify the properties of `theme` with the values in `config.theme`, however the top level properties of an imported module are readOnly which means that while properties of nested config objects will be merged, the top level `borderRadius`, `maxWidth`, and `sidebarWidth` properties will be ignored.

This could be easily solved by merging all properties into a new object, e.g.:

```
var mergedTheme = merge({}, theme, config.theme);
```

**Comment by sapegin** [comment]
Fell free to send a pull request to fix that ;-)
