### ISSUE TITLE
Implement smarter way to resolve components

### ISSUE THREAD

**Issue by smashercosmo** [styleguidist/react-styleguidist#572]
Currently react-styleguidist heavily rely on glob patters. And for 90% of cases it's ok. But sometimes there could me more complicated cased for which glob patterns are not enough. For example user could have several components in one folder, but wants to document only one of them. Imagine the following folder contents:
```
List.js
List.css
ListItem.js
ListItem.css
Readme.md
```
User wants to colocate ListItem component with List component, because ListItem won't be used anywhere out of List component. So there should be a way to specify resolving rule like that: get component, which name is equal to directory name. Maybe we can provide 'filter' option, which will accept a function, which will get component's path as an argument? Another option is to accept regexp along with glob patter.

**Comment by sapegin** [comment]
There’s a way to do that — pass a function to `components` option: https://react-styleguidist.js.org/docs/configuration#components

**Comment by smashercosmo** [comment]
Yeah, figured out how to do it) Thx

**Comment by sapegin** [comment]
@smashercosmo Feel free to improve the docs if have a good example ;-)
