### ISSUE TITLE
Filter components in Main content area, not just sidebar

### ISSUE THREAD

**Issue by skube** [styleguidist/react-styleguidist#582]
This is more of an idea...I'm just wondering if anyone else would find it useful if the filtering of components in the sidebar also affected the main content area.  That would allow one to easily scroll through the filtered components.

I **really** like the filtering, I just thought it could be _more_ useful.

**Comment by sapegin** [comment]
I’m afraid it could be very slow when you have many components.

**Comment by skube** [comment]
🙁 Oh well just a thought.
