### ISSUE TITLE
CSS EM unit is not isolate

### ISSUE THREAD

**Issue by papasmurf17** [styleguidist/react-styleguidist#584]
In my react components I use `EM` as font size unit, and when the components are rendered all font sizes are wrong.

I know that `EM` is relative unit and if the container changes font-size all childs inherit this change, but the final aim of react-styleguidist is:

> Isolated React component development environment

My workaround to bypass this problem was add this piece of configuration to the **styleguide.config.js**

```js
styles: {
    Examples: {
      root: {
        'font-size': '1em !important'
      }
    },
    Playground: {
      root: {
        'font-size': '1em !important'
      },
      preview: {
        'font-size': '1em !important'
      }
    },
    ReactComponent: {
      root: {
        'font-size': '1em !important'
      }
    },
    Section: {
      root: {
        'font-size': '1em !important'
      }
    },
    Sections: {
      root: {
        'font-size': '1em !important'
      }
    },
    StyleGuide: {
      root: {
        'font-size': '1em !important'
      },
      content: {
        'font-size': '1em !important'
      },
      hasSidebar: {
        'font-size': '1em !important'
      }
    },
```

**Comment by sapegin** [comment]
Please use fenced blocks with language tags (for example ```` ```js````) to make code examples more readable.

**Comment by sapegin** [comment]
Looks like we need to add font-size here:

https://github.com/styleguidist/react-styleguidist/blob/master/src/styles/setupjss.js#L21-L23

Feel free to send a pull request for that ;-)
