### ISSUE TITLE
skipComponentsWithoutExample should respect imports from other components

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#587]
I think I'm hitting an interesting edge case with `skipComponentsWithoutExample`.

This is how the component's structure looks like in my project:

```
├── DataGrid
│   ├── DataGrid.jsx
│   ├── DataGrid.md
│   ├── DataGrid.test.jsx
│   ├── DataGridCell.jsx
│   ├── DataGridCellDate.jsx
│   ├── DataGridColumn.jsx
│   ├── DataGridHeadingCell.jsx
│   ├── DataGridRow.jsx
│   ├── SortIndicator.jsx
│   ├── SortedDataGrid.jsx
│   ├── SortedDataGrid.md
│   ├── SortedDataGrid.test.jsx
│   ├── SortedDataGridColumn.jsx
│   ├── SortedDataGridHeadingCell.jsx
│   ├── __snapshots__
│   │   ├── DataGrid.test.jsx.snap
│   │   └── SortedDataGrid.test.jsx.snap
│   ├── constants.js
│   └── index.js
├── Dropdown
│   ├── Dropdown.jsx
│   ├── Readme.md
│   └── index.js
```

Please note that not every component in DataGrid has an example, but only topmost components are: i.e.  `DataGrid.md` and `SortedDataGrid.md`. At the same time, they require the underlying components from this directory in their source code i.e.

```javascript
import React, { Children, PropTypes } from 'react';
import DataGridColumn from './DataGridColumn.jsx';
import DataGridRow from './DataGridRow.jsx';
```

etc.

Now imagine I want to skip the styleguide for the `Dropdown` component so I've removed the `Dropdown/Readme.md` and set `skipComponentsWithoutExample: true`. 

Now all my DataGrid components stopped working since neither of components without the corresponding `.md` file were required anymore saying `ReferenceError: DataGridColumn is not defined`.

I _believe_ this should work differently and only exclude top-level components from the styleguide i.e. _components that are orphans in the dependency graph_. 

Am I missing some other use cases here?

**Comment by sapegin** [comment]
This feature is super stupid — there’s not dependency graph at all ;-| If you require a component from the source of another component, it should work. It won’t work if you try to use this component in an example of another component. 

Do you have any ideas how we can fix it?

As a workaround you could manually import all components you need like this:

```js
global.DataGridColumn = require('./components/DataGridColumn');
```

And then use this file in `require` style guide option.

**Comment by okonet** [comment]
One idea would include leveraging of the webpack dependency tree but as you mentioned, this probably will require a major rewrite :/
