### ISSUE TITLE
Question: Only find/use  components listed in index.js?

### ISSUE THREAD

**Issue by KatGr** [styleguidist/react-styleguidist#592]
Hello,

I have a problem/question:
All of our packages have one index.js in the root directory with all needed exports available from the outside.
Now it would be cool to make styleguidist only find/use the components described inside index.
But as soon as I use index.js as component path, every single file will be used (for example sql-files). 
I tried to use skipComponentsWithoutExample: true but it didn't work.

Is there any way I could use index.js?

sincerely,
Me

**Comment by sapegin** [comment]
I’m not sure I correctly understand your setup (an example would help) but looks like you need to parse / require your index.js, see what it imports and generate a list of file you could pass to `components` option.
