### ISSUE TITLE
Removing "Add Examples to this Component" link

### ISSUE THREAD

**Issue by besrabasant** [styleguidist/react-styleguidist#594]
How do I remove _Add examples to this component_ link that is below each components documentation. If I do not need to show examples for any component.

**Comment by SaraVieira** [comment]
Hello @besrabasant ,

You can hide it using the styles: 
https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide
https://react-styleguidist.js.org/docs/configuration.html#styles

You can also change the layout if you want:
https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide

**Comment by sapegin** [comment]
You won’t see it production build so there’s no need to hide it.

**Comment by besrabasant** [comment]
okkk

**Comment by sapegin** [comment]
@besrabasant “guys” may be insensitive, consider using “people” or “folks” next time.

**Comment by besrabasant** [comment]
sure... and sorry for that @sapegin

**Comment by sapegin** [comment]
@besrabasant Thanks! 🍕

**Comment by Dvoryan** [comment]
If it is useful to anyone else, the following helped me:

```javascript
module.exports = {
  styles: {
    ExamplePlaceholder: {
      button: {
        display: 'none'
      }
    }
  }
};
```
