### ISSUE TITLE
Cannot run styleguidist along side with laravel development server.

### ISSUE THREAD

**Issue by besrabasant** [styleguidist/react-styleguidist#596]
Hello folks,

I am trying to document my __React Components__ and I am running _styleguidist server_ along side with _Laravel development server_ but the _styleguidist server_ crashes with this error.
```
You have another server running at port 6060 somewhere, shut it down first

You can change the port using the `serverPort` option in your style guide config:
https://react-styleguidist.js.org/docs/configuration.html

```

I have configured the _styleguidist server_ to run at port _6060_ as to resolve this issue and succeeded to run the server only once. After that I am getting this issue again.

How can i resolve this??

**Comment by sapegin** [comment]
Looks like you still have something running on this port. Or the previous Node process stuck for some reason.

Try to [check](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac) which process is listening on this port and kill it.

**Comment by besrabasant** [comment]
@sapegin I tried checking the service running on this port but it returns nothing... It seems there are no services running on this port.

**Comment by SaraVieira** [comment]
@besrabasant Can you try to update to the latest version that runs on 8080 and try again please ?

**Comment by sapegin** [comment]
@SaraVieira Latest version of what? ;-|

**Comment by besrabasant** [comment]
I think there's a conflict while running two instances of `browsersync`.... @sapegin @SaraVieira

**Comment by sapegin** [comment]
Looks it’s not related to Styleguidist then?

**Comment by besrabasant** [comment]
actually styleguidist uses projects native `webpack configuration` and since laravel is already using that *configuration* to run its _browsersync devserver_ so `react-styleguidist` is having problem running the _browsersync devserver_ from same configuration. @sapegin

**Comment by besrabasant** [comment]
I think I need to change the port on which react syleguidist is trying to run the _browsersync server_

**Comment by sapegin** [comment]
Maybe you need to tweak your webpack configuration before passing it to Styleguidists and remove BrowserSync?

**Comment by besrabasant** [comment]
Yeah resolved the issue by ignoring the `browser-sync-webpack-plugin` after requiring the project's _webpack configuration_ . @sapegin @SaraVieira
