### ISSUE TITLE
webpackConfig resolve.extensions doesn't have any effect

### ISSUE THREAD

**Issue by seekshiva** [styleguidist/react-styleguidist#599]
When something isn’t working, include:

- Your style guide config (`styleguide.config.js`):  see example project
- Webpack version: ^3.5.5
- Reproducible demo: [example project](https://github.com/seekshiva/example).

I have a project setup where both native and web versions of a component exist. Just like how react-native apps use .js file extension and platform specific modifications can be done by creating .android.js or .ios.js files with the same name.

I've used the same concept so that `Button.js` provides the native button from react-native package and `Button.web.js` provides the web implementation of the button.

I've done the necessary webpack configuration so that whenever possible, filename.web.js is preferred over filename.js. It works correctly in my project. But in the above sample repo, you can see that Button.js is used even though a Button.web.js file is present. It looks like `resolve.extensions` in the webpack config is not being respected.

**Comment by sapegin** [comment]
It actually works but since we’re using webpack-merge to merge configs the result is this:

```
    "extensions": Array [
      ".js",
      ".jsx",
      ".json",
      ".web.js",
      ".js",
      ".web.js",
    ],
```

I’m not sure what would be the best fix for that, for now you could use `dangerouslyUpdateWebpackConfig` to overwrite default extensions.

**Comment by seekshiva** [comment]
Thanks a lot! That works 🎉

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you have an idea how this could be improved.
