### ISSUE TITLE
Styleguidist inaccessible through DNS resolution

### ISSUE THREAD

**Issue by AkshatM** [styleguidist/react-styleguidist#603]
This is easily verifiable by configuring `/etc/hosts` as so: 

```
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

127.0.0.1           test
```

and then running `styleguidist` through `styleguidist server`. 

I am able to view `styleguidist` content through `localhost:6060` - I cannot do so through `test:6060`, as Styleguidist's Webpack server then decides to respond with just `Invalid host header`.

[`Invalid host header` is now returned by default in `webpack-dev-server@2.4.3^` when the hostname specified in the initial request does not match those in the `devServer.host` settings as a security measure](https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3). Styleguidist currently supports `webpack-dev-server@2.7^`, meaning it is affected by this issue. Currently, [`devServer.host` is set to `0.0.0.0`](https://react-styleguidist.js.org/docs/configuration#serverhost), which makes DNS resolution impossible since the hostname specified in the request is not a raw IP address that webpack-dev-server understands.

We plan to use Styleguidist internally on an AWS box that will be accessed through its hostname - Styleguidist only listens on the internal IP address of that box, which makes it inaccessible from the world outside the internal AWS network, like from my laptop. Manually amending Webpack config options to set the hostname, though feasible, is inflexible to do with simple version control if we want to continue supporting both local running and deployment from a host machine. 

I would imagine this is a common situation that will arise as Styleguidist is more heavily adopted, and the correct resolution should involve support for hostnames. 

Please amend `styleguidist` to support [passing in public hostnames from the command line](https://stackoverflow.com/a/43621275) to the [devServer configuration](https://github.com/styleguidist/react-styleguidist/blob/6dfcabf91775697930f94bbaa46493e6c3210b3d/scripts/create-server.js). It should be possible to pass in `--public` as an option to `styleguidist server` and have it resolve correctly from that address. This preserves `dev-server`'s security.

**Comment by sapegin** [comment]
I’m not really sure what you’re trying to do. Do you want to deploy Styleguidist development server? And what’s the reason to do so instead of deploying a static HTML build?

**Comment by AkshatM** [comment]
We are trying to deploy the development server. Deploying a static HTML build is a good idea we hadn't considered in depth. 

For context, our original reasoning was that a static HTML build would involve relying on two processes, the actual server and the build process, and that would mean more moving parts that we'd need to regulate interaction between, hence discarded. However, in retrospect, this may be a better investment overall. 

Thanks! I'm going to go ahead and investigate deploying as static HTML build instead.

**Comment by leclercb** [comment]
Same problem here.
I develop on one machine, but I test on another one.
I can't access styleguidist from my test machine because I receive "Invalid host header".
Would it be possible to configure this ?
Thanks !

**Comment by sapegin** [comment]
@leclercb You’re use case looks very different though, please open a new issue.
