### ISSUE TITLE
Exposing a compiled <Styleguide> react component

### ISSUE THREAD

**Issue by alampros** [styleguidist/react-styleguidist#605]
Is it possible to expose a compiled styleguide as a renderable react component to include in an existing react app?

I realize this essentially inverts the paradigm, but often times a component library is only a single page of a larger design system. It would be great to be able to use the styleguide with other react-based systems (namely [gatsbyjs](https://www.gatsbyjs.org)) like this.

**Comment by sapegin** [comment]
Probably it would be easier to find a component to include any static HTML into a React app. I’m not sure it’s possible to do exactly what you describe.
