### ISSUE TITLE
Anywhere is editable？

### ISSUE THREAD

**Issue by gwuhaolin** [styleguidist/react-styleguidist#608]
Anywhere in page is editable, like component Title,here is the gif:
![editor-anywhere](https://user-images.githubusercontent.com/5773264/30576417-5477a302-9d3a-11e7-9510-6067748c361c.gif)

Only code can be edit, not anywhere!
Here is my project code:
[code.zip](https://github.com/styleguidist/react-styleguidist/files/1313099/code.zip)

**Comment by sapegin** [comment]
You’re doing it in `reset.scss`:

```css
-webkit-user-modify: read-write-plaintext-only;
```
