### ISSUE TITLE
Exclude components not work

### ISSUE THREAD

**Issue by chaosmirage** [styleguidist/react-styleguidist#615]
Hi.
[how-to-exclude-some-components-from-style-guide](https://react-styleguidist.js.org/docs/cookbook.html#how-to-exclude-some-components-from-style-guide) – it doesn't work.

- Style guide config.
```
module.exports = {
	title: 'React Style Guide Example',
	defaultExample: true,
	components: './lib/components/**/[A-Z]*.js',
	ignore: [
    './lib/components/Button/index.js',
    './lib/components/Button/Button.js'
  ],
	webpackConfig: {
		module: {
			loaders: [
				{
					test: /\.jsx?$/,
					exclude: /node_modules/,
					loader: 'babel-loader',
				},
				{
					test: /\.css$/,
					loader: 'style-loader!css-loader?modules&importLoaders=1',
				}
			]
		}
	},
};
```

- Webpack version.
3.4.1

- Reproducible demo.
[Demo](https://github.com/chaosmirage/react-styleguidist-example)

**Comment by sapegin** [comment]
Try to remove the `.` — it‘s a glob pattern.

**Comment by chaosmirage** [comment]
I tried – don't work.

**Comment by sapegin** [comment]
You need to pass a glob pattern, I’ve updated docs to make it more clear.
