### ISSUE TITLE
Including external resources

### ISSUE THREAD

**Issue by MarkMurphy** [styleguidist/react-styleguidist#624]
I'm trying to add jQuery to my styleguide and have so far been unsuccessful in doing so.

I've tried the following: 

```js
const path = require('path');

module.exports = {
  require: [
    path.join(__dirname, 'assets/js/jquery.js'),
  ],
```

The problem is that jQuery doesn't get added to `window` because I'm unable to list it as an external.

How can I work around this?

**Comment by sapegin** [comment]
I think the easiest way would be to use [custom template](https://react-styleguidist.js.org/docs/configuration#template) and load jQuery from CDN.
