### ISSUE TITLE
Only working with default export

### ISSUE THREAD

**Issue by hwaterke** [styleguidist/react-styleguidist#633]
I don't like default export and always write my components with named exports.

But then the only way to make Markdown examples work is to write the following:
```js
const Title = require('./Title').Title;
<Title>Helloo</Title>
```

Any better way to handle named exports and avoid this `require` in all my examples?

**Comment by sapegin** [comment]
> Any better way to handle named exports and avoid this require in all my examples?

Yes, use default exports.
