### ISSUE TITLE
Verbose flag not working in Node API

### ISSUE THREAD

**Issue by EdwardSalter** [styleguidist/react-styleguidist#637]
When running the styleguidist server via the node API, no output is displayed at all regardless of the value of the verbose flag in the configuration file.

An example repo of this in action is available here: https://github.com/EdwardSalter/example

Run running the server via the node API, I would expect the output to still be displayed. This is a bit of a problem since any output from webpack is swallowed so a broken build is impossible to fix.

I unfortunately cannot run the styleguidist server via the CLI since I need to set various variables and mocks in my code before starting the server.

**Comment by sapegin** [comment]
That’s because any output is disabled by default in the API, I’ve updated the API docs to clarify that.

**Comment by EdwardSalter** [comment]
Ah, thank you for clarifying that. I have just updated my config to add in the `logger` configuration which has enabled some output but webpack output is still not coming through.
I have updated my example repo to force a webpack error and this is the output I get from running via the CLI:

```
...
You can now view style guide in the browser.
  Local:            http://localhost:6060/
  On your network:  http://10.0.75.1:6060/
Loading components:
C:\Development\Other\react-styleguidist-example\lib\components\BabelIgnored\BabelIgnored.js
C:\Development\Other\react-styleguidist-example\lib\components\Button\Button.js
C:\Development\Other\react-styleguidist-example\lib\components\Modal\Modal.js
C:\Development\Other\react-styleguidist-example\lib\components\Placeholder\Placeholder.js
C:\Development\Other\react-styleguidist-example\lib\components\PushButton\PushButton.js
C:\Development\Other\react-styleguidist-example\lib\components\RandomButton\RandomButton.js
./lib/components/BabelIgnored/BabelIgnored.js
Module parse failed: C:\Development\Other\react-styleguidist-example\lib\components\BabelIgnored\BabelIgnored.js Unexpected token (5:4)
You may need an appropriate loader to handle this file type.
| const BabelIgnored = () => {
|   return (
|     <div>
|       Ignored by babel
|     </div>

Learn how to add webpack loaders to your style guide:
https://react-styleguidist.js.org/docs/webpack.html
...
```

and the output I get from the node api:

```text
Listening at http://0.0.0.0:6060
Loading components:
C:\Development\Other\react-styleguidist-example\lib\components\BabelIgnored\BabelIgnored.js
C:\Development\Other\react-styleguidist-example\lib\components\Button\Button.js
C:\Development\Other\react-styleguidist-example\lib\components\Modal\Modal.js
C:\Development\Other\react-styleguidist-example\lib\components\Placeholder\Placeholder.js
C:\Development\Other\react-styleguidist-example\lib\components\PushButton\PushButton.js
C:\Development\Other\react-styleguidist-example\lib\components\RandomButton\RandomButton.js
```

I now get the Loading components text and I can see the components that have been found but I cannot tell why the webpage gives me just a white screen because the webpack error has been swallowed somewhere.

**Comment by sapegin** [comment]
Looks like the CLI does more error handling:

https://github.com/styleguidist/react-styleguidist/blob/bc6e6510a13a785fc80675eee40fc587f34317a2/bin/styleguidist.js#L122-L131

`styleguide.server` returns a webpack compiler instance so you can try to attach an event handler to it and see if it works.

**Comment by EdwardSalter** [comment]
Yep, I have updated my example repo with code duplicated from the bin/styleguidist.js and it is now working as expected displaying the output in the console.
I would have thought that this behaviour would be a layer deeper in the `server` function so that it was the same for both the node API and the CLI.
This at least gives me a way of figuring out why my code doesn't compile so I will close the comment.

Thanks for your help @sapegin.
