### ISSUE TITLE
Styleguidist tries to render code blocks without language tag

### ISSUE THREAD

**Issue by wkillerud** [styleguidist/react-styleguidist#641]
> Any code block with a language tag of `js`, `jsx` or `javascript` will be rendered as a React component with an interactive playground

From the [documentation](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md#usage-examples-and-readme-files) it looks like only code blocks with the language tab `js`, `jsx`, or `javascript` should render React components. However React Styleguidist even tries to render code blocks without a language tag.

A workaround is to lie and mark the block as a valid but non-JavaScript/JSX language, for instance Java.

A repo which demonstrates the issue and workaround with a component called `Dots`: https://github.com/wkillerud/example

I would expect code blocks with no language set to be rendered as a code block and not an interactive version.

**Comment by sapegin** [comment]
This is expected behavior for backwards compatibility, use`static` modifier.

**Comment by wkillerud** [comment]
Allright. Could the documentation perhaps be updated to reflect this then? :) I can update the quoted line and add an entry to the cookbook if you'd like.

**Comment by sapegin** [comment]
We don’t recommend it but I agree it would be nice to mention that it still works ;-) 

I think this is the best place for it: https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md (and it should be mentioned that this is backwards compatible mode, not recommended one).
