### ISSUE TITLE
Styles (inc. inherited font styles) are reset in every preview section

### ISSUE THREAD

**Issue by dallonf** [styleguidist/react-styleguidist#652]
I noticed that Preview sections will aggressively reset many CSS properties back to `initial`. This means if you're using a style like this:

```css
body {
  /* i am not a graphic designer */
  color: red;
}
```

Your default preview will still show black text.

I've currently implemented a `styleguideComponents: { Preview }`-based workaround which re-renders the `Preview` component with the styles I want to be "global", but I expect this is a pretty common use case that should probably be considered.

I apologize, I don't have time to create a repro project right now. I can do that later if needed.

**Comment by sapegin** [comment]
Fell free to send a pull request that adds `color` inheritance:

https://github.com/styleguidist/react-styleguidist/blob/master/src/styles/setupjss.js#L27-L30
