### ISSUE TITLE
Customising/i18n placeholder input text "Filter by name"

### ISSUE THREAD

**Issue by quirico** [styleguidist/react-styleguidist#653]
Hello!

Is there a way to customise and/or translate the placeholder input text "Filter by name" in  TableOfContents component?

Thanks

**Comment by tizmagik** [comment]
You can override the TableOfContents component, https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/TableOfContents/TableOfContentsRenderer.js

See overriding, https://react-styleguidist.js.org/docs/configuration#styleguidecomponents

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
