### ISSUE TITLE
Support for absolute imports

### ISSUE THREAD

**Issue by zerocity** [styleguidist/react-styleguidist#658]
Hi,

on [create react app](https://github.com/facebookincubator/create-react-app/issues/1065) they have a discussion about supporting absolut imports via nested node_modules folder (src/node_modules).

With the current version (6.0.32) of Styleguidist the components are getting render but no changes to the source are recognise of the webDevServer in this folder.

If i change the value to 
`^(?!.*([/\\\\]src[/\\\\]node_modules[/\\\\])).*([/\\\\]node_modules[/\\\\])`
the changes are recognise in src/node_modules. ([other solution](https://github.com/facebookincubator/create-react-app/blob/01a0d737c79e02140c3cc0996d05ebd8a4eb3f84/packages/react-scripts/config/webpackDevServer.config.js#L79) )

I need the possibility to overwrite the ignore property or have a better default.

**Comment by sapegin** [comment]
I’ll be happy to merge a pull request with this feature.

**Comment by sapegin** [comment]
It should be possible now — #690.
