### ISSUE TITLE
Multiple Content Files 

### ISSUE THREAD

**Issue by gandhiamarnadh** [styleguidist/react-styleguidist#659]
We want to show an additional custom view  (that gives the stat of selected lib component usage) along with our library components. The information for this custom view is from another service.

So, before changing all the component read.md files to include this custom view, I want to check is it possible to add second content file path for components in config or any other way to achieve this?

**Comment by sapegin** [comment]
If I understand you correctly you want to have multiple “readme” files for each component?

It’s not possible now but maybe a good idea for a pull request: add a way to return a content of the documentation instead of a file path. Have a look at #621 too.

**Comment by gandhiamarnadh** [comment]
I've addressed my problem with editing all readme.md files now..
It would be great to add a new generic wrapper (over readme.md content with custom props dependent on file name ) like StyleGuideRenderer and Wrapper (over example react components).

**Comment by sapegin** [comment]
Cook, feel free to help with #621 anyway ;-)
