### ISSUE TITLE
When installed globally (npm install -g), styleguidist complains about "Webpack is required"

### ISSUE THREAD

**Issue by mikeaustin** [styleguidist/react-styleguidist#661]
$ styleguidist build -f html -o docs
    Webpack is required for Styleguidist, please add it to your project:

        npm install --save-dev webpack

    See how to configure it for your style guide:
    https://react-styleguidist.js.org/docs/webpack.html

I spent a good 20 minutes trying to figure out why it was complaining. Maybe I missed it in the docs? Is it possible to install it globally?

macOS 10.12.6 (16G29)
npm 3.10.10

**Comment by sapegin** [comment]
Any reason you want to install it globally? Global modules are a bad practice in most cases.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.

**Comment by mikeaustin** [comment]
It may be true that it’s bad practice, but the user experience remains. I feel a message stating that it must be installed locally would be nicer than an erroneous error. My $.02. FYI, I love the live editing!

**Comment by kopax** [comment]
Simple opinion but I am hitting a case where react-styleguidist is a dependency of another module which has webpack.

Any case, if I install this last module, I still must have webpack installed, while I am not using anywhere in my project. Can we arrange the error message not to force webpack to be installed at the latest level?
