### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by unindented** [styleguidist/react-styleguidist#663]
Reproducible on the public example styleguide: https://react-styleguidist.js.org/examples/basic/
~~Not reproducible on `dialog`'s styleguide: https://dialogs.github.io/dialog-web-components/~~ Can also repro there

Issue is that navigation is super broken. See the GIF:

![out](https://user-images.githubusercontent.com/69485/32303227-8f156dd0-bf24-11e7-88aa-48ce60c71350.gif)

- Navigating to a preview and then back results in other previews from the same section disappearing
- Trying to navigate from a preview back to the main page by clicking the little icon doesn't work
- Navigating directly to a preview by changing the URL results in a nasty error
- Back button on the browser seems to do nothing

Why does this not reproduce on `dialog`'s styleguide? How is it different from your basic example?

**Comment by unindented** [comment]
Ah no, `dialog`'s styleguide suffers from the same issues.

**Comment by unindented** [comment]
@sapegin if somebody gives me some pointers (which part of the codebase to look into, approach to take, etc.), I can help.

**Comment by sapegin** [comment]
I think first two issues are related to changes in #617 and definitely a bug that we should fix. Last too looks like routing issue described in #494.

**Comment by sapegin** [comment]
Please have a look at my attempt to fix it: #676. Looks like it fixes all four issues. I see the nasty error only when I try to navigate to a non-existent example.

**Comment by unindented** [comment]
Wow, nice! Thank you for tackling this! (I still don't have enough familiarity with the internals to evaluate your solution, sorry.)
