### ISSUE TITLE
"public" accessor on render() in class means the component is not found.

### ISSUE THREAD

**Issue by rluiten** [styleguidist/react-styleguidist#664]
Loving this tool by the way great turn around on component and style development.

I think I found a bug.
- Appears to me to be a parsing component bug
- Webpack v3.8.1
- Typescript v2.5.3
- tslint v5.8.1

I am using typescript and by default tslint was raising
*  "Requires explicit visibility declarations for class members." for the class member `render()`

I created this tiny example to test with, now if `public` is set for `render()` tslint doest not complain but then styleguidist cant find the component. The component works fine in the application.

```js
import * as React from 'react';

export class TestRow extends React.Component<{}, {}> {
    public render() {
        return <div>Row</div>;
    }
}

export default TestRow;
```

Removing the `public` returns it to working in styleguidist.

I have modified my `tslint.json` as follows so I don't have to use accessors.

* `"member-access": false`

Have included styleguide.config.js and ./styleguide/setup.js just in case.

styleguide.config.js
```js
const path = require('path');

module.exports = {
  title: 'React Components',
  components: 'src/components/guide/*.tsx',
  skipComponentsWithoutExample: true,
  ignore: [],
  require: [
    path.join(__dirname, './node_modules/enhanced-theme/enhanced/mfl.scss'),
    path.resolve(__dirname, './styleguide/setup.js')
  ]
};
```

./styleguide/setup.js referenced from styleguide.config.js
* provides a component to put borders around example components.
```js
// styleguide/setup.js
import DisplayComponent from '../src/components/guide/displayComponent';
global.DisplayComponent = DisplayComponent;
```

**Comment by sapegin** [comment]
Parsing of TypeScript code is done in [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript), I think you should open an issue there.

But I’d disable this TSLint rule. I’m not a TypeScript expect but I don’t see any value in having `public render()` instead of just `render()`.

**Comment by rluiten** [comment]
I am not using react-docgen-typescript.
Thats only required for prop type extraction afaik, and also has other problems for me at the moment.

**Comment by sapegin** [comment]
I believe it’s not a good idea because what’s happening for you, you’re actually using Flow syntax that is supported by react-docgen by default. But as soon as you start using something, that isn’t supported by Flow, like `public` it stops to work.
