### ISSUE TITLE
Also include sections for unrecognized components

### ISSUE THREAD

**Issue by jfschwarz** [styleguidist/react-styleguidist#665]
Due to the limitations of 'react-docgen` there are components which will not be recognized, e.g., when I import a component, apply a HOC, and export the result. For these components Styleguidist will generate warnings like:

> Warning: src/components/EnhancedComponent.js matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.

Why doesn't Styleguidist simply include sections for these unrecognized components in the generated style guide, too?

I get that we won't be able to get the props documentation, but at least that component would be listed as part of style guide and we could add docs and examples for it. That seems better than just omitting it altogether.

**Comment by sapegin** [comment]
Sounds reasonable ;-)

Would be nice if you can comment out this code and check if it would actually work.
