### ISSUE TITLE
require font?

### ISSUE THREAD

**Issue by eduardoinnorway** [styleguidist/react-styleguidist#666]
It does not load font?

require: [
    'babel-polyfill',
    path.join(__dirname, 'node_modules/bootstrap/less/bootstrap.less'),
    path.join(__dirname, 'assets/stylesheets/global-styles.less'),
    path.join(__dirname, 'assets/fonts/glyphicons-halflings-regular.woff2'),
  ],

**Comment by sapegin** [comment]
Please make a demo project that we can debug based on this repo: https://github.com/styleguidist/example

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
