### ISSUE TITLE
HMR doesn't work after upgrading from v6.0.17 to v6.0.31

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#668]
Somewhere between v6.0.17 and v6.0.31 the HMR stopped working:

https://github.com/styleguidist/react-styleguidist/compare/v6.0.17...v6.0.31

My config:

```js
/* eslint-env node */

const path = require('path');
const loaders = require('loaders');

module.exports = {
  components: 'src/content/app/components/ui/**/[A-Z]*.jsx',
  require: [
    './build/dev/web/fx/feedly-fx.css', // Require FX CSS
  ],
  showCode: true,
  showUsage: true,
  skipComponentsWithoutExample: true,
  webpackConfig: {
    resolve: {
      alias: {
        // Shortcut to __fixtures__
        __fixtures__: path.join(__dirname, 'src', '__fixtures__'),

        // Override Styleguidist components
        'rsg-components/Examples/ExamplesRenderer': path.join(
          __dirname,
          'src/styleguide/components/ExamplesRenderer'
        ),
      },
    },
    module: {
      loaders: loaders.all,
    },
  },
};

```

**Comment by sapegin** [comment]
> but did HMR work with persisting the state before?

A long time ago but it was buggy, now we’re using vanilla webpack hot reload.

**Comment by okonet** [comment]
Hmm, I'm wondering why it didn't work. I heard lots of "not working" recently and would love to hear some details on that.

**Comment by sapegin** [comment]
I don’t even think it’s necessary and worth added complexity. Also all of the HMR solutions are half-deprecated. But if you have time to investigate that, feel free to send a PR ;-)

**Comment by okonet** [comment]
I'm more wondering since I'm integrating it at Feedly right now ;)

**Comment by sapegin** [comment]
@okonet What should we do with this issue?
