### ISSUE TITLE
Styleguidist server not accessible from another host than localhost

### ISSUE THREAD

**Issue by leclercb** [styleguidist/react-styleguidist#669]
I develop on one machine, but I test on another one.
I can't access styleguidist from my test machine because I receive "Invalid host header".

I looks like the server only answers on 0.0.0.0.

Would it be possible to configure this when starting the server ?
Thanks !

**Comment by sapegin** [comment]
Do you know how to configure webpack-dev-server for that? It supposed to be accessible with 0.0.0.0 instead of `localhost`.

But actually it works for me, I’ve just tried to follow the instructions:

```
> styleguidist server

You can now view style guide in the browser.

Local:            http://localhost:6060/

On your network:  http://11.22.33.44:6060/
```

and was able to open the style guide from by phone, both are in the same network.

**Comment by leclercb** [comment]
Indeed, when I use the ip of the dev machine directly (in your example http://11.22.33.44:6060/) it works.
However, when I use a hostname (example "xyz" pointing to 11.22.33.44) via /etc/hosts, it doesn't work when trying to access http://xyz:6060.

Anyway, not a bit deal, as I can use the ip of the machine directly, which I didn't try before :(

**Comment by sapegin** [comment]
Looks like you need to use the `public` option for dev server and we shouldn’t do this by default because it would open style guide server for everyone:

https://github.com/webpack/webpack-dev-server/issues/882

**Comment by leclercb** [comment]
Not by default of course, but maybe that could be an option in the styleguide.config.js ?

**Comment by sapegin** [comment]
You can change any webpack dev server options via `devServer` option in webpack config.

**Comment by leclercb** [comment]
Thanks ! Problem solved.

**Comment by sapegin** [comment]
Would be nice if you could add this info to the docs though ;-)

**Comment by leclercb** [comment]
Pull request created:
https://github.com/styleguidist/react-styleguidist/pull/671
