### ISSUE TITLE
suppor for react-native?

### ISSUE THREAD

**Issue by Memoyr** [styleguidist/react-styleguidist#675]
Hi , 
Sorry I can't find information about if styleguidist will work with react-native components ? 
If no, is it on your roadmap ?

Thanks

**Comment by sapegin** [comment]
Try it, I don’t know ;-)

**Comment by Memoyr** [comment]
ok thanks , I will.

**Comment by Gregor1971** [comment]
@Memoyr, I just got styleguidist working with react-native.  See [this branch ](https://github.com/Gregor1971/react-native-elements/tree/react-native-web)for an example.

**Comment by sapegin** [comment]
@Memoyr Would be nice if you can add some info to the docs ;-)

**Comment by Gregor1971** [comment]
I'm making an example using styleguidist that will have a simpler configuration than the one I linked.  We should use that once it's done.  I'd be happy to submit a PR for the docs.

Just to be clear - this is using react-native-web, so it's not full react-native.  Full react-native would require a substantial re-write of styeguidist.

**Comment by Memoyr** [comment]
ok thank you @Gregor1971

**Comment by alexmngn** [comment]
@Gregor1971 I tried your branch but I get an error: 

```
Module build failed: Error: spawn /Users/alexmngn/Workspace/react-native-elements/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at _errnoException (util.js:1041:11)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)

    at onErrorNT (internal/child_process.js:374:16)

    at _combinedTickCallback (internal/process/next_tick.js:138:11)

    at process._tickCallback (internal/process/next_tick.js:180:9)

 @ ./src/rating/Rating.js 21:17-47

 @ ./src/index.js

**Comment by kumarpatel** [comment]
FYI. https://github.com/styleguidist/react-styleguidist/pull/816

**Comment by dilnara** [comment]
So, do I understand right that it's react-native-web in fact, not react-native? Or it's really NATIVE app that is run on the device?

**Comment by kopax** [comment]
@dilnara, react-native-web
