### ISSUE TITLE
Styleguide previews have extra unstyled wrappers

### ISSUE THREAD

**Issue by gscottolson** [styleguidist/react-styleguidist#678]
Thanks for working so hard on React Styleguidist. I am loving what I am seeing.

I want to know if there is a quick fix to this issue. I am happy to open a PR with solution, but maybe I am missing something obvious.

I want to style a preview to be a specific height. My embedded React component uses`height: 100%`, which means it relies on the parent element’s height. I can style the `example wrapper` as noted in the docs:

<img width="447" alt="2017-11-10-screenshot-1" src="https://user-images.githubusercontent.com/220979/32684207-5c1ec49e-c636-11e7-9c5a-1f70a017f13c.png">

My custom styles look like:

` ```jsx { "props": { "style": { "height": "80vh" } } } ...`

This works as noted, but there are two nested `<div>`s inside of the `<div class="rsg--preview">` container. Since neither of these `<div>`s provide height styles (e.g. `height: inherit;`), the preview’s height is different than the components. Here is a screenshot from Chrome Dev Tools:

<img width="571" alt="2017-11-10-screenshot" src="https://user-images.githubusercontent.com/220979/32684145-bbb3a8f8-c635-11e7-8f5f-067ac9787568.png">

It seems like a tough problem to solve, but maybe there is a quick win here. Like passing the styles to the preview wrapper to each of the nested child elements. Or maybe setting the child elements to `height: inherit` if `height` is set on the preview.

Thoughts?

**Comment by sapegin** [comment]
Yeah, it won’t be easy. These two divs are rendered here:

https://github.com/styleguidist/react-styleguidist/blob/29b8f9039419c43b368eaeea88fce40950700a72/src/rsg-components/Preview/Preview.js#L153-L154

This is also connected to a new plugin API — I may have made it worth with the new Container component — #505.

For your use case I’d suggest to try to replace the Wrapper component — it’s rendered inside these two empty divs.

Any ideas how to solve it in a generic way would be super cool! I’m not sure I know any good solutions now.

**Comment by gscottolson** [comment]
Documenting my fix for others…

I was able to style these wrapper `<div>`s using JSS nested syntax:

```
module.exports = {
  ...
  styles: {
    Playground: {
      preview: {
        '& > div, & > div > div': {
          height: '100%'
        }
      }
    }
  }
  ...
}
```

**Comment by sapegin** [comment]
I think we can close this.
