### ISSUE TITLE
Changes in `assetDir` do not cause a reload in dev server

### ISSUE THREAD

**Issue by esturcke** [styleguidist/react-styleguidist#682]
The dev server does not reload the page when files in `assetDir` change. I'm not sure if this is intentional, but I would find it helpful if the page would reload.  I think [`watchContentBase`](https://webpack.js.org/configuration/dev-server/#devserver-watchcontentbase) in `create-server.js` would get the dev server to reload.

This can be reproduced with [this repo](https://github.com/esturcke/styleguidist-no-reload-on-asset-change-bug):

1. `git clone git@github.com:esturcke/styleguidist-no-reload-on-asset-change-bug.git`
2. `cd git@github.com:esturcke/styleguidist-no-reload-on-asset-change-bug.git`
3. `yarn`
4. `yarn start`
5. Navigate to [http://localhost:6060/](http://localhost:6060/).
6. `cp public/{update,image}.png`

The page does not reflect the new image until the page is manually reloaded.

**Comment by sapegin** [comment]
Could you try `watchContentBase` and check if it helps here? You can set it via webpack config.

**Comment by esturcke** [comment]
Yup, this works:

```diff
diff --git a/public/image.png b/public/image.png
index f71184c..a7a4c53 100644
Binary files a/public/image.png and b/public/image.png differ
diff --git a/styleguide.config.js b/styleguide.config.js
index f08946b..9daf5bc 100644
--- a/styleguide.config.js
+++ b/styleguide.config.js
@@ -4,6 +4,9 @@ module.exports = {
   components: './lib/components/**/[A-Z]*.js',
   assetsDir: 'public',
        webpackConfig: {
+               devServer: {
+                       watchContentBase: true,
+               },
                module: {
                        loaders: [
                                {
```

**Comment by esturcke** [comment]
To keep using CRA's webpack config, it looks like I can do something like: 

```diff
diff --git a/styleguide.config.js b/styleguide.config.js
index f08946b..675270e 100644
--- a/styleguide.config.js
+++ b/styleguide.config.js
@@ -18,4 +18,8 @@ module.exports = {
                        ]
                }
        },
+       dangerouslyUpdateWebpackConfig: config => ({
+               ...config,
+               devServer : { watchContentBase: true }
+       }),
 };
```

**Comment by sapegin** [comment]
Cool! Do you want to send a PR that enables watchContentBase?

**Comment by esturcke** [comment]
Sure, I can work on this. Did you want this as a configuration flag or always set to true? Defaulting to true would be good for me, but I'm not sure if there are drawbacks. I'm not sure why webpack decided to default to false.

**Comment by sapegin** [comment]
I would enable it when `assetDir` is set. I don’t think we need an extra flag for that.

https://github.com/styleguidist/react-styleguidist/blob/8f76515c7d5cec85c01ba512a340a4eac8d53f0d/scripts/create-server.js#L19
