### ISSUE TITLE
Reset state after example

### ISSUE THREAD

**Issue by pke** [styleguidist/react-styleguidist#692]
Is there a way to further isolate examples?

I have 2 examples that are using a function to modify some kind of registry
`addExtension("Hello1", MyExtension1)`
`addExtension("Hello2", MyExtension2)`

However when the 2 examples have been run the registry then contains "Hello1" and "Hello2". In true isolation the registry should only always contain one either "Hello1" or "Hello2" at any time.

Therefore I wonder if there is a way to hook a function that runs *after* (similar to the props way for each example) the example has been rendered?
I could then call my `removeExtension` function after each example has been rendered.

**Comment by sapegin** [comment]
Looks like you need to restructure your code and make it easier to test.

**Comment by pke** [comment]
Maybe. But the setup works in real apps just fine. The idea is there is global, app wide registry for extensions. All this is also very testable in my unit tests. Adding a function to the registry to clear it would still not help in this case, as examples can not run this code, because the last line in the example must be the rendered component.

**Comment by sapegin** [comment]
I’m not sure we should support hat in Styleguidist. How about using dependency injection and make the function with side effect replaceable via props?

**Comment by pke** [comment]
I'm thinking about using react context. Which would not change the signature of the component. It would then either use context or the global function to get its data.

**Comment by pke** [comment]
I found a solution for my component. It uses now the provider pattern known from `redux` and others and its very good testable now. It can also run examples in styleguidist now in isolation.
