### ISSUE TITLE
use same build strategy as create-react-app

### ISSUE THREAD

**Issue by lifeiscontent** [styleguidist/react-styleguidist#694]
using the path from homepage, create-react-app will built its assets relative to the url you've specified.

Example: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages

it would be cool if react-styleguidist followed these conventions as well so I don't have to create my own rewrite strategy.

**Comment by sapegin** [comment]
Could you please elaborate how exactly it should work? I guess reading the same field won’t help.

**Comment by lifeiscontent** [comment]
whatever is after the domain name is used to map assets to their proper destinations.

e.g. if the styleguide was hosted at `https://example.com/foobar` all relative urls would have `/foobar` as a prefix to their original urls.

**Comment by lifeiscontent** [comment]
@sapegin

**Comment by sapegin** [comment]
So you want a similar option in Styleguidist config? Feel free to send pull request for that.

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.
