### ISSUE TITLE
Question: How does styleguidist determine the initialState in the code?

### ISSUE THREAD

**Issue by larabueno-paloit** [styleguidist/react-styleguidist#695]
Hi!

May I know how does styleguidist determine the initialState, the functions or the things that needs to be rendered in the code?

Thanks!

**Comment by sapegin** [comment]
Not sure I understand your question, `initialState` is described here: https://react-styleguidist.js.org/docs/documenting.html#writing-code-examples

**Comment by larabueno-paloit** [comment]
Thanks for the link but I'm more curious to know how the styleguidist handles it? not really the usage of it.

**Comment by sapegin** [comment]
You can check the code ;-) Basically it wraps your example code in a component with a state and then eval the example code wrapped in `with` that has `initialState` setter that calls `setState` of the wrapper component:

https://github.com/styleguidist/react-styleguidist/blob/a02e79362665d1db02c922e2d072317aa25ecd24/src/rsg-components/Preview/Preview.js#L124-L135

**Comment by larabueno-paloit** [comment]
Thanks for the quick response! I'll just check the file then :)
