### ISSUE TITLE
unable to customize TabButtonRenderer 

### ISSUE THREAD

**Issue by thecodejack** [styleguidist/react-styleguidist#698]
I am trying to customize TabButtonRenderer by following config.

```
styleguideComponents: {
    StyleGuideRenderer: path.join(__dirname, 'src/styleguide/StyleGuideRenderer'),
    TabButtonRenderer: path.join(__dirname, 'src/styleguide/TabButtonRenderer')
  },
```

custom `StyleGuideRenderer` is taken properly and work fine but fails to do same with custom `TabButtonRenderer`. I tried debug the issue and even observed that paths are added correctly to webpack.resolve in `make-webpack-config.js`.

react-styleguidist: 6.0.33
webpack: 3.8.1
react: 15.6.2

**Comment by sapegin** [comment]
I’ll need to debug it too. It looks correct: your code and the original TabButtonRenderer component.

**Comment by thecodejack** [comment]
debugged the issue. my bad. Started working with `TabButton` rather `TabButtonRenderer`. Following worked.

```
styleguideComponents: {
    StyleGuideRenderer: path.join(__dirname, 'src/styleguide/StyleGuideRenderer'),
    TabButton: path.join(__dirname, 'src/styleguide/TabButtonRenderer')
  },
```


Closing this here. It would be better if we have list of possible renderers and respective keys needed in documentation.

**Comment by sapegin** [comment]
Feel free to send a PR if you can find a way to generate such a list ;-)

**Comment by thecodejack** [comment]
Sure..will do
