### ISSUE TITLE
No live reload on CSS Modules

### ISSUE THREAD

**Issue by sylvainar** [styleguidist/react-styleguidist#699]
Hey !

My team and I are using styleguidist on a new project, and we're using css modules and scss. For each component, I've got a folder looking like this:
- Component
  - Component.jsx
  - Component.md
  - Component.scss

The problem is that I save my .scss file, it doesn't autoreload the styleguide.

Thanks !

**Comment by sapegin** [comment]
We have a `customised` example in the repo that uses CSS Modules and it works fine. I also use CSS Modules with Sass at work without any issues. 

Please make a demo project that we can debug based on this repo: https://github.com/styleguidist/example

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
