### ISSUE TITLE
How to use Material Icons in documentation?

### ISSUE THREAD

**Issue by Harshit369** [styleguidist/react-styleguidist#700]
Is there any way to render Material Icons that I have been using through CDN like this? 
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
``` 
It displays the icon name rather than the actual icon.

Thanks!

**Comment by sapegin** [comment]
Please make an example as [described here](../blob/master/Issue_Template.md).

**Comment by sidharthmehra** [comment]
@Harshit369 you can add a styleguide.config.js
and within it:
```
export {
   template: './template.html'
}
```
In template.html add ```<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">``` within the head tag.

**Comment by Harshit369** [comment]
@sidharthmehra Thanks a lot !! It worked very well.
Just for anybody following this thread, you also have to add:
`<div id="app"></div>` 
inside your <body> In your template.html file. Otherwise, it will throw something like this:
![Target container is not a DOM element.](https://user-images.githubusercontent.com/7912702/33676030-99350718-dada-11e7-9f4b-92b5b549d3dc.png)

**Comment by sapegin** [comment]
More correct would be: you *should not* remove it.
