### ISSUE TITLE
Theme variable for tab button text transform style

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#702]
Add a new variable to the [theme](https://github.com/styleguidist/react-styleguidist/blob/master/src/styles/theme.js) and use it instead `textTransform: 'uppercase'` in the [TabButton](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/TabButton/TabButtonRenderer.js) component.

**Comment by jmurret** [comment]
@sapegin, is something like this what you had in mind : https://github.com/styleguidist/react-styleguidist/pull/728 ? 

I've tested it by changing it to capitalize and seeing the updated example 'VIEW CODE' change to 'View Code'.

Happy to modify this if you had something else in mind.
