### ISSUE TITLE
Incorrect cursor on headers

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#703]
It shows text cursor instead of a pointer:

![image 2017-11-24 at 2 52 58 pm](https://user-images.githubusercontent.com/70067/33213281-3ad7483c-d127-11e7-9e86-db90d8a71136.png)

**Comment by sanjsanj** [comment]
Is the desired behaviour that it should just show a pointer and no underline on hover on desktop, and click on device?

```
<h1 class="rsg--root">
  <a class="rsg--heading">  // <-- this element
    ...
  </a>
</h1>
```

**Comment by sapegin** [comment]
It has an underline on hover already, but it has incorrect cursor.

**Comment by jmurret** [comment]
Should be fixed with this PR: https://github.com/styleguidist/react-styleguidist/pull/727

Chrome did not show this behavior for me, but Firefox did.  Verified that it was corrected with above PR.
