### ISSUE TITLE
Format docs with Prettier

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#704]
* Add script to `package.json` that will format Markdown files with Prettier.
* Run it as part of `npm test`

Config could be similar to https://github.com/sapegin/blog.sapegin.me/blob/master/.prettierrc

**Comment by UmenR** [comment]
Hey @sapegin  I'd like to take this up! but before i start i have a question to ask. Im  a tad new to this so if i want to run prettier as part of `npm test` i could add it to the end of the current test script with a semicolon right? but doing so would mean that if jest failed prettier wont run either. Im assuming that's not an issue ?  and also do you want me to format the all the `.md` files before i submit a PR ? :smile:

**Comment by sapegin** [comment]
@UmenR Hey! Thanks for your interest, there’s a PR already: https://github.com/styleguidist/react-styleguidist/pull/709

There are two ways chain npm scripts:

1. Use `&&`: `npm run test:jest && npm run format:md` — in this case if Jest fails it won’t run Prettier.
2. Use `pre*` or `post*` scripts like `pretest` or `posttest`, you can find an example in our package.json.

**Comment by UmenR** [comment]
Oh did not see that PR :smile:  Thanks for the response :+1:
