### ISSUE TITLE
Using recompose components don't get found

### ISSUE THREAD

**Issue by lifeiscontent** [styleguidist/react-styleguidist#705]
As title describes, when I create a UI component using recompose react-styleguidist doesn't pick up that it's a react component and doesn't render it to the styleguide. E.g. when using the`componentFromProp` hoc.

**Comment by sapegin** [comment]
I believe this will fix that: #657.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.

**Comment by diegohaz** [comment]
I'm getting the same behavior as @Didericis

**Comment by jesstech** [comment]
It would be nice to get to the bottom of this.  This is what is preventing us from switching to Emotion.js with its use of recompose.

**Comment by santaclauze** [comment]
Problem not yet solve?

**Comment by kopax** [comment]
@sapegin, does #657 solved the issue with redux and propTypes tables?

We still cannot get propType table if the component is connected with redux. We had to split our UI component and the connect logic in order to be able to display our propTypes.

**Comment by sapegin** [comment]
I don't know, try it ;-)

**Comment by kopax** [comment]
@sapegin, well, as I said, we have tried. As an user and the main maintainer, did you experience issues while trying to generate the documentation for `react-redux` ?
