### ISSUE TITLE
ComponentsListRenderer extending not works

### ISSUE THREAD

**Issue by jeradrutnam** [styleguidist/react-styleguidist#710]
Tried extending the `ComponentsListRenderer.js` component. And it s not working as expected. I tried extending other `*Renderer` components and works fine, except this one.

styleguide.config.js

```js
...
styleguideComponents: {
    ComponentsListRenderer: path.join(__dirname, 'styleguide/components/ComponentsListRenderer'),
},
...
```

**Comment by sapegin** [comment]
Please make a demo project that we can debug based on this repo: https://github.com/styleguidist/example

**Comment by jeradrutnam** [comment]
Sure I will do. :)

**Comment by danwoodbury** [comment]
im getting this issue too, very strange

**Comment by sapegin** [comment]
@danwoodbury 

> Please make a demo project that we can debug based on this repo: https://github.com/styleguidist/example

**Comment by Mikrovolnovka** [comment]
In the scope of anybody else will face this issue, I've got the fix to this.
I've met the same thing with HeaderRenderer and looked into `index.js` file:

```
export { default } from 'rsg-components/Heading/HeadingRenderer';
```

So we should override not the `HeadingRenderer` but `Heading` component
The same thing is with `ComponentsListRenderer`: https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/ComponentsList/index.js

We should override the `ComponentsList`, not the `ComponentsListRenderer` component

**Comment by HipsterZipster** [comment]
When is 6.2.0 slated for release? Looking forward to this fix!

**Comment by sapegin** [comment]
Out in [6.2.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.2.0)!

@HipsterZipster
