### ISSUE TITLE
Disable HMR option

### ISSUE THREAD

**Issue by KrickRay** [styleguidist/react-styleguidist#711]
We do not use HMR in projects. Now I could not disable HMR either through webpackConfig, or through dangerouslyUpdateWebpackConfig.

**Comment by sapegin** [comment]
What issues do you have because of HMR?

**Comment by KrickRay** [comment]
@sapegin I think we could get over it. I just wanted more configuration. Perhaps you can close or leave for discussion, because unfortunately I did not check everything up to the end and the self-written version  was based on your loaders.  It would be nice if you made them in separate packages.

**Comment by sapegin** [comment]
I believe you’ll be able to disable HMR after: #690.

Which loaders do you mean?

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
