### ISSUE TITLE
Investigate JSX fragments

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#713]
Could be useful to show multiple examples of a component:

```jsx
<div>
  <Button size="small">Hello</Button>
  <Button size="medium">Hello</Button>
  <Button size="large">Hello</Button>
</div>
```

→

```jsx
<>
  <Button size="small">Hello</Button>
  <Button size="medium">Hello</Button>
  <Button size="large">Hello</Button>
</>
```

https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

* To enable fragments support in code examples we’ll need dependencies to support them first:
  * ~~Buble: https://github.com/Rich-Harris/buble/issues/62~~
  * ~~CodeMirror: https://github.com/codemirror/CodeMirror/issues/5101~~
  * ~~Highlight.js seems to work fine~~
* ~~Or maybe later we can wrap examples in fragments automatically?~~ — done in #842

**Comment by albertogasparin** [comment]
+1 on wrapping examples in fragments automatically. So the consumer doesn't have to care and any code just works ;)

**Comment by sapegin** [comment]
> any code just works ;)

@albertogasparin That’s the hard part here because you can have something like this:

```js
const foo = 'bar';
<Button>{foo}</Button>
```

**Comment by albertogasparin** [comment]
Well, I haven't looked at the current implementation but my thought was that anything before the first jsx element would have been treated as plain javascript, then from the first `<Something` will be wrapped with a `React.Fragment`. Am I wrong?

**Comment by sapegin** [comment]
That’s very naïve: `<Something` is not necessary a JSX element, maybe `if (x<Something)`. The easiest way I see now is to wrap examples in `React.Fragment` only when they have JSX and no regular JS.

**Comment by abottega** [comment]
Does styleguidist support <fragment></fragment> in the markdown example files now? Or is this still being worked on?

**Comment by sapegin** [comment]
We now have autowrapping in React.Fragment, JSX fragments syntax also works and looks good:

![image 2018-04-02 at 11 06 06 am](https://user-images.githubusercontent.com/70067/38190864-7bebfb02-3666-11e8-9d00-baa163a15db6.png)
