### ISSUE TITLE
Styled-components ThemeProvider solutions ?

### ISSUE THREAD

**Issue by Memoyr** [styleguidist/react-styleguidist#715]
Hi,
Anyone tried to use it with styled-components [ThemeProvider](https://www.styled-components.com/docs/advanced#theming) ? 
I have tried without any success to implement with a Wrapper similar as what is documented for Redux [here](https://react-styleguidist.js.org/docs/thirdparties.html#styled-components).

**Comment by Memoyr** [comment]
Actually, I got it working. 
I had similar problem as seen in here [#578](https://github.com/styleguidist/react-styleguidist/issues/578)

**Comment by sbmadhav** [comment]
@Memoyr - How did you get it to work? I keep getting `TypeError: Cannot read property 'children' of undefined`
