### ISSUE TITLE
Tagged template strings are not supported

### ISSUE THREAD

**Issue by pke** [styleguidist/react-styleguidist#720]
I want to include the following styled-components example:

```jsx
const styled = require("styled-components");

const StyledBalance = styled(Balance)`
  &.positive {
    color: green;
  }
  &.negative {
    color: red;
  }
`;

<StyledBalance amount="42"/>
```

But rendering fails with this error message:

```
CompileError: Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (3:22)
1 : const styled = require("styled-components");
2 : 
3 : const StyledBalance = styled(Balance)`
```

Is this a react-docgen error or coming from react-styleguidist? It fails to mention where I have to put the `transforms: { templateString: false }`

**Comment by sapegin** [comment]
You can enable it here: https://react-styleguidist.js.org/docs/configuration#compilerconfig

**Comment by pke** [comment]
@sapegin I added this:

```
compilerConfig: {
  templateString: false,    
  dangerousTaggedTemplateString: true,
},
```

or

```
compilerConfig: {
    dangerousTaggedTemplateString: true,
},
```

or 

compilerConfig: {
  templateString: false,    
```

And still get the same error all the time. Styleguidist was restarted. Do you know of any user that successfully uses styled components in example files?

What other way would there be to provide styles for an example when I need to demo the `className` prop and not want to resort to inline styles?

**Comment by okonet** [comment]
Yes, just ran across this one. @pke can you create a PR please?

**Comment by MiguelMadero** [comment]
While this works, why is it considered "dangerous"?

**Comment by sapegin** [comment]
I guess because the transformation isn't fully spec-compliant?

**Comment by gazpachu** [comment]
I've just run on this one too. The fix worked but I still get this error `TypeError: styled is not a function`.  The module is loading correctly using `const styled = require('styled-components');` so I don't know what's wrong. Anyone had this before? @pke @okonet @sapegin

**Comment by gazpachu** [comment]
Fixed `const {default: styled } = require("styled-components");`
