### ISSUE TITLE
Custom DefinePlugin being ignored

### ISSUE THREAD

**Issue by renancouto** [styleguidist/react-styleguidist#726]
I am trying to pass some env vars to my components using webpack's `DefinePlugin`, but I keep getting only `{ NODE_ENV: 'development' }` on `process.env`.

I forked the [example](https://github.com/renancouto/example) repo, as an example. This is my setup: https://github.com/renancouto/example/commit/980967e7df67aaa0c26423a604c521f240586313

**Comment by sapegin** [comment]
That’s the reason:

> When defining values for process prefer 'process.env.NODE_ENV': JSON.stringify('production') over process: { env: { NODE_ENV: JSON.stringify('production') } }. Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined. 

https://github.com/styleguidist/react-styleguidist/blob/c39394c9850b51e17974d9331860260ebdebc84e/scripts/make-webpack-config.js#L44-L49
