### ISSUE TITLE
Using with lerna

### ISSUE THREAD

**Issue by danwoodbury** [styleguidist/react-styleguidist#735]
Im using this in a lerna package, which works to a certain extent except from a couple of issues.

My file structure is:
```
packages/
-- Button/
---- readme.md
---- src/
------ index.tsx
------ index.test.tsx
```

I can get styleguidist to see that there is a component there and get it to load the readme but it always displays the component title as **'index'**, so every component in the styleguide is named **'index'**. I have tried setting a handler exactly as shown in the docs but it didnt even seem to run let alone make a difference to the output.

Also, the examples do not work, it says `ReferenceError: Button is not defined` just above the code preview, im assuming this is because it is trying to import a file named `Button.tsx` rather than `index.tsx` where the component is actually located.

Is there a way to fix this?

**Comment by sapegin** [comment]
> im assuming this is because it is trying to import a file named Button.tsx rather than index.tsx where the component is actually located.

Most likey it registers the component as `index`.

How do you export your component? I guess it’s an issue with [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript):

https://github.com/styleguidist/react-docgen-typescript/blob/cf90374b93821f8d41257b21ec372d4b7975bda7/src/parser.ts#L349-L358

**Comment by danwoodbury** [comment]
the component is exported in a standard way:
`export default class Button extends React.Component<ButtonProps, {}> {`

**Comment by sapegin** [comment]
You need to use named exports as described in their docs.

**Comment by danwoodbury** [comment]
can you give me an example of how to do this?

**Comment by sapegin** [comment]
Please follow instruction in the docs: https://github.com/styleguidist/react-docgen-typescript

**Comment by danwoodbury** [comment]
Perfect, all working well now. Thanks for the pointer in the right direction
