### ISSUE TITLE
Escape hatch to just add <link> tag to load a css file

### ISSUE THREAD

**Issue by arackaf** [styleguidist/react-styleguidist#737]
I searched all over, but came up empty. 

Is there an escape hatch to tell react-styleguidist to "just add <link> tags for some css files I specify?"  I've already once in my life attempted to get all of webpack's loaders just right so bootstrap would load, but wound up quitting, and opting for a plain and simple <link> tag in my html file. 

Does such an option exist here?

**Comment by arackaf** [comment]
For the benefit of anyone else finding this issue, the solution is to just use the template option, and provide your own html file with whatever script or link tags you want.

It seems styleguidis expects there to be a div with an id of app, so be sure to include that.  ie

```html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="app"></div>
    </body>
</html>
```

**Comment by sapegin** [comment]
Would be nice to add an example here: https://react-styleguidist.js.org/docs/cookbook.html ;-)

**Comment by arackaf** [comment]
I'll see what I can do :)

**Comment by stonebk** [comment]
Also looks like you can use `template.head.raw`:
https://react-styleguidist.js.org/docs/configuration.html#template
https://github.com/vxna/mini-html-webpack-template#readme
