### ISSUE TITLE
Global components unavailable in component specific routes

### ISSUE THREAD

**Issue by corygibbons** [styleguidist/react-styleguidist#738]
Noticing an issue with the `v6.1.0` release where when visiting a component specific route eg. _(http://localhost:6060/#!/Placeholder)_ all components other than `Placeholder` are not available.

`ReferenceError: Button is not defined`

Which seems to go against:
>Code examples in Markdown use the ES6+JSX syntax. They can access all the components of your style guide using global variables:

Example repo here: https://github.com/corygibbons/styleguidist-example

Works when you navigate from the main index, but as soon as you refresh the error comes up. 🤷‍♂️

**Comment by lgordey** [comment]
@sapegin Hi man!
When do you plan to release **6.2.0.**?

I really need this feature and some others from this scope :)

Btw, thanks for awesome project! 👍

**Comment by sapegin** [comment]
@lgordey Will try to release this or next week.

**Comment by sapegin** [comment]
Out in [6.2.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.2.0)!

@lgordey

**Comment by ShyamRaj** [comment]
I still see this error in the latest version @7.0.14.
