### ISSUE TITLE
Unneccassary <p> tag in props and methods description

### ISSUE THREAD

**Issue by gazzwi86** [styleguidist/react-styleguidist#740]
v6.1.0

I have noticed the alignment in the props and methods description is off, due to an additional paragraph tag.  Simple enough fix, just thought I would flag it.  Will add a PR if I get change today.

<img width="542" alt="screen shot 2017-12-19 at 11 10 12" src="https://user-images.githubusercontent.com/1395135/34154376-37230de0-e4ad-11e7-9644-4aeeef80b899.png">

**Comment by sapegin** [comment]
Thanks, PR would be very nice ;-)

**Comment by gazzwi86** [comment]
@sapegin it looks like the issue is with the Markdown plugin.  Is that required in this instance, since its just grabbing text from a code comment?

**Comment by sapegin** [comment]
Yes, it’s required — we support Markdown in comment. And most likely it’s an issue in our code. 

How to reproduce it? I don’t see it in the example style guide.

**Comment by gazzwi86** [comment]
The Proptypes here are those shown in the picture:

```
import React from 'react';
import PropTypes from 'prop-types';
import styles from './styles';

/**
 * A basic html image
 *
 * @param {object} props - properties pass to and used by the component, @see propTypes
 * @param {string} props.source - the image src to display (Path or base64)
 * @param {string} props.alt - alternative text describing the image
 * @returns {object} - a react compatible component
 */
const Image = props => (
  <div style={styles.container}>
    <img src={props.source} alt={props.alt} style={styles.image} />
  </div>
);

Image.propTypes = {
  /** The image src to display (Path or base64) */
  source: PropTypes.string.isRequired,
  /** Alternative text describing the image */
  alt: PropTypes.string,
};

Image.defaultProps = {
  alt: '',
};

export default Image;
```

**Comment by sapegin** [comment]
I can’t reproduce it in an example styleguide:

![image 2017-12-20 at 9 51 58 am](https://user-images.githubusercontent.com/70067/34198642-6f4fc406-e56b-11e7-8244-d44cf3646049.png)

Please make a demo project that we can debug based on this repo: https://github.com/styleguidist/example

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
