### ISSUE TITLE
Add examples regression, entities are escaped

### ISSUE THREAD

**Issue by frontsideair** [styleguidist/react-styleguidist#741]
I upgraded from `6.0.33` to `6.1.0` and when I click `Add examples to this component` I see this instead of 🍕:
<img width="948" alt="screenshot 2017-12-19 14 37 57" src="https://user-images.githubusercontent.com/868283/34155497-92234dbe-e4ca-11e7-9918-f97e472dc6aa.png">

**Comment by sapegin** [comment]
Thanks for bug report! I’ll take a look, but feel free to send a pull request if you have time ;-)

**Comment by frontsideair** [comment]
Sure, I hope I'll have time, I've always wanted to contribute.

**Comment by sapegin** [comment]
Out in [6.2.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.2.0)!
