### ISSUE TITLE
Style guide will not load (browser hangs)

### ISSUE THREAD

**Issue by robcaldecott** [styleguidist/react-styleguidist#742]
I've just upgraded to 6.1.0 from 6.0.33 and our style guide seems to build but will not display in any browser I have tried (it hangs and you're eventually prompted to kill the tab.)

Both development and statically built style guides exhibit the same issue.

Running with --verbose shows nothing out of the ordinary: it picks up the correct list of components, etc. But I cannot reproduce it with the template and my project requires code from a private npm registry so I cannot easily share it either.

**Is there anything else I can try to trace the issue?** Note that I cannot even get Chrome to open DevTools: the tab just hangs (also tried Firefox and Edge with the same results.)

**Comment by sapegin** [comment]
I can only suggest to remove things one by one until it start working, and then we’ll have an idea what’s wrong and how can we fix that ;-|

**Comment by vysinsky** [comment]
Hello, I have same issue in 6.1.0. I've found out the problem (at least for me) is HTML in Markdown:

https://gist.github.com/vysinsky/7f40d4673e5e84004bdbe08561ab1557 (see Release checklist)

CPU is on 100 % and page is indefinitely loading. When I load some other page where there is no such HTML styleguide loads correctly. There are no errors in console so I am not sure, how to debug it and provide more information.

**Comment by sapegin** [comment]
I guess it’s because of #725. @probablyup Could you please take a look?

**Comment by sapegin** [comment]
I think it was https://github.com/probablyup/markdown-to-jsx/issues/136

**Comment by sapegin** [comment]
If you remove `node_modules` and the lock file, and reinstall packages, it should pick up the new version.

**Comment by vysinsky** [comment]
Great! Thank you.
