### ISSUE TITLE
Customised example is not working 

### ISSUE THREAD

**Issue by jaredwilli** [styleguidist/react-styleguidist#745]
When I cloned this repo and tried to run the customised example without changing anything at all it gives the error `Cannot find babel-core`.

So then I npm installed babel-core. When I did that it said `Cannot find preset env relative to the path directory`. So naturally I npm installed babel-preset-env. I removed the beta versions. Which of course created a whole new problem that I'm not sure how to proceed with exactly

```js
Module build failed: ReferenceError: [BABEL] /Users//Sites/styleguides/react-styleguidist/examples/customised/src/components/Button/Button.js: Unknown option: /Users//Sites/styleguides/react-styleguidist/examples/customised/node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options. (While processing preset: "/Users//Sites/styleguides/react-styleguidist/examples/customised/node_modules/react/index.js")
    at Array.map (native)
./src/components/Placeholder/Placeholder.js
```

I assume that the babel beta versions aren't exactly working condition yet, and this is why. I'm not sure if these packages were updated in the example but not tested?

I was just hoping to check out the customised example so I could leverage some of the things in it. I suppose for now I can just try using one of the other working examples and pull some things from the custom one.

I was going to try digging deeper into this, and will see if I can later on when I have some time.

**Comment by sapegin** [comment]
Seems to work fine for me. What did you do?

**Comment by sapegin** [comment]
The error looks like `babel-preset-react` isn’t installed. Try to remove `node_modules` folder.

**Comment by jaredwilli** [comment]
I just tried again and still seeing the same issue. 
It is happening when I do nothing except `npm install` in the customised example, even after a newly cloned. Maybe I am doing something wrong? Is there a specific version of node I should be on perhaps?

**Comment by sapegin** [comment]
I guess it should work find with Node 6+. Try to run `npm ls` — do you have any warning here?

Would it work if you run `npm run start:customised` from the repo root?

**Comment by jaredwilli** [comment]
Yes, running it from the root worked.
