### ISSUE TITLE
Invalid markdown table rendering

### ISSUE THREAD

**Issue by AwK55** [styleguidist/react-styleguidist#751]
Hi, thank you for your tool. Its really helpful!

But I've a truble with styled-component and md tables. Here [example](https://github.com/AwK55/example)

Styleguide is built but ms table from README.md  renders incorrect.  I've checked `markdown-to-jsx` lib which you use and compiler function return jsx with invalid childern: tbody's children have extra column besides first child. And thats why all columns shift to the right as you can see on picture. 
![image](https://user-images.githubusercontent.com/11617476/34261619-c31b0112-e67a-11e7-86a9-934c361f8a1b.png)

I've forked your example repo and add styled component and `react-docgen-annotation-resolver` lib and problem've appeared. I guess that problem with this resolver.

**Comment by sapegin** [comment]
Please report this at markdown-to-jsx, I can reproduce the issue on their demo page: http://probablyup.github.io/markdown-to-jsx/

**Comment by AwK55** [comment]
https://github.com/probablyup/markdown-to-jsx/issues/138

**Comment by AwK55** [comment]
Issue was fixed in 6.3.2

**Comment by sapegin** [comment]
You can reinstall dependencies and it should pick up the new version.
