### ISSUE TITLE
How to change the id of the main container in the template

### ISSUE THREAD

**Issue by friedrith** [styleguidist/react-styleguidist#753]
Hi,

**Situation**
I have a react component named App.

**Issue**:
The anchor link to my component doesn't work in the left menu of the documentation.

**Reason**
There is alredy one div with the id "app" which is the main container of the default template. I tried to create my own template but of course styleguidist looks for a div with the id "app" and doesn't anything if it doesn't find it. 
Is there a way to setup the id of the main container in the template ?

Best regards,

**Comment by sapegin** [comment]
We should just change it to something like `rsg-root`. Feel free to send a pull request ;-)

**Comment by friedrith** [comment]
I am ready to work on it. However, I propose a feature for retrocompatibility: 
* if the id `app` is found in the template, it uses it.
* if the id `app` is not found, it tries to find the id `rsg-root`

Do you find this proposal acceptable ?

**Comment by sapegin** [comment]
Sounds good! I’d show a deprecation warning if `app` is found. Which could only happen if the user has a custom template. That way we could remove the condition in the next major release.

**Comment by friedrith** [comment]
Ok let's do it!

**Comment by sapegin** [comment]
I think it was in [deabsdeep](https://github.com/sapegin/deabsdeep) and should be fixed now.

**Comment by friedrith** [comment]
Thx it will try again.

**Comment by friedrith** [comment]
Sorry to disappoint you but the problem seems to persist because of snapshots.

**Comment by sapegin** [comment]
Could you try to run tests on [deabsdeep](https://github.com/sapegin/deabsdeep). I was hoping to fix that ;-/

**Comment by friedrith** [comment]
I launched tests on deabsdeep on windows:

```bash
$ git clone https://github.com/sapegin/deabsdeep.git
$ cd deabsdeep
$ yarn install
$ yarn test
````

And I got the following 2 tests Suites failing, (4 Tests failed and 3 snapshots). The errors is always like that:

```
custom mask

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

      Array [
    -   "<rootDir>/src/__tests__/a/b.js",
    +   "C:\\Users\\<my login>\\Documents\\deabsdeep\\src\\__tests__/a/b.js",
      ]


```

**Comment by friedrith** [comment]
ok thx a lot. I made the changes on my own but I wasn't able to push them because of the tests. Thx again.

**Comment by lichangwei** [comment]
@sapegin @friedrith This problem was not fixed. I have a component named 'App' and in the webapp its dom id is 'app'. when render again, the app will be render inside App component section.
[Code](https://github.com/styleguidist/react-styleguidist/blob/master/src/index.js#L23)

```js
var render = function render() {
	// eslint-disable-next-line import/no-unresolved
	var styleguide = require('!!../loaders/styleguide-loader!./index.js');
	var containerId = 'rsg-root';
        
        // if i have a component named 'App', the DOM will render in 'App' component section
        // when i remove below code, i will get the correct result 
	if (document.getElementById('app')) {
		// eslint-disable-next-line no-console
		console.warn("The use of 'app' element id in the template is deprecated. Please, update your template file to use 'rsg-root' as the container id.");
		containerId = 'app';
	}

	ReactDOM.render(renderStyleguide(styleguide, codeRevision), document.getElementById(containerId));
};
```
