### ISSUE TITLE
Generate styleguide inside a React app

### ISSUE THREAD

**Issue by romelperez** [styleguidist/react-styleguidist#754]
Is there a way to render the style guide inside another react application instead of creating a server or building it? For example:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Styleguidist } from 'react-styleguidist';

import Button from './src/Button';
import Modal from './src/Modal';

// Styleguidist options
const options = {
  components: [Button, Modal]
};

const MyApp = () => (
  <div className='my-root'>
    <Styleguidist {...options} />
  </div>
);

ReactDOM.render(<MyApp />, document.querySelector('#root'));
```

Of course the options wouldn't be the same, as many of them works from Node.js and webpack. But supposing you have processed those kind of options.

**Comment by sapegin** [comment]
I guess you can try to do this now: https://github.com/styleguidist/react-styleguidist/blob/master/src/utils/renderStyleguide.js

But you’ll need to do something will all the data like the `styleguide` argument which is coming from a webpack loader: https://github.com/styleguidist/react-styleguidist/blob/master/src/index.js#L13

There are also several webpack aliases that you’ll need to add to your webpack config: https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js

**Comment by romelperez** [comment]
I reviewed the object `styleguide` passed to `renderStyleguide` and there is a lot of work done by the webpack loaders that I wouldn't like to implement in the app, since it is running using [next.js](https://github.com/zeit/next.js/).

To get the components docs I'll try with [react-docgen](https://github.com/reactjs/react-docgen), render the markdown with [marksy](https://github.com/storybooks/marksy) and create the examples with [react-live](https://react-live.philpl.com/).

Thanks!

_This is for the website docs of a pet project if you want to see: [Arwes](https://arwes.romelperez.com)._

**Comment by sapegin** [comment]
> there is a lot of work done by the webpack loaders that I wouldn't like to implement in the app

It would make sense to make this part more modular.

> To get the components docs I'll try with react-docgen

There are much more that just react-docgen ;-)

**Comment by romelperez** [comment]
I wanted to use the components from the `/react-styleguidist/lib/rsg-components/` but they aren't completely converted with babel to ES5 so I couldn't and I didn't want to configure webpack. At the end I copied some components and re-made others. (Code: [`/site/components/Api.js`](https://github.com/romelperez/arwes/blob/master/site/components/Api.js) Result: [arwes.romelperez.com/api/words](https://arwes.romelperez.com/api/words))

I did the work of webpack to get the components definitions and APIs in a different script. ([`/scripts/api.js`](https://github.com/romelperez/arwes/blob/master/scripts/api.js))

Are they any plans on making the React components to be used without the whole toolset and without configuring webpack?

_Sorry for the delay, I was on vacation_

**Comment by sapegin** [comment]
> I wanted to use the components from the /react-styleguidist/lib/rsg-components/ but they aren't completely converted with babel to ES5 

Not sure I understand what you mean. If that was true nobody could use Styleguidist.

> Are they any plans on making the React components to be used without the whole toolset

Would be nice to extract props parser to a separate module and make it work without webpack. Feel free to do that.

> and without configuring webpack?

I don’t think there’s an easy way to do that.

**Comment by romelperez** [comment]
The first question is about completely converting the components so they can be used outside without configuring webpack. For example, the `import` and `export` declarations are not transpiled/compiled and there is a shortcut in webpack which needs to be configured ([example](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Code/CodeRenderer.js#L3)).

For the transpiling I would think we need to add more plugins in the babel definition: [.babelrc#L11](https://github.com/styleguidist/react-styleguidist/blob/master/.babelrc#L11). I need to review properly but there are some other tweaks needed.

Well, I would like to contribute to the project. I am using it and I really like it.

**Comment by sapegin** [comment]
> the import and export declarations are not transpiled/compiled 

Webpack 2+ supports ESM natively.

> there is a shortcut in webpack which needs to be configured (example).

It's required to make components configurable, I don't know an easy way to avoid it.

> For the transpiling I would think we need to add more plugins in the babel definition: .babelrc#L11. I need to review properly but there are some other tweaks needed.

For example?

It *is working* already, I don't see any requirements except couple of aliases. Would be cool to avoid that but I don't see an easy way to do that now.

**Comment by romelperez** [comment]
Let me review properly and I'll open a new issue to discuss those changes so I can make a PR. Thank you @sapegin !

**Comment by jasonsims** [comment]
@romelperez we're you ever able to make any progress on this idea? Being able to render styleguidist inside another app would be a great addition.

**Comment by romelperez** [comment]
@jasonsims I couldn't work on this because of time. I ended up making my own version. And yes, it would definitely be an awesome addition.
