### ISSUE TITLE
Typescript Components Examples In Markdown

### ISSUE THREAD

**Issue by kohearon** [styleguidist/react-styleguidist#758]
Hey guys / gals,

I'm making use of the react-docgen-typescript to generate the information about the props for my typescript components which is great! However, I can't find a way to actually render any examples from within markdown. 

I've done a bit of research and from what I gather react-styleguidest makes use of buble to convert the js and jsx in the markdown files to es5. Just wondering if there was anyway I could also have examples of my typscript components actually rendered instead of simple text examples?

Thanks

**Comment by sapegin** [comment]
It was discussed several times: #462, #621, #324. Feel free to send a PR to fix any of them.
