### ISSUE TITLE
component example placeholder text encoding

### ISSUE THREAD

**Issue by stephtr** [styleguidist/react-styleguidist#761]
- webpack version: 3.10.0
- react-styleguidist version: 6.1.0

When viewing a component without a readme file, an _Add examples to this component_ link appears. Clicking on it reveals a readme sample, with html entities falsely encoded:
```
'''js
&lt;Test pizza="&#x1f355;" /&gt;
'''
```

If necessary I could provide my files, even though it occurs with the default configuration.

![unbenannt](https://user-images.githubusercontent.com/5764184/34418508-cc53f4da-ebfe-11e7-92ac-147c839c73a6.PNG)

**Comment by sapegin** [comment]
Duplicated of #741.

**Comment by stephtr** [comment]
Sorry, I searched for the text and additionally the open issues but didn't find it.
