### ISSUE TITLE
support on-the-fly css classes

### ISSUE THREAD

**Issue by bochen2014** [styleguidist/react-styleguidist#762]
I have a component that takes in `className` as `props`. I want to be able to define a css classname within the markdown
```jsx
// this is inside my MyComponents.md
<style>
  .myClass{
    width: 400px; 
}
</style>

<MyComponent className="myClass" />
```
Is it even possible? 

Note: there are 2 walk arounds
1. use `styles`
2. define a css file in a file and do a `require` inside the markdown

**Comment by sapegin** [comment]
I guess you can create a Style component that would attach styles to the page. I don’t think the style tag would work in React.

**Comment by bochen2014** [comment]
you are right. 

`react` or `jsx` to be more specific doesn't understand what a `<style>` tag means, but `html` does. 
I think the issue is that `styleguidist` only allow defines `JSX` inside markdown. 
Is it possible that  inline css are supported as well?  we may need to look at the `markdown engine` part of the code

**Comment by sapegin** [comment]
It actually works right now:

![image 2017-12-30 at 10 24 25 am](https://user-images.githubusercontent.com/70067/34453077-b5e9e846-ed4b-11e7-84ed-bdcdc223c812.png)

**Comment by bochen2014** [comment]
wonderful!!!

**Comment by bjmin** [comment]
Hi, is this not working anymore?
I've tried add `<style />` tag in `.md`, but its content turns out to be converted to `<p />` in `<style />` tag, which block the style inject.
any idea?

current version: 7.0.9

**Comment by gibbitz** [comment]
Yeah not working for me either. FWIW, I am currently more-or-less doing this:
```jsx
css=document.createElement('style');
css.textContent = `
.search-icon-example {
	width: 80px;
}
`;
document.head.append(css);
<SearchIcon className="search-icon-example" />
```
The possibility of bleed is disgusting though...
