### ISSUE TITLE
Typescript: stateless functional component doesn’t export a component

### ISSUE THREAD

**Issue by rifler** [styleguidist/react-styleguidist#763]
repo with two similar components - `BadHeader` (stateless, doesn't work) and `GoodHeader` (es6 class, works)
https://github.com/rifler/styleguidist-ts-app

How to reproduce:
1) `git clone https://github.com/rifler/styleguidist-ts-app.git`
2) `npm i`
3) `npm run styleguide`
4) get warning `Warning: src/components/BadHeader/BadHeader.tsx matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.
`

Versions:
`tsc - 2.5.3`, also `2.6.2`
`node - 8.9.1`
`npm - 5.5.1`
`react - 16.2.0`
`react-dom - 16.2.0`
`react-scripts-ts - 2.8.0`
`react-styleguidist - 6.1.0`
`react-docgen-typescript - 1.1.0`

**Comment by sapegin** [comment]
I think you should file this issue here: /acorn5-object-spread
