### ISSUE TITLE
Cannot stop server.

### ISSUE THREAD

**Issue by ryanpcmcquen** [styleguidist/react-styleguidist#766]
```
$ npm run styleguide

> styleguidist server

You have another server running at port 6060 somewhere, shut it down first

You can change the port using the `serverPort` option in your style guide config:
https://react-styleguidist.js.org/docs/configuration.html
```

I am unable to stop the server. Even after running:
```
ps -ef | grep "node" | awk '{print $2}' | xargs kill -9
```

* Your style guide config (`styleguide.config.js`).
```
$ cat styleguide.config.js
module.exports = {
        components: "source/{components,containers}/**/*.{js,jsx,ts,tsx}",
        webpackConfig: require("./gulp/config/build.webpack.config.js")
};
```
* Webpack version.
```
$ grep webpack package.json
                "webpack": "^3.10.0",
```

**Comment by sapegin** [comment]
The question is not related to Styleguidist. You have *something* running on that port. Not necessarily Styleguidist.

**Comment by ryanpcmcquen** [comment]
@sapegin, it is _Styleguidist_, it was running and then I <kbd>Ctrl</kbd> + <kbd>C</kbd>'ed out of it. Now it will not let me run the server again.

**Comment by sapegin** [comment]
I guess if you restart your computer it will work again.

**Comment by ryanpcmcquen** [comment]
@sapegin, is the the only way to stop the server?

**Comment by sapegin** [comment]
It works fine for other people. Feel free to send a pull request if you believe it’s a bug in Styleguidist.
