### ISSUE TITLE
editorConfig is not working on 6.1.0 release

### ISSUE THREAD

**Issue by 4mgad** [styleguidist/react-styleguidist#771]
After upgrading to the latest release 6.1.0 and trying out "editorConfig" option, I received the following error:

Unknown config option editorConfig was found ...

**Comment by sapegin** [comment]
It's planned for [6.2.0](https://github.com/styleguidist/react-styleguidist/milestone/9?closed=1).

**Comment by 4mgad** [comment]
Yet it's mentioned in the Docs?

https://react-styleguidist.js.org/docs/configuration.html#editorConfig

**Comment by sapegin** [comment]
Feel free to help us solve the issue of docs using master branch.
