### ISSUE TITLE
Floated elements are not contained

### ISSUE THREAD

**Issue by roblevintennis** [styleguidist/react-styleguidist#772]
We have some floated buttons. I noted there's no [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context) in the styleguideist wrapper divs e.g. `display: inline-block; width: 100%;` (probably preferable to overflow hidden which would also work). Essentially, this means no floated element can be displayed and contained successfully within the main component box. Here's an example from the button on demo .. note I've added a float to the button and it's no longer contained:

![image](https://user-images.githubusercontent.com/142403/34800881-a584ddd0-f61a-11e7-8abc-bd1437fe8b4d.png)

**Comment by sapegin** [comment]
Feel free to send a pull request to fix that.

**Comment by roblevintennis** [comment]
@sapegin Sure thanks .. would you recommend I figure out how to just add it to the "base theme" and/or could you point me to which files best to touch? Guess I'll try that unless you have another recommendation.

**Comment by sapegin** [comment]
I’d start here:

https://github.com/styleguidist/react-styleguidist/blob/ab903f751f9e337108d24dbda4410a98b80804a9/src/rsg-components/Playground/PlaygroundRenderer.js#L10-L14

**Comment by roblevintennis** [comment]
Thank you very much for the 411 @sapegin .. I think my team's gonna give me some time today to do that ... I'll at mention on the PR!

**Comment by sapegin** [comment]
Out in [6.2.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.2.0)!

**Comment by roblevintennis** [comment]
oh cool! thanks for the heads up .. I can change my package.json pointer!
