### ISSUE TITLE
Providing an array of component locations in config

### ISSUE THREAD

**Issue by selbekk** [styleguidist/react-styleguidist#774]
Hi there! Great project! Thanks for putting in the time to make this awesome product, and then just give it away for free.

I have a question about the styleguide.config.js configuration, before I potentially provide a PR:

When you specify components for a given section, and you want several locations, you have to provide a function that returns an array instead of a simple array. Why can't you simply specify an array? 

Here's an example config to show what I mean:

```js
module.exports = {
    title: 'My style guide',
    sections: [
        {
            name: 'Buttons',
            components: () => [ // this! why not just a simple array?
              'packages/button/src/Button.js', 
              'packages/action-button/src/ActionButton.js',
          ],
        },
    },
};
```

I'd love to provide a PR to add this functionality if there isn't any particular reason why the API is this way.

**Comment by sapegin** [comment]
Simple reason: functions are more powerful and arrays are more like a shortcut. So that means I'll be happy to merge a PR that adds arrays too ;-)
