### ISSUE TITLE
Improve flowtype support

### ISSUE THREAD

**Issue by nanot1m** [styleguidist/react-styleguidist#780]
react-docgen grabs a lot of information from flow types. Maybe we should improve prop-types rendering?

For example, we can make something like this
![image](https://user-images.githubusercontent.com/9278185/35172954-841111e6-fd8b-11e7-9613-14c71d6b1fc6.png)

**Comment by nanot1m** [comment]
I’m ready to help (:

**Comment by sapegin** [comment]
Yeah, feel free to send PR(s) — I don’t use Flow personally but will be happy to merge improvements.

**Comment by nanot1m** [comment]
#781

**Comment by sapegin** [comment]
Should we close this now?

**Comment by nanot1m** [comment]
Yes, thanks for improvement of styleguidist!
