### ISSUE TITLE
Build is broken: r is not defined

### ISSUE THREAD

**Issue by lgordey** [styleguidist/react-styleguidist#783]
Hi!
After updating to 6.2.0 most of components have an error:
![image](https://user-images.githubusercontent.com/5946242/35206767-07f7b76a-ff50-11e7-8a19-88116aa5dbba.png)
Demo - https://github.com/lgordey/example

It reproduced only on build task - **styleguide:build**
In development mode everything seems fine

**Comment by lgordey** [comment]
I guess that the thing, that unite all crashed components - is they all have readme example with some text inside.
Cause examples with Placeholder or RandomButton don't have such error.

**Comment by sapegin** [comment]
Two funny facts:

1. I don’t see it when I build the basic styleguide in the main repo.
2. When I build your repo, I see slightly different error: `ReferenceError: can't access lexical declaration `r' before initialization`.

It feels like some new version of UglifyJS to me.

**Comment by lgordey** [comment]
> of course they don’t have a change log :man_facepalming:

of course 😂

**Comment by lgordey** [comment]
![image](https://user-images.githubusercontent.com/5946242/35208463-a0aee268-ff59-11e7-995d-405b31e8ee9f.png)

I think they are not completely sure about `uglify-es` version 😄

**Comment by sapegin** [comment]
As a temporary workaround I guess you can add an older version of `uglify-es` as a dependency of your project. I'm still not sure what would be the right fix for that and what exactly is broken.

**Comment by bstream** [comment]
Ran in to the same error (I think, although for me it said `ReferenceError: n is not defined`. For me the error occurs with `uglify-es@3.3.8` but not with `uglify-es@3.3.7`. If you are using using `yarn@1.x` you can use the [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) field for this, like so:

```
"resolutions": {
  "uglify-es": "3.3.7"
}
```

Also; maybe this is related? https://github.com/mishoo/UglifyJS2/issues/2842

**Comment by lgordey** [comment]
Updating to `uglifyjs-webpack-plugin@1.1.5` inside `react-styleguidist` also should fix the problem, cause they freeze `uglify-es` version here https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/199/files

**Comment by bluetidepro** [comment]
Yeah, I'm having this same problem with my builds, so a patch for this would be great.

**Comment by iamtyce** [comment]
I can confirm that @bstream's approach worked perfectly for us. Hoping to remove that when Uglify push a fix.

**Comment by diegohaz** [comment]
@bstream's workaround fixed it for me.

**Comment by alanbsmith** [comment]
oh, man. I'm so glad other people were seeing this too. I thought I was crazy. Can also confirm it's UglifyJS and @bstream 's workaround resolves it.

**Comment by nisargrthakkar** [comment]
I am using ```  "react-styleguidist": "^7.3.2"``` and still facing the issue 

![capture](https://user-images.githubusercontent.com/26029722/44896490-03d55b00-ad16-11e8-9d49-1f155fb0d6d4.PNG)

**Comment by GuptaWeber** [comment]
I am using `"react-styleguidist": "^9.2.0"` and still I am facing this issue.

It's working when if we manually import all the required dependencies for the project in the Styleguidist example. But my Repository has many packages and many examples. It ends in a lot of code repetition. 

Is there any way to solve this? 
Help me guys..!

**Comment by hamedmam** [comment]
I am having this issue in 10.1.0
