### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'methods' of undefined

### ISSUE THREAD

**Issue by DongShelton** [styleguidist/react-styleguidist#785]
Thanks react-styleguidist, that help me lot.
But here is a problem when I using styleguidist, if I add README.md file, it will cause:
```
Module build failed: TypeError: Cannot read property 'methods' of undefined
```
How could I solve this problem? And what cause this?

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
