### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by DongShelton** [styleguidist/react-styleguidist#786]
See example: [Issue Example](https://github.com/DongShelton/example)
When it runs `npm start`, it will cause `Cannot resolve module`

**Comment by sapegin** [comment]
It won't work with a glob pattern like this: `/lib/components/Common/**/index.tsx`, you should point to Styleguidist to your components, see examples in the docs: https://react-styleguidist.js.org/docs/components.html
