### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by peterlenagh** [styleguidist/react-styleguidist#787]
I was wondering if there's any way of working with multiple components with the same name within a styleguide.

We have client domains/namespaces and base component domain/namespace (as sections) within the same codebase.

So i have lib/base/components/button.jsx (Button) and lib/client1/components/button.jsx (Button). lib/client2/components/button.jsx (Button).

They all come out as #!/Button.

**Comment by peterlenagh** [comment]
i can hack in "namespaces" by changing the logic in getInfoFromHash and globalizeComponent but that feels a bit brittle.

**Comment by sapegin** [comment]
Not now but if you have any ideas how to make it possible without making the codebase more complicated, feel free to send a pull request ;-)

**Comment by n1313** [comment]
@peterlenagh are these two buttons members of the same package?

**Comment by peterlenagh** [comment]
@n1313 they're in the same npm package, but we don't export them from one index.js (so you don't import the world to `import { Button } from world;` - tree shaking wasn't working in webpack last time I checked). Rather we do `import { Button } from world/lib/client1/components/Button;`

I see what you're saying though; if they were they'd need to handle namespacing at the package/index.js level.

**Comment by peterlenagh** [comment]
@sapegin - if uri structure reflected sections that would solve my issue nicely.

i.e. a component inside a section called client1 would have the uri #!/client1/component rather than #!/component.

There would still be issues with the global components though...

**Comment by n1313** [comment]
That's an interesting problem. I would argue that technically you have separate packages, and maybe you should have separate styleguidists to cover them, but I also see the benefit of having all of them on one page.

Consider this: your customers are importing your different buttons using names that you assign to them in your entry points, but Styleguidist doesn't care for that, it reads files. So, I think it should be possible to have components with namespaced names, but exported with plain names:

* `lib/base/components/button.jsx` has an `export class BaseButton {}`
* `lib/client1/components/button.jsx` has an `export class FancyButton {}`
* `lib/base/index.js` re-exports `BaseButton` as `Button`
* `lib/client1/index.js` re-exports `FancyButton` as `Button`
* Styleguidist is configured to read both `lib/base/components/button.jsx` and `lib/client1/components/button.jsx`, and it gets namespaced names `BaseButton` and `FancyButton`
* ???
* could work?

**Comment by n1313** [comment]
> if uri structure reflected sections that would solve my issue nicely

I think the problem here is not the routing but the name collision. Two components with the same name just cannot exist together in one context. They have to be named differently.

**Comment by peterlenagh** [comment]
thanks for your commments @n1313.

For the time being I'm going to name the actual components differently and sort the naming out with directory names / exporting as default from component-level index.js.
```jsx
// consuming app
import Button from 'styleguilde/lib/Client1/Components/Button';

<Button />
```

```jsx
// lib/Client1/Button/button.jsx
import Button as BaseButton from '../../Base/components/Button';
const Client1Button = () => {
    <SomeSortOfThemeProvider>
        <BaseButton/>
    </SomeSortOfThemeProvider>
}

export default Client1Button;
```

```jsx
// lib/Client1/Button/index.jsx
...
export { default } from './button.jsx';
...
```

Within the styleguide they will then appear as #!/BaseButton, #!/Client1Button, #!/Client2Button etc., and I'm already overriding ReactComponentRenderer so I can just rm the namespaces from the component.names for display purposes there too.
