### ISSUE TITLE
Inline code blocks in Markdown files cannot be styled?

### ISSUE THREAD

**Issue by wachunga** [styleguidist/react-styleguidist#791]
I have a markdown file like `Component.md` with contents:
```markdown
A checkbox similar to HTML's `<input type="checkbox">`.
```

I would like to customize the font-size of that inline code block, which is too large (the monospace font defaults to size `inherit`). 

Overriding `CodeRenderer` via `styleguideComponents` doesn't work, because Markdown has its own [`Code`](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Markdown/Markdown.js). Similarly, I can't get configuration styles or themes configuration to affect this.

Is there a way to modify the font-size other than overriding the whole `Markdown` component?

**Comment by n1313** [comment]
In configuration styles, try something like 

```
Markdown: {
  pre: {
    fontSize: '12px'
  }
} 
```

**Comment by sapegin** [comment]
It should be `code`, not `pre`, but that should work.

**Comment by wachunga** [comment]
Thanks. I was trying with Code before and it would not work, but this did:
```
  styles: {
    Markdown: {
      code: {
        fontSize: 13
      },
    },
  },
```
