### ISSUE TITLE
Inherit comments from spread prop types

### ISSUE THREAD

**Issue by milesj** [styleguidist/react-styleguidist#792]
I haven't seen this anywhere in the documentation, and it definitely is not supported right now, but it would be great if the docs could inherit comments from objects who were spread into `propTypes`, like the following.

```js
const propTypes = {
  /* This does something. */
  bar: PropTypes.node,
};

export default function Foo(props) {
  return <div />;
}

Foo.propTypes = {
  ...propTypes,
};

Foo.defaultProps = {
  bar: null,
};
```

As it stands, styleguidist shows the `bar` prop, but without a comment.

**Comment by n1313** [comment]
I think this is something that react-docgen (which parses js files for info for react-styleguidist to consume) should do.

**Comment by milesj** [comment]
Thanks, I'll cross post it there too.

**Comment by pasupuletics** [comment]
@milesj , As @n1313 said its defiantly a bug(at least not supported) of react-docgen. And just to add that react-docgen doesn't support spread operator.

**Comment by sapegin** [comment]
I’m going to close this for now, because there’s nothing we can do on our side.
