### ISSUE TITLE
Preserve Table of Contents in isolation view

### ISSUE THREAD

**Issue by jeffkamo** [styleguidist/react-styleguidist#799]
Is there a way to preserve the table of contents? I would like TOC to remain fully populated, even when in isolated view.

Using [better-react-spinkit](http://better-react-spinkit.benjamintatum.com/) as an example...

![toc](https://user-images.githubusercontent.com/734535/35596981-228036ac-05d1-11e8-88c8-3c53043aa7e4.gif)

In my project, I am basically trying to make the table of contents become the links to the isolated pages. The index page would be blank. The table of contents becomes the primary means for navigating the full list of components.

Is this possible?

**Comment by sapegin** [comment]
That's the point of *isolated* mode -- to remove distractions and allow you to work on a single component.

I guess what you need is this: https://github.com/styleguidist/react-styleguidist/pull/768

**Comment by jeffkamo** [comment]
Ah, thanks for linking to that PR, I hadn't seen that one. But yes, that looks exactly like what my team needs!

Consider this question answered 👍
