### ISSUE TITLE
Include path in section props

### ISSUE THREAD

**Issue by wachunga** [styleguidist/react-styleguidist#800]
I would like to add "Edit this doc" links to each section. It's easy enough to do so with a custom `ReactComponentRenderer` (eg, getting the path via `pathLine`) but less so with markdown sections (via `SectionRenderer`).

Any objections to including filepath as a prop [in processSection](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/utils/getSections.js#L58)?

**Comment by sapegin** [comment]
Feel free to send a PR! ;-)

**Comment by wachunga** [comment]
Thanks for releasing this. 👍
