### ISSUE TITLE
Component file name conventions

### ISSUE THREAD

**Issue by dzdrazil** [styleguidist/react-styleguidist#804]
I believe that I have thoroughly read what documentation I could find, so this is either a feature request or I simply don't know where to look for the appropriate documentation.

I would prefer to name my component files `button.component.tsx` whereas styleguidist prefers `Button.tsx`. Unfortunately, because the file name (instead of the component display name or class name) is used to generate the local variables in the live code examples, `button.component` is not a valid identifier to create JSX.

At first, I had assumed that I could overwrite this with either the resolver or handlers config options, but (perhaps because of react-docgen-typescript?) neither of the custom functions I supplied were invoked. Was I on the right track? Is this something I could do if I got the resolver or handlers config working? Or is this something that exists elsewhere? Or does it need to be built into styleguidist yet?

**Comment by sapegin** [comment]
You should file an issue at react-docgen-typescript, Styleguidist uses displayName if it's available.

**Comment by dzdrazil** [comment]
Thanks @sapegin !

For anyone else who is looking here, I discovered that the displayName property in objects returned by the config's `parse` function is used to generate the components. Short of a change or a fix over at react-docgen-typescript, you can do what I did, wrap the default parse function of choice, and perform some string manipulation on the display name there.

With that, I was able to get it working, though I believe you're right in that the react-docgen-typescript definitely is not correctly parsing the display name (even when a static display name property is provided on the component).
