### ISSUE TITLE
Production build doesnt work

### ISSUE THREAD

**Issue by joshribakoff** [styleguidist/react-styleguidist#806]
Dev build is working great, but when I try to get a production build it tells me the JS is invalid:

![screen shot 2018-02-04 at 7 01 06 pm](https://user-images.githubusercontent.com/4021306/35786693-e2f760d0-09dd-11e8-96c8-7f090531a1a1.png)

![screen shot 2018-02-04 at 7 01 01 pm](https://user-images.githubusercontent.com/4021306/35786694-e30dee4a-09dd-11e8-913c-2b6dbe481853.png)

 I tried editing the HTML file & added UTF8 to the meta tag, and to the script tag, still get same error:
![screen shot 2018-02-04 at 7 01 12 pm](https://user-images.githubusercontent.com/4021306/35786692-e2df8a0a-09dd-11e8-9ba8-c1220ef093da.png)

 I grep the code & it shows its in these libraries, buble acorn, babylon. I don't use any of these libs on my end, they got pulled in as part of styleguidist. I am using styleguideist w/ own webpack config which has babel presets: ["react", "stage-0"]:

![screen shot 2018-02-04 at 7 01 22 pm](https://user-images.githubusercontent.com/4021306/35786691-e2c7c514-09dd-11e8-9923-2f5c5537fcb7.png)

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**

**Comment by joshribakoff** [comment]
FYI the problem was fixed when updating nginx to output `content-type:
application/javascript; charset=utf-8` instead of `content-type:
application/javascript`.

For some reason Chrome was ignoring the meta tag on the page that said utf8.
