### ISSUE TITLE
[v6.2.2] TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by diegohaz** [styleguidist/react-styleguidist#807]
Using object rest properties on js blocks causes that error:

```js
const { foo, ...rest } = { foo: 'bar', baz: 'qux' };
```

```js
const Example = ({ ...rest }) => <div {...rest} />;
```

It was introduced in v6.2.2. It works on v6.2.1. Probably related to #801.

cc/ @lgordey

**Comment by lgordey** [comment]
May be it's cause of `buble` downgrade but now I can't up it https://github.com/Rich-Harris/buble/issues/107

**Comment by lgordey** [comment]
But yea, support for rest properties was added in `v0.17.0` here https://github.com/Rich-Harris/buble/pull/30

**Comment by lgordey** [comment]
I suppose this will help https://github.com/styleguidist/react-styleguidist/pull/815
