### ISSUE TITLE
Feature Request: Better support for extending styleguideComponents

### ISSUE THREAD

**Issue by dallonf** [styleguidist/react-styleguidist#810]
When configuring `styleguideComponents`, sometimes I don't want to completely _replace_ a component; sometimes I want to _add_ to it. An example where I add a link to the source code of the component to the `Pathline`: https://github.com/dallonf/example/blob/extending-styleguide-components/lib/__styleguide__/Pathline/Pathline.js

Notice I have to reach deep into internals of the library to access the default implementation:

```js
import DefaultPathline from 'react-styleguidist/lib/rsg-components/Pathline/PathlineRenderer';
```

This is especially smelly because if I try to import the index (which feels like a slightly better approach than reaching deeper into the internals):

```js
import DefaultPathline from 'react-styleguidist/lib/rsg-components/Pathline';
```

It fails, because the index apparently is using some magic to import a package (`rsg-components`) that isn't actually a dependency:

```
./node_modules/react-styleguidist/lib/rsg-components/Pathline/index.js
Module not found: Can't resolve 'rsg-components/Pathline/PathlineRenderer' in '/Users/dallonf/devroot/oss/styleguidist-example/node_modules/react-styleguidist/lib/rsg-components/Pathline'
```

Is there a better way to import the default implementations of these components? If not, _could_ there be?

Full example project: https://github.com/dallonf/example/tree/extending-styleguide-components

**Comment by sapegin** [comment]
This is the right way to do that:

```js
import DefaultPathline from 'react-styleguidist/lib/rsg-components/Pathline/PathlineRenderer';
```

I don't see how we can make it significantly simpler, and I don't think we really should.

**Comment by jbachhardie** [comment]
A possibility would be to have a way to provide a higher-order component that styleguidist would call with the native styleguidist component. e.g.

```jsx
const withSourceLink = (DefaultComponent) => (...props) => (
  <div style={{ position: 'relative' }}>
    <DefaultComponent {...props}/>
    <SourceLink path={props.children} />
  </div>
);
```

and then in config

```js
styleguideComponentDecorators: {
  Pathline: [path.join(__dirname, 'lib/__styleguide__/decorators/withSourceLink')]
}
```

**Comment by dallonf** [comment]
If importing from deep in `lib` is the preferred method, I could write up a docs PR. I'd feel better knowing that approach is officially supported.

**Comment by sapegin** [comment]
@jbachhardie I don't think that feature is *that* important, and I think the way it works is simple enough. 

@dallonf Would be cool! “officially supported” is probably not the right name, we can’t guarantee no braking changes, otherwise any changes in Styleguidist components would require a new major release, so it’s up to the user to update their code. But the way imports work would be supported. I believe that’s a good compromise between ability to change anything and keeping the implementation simple enough.

**Comment by AveVlad** [comment]
@sapegin 

docker build

```
 FAIL  Failed to compile

./~/react-styleguidist/lib/rsg-components/Logo/index.js
Module not found: Can't resolve 'rsg-components/Logo/LogoRenderer' in '/www/qw/node_modules/react-styleguidist/lib/rsg-components/Logo'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend-desktop@1.0.0 styleguidist-build: `yarn styleguidist --config=ui-kit.config.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend-desktop@1.0.0 styleguidist-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-17T21_26_00_692Z-debug.log

```


config:

```js
module.exports = {
  require: ['babel-polyfill', p('styles/index.less')],
  title: 'titile',
  styleguideComponents: {
    LogoRenderer: p('src/styleguide/Logo'),
  },
  defaultExample: true,
  sections,
  styleguideDir: styleguideDir,
  template: p('src/index-ui-kit.html'),
  webpackConfig: {
    module: cfg.module,
    plugins: [
      new ExtractTextPlugin('styles.css'),
      new webpack.DefinePlugin({
        __APP_ELEMENT__: JSON.stringify('#app'),
        __DEV__: JSON.stringify(development),
        __DEBUG__: JSON.stringify(development),
        __LAST_BUILD_TIME__: JSON.stringify(new Date()),
        __API_ENDPOINT__: JSON.stringify(API_ENDPOINT),
        __I18N_LOCALE_FILE__: JSON.stringify(i18n_locale_file),
        'process.env.NODE_ENV': JSON.stringify(env),
      }),
    ],
  },
};

```

Logo.js

https://gist.github.com/AveVlad/0cd7685775cb94b711a60b168fc9b96f

**Comment by sapegin** [comment]
I'm going to close this because there's nothing we can do now. Feel free to send a pull request if you see what can be improved ;-)
