### ISSUE TITLE
The new state change won't be reflected in callback function.

### ISSUE THREAD

**Issue by viraths** [styleguidist/react-styleguidist#817]
```
```jsx
initialState = {
    myState: 5,
};
  
const updateState = () => {
   console.log('changing state');
   setState(
     { myState: 2 },
     () => { console.log('new state: ', state.myState); }
   );
};
  
<div><a onClick={updateState}>Change state</a></div>
```

Expected outcome `new state: 2`
Current outcome `new state: 5`

Please note that I use above code example inside markdown file. (myExample.md).

It works perfectly in react. Please refer to the following example.
[React code snippet](https://codesandbox.io/s/504xq43r6l)

Thanks.

**Comment by sapegin** [comment]
Feel free to send a pull request to fix that if that’s possible.  There’s a bit of magic here and I’m not really sure there are many use cases where this would be important.

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.

**Comment by n1313** [comment]
@viraths take a look at the last code example in https://react-styleguidist.js.org/docs/documenting.html#writing-code-examples, it documents a different approach to writing code examples and might be helpful in your situation

**Comment by dtuyenle** [comment]
Having the same issue. @viraths  how did you solve this ?

**Comment by viraths** [comment]
@dtuyenle I just used the given example in above post.
