### ISSUE TITLE
Get override of Preview class

### ISSUE THREAD

**Issue by krishna63** [styleguidist/react-styleguidist#819]
Hi Team,

In my project we are creating a modal so we need to append them to the body tag directly, doing so the styles are not getting applied, as it is looking for the selector 

``` CSS

[class*="preview-"] .testComponent
```

So as of now i have to create one more wrapper `div` in my testComponent and give a class attribute and value as `preview-TobeRemoved`. Can i get over of this. If so please suggest.

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
