### ISSUE TITLE
Manually rendering PropTypes

### ISSUE THREAD

**Issue by Baudin999** [styleguidist/react-styleguidist#832]
I'm building my components documentation "by hand". I don't use the automatic generation features because I have multiple silly and simple components, thins like:

```js
export const PaperWithContent = Radium(({ children, stacked = false }) => (
  <Paper style={{ marginTop: stacked ? null : "1rem" }} elevation={4}>
    <Content>{children}</Content>
  </Paper>
));
PaperWithContent.propTypes = {
  stacked: PropTypes.oneOfType([PropTypes.bool, null, undefined]),
  children: PropTypes.node
};
PaperWithContent.defaultProps = {
  stacked: false
};

export const Header = ({ children }) => (
  <Typography type="headline" component="h3">
    {children}
  </Typography>
);
```

What I do now is that I've added a `styleguide.config.js`:

```json
const reactDocgen = require("react-docgen");

module.exports = {
  resolver: reactDocgen.resolver.findAllExportedComponentDefinitions,
  sections: [
    {
      name: "Layout",
      sections: [
        {
          name: "Row",
          content: "src/styleguidist/layout.Row.md"
        },
        {
          name: "Column",
          content: "src/styleguidist/layout.Column.md"
        }
      ]
    },
    {
      name: "Content Components",
      sections: [
        {
          name: "Header",
          content: "src/styleguidist/layout.Header.md"
        },
        {
          name: "Paper",
          content: "src/styleguidist/layout.PaperWithContent.md"
        }
      ]
    }
  ]
};

```

The problem I have is that I want to manually add PropTypes information to the rendering of a component. I want the pretty table in my result :)

My `layout.PaperWithContent.md` file looks like (read \` as just a `):

```md

A paper with content

\`\`\`jsx
const { PaperWithContent, Header } = require("./../components/layout");
<PaperWithContent>This is a piece of paper from Material UI</PaperWithContent>
\`\`\`

And now with a header...

\`\`\`jsx
const { PaperWithContent, Header } = require("./../components/layout");
const 
<PaperWithContent>
    <Header>This is the header</Header>
    This is a piece of paper from Material UI
</PaperWithContent>
\`\`\`

```

Is there some way to manually put that pretty table in my example file?

**Comment by vgnshs2** [comment]
You mean you want to draw a table kind of structure with some rows and columns, list down details of your PropTypes?

**Comment by sapegin** [comment]
I don’t understand what problem you’re trying to solve bu I doubt there will be an easy way to do that.

**Comment by Baudin999** [comment]
Thank you for commenting. I'll try to explain.

If you just have one component per module (file) you get the default behaviour of styleguidist, which is great. But I want to have multiple components in my files and I want my PropTypes to be defined in another module (I call it my `propDefinitions.js` file). (extra info: I also have my flow type definitions in another file this seems to keep the code clean and makes it easier to refactor the code.) I only use Pure Functions. 

Using these three concepts, Pure Functions, multiple components in one module and clean definition files makes my project really easy to maintain. The only problem I have is that I can't really use styleguidist as it was intended. I'll gladly suffer manual configuration and manual writing of my styleguide if it means that I can maintain my way of working but I can't really get everything to render properly. 

I manually make sections and for each component I add a `.md` file in my documentation folder. Inside this `.md` file I am trying to document my component:

 1) Examples: work great, really easy to do
 2) Documentation: works great, markdown is super
 3) **PropTypes**: I can't find a way to render these manually. 

If you need more information I can try and create a little test project.

**Comment by pasupuletics** [comment]
@Baudin999 , Styleguidist relies on [react-docgen](https://github.com/reactjs/react-docgen) to extract doclets out of out source components files, If i understood 3rd problem properly that, propTypes are defined in external module which is included in your components files. If this is the case styleguidist would fail to generate docs for this. In fact [react-docgen](https://github.com/reactjs/react-docgen) not styleguidist, because is does only static analysis of all component source files.

To over come this problem you might need to write your own custom handler for [react-docgen](https://github.com/reactjs/react-docgen), and amend [react-docgen](https://github.com/reactjs/react-docgen) generated documentation object before it gets hand it over to styleguidist.

**Comment by Baudin999** [comment]
@pasupuletics Thank you for your reply. I think I understand. I'll dive into react-docgen and will see if I can get things to work. If I manage to solve the problem I'll report back. 

I'll close this issue and I'll reopen it if/when I have a solution.
