### ISSUE TITLE
Recommend npx instead of npm scripts in docs

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#836]
- [ ] Replace all `npm run styleguide` with `npx styleguidist server`.
- [ ] Replace all `npm run styleguide:build` with `npx styleguidist build`.
- [ ] Remove 3rd them in [the getting started guide](https://github.com/styleguidist/react-styleguidist/blob/master/docs/GettingStarted.md).

**Comment by farrahD** [comment]
@sapegin can I try this out, I'm new at this

**Comment by sapegin** [comment]
@farrahD Sure, that would be awesome! There are no code changes, only docs.

**Comment by farrahD** [comment]
Okay, thats fine. I still want to try just to get the hang of it. Thanks!

**Comment by farrahD** [comment]
I did a Commit but not sure if I was supposed to do a Pull Request?
I didn't see a 3rd them 
"Remove 3rd them in the getting started guide."

**Comment by sapegin** [comment]
> I did a Commit but not sure if I was supposed to do a Pull Request?

@farrahD Yup, otherwise I wouldn't be able to review and merge the code.

> I didn't see a 3rd them

“3. Add npm scripts for convenience”, see the link in the issue description.

**Comment by farrahD** [comment]
'3. Add npm scripts for convenience' has the user add scripts to their package.json. If you're replacing npm with npx does that mean I should be removing the lines containing #3 from the getting started file?

**Comment by sapegin** [comment]
Remove the whole 3rd step, it's up to the user now whether they want to create npm scripts or not.

**Comment by okonet** [comment]
So, basically this recommends removing `react-styleguidist` from dependencies, right? I'm not sure this is a good practice keeping in mind there is a build step which is suppose to be executed on CI servers. @sapegin what's the motivation behind it?
