### ISSUE TITLE
Handlers and resolver dependent on propsParser

### ISSUE THREAD

**Issue by eps1lon** [styleguidist/react-styleguidist#837]
After some time spent trying to get `handlers` to work with `react-docgen-typescript` as a `propsParser` I realized that the `handlers` and `resolver` config options are only used by the `propsParser` option.

However I couldn't find a documentation for that behavior. The documentation should at least contain a warning that it is possible that those options are ignored by the `propsParser`.

In the case of the `resolver` it might make sense for `react-docgen-typescript` to ignore this options but this is very unfortunate for `handlers`.

In an ideal world those options would be moved to the `propsParser` and `react-docgen-typescript` would implement the resolvers from `react-docgen` and support custom handlers. Even better would be if `react-docgen` would use babel-preset-typescript.

**Comment by sapegin** [comment]
I’m not really sure what we can do here: feel free to send a pull request if you see possible improvements.
