### ISSUE TITLE
Wrap examples in React.Fragment

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#840]
This will allow to render multiple components without wrapping them in some `<div>`:

```jsx
// Before
<div>
  <Button>push</Button>
  <Button secondary>push</Button>
</div>

// After
<Button>push</Button>
<Button secondary>push</Button>
```

We should keep React 15 compatibility and check if `React.Fragment` is available. Keep the existing behavior in React 15.

**Comment by tizmagik** [comment]
Ah great idea! For React 15, is there harm in transparently wrapping in a div anyway so users wouldn’t have to explicitly wrap? 🤔 Something like:

```js
const Fragment = React.Fragment || <div />;

return <Fragment>{example_here}</Fragment>
```

**Comment by sapegin** [comment]
Maybe not, if we make a major release. It may break some custom styles because of new added DOM element.

**Comment by MarkMurphy** [comment]
This should probably be an overridable styleguidist component. This way, I can supply my own `Example` component that applies a flexbox layout and spacing around.

**Comment by sapegin** [comment]
You can already do it with the `Wrapper` component.

**Comment by MarkMurphy** [comment]
> You can already do it with the Wrapper component.

How's that? 

```
const Example = styled.div`
  display: flex;
  > * {
    margin: ${props => props.theme.spacing(1)};
  }
`;

const Wrapper = ({ children }) => (
    <Example>{children}</Example>
);
```


This: 

    ```js
      <Button>Default</Button>
      <Button primary>Primary</Button>
      <Button secondary>Secondary</Button>
      <Button disabled>Disabled</Button>
    ```

Results in:
```
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (2:2)
1 :   <Button>Default</Button>
2 :   <Button primary>Primary</Button>
      ^
```

**Comment by MarkMurphy** [comment]
There's another component or two between the Wrapper and the content rendered from the code block so you can't just use the Wrapper.

**Comment by joetidee** [comment]
Could also do this to avoid adding in unnecessary HTML tags:
```
const Fragment = React.Fragment || props => props.children;

return <Fragment>{example_here}</Fragment>
```

**Comment by mhelvens** [comment]
Any chance this could be made to work when the example code starts with some initialization?

```js
initialState = { counter: 0 };

<Button onClick={() => setState({ counter: state.counter + 1 })}>Click Me</Button>
<span>{_.repeat(' ✓', state.counter)}</span>
```

This still gives me the `Adjacent JSX elements must be wrapped in an enclosing tag` error.

**Comment by sapegin** [comment]
It's just a convenience, you can sill use fragments manually:

```js
initialState = { counter: 0 };

<>
  <Button onClick={() => setState({ counter: state.counter + 1 })}>Click Me</Button>
  <span>{_.repeat(' ✓', state.counter)}</span>
</>
```
