### ISSUE TITLE
StencilJs support with react renderer

### ISSUE THREAD

**Issue by mnemanja** [styleguidist/react-styleguidist#845]
I'm building a micro frontends app utilizing react as a composition layer and StencilJs with React renderer as a parts that will be composed.

I find Styleguidist to be a perfect fit since I would need a way to test the component in isolation.

Any chance to have a support for this? 
Thanks!

**Comment by sapegin** [comment]
I have no idea what StencilJs is and how valuable will be its support for other users. And, more important, how can we support it.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.

**Comment by FDiskas** [comment]
Still valid
