### ISSUE TITLE
JSX examples without compilation

### ISSUE THREAD

**Issue by thaggie** [styleguidist/react-styleguidist#846]
We have a bunch of places in our documentation where our examples aren't compilable to keep them briefer and to the point.

Is there a way to mark sample code in a markdown file such that its code isn't compiled.

```jsx!
<MorePseudoCodeThan really jsx ... />
```

**Comment by sapegin** [comment]
Use `static` modifier: https://react-styleguidist.js.org/docs/documenting#usage-examples-and-readme-files
