### ISSUE TITLE
Replace webpack with Parcel-Bundler?

### ISSUE THREAD

**Issue by pke** [styleguidist/react-styleguidist#847]
Have you taken a look at [ParcelJS](https://parceljs.org/). It is much easier to setup than webpack, faster in compiling, produces smaller bundles and supports hot-reloading.
With the insight how webpack is used in styleguidist, do you think a switch of the bundler would be possible?

**Comment by KnisterPeter** [comment]
I think it would be way better and easier to move to webpack 4.
Its fast as well, has zero config too and will need less transition.

**Comment by pke** [comment]
Aha. Didn't know there is a webpack 4 already :) Can it do proper tree shaking now finally?

**Comment by pke** [comment]
Everytime I come back to setup react component documentation with my favorite style guide tool I long for parcel support. 
My projects almost never use webpack for over 2 years now, cause its "zero-configuration" is still mostly a myth, even with v4.

Parcel truly shines in this aspect and I wish react-styleguidist would support it. At the moment I install webpack in a docs subfolder alongside this minimal webpack config inside `styleguide.config.js`

```js
webpackConfig: {
    module: {
      rules: [
        {
          test: /\.js?$/,
          exclude: /node_modules/,
          loader: "babel-loader",
        },
        {
          test: /\.(jpg|png|svg)$/,
          use: {
            loader: "url-loader",
          },
        },
        {
          test: /\.css$/,
          use: ["css-loader"],
        },
      ],
    },
```

Which is not really "zero-config". Parcel supports all that by default and I really wonder @sapegin what you think about it? How difficult do you estimate is a switch of the bundler? Parcel also supports hot-loading and such which would be required for the interactive examples.
