### ISSUE TITLE
Is it possible to not document some components

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#848]
Hi, I have 3 components

- `<ProgressBar />`
- `<Step />`
- `<StepProgress />`

We want to only document the `<StepProgress />`, but we still need to have import available of the other components. I haven't seen such option in the documentation, is that possible ?

**Comment by sapegin** [comment]
https://react-styleguidist.js.org/docs/cookbook#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples
