### ISSUE TITLE
order for sections and components if they are in the same section

### ISSUE THREAD

**Issue by hsiaoyu-chou** [styleguidist/react-styleguidist#854]
If there is sections and components in the same section, the components will be rendered before the sections. However, in sidebar, the components will be rendered after the sections. 

<https://github.com/hsiaoyu-chou/styleguidist_example>

This can be solved by change the order of `components` and `sections` in function SectionRenderer in  [SectionRenderer.js](https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Section/SectionRenderer.js)

**Comment by sapegin** [comment]
Feel free to send a PR. Though I'm not sure which order is the right one ;-)
