### ISSUE TITLE
No trace or debug information on fatal errors

### ISSUE THREAD

**Issue by chucksellick** [styleguidist/react-styleguidist#860]
I am using latest version of Styleguidist and I have now documented a few components. When I try to start the server I get fatal error "components should be string or function, received object." and the server bombs out, no information about which file or component has caused this error. I can't provide a demo since I don't know which file is even causing this.

**Comment by sapegin** [comment]
I don't know either, and only you can find them. There's no way we can help you with the info you provided. Feel free to reopen with a demo.
