### ISSUE TITLE
Proposal: Make currently selected component available to styleguide components

### ISSUE THREAD

**Issue by ahuth** [styleguidist/react-styleguidist#862]
Thank you for the great project! Is the community here open to making the currently selected component available to the styleguide components for styling purposes?

We have a use case for highlighting which item from the left nav is currently selected. See here for an example:
![mds](https://user-images.githubusercontent.com/2503289/37066344-e3dcaa26-2159-11e8-975b-62e77dbfe974.png)

Note that the "Overview" link in the TableOfContents is bold and has a blue bar next to it.

Right now we're determining which component is selected by directly accessing the `window.location.hash`.

If folks here are open to the idea, I'll submit a PR to do the following:
- Return `targetName` from the `getRouteData` utility function
- Pass `targetName` as a prop to `<Styleguide>`
- Make `targetName` available on context

That way, any override of styleguide components we provide can determine what the currently selected item is.

Thanks for your feedback!

**Comment by ahuth** [comment]
Ah, just realized this may be harder than I realized.

`getInfoFromHash` only returns the target of something like '#!/Button' and not '/Button'.

**Comment by sapegin** [comment]
I think this would be easy to do for an isolated or a single component view (will be available in the next version). Otherwise you'll have to listen to scroll events, because hash doesn't really say which component is in the viewport. Both PRs would be super cool ;-)

**Comment by ahuth** [comment]
Thanks. Closing for now, as I'm not sure we'll actually get to this now. If that changes, I'll let you know.
