### ISSUE TITLE
Using state in combination with Immutable JS

### ISSUE THREAD

**Issue by Baudin999** [styleguidist/react-styleguidist#864]
Hi, I'm trying to create a styleguide while using Immutable JS. I find it important to keep my example code as close to the actual code as possible. I was wondering if I'm doing something wrong?

The [example](https://github.com/Baudin999/example) solution.

The actual code:

```jsx
const { Map } = require("immutable");
initialState = Map({ index: 0 });
(() => {
  //this will fail as well 
  console.log(state.get("index"));
})();

<div>
  <button
    onClick={() => {
      console.log(state);
      // this will fail
      setState(state.set("index", state.get("index") + 1));
    }}
  >
    +
  </button>
  <div>Our current index is: {state.index || 0}</div>
</div>;
```

Is there a workaround? Or should I start digging through the source code and see if I can find a solution?

**Comment by sapegin** [comment]
I believe that’s because of this line:

https://github.com/styleguidist/react-styleguidist/blob/dae9d6696449f25cdc6f18620074cde785776333/src/rsg-components/Preview/Preview.js#L29

We could probably just do `this.state = initialState`. Feel free to submit a pull request ;-)

**Comment by Baudin999** [comment]
Cool, thank you, will try and submit it tonight.
