### ISSUE TITLE
webpack externals not being referenced by styleguidist

### ISSUE THREAD

**Issue by gardezii** [styleguidist/react-styleguidist#869]
Hello guys, I'm initializing some variables in web pack externals. in styleguidist I'm telling it about my external but they are not being referenced. Can you please tell me what is it that I'm doing wrong 

```
{
   //some code over here
   "externals":[
      {
         "variableA":"true",
         "variableB":"abcd"
      }
   ],
   // some code over here
}

```

```
module.exports = {
    components: 'src/js/components/**/*.js',
    webpackConfig: Object.assign({}, require('./webpack/tests.js'), {
        /* Custom config options */
        externals:{
            variableA: 'variableA',
            variableB: 'variableB' ,
        },
    }),
}
```
Please correct me what is it that I'm doing wrong thanks

**Comment by n1313** [comment]
https://react-styleguidist.js.org/docs/configuration.html#webpackconfig

"entry, externals, output, watch, and stats options will be ignored. For production builds, devtool will also be ignored."

You might need to https://react-styleguidist.js.org/docs/configuration.html#dangerouslyupdatewebpackconfig
