### ISSUE TITLE
Compiling fails on components with spread flow types

### ISSUE THREAD

**Issue by kure-** [styleguidist/react-styleguidist#882]
Hey, i'm having an issue with compiling a styleguide with components that are using spread flow types. Appearently that was an issue with react-docgen dependency itself and it should be fixed with react-docgen 3.0.0-beta11 meanwhile styleguidist is dependent on 3.0.0-beta8.
I'm able to submit a PR with the dependency change, but I'm not able to test the update properly myself on my fork of styleguidist, as all test are failling for me on my machine due to the slashes/back-slashes being converted on windows :-) Perhaps there would be some1 lucky to try?:)

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
