### ISSUE TITLE
Invalid prop `props.props` of type `array` supplied to `UsageTabButton`, expected `object`

### ISSUE THREAD

**Issue by denchen** [styleguidist/react-styleguidist#883]
Starting at `6.4.0`, I'm seeing this warning / error:

![screenshot 2018-03-21 13 06 17](https://user-images.githubusercontent.com/2073768/37734748-47b96f60-2d09-11e8-9d7a-9c2399af3087.png)

Reproducing is easy.

1. Clone https://github.com/styleguidist/example (with *no modifications*)
2. `npm install`
3. `npm run styleguide`
4. Open the website in Chrome and open DevTools. You should see the error.

Downgrading to `6.2.7`, and the error disappears.

**Comment by ZxBing0066** [comment]
I have the same problem.

**Comment by sapegin** [comment]
I believe it's fixed in master, I'm going to release 6.5.0 very soon.
