### ISSUE TITLE
Connect with material-ui fields

### ISSUE THREAD

**Issue by doskogerman** [styleguidist/react-styleguidist#898]
Hi, I'm trying connect react-styleguidist with material-ui TextField and when I want to wrap <App /> with <MuiThemeProvider />  I get this error "Cannot read property 'prepareStyles' of undefined".

Btw when I wrap only the TextField with <MuiThemeProvider /> all work well.

Does anyone know what is happening and how to solve it?

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
