### ISSUE TITLE
Global styles using styled-components injectGlobal?

### ISSUE THREAD

**Issue by tysonmatanich** [styleguidist/react-styleguidist#903]
Any way to import CSS from JS used for styled-components injectGlobal``?

https://www.styled-components.com/docs/api#injectglobal

Tried using require with no luck:
```
require: [path.join(__dirname, 'src/styles/global.js')],
```
global.js
```
import { injectGlobal } from 'styled-components';
import reset from 'styled-reset';
import base from './base';

export default () => injectGlobal`
  ${reset}
  ${base}
  div {
    color: red;
  }
`;
```

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**

**Comment by anikolaev** [comment]
I've also faced this issue. Not sure what demo is required in this case.
