### ISSUE TITLE
Overriding styling using styles seems to be broken

### ISSUE THREAD

**Issue by joakimkemeny** [styleguidist/react-styleguidist#909]
I tried upgrading from 6.2.3 to the latest version and all my custom styling stopped working. Here is an example that no longer works.

```js
styles: {
  Markdown: {
    code: {
      backgroundColor: "red"
    }
  }
}
```

I seems like the problem started in 6.2.4.

I created a sample repo to show the problem, https://github.com/joakimkemeny/styleguidist-broken-styles-example. If you run that styleguide, code blocks will not be red but if you change the version back to 6.2.3 it will.

**Comment by sapegin** [comment]
We've refactored Markdown components recently:

```diff
-  styles: {
-      Markdown: {
-        code: {
-          backgroundColor: "red"
-        }
-      }
-    },
+	styles: {
+		Markdown: {
+			code: {
+				backgroundColor: 'red',
+			},
+		},
+		Pre: {
+			pre: {
+				backgroundColor: 'green',
+			},
+		},
+	},
```

**Comment by joakimkemeny** [comment]
Thank you for a quick answer but it doesn't work.

If I follow the instructions in the documentation I see that the React structure looks like this.

```jsx
<Markdown>
  ...
  <ParaRenderer>
    ...
    <CodeRenderer>
      <code>...
```

So the configuration should probably be.

```js
styles: {
  CodeRenderer: {
    code: {
      backgroundColor: "red"
    }
  }
}
```

...but that doesn't work either.

**Comment by sapegin** [comment]
It works in your example, I've tried it.

**Comment by joakimkemeny** [comment]
Sorry, I see I wrote code blocks, I really meant inline blocks like `this`. Thats why I had the structure I described above with a CodeRenderer and not a PreRenderer (and the code block is lower down on the page so didn't see it, sorry again).

So obviously some styling works but not all. If you downgrade to 6.2.3 you'll see that code-tags (like `any`, `js`, `jsx`, `javascript` and `noeditor`) are red but in 6.2.4 they are not.

**Comment by sapegin** [comment]
This works:

```js
	styles: {
		Code: {
			code: {
				backgroundColor: 'red',
			},
		},
	},
```

**Comment by joakimkemeny** [comment]
Great, thank you!

Btw the documentation should probably be updated to reflect this change https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide

**Comment by sapegin** [comment]
I don't see what should be changed there, but feel free to send a pull request.

**Comment by BboyAwey** [comment]
I've found an interesting thing, if write `styles` in shorthand like below, it will not work.

```js
module.exports = {
  styles (theme) {
    return {
      Logo: {
        logo: { color: theme.color.link }
      }
    }
  }
}
```

but if write this config in a normal way like
```js
module.exports = {
  styles: function (theme) {
    return {
      Logo: {
        logo: { color: theme.color.link }
      }
    }
  }
}
```
it works fine.

And I've checked the source code in `/src/client/styles/createStyleSheet.ts`, it seems everything is ok:

```typescript
const customStyles =
			typeof config.styles === 'function' ? config.styles(mergedTheme) : config.styles;
```

you guys just execute the `styles` function with config and get the results.

So why it dose not support the handy way? Emm...
