### ISSUE TITLE
Error: components config option should be string or function, received Array.

### ISSUE THREAD

**Issue by giacomocerquone** [styleguidist/react-styleguidist#911]
Hi everyone, [here](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md) and [here](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Components.md) the docs tell us that we can pass an array of strings (paths) to the components field in the `styleguide.config.js` file, but I if I do that, I've got this error:

```
Something is wrong with your style guide config

components config option should be string or function, received Array.

Example:

{
  components: 'components/**/[A-Z]*.js'
}

Learn how to configure your style guide:
https://react-styleguidist.js.org/docs/configuration.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@0.0.1 styleguide: `styleguidist server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@0.0.1 styleguide script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Giacomo\AppData\Roaming\npm-cache\_logs\2018-03-30T16_26_35_501Z-debug.log
```

Reproducible demo:
1. Set up react-styleguidist on a project
2. Put an array inside the config components like so: `components: ['app/components/[A-Z]*.js', 'app/containers/[a-z]*.js'],`
3. Watch it fail

**Comment by sapegin** [comment]
Fixed in 5d9e52d6b5f361f06a8abe7f060778cbd0e12a62.
