### ISSUE TITLE
Webpack 4 breaking change

### ISSUE THREAD

**Issue by crobinson42** [styleguidist/react-styleguidist#914]
My project was working fine then I upgraded to webpack 4 and react-styleguidist is blowing up:

```
Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
```

* Note - my only configs are 
```
module.exports = {
  template: 'src/templates/index.html',
}
```

Let me know if I can help with a PR or other, will update if I find some resolution.

**Comment by sapegin** [comment]
It's almost done: 
https://github.com/styleguidist/react-styleguidist/milestone/11

**Comment by sapegin** [comment]
Could you publish a demo project? I don't know what's html-webpack-plugin-before-html-processing but it's something from your project, not styleguidist.
