### ISSUE TITLE
webpack-dev-server → webpack-serve

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#916]
[webpack-dev-server](https://github.com/webpack/webpack-dev-server) is in maintenance mode, [webpack-serve](https://github.com/webpack-contrib/webpack-serve) is a newer faster alternative. It work only in webpack 4, so we have to wait until #915.

**Comment by everdimension** [comment]
By the way, shouldn't `webpack` be listed in either `peerDependencies` or `dependencies`?

**Comment by sapegin** [comment]
Nope, because we should support tools like Create React App that have their own webpack, so you don't have it as a dependency of your project. But if Styleguidist couldn't load webpack, it will ask you to install it.

**Comment by sapegin** [comment]
We support webpack 3 and 4, so you’ll likely see some warnings in both cases, but it works somehow. We’ll drop webpack 3 as soon as CRA supports webpack 4, but there are other issues with that (like #987), and then we could upgrade dependencies and get rid of warnings.

**Comment by marcofugaro** [comment]
Not anymore, webpack-serve has been deprecated

https://github.com/webpack-contrib/webpack-serve

**Comment by sapegin** [comment]
@marcofugaro Awesome, let's close this then ;-)
