### ISSUE TITLE
Downgrade markdown-to-jsx

### ISSUE THREAD

**Issue by stephtr** [styleguidist/react-styleguidist#922]
At the moment `markdown-to-jsx` has some severe issues rendering HTML within markdown (for example [markdown-to-jsx/#170](https://github.com/probablyup/markdown-to-jsx/issues/170)). Since only some of them will get fixed, one long-term option maybe would be to switch to another parser like markdown-it and inject the components into the generated HTML code.

In the near term it maybe would be useful to keep markdown-to-jsx@^6.4.1 such that one can locally fix it to 6.4.1 if needed.

**Comment by sapegin** [comment]
No, we're not going back to massive Markdown parsers. 

I guess the issues with markdown-to-jsx as soon as someone submits a pull request to fix them. 

But feel free to send a pull request to downgrade markdown-to-jsx.

**Comment by stephtr** [comment]
Ah ok, I didn't know that was an issue. I just had the feeling that for smaller projects like `markdown-to-jsx` it is much more complex/problematic to support the whole Markdown specification than for a specialized parser.

**Comment by bjmin** [comment]
Hi, seems https://github.com/probablyup/markdown-to-jsx/issues/170 had been fixed
should we upgrade `markdown-to-jsx` version?

**Comment by stephtr** [comment]
It [isn't fully fixed](https://github.com/probablyup/markdown-to-jsx/pull/175#issuecomment-387533914) at the moment and since yarn/npm by default install the most recent version, I don't see the need for updating the dependency (at least now).

**Comment by bjmin** [comment]
thanks, it works as you said.

**Comment by stephtr** [comment]
FYI: Since the issue has been fixed (thanks to probablyup), I have submitted a pull request for updating the dependency (#982).
