### ISSUE TITLE
Is it possible to include an example with multiple language tabs

### ISSUE THREAD

**Issue by dinukadesilva** [styleguidist/react-styleguidist#923]
I have an extra javascript to be executed along with the react component. So, is it possible to have examples with multiple code tabs.

Eg:-

```
<Abcd />
```

```
document.body.dispatchEvent(new CustomEvent('triggerAlert', {
      "detail":{
         "message": "Haaai"
      }
  }));
```

**Comment by sapegin** [comment]
There are at least several ways to do that described in the docs, depending on what exactly you want to achieve.

**Comment by linonetwo** [comment]
I can't find that doc in the cookbook.
