### ISSUE TITLE
Nested spans and divs get a mangled structure

### ISSUE THREAD

**Issue by roblevintennis** [styleguidist/react-styleguidist#928]
I've got a test case here:
https://github.com/styleguidist/react-styleguidist/pull/927

Here's screen shot of examples/basic
![image](https://user-images.githubusercontent.com/142403/38390973-bffed6a2-38d7-11e8-83c8-d04a101fc5ee.png)

Here's in our design system where we discovered:

![image](https://user-images.githubusercontent.com/142403/38391011-dde88bae-38d7-11e8-8054-4bbb23af8502.png)

Note, we notice this is only an issue since the last release.

We're happy to try and help, but for all I know this is due to some external parsing library being used. Lmk if you have an idea and/or if this is already slated to be fixed ... thanks!

**Comment by sapegin** [comment]
>  When something isn’t working for you, include a reproducible demo:
>   1. Fork the example project repository: https://github.com/styleguidist/example
>      **(please don’t use the main, styleguidist/react-styleguidist, repository).**
>   2. Modify it to reproduce the issue.
>   3. Push to GitHub and paste the link here.
>

**Comment by sapegin** [comment]
Anyway, I can reproduce it at [markdown-to-jsx](https://probablyup.com/markdown-to-jsx/), so it should be reported there.

**Comment by roblevintennis** [comment]
![image](https://user-images.githubusercontent.com/142403/38510136-e9ccaf14-3bd8-11e8-977b-8bef139a86f1.png)
seems to work fine from their wysiwig
