### ISSUE TITLE
rsg-components/Props/util.js: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by vashchukmaksim** [styleguidist/react-styleguidist#935]
Sorry, don't know how to create the issue properly since I can't say how to reproduce it and what exactly cause it, but I faced up an error message after successful build on the localhost:6060 index page that said:

`TypeError: Cannot read property 'replace' of null`

I found a place where it occurs: `rsg-components/Props/util.js` in the `unquote` function.

```
export function unquote(string) {
    return string.replace(/^['"]|['"]$/g, '');
}
```

And if we roughly change it to any check of a `string` argument e.g.:

```
export function unquote(string) {
  return string ? string.replace(/^['"]|['"]$/g, '') : '';
}
```

then the documentation shows up correctly instead of an error.

**Comment by sapegin** [comment]
That's definitely not a fix: that will just hide  and error instead of a fixing the root cause. But with this amount of details I couldn't do anything. Most likely one of your components has something unusual that causes the error, but you need to find it, and then:

>  1. Fork the example project repository: https://github.com/styleguidist/example
>     (please don’t use the main, styleguidist/react-styleguidist, repository).
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.

**Comment by vashchukmaksim** [comment]
Absolutely this is not the fix. I just meant that there is nothing else broken since we hide an error. I'll try to investigate further but there is almost no information on what and where it can be.
