### ISSUE TITLE
Launching with command that auto configures serverPort?

### ISSUE THREAD

**Issue by santaclauze** [styleguidist/react-styleguidist#936]
Hi, 

I am working with your library more and more and its awesome! So much that i am working on multiple modules that have styleguidist. 

### My issue is that:

Following the documentation it seems that the port used by styleguidist seems to be `6060` by default and that it can only be changed with `serverPort` , in the `styleguide.config.js`.

This is a pain as I do not want to change the config just for a temporary need.

### Question / Request

Is it possible to launch the dev server by setting the port **in** the command?
ex:
 ```bash
$ npm run styleguide --port=6061
````

**Comment by philwolstenholme** [comment]
@santaclauze you could use https://github.com/indexzero/node-portfinder to set an open port automatically?

**Comment by santaclauze** [comment]
@gergely-nagy, that would be great.

TBH, my family life make it hard to spend time on side projects and I am a dev in the making, so it takes even longer.

As for now, a quick and not elegant way was to add the following line in the [scrip file](https://github.com/styleguidist/react-styleguidist/blob/master/scripts/schemas/config.js)

`
	serverPort: {
		type: 'number',
		default: parseInt(process.argv[5] || '6060', 10),
	},
`

**Comment by kopax** [comment]
I've published a quick fix in the schema for `NODE_PORT`. I've checked detect-port, it look simple but its' async which doesn't fit well in the current pattern.

See #995

**Comment by ruchern** [comment]
@gergely-nagy I tried with `portfinder` and am unable to increment the port if the previous port is used. There seems to be a Promise issue where the styleguidst server will finish launching the server before the Promise could finish. Would you like to help me on this?
