### ISSUE TITLE
How to migrate template.html from v6 to v7

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#944]
I have read the release page.

We are stuch and failed upgrading our webpack html template with the new one that use htmlwebpackmini plugin to upgrade react-styleguide from v6 to v7.

How do you insert your template in the latest version v7?

**Comment by sapegin** [comment]
https://react-styleguidist.js.org/docs/configuration#template
https://react-styleguidist.js.org/docs/cookbook.html
