### ISSUE TITLE
How to dynamically load sections and components

### ISSUE THREAD

**Issue by ZxBing0066** [styleguidist/react-styleguidist#946]
Is there any way for me to dynamically load sections and components in styleguide config?
Once I add a component, I need to add section config and components and then restart styleguide, I don't want to restart everytime.

**Comment by sapegin** [comment]
No, we won't do that, it's not worth it.

> Once I add a component, I need to add section config and components and then restart styleguide

Don't create a new section for each component, use glob patterns.
