### ISSUE TITLE
How to get propTypes from used component

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#947]
I am using react-styleguide `7.0.7`, I want to wrap a component before connecting, but by doing this, all my table props are disappearing.

I have tried to write it in many ways, for example, this only display one table with `size`

```
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import Toggle from 'bootstrap-styled-toggle/lib/components/Toggle';
import { createStructuredSelector } from 'reselect';
import { changeTheme as changeThemeAction } from '../../actions';
import { selectValue, selectValues } from '../../selectors';

/**
 * ThemeToggle is used to display a select option to change theme
 * @constructor
 */
export const ThemeToggle = (props) => <Toggle {...props} />;


const mapStateToProps = createStructuredSelector({
  value: selectValue,
  values: selectValues,
});

export const mapDispatchToProps = (dispatch) => ({
  onToggle: (evt) => dispatch(changeThemeAction(evt.target.value)),
});

ThemeToggle.propTypes = {
  /** from toggle */
  ...Toggle.propTypes,
  size: PropTypes.array,
};
export default connect(mapStateToProps, mapDispatchToProps)(ThemeToggle);
```

How can I display all the `propTypes` of my component?

**Comment by santaclauze** [comment]
I think the issue is also related to this post #705.

**Comment by kopax** [comment]
it is still unfixed

**Comment by dankreft** [comment]
I'm experiencing a similar problem, I think...

My parent component says this:

```js
// File: SnackBar.jsx

import SnackBarIcon from './SnackBarIcon'

export default class SnackBar extends PureComponent {
  static propTypes = {
    type: SnackBarIcon.propTypes.type,
  }
}
```
The child component:

```js
// File: SnackBarIcon.jsx

import PropTypes from 'prop-types'

export default function SnackBarIcon({ type }) {
  return ( ... )
}

Icon.propTypes = {
  type: PropTypes.oneOf(['error', 'neutral', 'success']).isRequired,
}
```

In the generated documentation for `SnackBarIcon` I see this:

![image](https://user-images.githubusercontent.com/42359759/50801627-69c08900-129a-11e9-9079-7f020b8347f9.png)

But in the generated docs for `SnackBar`, I get this:

![image](https://user-images.githubusercontent.com/42359759/50801639-7c3ac280-129a-11e9-9e25-c51e87a07e67.png)

**Comment by mickatron** [comment]
Have you tried using named exports rather than defaults?

I've had a similar problem in a style guide using higher order components in a Typescript styleguisidt implementation and found that just using named exports made things a heap easier.

I think the issue is more related to `react-docgen`. There's a few reports about this over in that repo.

You can also look at;
https://github.com/jmeyering/react-docgen-annotation-resolver

Hope it helps

**Comment by mickatron** [comment]
I can only provide a working example in Typescript for documenting a HOC wrapped component. Exporting it as a default will result in the props not being defined in styleguidist, but named exports work just fine. Typescript handles named exports better too particularly when assigning namespaces.

```
import {
  withDynamicWrapper,
  DynamicWrapper
} from '../../../HOC/withDynamicWrapper/withDynamicWrapper';

export namespace ButtonIcon {
  export interface Props extends DynamicWrapper.Props {}
}

/**
 * **wrapper:** `span.Button__icon`
 *
 * Presentational Sub Component.
 * An icon for a `Button` component.
 */
export const ButtonIcon: React.ComponentClass<ButtonIcon.Props> = withDynamicWrapper({
  name: 'ButtonIcon',
  element: 'span'
});

```

@dankreft Is it just the 'custom' type def that was a concern? I think that is the standard type given when not directly referencing propTypes, I might be wrong but it seems normal to me. I believe that is compiled by `react-docgen` though and not by `styleguidist`.
