### ISSUE TITLE
Animation Frame Fired - Performance dev tools

### ISSUE THREAD

**Issue by santaclauze** [styleguidist/react-styleguidist#948]
Hey,

I have been bench-marking our doc and it shows that the `Preview` component is calling a function `Animation Frame Fired`.
![nanimationpreview](https://user-images.githubusercontent.com/17665998/39024690-a8477788-4496-11e8-9da9-f930c3b9c7db.png)

![preview](https://user-images.githubusercontent.com/17665998/39024691-aa3607da-4496-11e8-8109-d4fe82492b67.png)

I saw in your doc that you pass props to the [examples](https://react-styleguidist.js.org/docs/documenting.html#usage-examples-and-readme-files). I suspect that there is a reason to this as it also works by passing the props to the component within the example.

### Questions
1. Is there a reason why you would pass the components as described in the doc rather than straight on the components within the example?
1. is the `Animation Frame Fired`.coming from the source code?
1. if not, is it because I have wrongly configurated `react-styleguidist`?

**Comment by kopax** [comment]
I think this is a requirement for styleguide to process the js inside the example.
When you got lots of components (like 50) rendered in this page, the time to process is about 30 seconds, this is why you should always include in the template HTML a loader directly.

Another way to get over this problem would be to remove components from the massive rendering you are doing. 

Probably that `react-router-redux` can be used.

**Comment by sapegin** [comment]
Feel free to send a pull request that improves performance.

**Comment by kopax** [comment]
@sapegin we are seriously considering improving the lib. Only issue is that we miss information from the author to get started with the work.

I would rather start with #705, I am not familiar with your work and I'd like you to share the flow for the table rendering and the example rendering. Which files should I edit, where does it happen, if you can share such information, I will dig into the code and try to solve #705 first and then #948.

Best,
