### ISSUE TITLE
Documenting components with TypeScript - Can't document with interactive playground

### ISSUE THREAD

**Issue by gCardinal** [styleguidist/react-styleguidist#950]
I'm having trouble getting TypeScript components to render... I've created a demo repo here: https://github.com/gCardinal/styleguidist-no-render-demo. I couldn't use the example repo since it's based on JS. I'm using Docker in the repo.

At first I thought it was because I'm using TypeScript, but... Even rendering a simple `<div>Foo</div>` breaks down. I'm not sure what I'm doing wrong here.

Markdown files get parsed without issue, it's only when I put a code block without `static` that things go crazy.

I use yarn's autoclean function. You can see what gets cleaned in the .yarnclean file, but I doubt I'd be cleaning something required for the playground to work.

(I also posted in Gitter yesterday morning. I'll update this issue with anything said there.)

**Comment by sapegin** [comment]
I'm not sure I want to install Docker just to run the code…

**Comment by gCardinal** [comment]
You shouldn't need it, simply running `npx styleguidist --config ./config/styleguide.config.js server` as usual should work. I just felt it would be easier with Docker. I've added this command to the `README.md`.
