### ISSUE TITLE
Clicking the title when using pagePerSection will result in a faulty URL

### ISSUE THREAD

**Issue by Neglexis** [styleguidist/react-styleguidist#951]
When my config contains the `pagePerSection: true` parameter, the components have a separate page as expected.

However, when clicking the title, the page tries to navigate to the component as it would've not had its own page.

E.g.

Component on page

`http://localhost:6060/#!/Draggable`

will have its title redirect to 

`http://localhost:6060/#draggable`

**Comment by sapegin** [comment]
#941 _may_ fix that.

**Comment by sapegin** [comment]
I think it should be fixed in 7.1.0. Feel free to reopen if not.
