### ISSUE TITLE
index.jsx and ComponentName.md don't play nice together

### ISSUE THREAD

**Issue by crobinson42** [styleguidist/react-styleguidist#958]
Our projects follow a component directory naming convention which uses `index.jsx` as the component file name and this does not work with Styleguidist. Styleguidist still shows the components based on component naming but not the .md code examples, ie:
```
- Button/
-- Button.md
-- index.jsx
-- index.test.jsx
```

The only way for this to work with Styleguidist is by naming `Button.md` to Readme.md or renaming `index.js` to `Button.jsx`. Is this something that the lib authors are willing to change or accept a PR to add as functionality which correlates and `index.jsx/.js` file with a component name matching the .md file in the same directory?

**Comment by n1313** [comment]
There are some configuration options that might be helpful here:

https://react-styleguidist.js.org/docs/configuration.html#components
https://react-styleguidist.js.org/docs/configuration.html#getexamplefilename

**Comment by stepancar** [comment]
@crobinson42 have you tried https://react-styleguidist.js.org/docs/configuration.html#getexamplefilename
?
