### ISSUE TITLE
Importing components directly from JSON output of react-docgen?

### ISSUE THREAD

**Issue by DylanLyon** [styleguidist/react-styleguidist#959]
Hey all,

Since Styleguidist uses react-docgen, there should be a way to import a JSON output from react-docgen, right? Due to some incompatibility that exists between my code and the way Styleguidist parses components, it's infinitely easier to use react-docgen first to spit out some JSON of my JSDoc compliant comments and then import that into Styleguidist. 

Is there currently a way this can be done? If not, how possible would it be to have it be done?

**Comment by sapegin** [comment]
I'm not really sure what problem you're trying to solve but feel free to send a pull request.
