### ISSUE TITLE
Styleguidist build doesn't work because of System.import

### ISSUE THREAD

**Issue by ivasilov-h4** [styleguidist/react-styleguidist#960]
The change introduced in #901 broke the build process of the Styleguidist. When trying to build my styleguide, I receive:

``` FAIL  Failed to compile

{obscured for security reasons}/node_modules/react-styleguidist/lib/rsg-components/Editor/EditorLoader.js
Syntax error: 'import' and 'export' may only appear at the top level (36:3)

  34 | 			var _this2 = this;
  35 |
> 36 | 			import('rsg-components/Editor/Editor').then(function (module) {
     | 			^
  37 | 				_this2.setState({ editor: module.default });
  38 | 			});
  39 | 		}
error An unexpected error occurred: "Command failed.
```

I'm using webpack 3.10.0.

**Comment by sapegin** [comment]
> When something isn’t working for you, include a reproducible demo:
>  1. Fork the example project: https://github.com/styleguidist/example
>  2. Modify it to reproduce the issue.
>  3. Push to GitHub and paste the link here.
>
> Most likely you’ll find an issue yourself, while creating a demo.
>
> **Issues without a demo will be closed!**
