### ISSUE TITLE
Using import/export in styleguide examples

### ISSUE THREAD

**Issue by bugzpodder** [styleguidist/react-styleguidist#969]
I want to able to write examples using import syntax, but currently I have to convert them to require.
What is the reasoning around this (node v6?) and is there anyway around it?

I was able to work around by writing the code in es6 this by using babel to transpire the example, but the source code displayed is the babel transpiled version and even less ideal.

updateExample: function(props, exampleFilePath) {
  props.content = babel.transformFileSync(path.resolve(exampleFilePath, "..", file)).code;
  return props;
},

I ended up adding the same sample twice, once to render it after babelify it, and another time to show the code with static=true

**Comment by bugzpodder** [comment]
Ok  found the source for examples loader and it seems pretty complicated...

**Comment by sapegin** [comment]
> Styleguidist uses Bublé to run ES6 code on the frontend, it supports most of the ES6 features.

https://react-styleguidist.js.org/docs/documenting#writing-code-examples
