### ISSUE TITLE
Allow updates to readOnly Editor

### ISSUE THREAD

**Issue by kidkuro** [styleguidist/react-styleguidist#979]
**The problem**

Currently the `Editor` component returns `false` from `shouldComponentUpdate`. However, if the `Editor` is configured to be `readOnly` via `editorConfig` it should be able to update. This would be necessary for plugins such as the proposed "View HTML" plugin in #968.

**Proposed solution**

Update `shouldComponentUpdate` in `Editor` to return `true` if `editorConfig.readOnly` and `code` has changed

I will raise a PR for this if #974 is approved, or if it is easier, I can cancel that and a create a single PR that addresses this ticket and #973 simultaneously since they are closely related.

**Comment by sapegin** [comment]
I think we can close it too ;-)
