### ISSUE TITLE
How to use the code editor to create an educational tool?

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#980]
**The problem**

I would like to create a documentation for student.

I expect them to do some sort of exercice, and from what I see, react-styleguidist is having a wonderful sandbox that work with react and can be configured with any library, simply amazing.

I want to add a feature, to be able to catch from the example: 

- one or many console.log made by the user.
- global namespace (function, variable, ...)
- the generated result, if html to modify it and generate a different result. (not always the rendering, but for exemple values catch with `console.log`, call to function that should pass (sort of unit testing of the code written by the student based on criteria).

**Proposed solution**

I am looking for advice regarding such an implementation, so far react-styleguidist is my favorite choice, I still need some sort of indication/advice that could help such implementation.

Would you be interested to have this feature in the core ?

**Comment by sapegin** [comment]
I'm not really sure what changes to Styleguidist are needed for your use case, or that Styleguidist is a better choice than Codesandbox for example.

But I've used Styleguidist in a similar way: https://github.com/sapegin/component-driven-development

**Comment by kopax** [comment]
Hi @sapegin, test for your reply, I will have a look at Codesandbox for sure. 
I've cloned the component driver development tutorial and I have not seen any input for the user to complete to achieve such interactive task in your documentation.

**Comment by sapegin** [comment]
Yup, you have to edit files, that's why Codesandbox may be a better choice for you. In Styleguidist you  can only edit examples on the page: you could use that but there's no way to preserve changes.
