### ISSUE TITLE
Rollup

### ISSUE THREAD

**Issue by GazzaHazza** [styleguidist/react-styleguidist#981]
Hiya,

I have searched all of the internet and not found a answer to my question, so here it is. 

Can `react-styleguidist` be used along side `rollup`?

Thanks

**Comment by n1313** [comment]
React-styleguidist uses webpack internally and cannot use rollup. Your code can use whatever bundler  you find the most fitting, it doesn't matter to react-styleguidist at all.

**Comment by sapegin** [comment]
But you’ll need create a webpack config to load your files anyway.

**Comment by yugandhar-pathi** [comment]
What kind of config should we use in webpack ? Does react styleguidist compile my react code ? I am using rollup with typescript.
