### ISSUE TITLE
Can't alias rsg-components using webpackConfig

### ISSUE THREAD

**Issue by kopax** [styleguidist/react-styleguidist#984]
The code say :

	// Add components folder alias at the end so users can override our components to customize the style guide
	// (their aliases should be before this one
        webpackConfig.resolve.alias['rsg-components'] = path.resolve(sourceDir, 'rsg-components');

version: 7.0.10

We fixed it with:

	// Add components folder alias at the end so users can override our components to customize the style guide
	// (their aliases should be before this one
	if (!webpackConfig.resolve.alias['rsg-components']) {
  		webpackConfig.resolve.alias['rsg-components'] = path.resolve(sourceDir, 'rsg-components');
	}

PR: https://github.com/styleguidist/react-styleguidist/pull/983

**Comment by sapegin** [comment]
The comment is actually incorrect anymore, users should use [styleguideComponents](https://react-styleguidist.js.org/docs/configuration.html#styleguidecomponents) option.

**Comment by kopax** [comment]
@sapegin we have hit this while trying to use the alias. I wonder why we should keep such a restriction, the `:fix` could be accepted as a `:feature` if not forbidden. Otherwise, this should be clearly stated in the documentation as a restriction.
