### ISSUE TITLE
Support for documenting instance/static members?

### ISSUE THREAD

**Issue by atomicpages** [styleguidist/react-styleguidist#990]
Is it possible to document variables in addition to public methods? I searched far and wide (and hopefully thoroughly)  yet saw nothing indicating Styleguidist supports documentation of variables.

**Comment by sapegin** [comment]
Have you _tried_? I guess it won’t work though, and I’m not sure what we need to change to enable it to work similar to public methods. Could you show some use cases?

**Comment by atomicpages** [comment]
Yep. Here's a practical example:

```js
export default class FooBar extends Component {

    render() {
        return <div>World</div>;
    }

}

export default class Foo extends Component {

    /**
     * I should show something on styleguidist
     * @type {CustomType}
     */
    static Bar = FooBar; // access via Foo.Bar

    render() {
        return <div>Hello</div>;
    }

}
```

The above approach is [particularly common with semantic UI react components](https://react.semantic-ui.com/views/card).

**Comment by stepancar** [comment]
@atomicpages Could you provide more realistic example?

**Comment by atomicpages** [comment]
@sapegin 
![screen shot 2018-06-25 at 6 54 26 pm](https://user-images.githubusercontent.com/1824291/41884671-3a668b2c-78a9-11e8-91ca-9515c9d2a954.png)

**Comment by pasupuletics** [comment]
@atomicpages , styleguidist doesn't doc for variables(static) as it relies on react-docden. Better you can check react-docegen api and write your own handler to generate doc. I did the same for nested components.
