### ISSUE TITLE
Trying to use a custom wrapper

### ISSUE THREAD

**Issue by LokeCarlsson** [styleguidist/react-styleguidist#992]
**Current behavior**

I am following the steps provided in the [Cookbook](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Cookbook.md#how-to-change-the-layout-of-a-style-guide) exactly.

I have tested implementing this wrapper to allow for react-intl to be used on example components in 2 different project as well as the demo repo provided below. 

I am getting the following error every time:

> ./node_modules/react-styleguidist/lib/rsg-components/Preview/Preview.js
Module not found: Can't resolve 'rsg-components/Wrapper' in '/Users/loke/Code/javascript/example/node_modules/react-styleguidist/lib/rsg-components/Preview'

In the two first project version 7.0.14 of react-styleguidist was used but in the demo project version 6.2.7 is used.

**To reproduce**

https://github.com/LokeCarlsson/example

**Expected behavior**

If i go into the the file in node_modules where the error is originating from and manually change the following import of the wrapper the problem seem to be gone (though this is only a temporary hack to see where the error comes from):

from:
`import Wrapper from 'rsg-components/Wrapper';`

to:
`import Wrapper from '../../../../../src/lib/styleguide/Wrapper';`

Somehow when trying to change the Wrapper in styleguideComponents it is not using the correct using the right one.

**Comment by coreybruyere** [comment]
@LokeCarlsson running into a similar issue when trying to use a theme wrapper. Did you come across a solution?

**Comment by LokeCarlsson** [comment]
@coreybruyere The problem for me was the project structure, I had my custom Wrapper placed in the wrong folder. Might be the lib folder for you.
