### ISSUE TITLE
h5 should be different from body text

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#994]
**Current behavior**

![cloudapp annotation 2018-05-28 at 10 06 57 pm png](https://user-images.githubusercontent.com/70067/40628164-b481492a-62c3-11e8-8de9-e33f3bdff073.png)

**To reproduce**

Any Markdown with h5:

```
##### Heading

Body text
```

**Expected behavior**

Headings should look different from the body text, bold for h5 could work.

**Comment by sterlingssmith** [comment]
@sapegin - I'd like to work on this issue.

**Comment by sapegin** [comment]
@sterlingssmith Awesome! 🦄

**Comment by jmiazga** [comment]
What would you like the font sizes to be? This is what they currently are:

```
export const fontSize = {
	base: 15,
	text: 16,
	small: 13,
	h1: 48,
	h2: 36,
	h3: 24,
	h4: 18,
	h5: 16,
	h6: 16,
};
```

Paragraphs also have a font size of 16px.

![image](https://user-images.githubusercontent.com/181441/41812307-78c4ae6a-76ee-11e8-9631-c78441e6ce9b.png)

**Comment by sapegin** [comment]
We can make h5 bold and h6 italic.

**Comment by jmiazga** [comment]
@sapegin I created a PR to address this issue https://github.com/styleguidist/react-styleguidist/pull/1024
