### ISSUE TITLE
support `import` statements and `flow` type annotations in code examples

### ISSUE THREAD

**Issue by kevinbarabash** [styleguidist/react-styleguidist#996]
**The problem**
I'd like to be able to use `import` in code examples, but currently that isn't support b/c bublé doesn't support `import`/`export` statements.  I'd also like to be able to use flow type annotations.  I have a script that generates jest snapshot tests from the code examples.  I'd like to type check those examples as well, but bublé doesn't support flow either.

**Proposed solution**
Switch from bublé to babel.

**Alternative solutions**
Another option is sucrase.  It's faster, but doesn't have the same ecosystem of plugins that babel has.

**Additional context**
n/a

**Comment by sapegin** [comment]
Please use search, it was discussed million times already and I believe both questions have open issues.
