### ISSUE TITLE
How do i override jss-isolate

### ISSUE THREAD

**Issue by jquense** [styleguidist/react-styleguidist#997]
jss-isolate is extremely frustrating because it makes theming a styleguide very hard if you need to make blanket  changes for things that aren't theme variables. For instance i seem to have to manually override the styles for every. single. component. if I want the default font-weight to be something other than `normal`.

What is the value of this plugin in the context of a styleguide, The defaults react-styleguidist provide should be extremely easy to override, but it often feels impossible

**Comment by sapegin** [comment]
The reasons why we do this are explained here: https://react-styleguidist.js.org/docs/development.html

You _can_ disable jss-isolate per rule, but then there's no guarantee than your app styles won't break Styleguist UI:

https://github.com/styleguidist/react-styleguidist/blob/5c07e8125a7581a98661b0b45671001abec683de/src/rsg-components/Editor/EditorLoaderRenderer.js#L22-L25

Feel free to send a pull request if you have an idea how to make the theming experience better.

**Comment by jquense** [comment]
disabling still seems to be on a per component basis. The frustrating bit here is that if I want something to cascade it's almost impossible. In this case `jss-issolate` forces every component to have a `font-weight` of `normal` (400), when our default weight is `300`, trying to change doesn't seem feasible?

I understand the need to isolate the chrome styles from the examples generally, but find it hard to work with in the particular cases. Every time i've setup a RSG site, i've needed to theme the guide, to _match_ the general assumptions of the styleguide components, in order for them to look right in context. That is really tough, when the styleguide insists that certain values be set. That wouldn't be so much of a problem if it was easier to make blanket changes to the theme values.

Perhaps a practical suggestion would be to allow configuring the isolate values at a theme level? If we could automatically add any value that `jss-isolate` resets to the theme variables, it'd be a non-problem 👍
